### ISSUE TITLE
[NETCORE] Alpha 4 - Saving a nested block list with item limits (min/max) results in NullReferenceException

### ISSUE THREAD

**Issue by robertjf** [umbraco/Umbraco-CMS#10095]
I created a block list schema including nested items - when I went to save a content node with the properties I received the following error:

```
Object reference not set to an instance of an object.

Exception Details
System.NullReferenceException, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: Object reference not set to an instance of an object.
at Umbraco.Web.PropertyEditors.BlockEditorPropertyEditor.MinMaxValidator.Validate(Object value, String valueType, Object dataTypeConfiguration)+MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at Umbraco.Cms.Core.PropertyEditors.DataValueEditor.Validate(Object value, Boolean required, String format)
   at Umbraco.Core.Services.PropertyValidationService.ValidatePropertyValue(IDataEditor editor, IDataType dataType, Object postedValue, Boolean isRequired, String validationRegExp, String isRequiredMessage, String validationRegExpMessage)+MoveNext()
   at Umbraco.Web.PropertyEditors.ComplexEditorValidator.GetNestedValidationResults(IEnumerable`1 elements)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Umbraco.Web.PropertyEditors.ComplexEditorValidator.Validate(Object value, String valueType, Object dataTypeConfiguration)
   at Umbraco.Cms.Core.PropertyEditors.DataValueEditor.<>c__DisplayClass23_0.<Validate>b__0(IValueValidator v)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at Umbraco.Cms.Core.PropertyEditors.DataValueEditor.Validate(Object value, Boolean required, String format)
   at Umbraco.Core.Services.PropertyValidationService.ValidatePropertyValue(IDataEditor editor, IDataType dataType, Object postedValue, Boolean isRequired, String validationRegExp, String isRequiredMessage, String validationRegExpMessage)+MoveNext()
   at Umbraco.Web.PropertyEditors.ComplexEditorValidator.GetNestedValidationResults(IEnumerable`1 elements)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Umbraco.Web.PropertyEditors.ComplexEditorValidator.Validate(Object value, String valueType, Object dataTypeConfiguration)
   at Umbraco.Cms.Core.PropertyEditors.DataValueEditor.<>c__DisplayClass23_0.<Validate>b__0(IValueValidator v)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at Umbraco.Cms.Core.PropertyEditors.DataValueEditor.Validate(Object value, Boolean required, String format)
   at Umbraco.Core.Services.PropertyValidationService.ValidatePropertyValue(IDataEditor editor, IDataType dataType, Object postedValue, Boolean isRequired, String validationRegExp, String isRequiredMessage, String validationRegExpMessage)+MoveNext()
   at Umbraco.Web.PropertyEditors.ComplexEditorValidator.GetNestedValidationResults(IEnumerable`1 elements)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Umbraco.Web.PropertyEditors.ComplexEditorValidator.Validate(Object value, String valueType, Object dataTypeConfiguration)
   at Umbraco.Cms.Core.PropertyEditors.DataValueEditor.<>c__DisplayClass23_0.<Validate>b__0(IValueValidator v)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at Umbraco.Cms.Core.PropertyEditors.DataValueEditor.Validate(Object value, Boolean required, String format)
   at Umbraco.Core.Services.PropertyValidationService.ValidatePropertyValue(IDataEditor editor, IDataType dataType, Object postedValue, Boolean isRequired, String validationRegExp, String isRequiredMessage, String validationRegExpMessage)+MoveNext()
   at Umbraco.Cms.Web.BackOffice.Filters.ContentModelValidator`3.ValidatePropertyValue(TModelSave model, TModelWithProperties modelWithProperties, IDataEditor editor, ContentPropertyDto property, Object postedValue, ModelStateDictionary modelState)
   at Umbraco.Cms.Web.BackOffice.Filters.ContentModelValidator`3.ValidatePropertiesData(TModelSave model, TModelWithProperties modelWithProperties, ContentPropertyCollectionDto dto, ModelStateDictionary modelState)
   at Umbraco.Cms.Web.BackOffice.Filters.ContentSaveValidationAttribute.ContentSaveValidationFilter.OnActionExecutingAsync(ActionExecutingContext context)
   at Umbraco.Cms.Web.BackOffice.Filters.ContentSaveValidationAttribute.ContentSaveValidationFilter.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

## Umbraco version

I am seeing this issue on Umbraco version: nightly build 9.0.0-beta001.20210222.10

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

I may need to provide a copy of the database... will be available on request privately :)

**Comment by robertjf** [comment]
some further notes on this - when I cleared out all the nested blocklist content, saved the document and then added them back, I was unable to replicate the issue...

**Comment by nul800sebastiaan** [comment]
Thanks @robertjf! Don't know if you still have the db at the time of the problem? If not, could you try to create a new node with a nested content item and see if it returns? I have a feeling it's a problem with the validation that we're still working on, also for v8. Usually the problem only occurs the first time you save a node where validation doesn't pass the first time.

**Comment by bergmania** [comment]
I'll close this one. If you anyone see this issue and are able to describe how to reproduce it, we can reopen :)
