### ISSUE TITLE
Umbraco 7 - Weird PublishedMediaCache issue : ContentTypeService failed to find a media type with alias

### ISSUE THREAD

**Issue by rustybox** [umbraco/Umbraco-CMS#10104]
I don't really expect anyone to look into this issue, but it might be handy if the search engines index it so folk can see my workaround.

A while back a coworker of mine mentioned that they couldn't run a project locally as they got a 500 page with the message

```
System.InvalidOperationException: ContentTypeService failed to find a media type with alias "foo".
```

I thought this odd as the alias made no sense in the context of the project but did fit another Umbraco 7 project we both work on.

I told them to turn their PC off and on and everything was fine.

Today I managed to reproduce.

Problem site has umbracoLocalTempStorage = Default (not set)
The other has umbracoLocalTempStorage = EnvironmentTemp (could be a config transform for release only but it's not).

It appears that somehow the Umbraco content in %temp% is impacting the other site which should be looking only in ~/App_Data, I haven't dug in much to work out how or why.

My workaround other than restarting machine is just to nuke %temp%/UmbracoData and carry on with my day.

Most of the content on the problem site makes complete sense (comes from correct umbraco.config) it's just a one random call to GetCroppedImageUrl that exhibits the behaviour.

```
   at Umbraco.Core.Models.PublishedContent.PublishedContentType.CreatePublishedContentType(PublishedItemType itemType, String alias)
   at Umbraco.Core.Models.PublishedContent.PublishedContentType.<>c__DisplayClass25_0.<Get>b__0()
   at Umbraco.Core.Cache.CacheProviderExtensions.<>c__DisplayClass5_0`1.<GetCacheItem>b__0()
   at Umbraco.Core.Cache.StaticCacheProvider.<>c__DisplayClass11_0.<GetCacheItem>b__0(String key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Umbraco.Core.Cache.StaticCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem)
   at Umbraco.Core.Cache.CacheProviderExtensions.GetCacheItem[T](ICacheProvider provider, String cacheKey, Func`1 getCacheItem)
   at Umbraco.Core.Models.PublishedContent.PublishedContentType.Get(PublishedItemType itemType, String alias)
   at Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedMediaCache.DictionaryPublishedContent..ctor(IDictionary`2 valueDictionary, Func`2 getParent, Func`3 getChildren, Func`3 getProperty, XPathNavigator nav, Boolean fromExamine)
   at Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedMediaCache.CreateFromCacheValues(CacheValues cacheValues)
   at Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedMediaCache.GetUmbracoMedia(Int32 id)
   at Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedMediaCache.GetById(UmbracoContext umbracoContext, Boolean preview, Int32 nodeId)
   at Umbraco.Web.PublishedCache.ContextualPublishedCache`1.GetById(Boolean preview, Int32 contentId)
   at Umbraco.Web.PropertyEditors.ValueConverters.LegacyMediaPickerPropertyConverter.ConvertSourceToObject(PublishedPropertyType propertyType, Object source, Boolean preview)
   at Umbraco.Web.Models.DetachedPublishedProperty.<.ctor>b__7_1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Umbraco.Web.Models.DetachedPublishedProperty.get_Value()
   at Umbraco.Web.PublishedPropertyExtension.GetValue[T](IPublishedProperty property, Boolean withDefaultValue, T defaultValue)
   at Umbraco.Web.PublishedContentExtensions.GetPropertyValue[T](IPublishedContent content, String alias, Boolean recurse, Boolean withDefaultValue, T defaultValue)
   at Umbraco.Web.PublishedContentExtensions.GetPropertyValue[T](IPublishedContent content, String alias)
   at Some.Web.Site.Models.PublishedContentModels.GroupFeatureItem.get_Icon() 
   ```

**Comment by nul800sebastiaan** [comment]
Thanks, I have absolutely no advise either, but might be good for Google one day! 😅
