### ISSUE TITLE
Recurrent exception 'Umbraco.Core.Exceptions.PanicException: failed to get root with id'

### ISSUE THREAD

**Issue by lindeberg** [umbraco/Umbraco-CMS#10522]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.13.0

### Bug summary

This exception keeps getting thrown:
```
Umbraco.Core.Exceptions.PanicException: failed to get root with id=1276
   at Umbraco.Web.PublishedCache.NuCache.ContentStore.GetRequiredLinkedNode(Int32 id, String description, Nullable`1 gen) in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\ContentStore.cs:line 923
   at Umbraco.Web.PublishedCache.NuCache.ContentStore.<GetAtRoot>d__64.MoveNext() in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\ContentStore.cs:line 1240
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<OfTypeIterator>d__95`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
```

When calling this method:
```
public static Site? SiteNode(this UmbracoHelper umbracoHelper)
{
    return umbracoHelper.ContentAtRoot()
        .OfType<Site>()
        .FirstOrDefault();
}
```

The method call is happening in a Hangfire job where we get an UmbracoHelper by calling 

```
private UmbracoHelper GetUmbracoHelper()
{
    _umbracoContextFactory.EnsureUmbracoContext();
    return DependencyResolver.Current.GetService<UmbracoHelper>();
}
```

In the background we are using the content service to create and update descendants of the node (but not the node that is logged). That might be related?

Tried rebuilding memory cache and database cache, resaving/publishing the nodes and it doesn't help.

### Steps to reproduce

Write a method like the one above and if you're lucky it might throw a panic exception.

**Comment by emma-hq** [comment]
Hey @lindeberg 

I'm looking at issues relating to Hangfire at the mo so will take a look at this and see if any relate. I'll post anything I find back here.

Thanks for reporting!

Emma

**Comment by Wiggee11** [comment]
I am seeing the same errors being thrown continually in a couple of applications, one running 8.13.0 and one running 8.14.1.

One is a load-balanced application with large volumes of data (200,000+ nodes).

Similarly to the original post, the applications are using the Content Service to update records, but I am seeing it happening in both background threads and also custom API Controllers just returning content from the cache.

The node Id's referenced in the errors are always available in the backoffice.

**Example 1 (API Controller):**
```
Umbraco.Core.Exceptions.PanicException: failed to get content with id=26454
at Umbraco.Web.PublishedCache.NuCache.PublishedContent.<get_ChildrenForAllCultures>d__57.MoveNext() in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\PublishedContent.cs:line 298
at System.Linq.Enumerable.WhereEnumerableIterator1.MoveNext()    at System.Linq.Enumerable.<SelectManyIterator>d__172.MoveNext()
at Umbraco.Web.PublishedContentExtensions.<EnumerateDescendants>d__89.MoveNext() in D:\a\1\s\src\Umbraco.Web\PublishedContentExtensions.cs:line 1053
at System.Linq.Enumerable.<SelectManyIterator>d__172.MoveNext()    at Umbraco.Web.PublishedContentExtensions.<EnumerateDescendants>d__89.MoveNext() in D:\a\1\s\src\Umbraco.Web\PublishedContentExtensions.cs:line 1053    at System.Linq.Enumerable.<SelectManyIterator>d__172.MoveNext()
at Umbraco.Web.PublishedContentExtensions.<EnumerateDescendants>d__88.MoveNext() in D:\a\1\s\src\Umbraco.Web\PublishedContentExtensions.cs:line 1045
at System.Linq.Enumerable.WhereEnumerableIterator1.MoveNext()    at System.Linq.Enumerable.<SelectManyIterator>d__172.MoveNext()
at System.Linq.Enumerable.WhereEnumerableIterator1.MoveNext()    at System.Collections.Generic.List1..ctor(IEnumerable1 collection)    at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
at Application.Api.Services.JournalService.GetAnnouncements() in C:\src\Application.Api\Services\JournalService.cs:line 57
at Application.Api.Controllers.JournalController.Get(String issn) in C:\src\Application.Api\Controllers\JournalController.cs:line 92
at lambda_method(Closure , Object , Object[] )
at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
```

The GetAnnouncements() method throwing the error is getting content by ContentType:
```
using (var contextReference = _contextFactory.EnsureUmbracoContext())
{
	announcements = contextReference.UmbracoContext.Content.GetByContentType(Announcement.GetModelContentType()).ToList();
}
```

**Example 2 (API Controller):**
```
Umbraco.Core.Exceptions.PanicException: failed to get content with id=165242
at Umbraco.Web.PublishedCache.NuCache.PublishedContent.<get_ChildrenForAllCultures>d__57.MoveNext() in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\PublishedContent.cs:line 298
at System.Linq.Enumerable.WhereEnumerableIterator1.MoveNext()    at System.Linq.Enumerable.<SelectManyIterator>d__172.MoveNext()
at Umbraco.Web.PublishedContentExtensions.<EnumerateDescendants>d__89.MoveNext() in D:\a\1\s\src\Umbraco.Web\PublishedContentExtensions.cs:line 1053
at System.Linq.Enumerable.<SelectManyIterator>d__172.MoveNext()    at Umbraco.Web.PublishedContentExtensions.<EnumerateDescendants>d__88.MoveNext() in D:\a\1\s\src\Umbraco.Web\PublishedContentExtensions.cs:line 1045    at System.Linq.Enumerable.WhereEnumerableIterator1.MoveNext()
at System.Collections.Generic.List1.InsertRange(Int32 index, IEnumerable1 collection)
at Application.Api.Services.ContentApiService.Search(Nullable1 updatedSince, Nullable1 updatedBefore, String issn, String type, Boolean publishedOnly) in C:\src\Application.Api\Services\ContentApiService.cs:line 68
at Application.Api.Controllers.ContentApiController.Search(String start, String count, String updatedSince, String updatedBefore, String issn, String type, String published) in C:\src\Application.Api\Controllers\ContentApiController.cs:line 253
at lambda_method(Closure , Object , Object[] )
at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
```

The Search() method throwing the error is getting a bunch of descendants of type from root node:
```
using (var contextReference = _contextFactory.EnsureUmbracoContext())
{
	var contentCache = contextReference.UmbracoContext.Content;
	
	var websiteRoot = contentCache.GetAtRoot(true)
		.FirstOrDefault(x => x.ContentType.Alias == Website.ModelTypeAlias);

	var contentPages = websiteRoot.DescendantsOfType(ContentPage.ModelTypeAlias);
	var newsArticles = websiteRoot.DescendantsOfType(NewsArticle.ModelTypeAlias);
	var otherArticles = websiteRoot.DescendantsOfType(OtherArticle.ModelTypeAlias);
}
```

**Example 3 (Hangfire background task):**
```
Umbraco.Core.Exceptions.PanicException: failed to get content with id=1123
at Umbraco.Web.PublishedCache.NuCache.PublishedContent.<get_ChildrenForAllCultures>d__57.MoveNext() in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\PublishedContent.cs:line 298
at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext()    at System.Collections.Generic.List1..ctor(IEnumerable1 collection)    at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
at Umbraco.Core.Xml.XPath.NavigableNavigator.State.GetContentChildIds(Int32 maxDepth) in D:\a\1\s\src\Umbraco.Core\Xml\XPath\NavigableNavigator.cs:line 1196
at Umbraco.Core.Xml.XPath.NavigableNavigator.MoveToFirstChildElement() in D:\a\1\s\src\Umbraco.Core\Xml\XPath\NavigableNavigator.cs:line 579
at Umbraco.Core.Xml.XPath.NavigableNavigator.MoveToFirstChild() in D:\a\1\s\src\Umbraco.Core\Xml\XPath\NavigableNavigator.cs:line 559
at MS.Internal.Xml.XPath.XPathDescendantIterator.MoveNext()
at MS.Internal.Xml.XPath.DescendantQuery.Advance()
at MS.Internal.Xml.XPath.FilterQuery.Advance()
at MS.Internal.Xml.XPath.XPathSelectionIterator.MoveNext()
at Umbraco.Web.PublishedCache.NuCache.ContentCache.GetSingleByXPath(XPathNodeIterator iterator) in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\ContentCache.cs:line 335
at Application.BackgroundTasks.Import.Publication.EditorsImport.GetExistingEditors(Int32 publicationId) in C:\src\Application.BackgroundTasks.Import\Publication\EditorsImport.cs:line 435
at Application.BackgroundTasks.Import.Publication.EditorsImport.Import(Int32 publicationId, String editorsData, JournalImportRecord journalImportRecord) in C:\src\Application.BackgroundTasks.Import\Publication\EditorsImport.cs:line 61
at Application.BackgroundTasks.Import.Publication.Publications.ProcessPublication(String publicationData) in C:\src\Application.BackgroundTasks.Import\Publication\Publications.cs:line 435
at Application.BackgroundTasks.Import.Publication.Publications.ProcessPublications(String fileData, CancellationToken cancellationToken) in C:\src\Application.BackgroundTasks.Import\Publication\Publications.cs:line 125
```

The GetExistingEditors() method throwing the error is getting a node out of the cache by XPath:
```
using (var contextReference = _contextFactory.EnsureUmbracoContext())
{
	var contentCache = contextReference.UmbracoContext.Content;
	journal = contentCache.GetSingleByXPath(true, $"//{Journal.ModelTypeAlias}[@id=\"{node.Id}\"]");
}
```

This issue is not isolated to background threads. I have seen various community comments suggesting it could be related to GetByContentType() or DescendantsOfType(), guess they're doing similar things. It seems that the DB and cache are not synching correctly.

Hope that helps and let me know if I can provide any further information, as really need to get to the bottom of these issues.

**Comment by lindeberg** [comment]
@Wiggee11 Have you found any workaround?

**Comment by Wiggee11** [comment]
Nope, and no help / response from Umbraco or @emma-hq .

This issue is now affecting multiple live applications continually.

**Comment by nul800sebastiaan** [comment]
Thanks for all the feedback everyone and apologies for the delay. I don't have the magic bullet for you, so I've gathered some suggestions from the team at HQ for you all to try:

First of all, we have been fixing a lot of things in NuCache recently and we would only be able to investigate further if you still see these problems on 8.15.2. 

There's a good tip to help you make your code a bit more performant, I'll quote some of the replies:

> Could be also calls like this could be optimized: `var newsArticles = websiteRoot.DescendantsOfType(NewsArticle.ModelTypeAlias);`
> 
> I.e. probably news articles sit in a particular section of the tree - e.g. under a "News landing page", so it would likely be better to find that first and then do a DescendantsOfType under there rather than the website root.

In other words, the less digging that the query has to do the better! 

> Using UmbracoContext without an http request absolutely 100000% requires that you dispose things correctly if using EnsureUmbracoContext().
> UmbracoContext is a scoped object. If you don't end it's scope, bad things happen. 
 
Additionally, we can't see what's going on in your custom code, so while these examples are great, please do review the code that's not shown. Related to that:

So in the first example: `_umbracoContextFactory.EnsureUmbracoContext();` that is going to cause problems, make sure to use a using block: 

```csharp
using (var umbracoContext = _contextFactory.EnsureUmbracoContext())
{ 
    // your code
}
```

> It's VERY important to not statically pin an UmbracoContext to the application root. I see this all the time. Any statically pinned scoped objects: HttpContext, UmbracoContext, UmbracoHelper will cause issues.

So if you ever assign these things to a static variable, you can expect some problems. 

But as said, first of all, we'd like to hear if you still have these problems with 8.15.2 and you've reviewed your code with these remarks then we can look a bit deeper.

**Comment by Wiggee11** [comment]
> First of all, we have been fixing a lot of things in NuCache recently and we would only be able to investigate further if you still see these problems on 8.15.2.

Running 8.16.0 and still seeing these issues.

> > Could be also calls like this could be optimized: `var newsArticles = websiteRoot.DescendantsOfType(NewsArticle.ModelTypeAlias);`
> > I.e. probably news articles sit in a particular section of the tree - e.g. under a "News landing page", so it would likely be better to find that first and then do a DescendantsOfType under there rather than the website root.
> 
> In other words, the less digging that the query has to do the better!

We have a generic NewsArticle doc type which can be created under multiple other doc types, hence why we query from the root.

> So in the first example: `_umbracoContextFactory.EnsureUmbracoContext();` that is going to cause problems, make sure to use a using block:
> 
> ```cs
> using (var umbracoContext = _contextFactory.EnsureUmbracoContext())
> { 
>     // your code
> }
> ```

`_umbracoContextFactory.EnsureUmbracoContext();` is always wrapped in a `using` statement as per the examples outlined above.

**Comment by bielu** [comment]
I can actually reproduce that issue on both v9 and v10, which is not great 😓, I think it should be revisited again as it makes it impossible to work with nuCache.

**Comment by kjac** [comment]
Hi everyone 👋 

Sorry for the late response here.

`UmbracoHelper` won't work in a Hangfire context, it's meant to be used solely in a rendering context. `IPublishedCache` likely won't work either. You'll have to use the `IPublishedContentQuery` to access published content outside the rendering context

The following code (copied from [this article](https://cultiv.nl/blog/using-hangfire-to-update-umbraco-content/)) has been tested on 10.3.2 but should work on V9 too:

```csharp
using Hangfire;
using Hangfire.Console;
using Hangfire.Server;
using Umbraco.Cms.Core;
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.Web;

namespace Umbraco10._3._2;

public class HangfireComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.Services.AddScoped<IHangfireJob, HangfireJob>();
        
        RecurringJob.AddOrUpdate<IHangfireJob>(job => job.ReportFirstContentAtRoot(null), Cron.Yearly);
    }
}

public interface IHangfireJob
{
    void ReportFirstContentAtRoot(PerformContext? context);
}

public class HangfireJob : IHangfireJob
{
    private readonly IServiceProvider _serviceProvider;
    private readonly IUmbracoContextFactory _umbracoContextFactory;

    public HangfireJob(IServiceProvider serviceProvider, IUmbracoContextFactory umbracoContextFactory)
    {
        _serviceProvider = serviceProvider;
        _umbracoContextFactory = umbracoContextFactory;
    }

    public void ReportFirstContentAtRoot(PerformContext? context)
    {
        using var _ = _umbracoContextFactory.EnsureUmbracoContext();
        using var serviceScope = _serviceProvider.CreateScope();

        var query = serviceScope.ServiceProvider.GetRequiredService<IPublishedContentQuery>();

        var rootNode = query.ContentAtRoot().FirstOrDefault();
        if (rootNode != null)
        {
            context.WriteLine($"Root node retrieved from query - Id: {rootNode.Id} | Name: {rootNode.Name}"); 
        }
    }
}
```
