### ISSUE TITLE
Lock request time out period exceeded. The statement has been terminated. Umbraco.Web\Editors\PasswordChanger.cs:line 195

### ISSUE THREAD

**Issue by No1sBothered** [umbraco/Umbraco-CMS#10596]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.14

### Bug summary

We are seeing the following issue when using MembershipHelper ChangePassword:

`System.Data.SqlClient.SqlException (0x80131904): Lock request time out period exceeded.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 272
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<ExecuteNonQuery>b__31_0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 209
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 222
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 219
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteNonQuery() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 209
   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   at NPoco.Database.NPoco.IDatabaseHelpers.ExecuteNonQueryHelper(DbCommand cmd)
   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)
   at NPoco.Database.Execute(Sql Sql)
   at NPoco.Database.Execute(String sql, Object[] args)
   at Umbraco.Core.Persistence.SqlSyntax.SqlServerSyntaxProvider.ObtainWriteLock(IDatabase db, TimeSpan timeout, Int32 lockId) in D:\a\1\s\src\Umbraco.Core\Persistence\SqlSyntax\SqlServerSyntaxProvider.cs:line 285
   at Umbraco.Core.Persistence.SqlSyntax.SqlServerSyntaxProvider.WriteLock(IDatabase db, Int32[] lockIds) in D:\a\1\s\src\Umbraco.Core\Persistence\SqlSyntax\SqlServerSyntaxProvider.cs:line 278
   at Umbraco.Core.Scoping.Scope.ObtainWriteLock(Int32 lockId) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 738
   at Umbraco.Core.Scoping.Scope.LockInner(Guid instanceId, Dictionary`2& locks, HashSet`1& locksSet, Action`1 obtainLock, Action`2 obtainLockTimeout, Nullable`1 timeout, Int32[] lockIds) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 695
   at Umbraco.Core.Scoping.Scope.WriteLockInner(Guid instanceId, Nullable`1 timeout, Int32[] lockIds) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 647
   at Umbraco.Core.Scoping.Scope.WriteLockInner(Guid instanceId, Nullable`1 timeout, Int32[] lockIds) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 639
   at Umbraco.Core.Scoping.Scope.WriteLockInner(Guid instanceId, Nullable`1 timeout, Int32[] lockIds) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 639
   at Umbraco.Core.Scoping.Scope.WriteLock(Int32[] lockIds) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 606
   at Umbraco.Core.Services.Implement.MemberService.Save(IMember member, Boolean raiseEvents) in D:\a\1\s\src\Umbraco.Core\Services\Implement\MemberService.cs:line 835
   at Umbraco.Web.Security.Providers.UmbracoMembershipProvider`2.PerformChangePassword(String username, String oldPassword, String newPassword) in D:\a\1\s\src\Umbraco.Web\Security\Providers\UmbracoMembershipProvider.cs:line 88
   at Umbraco.Core.Security.MembershipProviderBase.ChangePassword(String username, String oldPassword, String newPassword) in D:\a\1\s\src\Umbraco.Core\Security\MembershipProviderBase.cs:line 370
   at Umbraco.Web.Editors.PasswordChanger.ChangePasswordWithMembershipProvider(String username, ChangingPasswordModel passwordModel, MembershipProvider membershipProvider) in D:\a\1\s\src\Umbraco.Web\Editors\PasswordChanger.cs:line 195
ClientConnectionId:e304e8f4-f899-49b4-8dd2-ce2a21fee32e
Error Number:1222,State:51,Class:16
ClientConnectionId before routing:087fe6ab-456f-4b46-9e49-fc4f030849c6
Routing Destination:xxx
`
This is happening when we have a high number of people trying to change their passwords at once.

We have set the following in the app settings: 

Umbraco.Core.MainDom.Lock = SqlMainDomLock
Umbraco.Core.SqlWriteLockTimeOut = 5000

We are on an Azure Web App and using Azure SQL

Any help would be appreciated!

### Steps to reproduce

call the MembershipHelper.ChangePassword at load.

**Comment by emma-hq** [comment]
Hey @No1sBothered 

Thanks for reporting this one and for all the info above. I need a little more info before I go ahead and progress this issue. Does this issue happen often? With the high numbers of people changing passwords all at once? The way that the membership provider is built doesn't take into account such high throughput writing. We find that using an external membership provider (something along the lines of Identity server) works well for higher volumes. 

Emma

**Comment by No1sBothered** [comment]
Hi @emma-hq thanks for the reply, when you say Identity Server, do you have any links to resources?

**Comment by No1sBothered** [comment]
@emma-hq also, this does happen often, we have tried MembershipHelper and MemberService but both seem to have the same effect at volume in locking up any call to the members.

**Comment by emma-hq** [comment]
Hey @No1sBothered  - when I asked if it happens often I meant in practice. Not under test conditions. Really I meant to ask if high numbers of people changed their passwords all at once. 

As for Identity server, the docs are fab and all can be found here  https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-5.0&tabs=visual-studio 

Emma

**Comment by No1sBothered** [comment]
Hey @emma-hq  this is in a live environment, it's only until we started to see a large number of real-world users that the issue became apparent.

**Comment by emma-hq** [comment]
Hey @No1sBothered 

Sorry, we're talking in two places! But yes, I'd go in the direction of something akin to Identity Server which'll scale nicely. I can't advise on approaches but I can point you to the forum where others can over [here](https://our.umbraco.com/forum/).

All the best,

Emma
