### ISSUE TITLE
V9: Concurrent update exception

### ISSUE THREAD

**Issue by vsilvar** [umbraco/Umbraco-CMS#10699]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc001

### Bug summary

A possible concurrency issue seems to exist in the `EnsureApplicationMainUrl` of `AspNetCoreHostingEnvironment` (which is called by `UmbracoRequestMiddleware` in all requests), when adding a new application url.
I assume this can only happen when two simultaneous requests occur when initially adding the new application url.

### Specifics

```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
   at System.Collections.Generic.HashSet`1.Add(T item)
   at Umbraco.Cms.Web.Common.AspNetCore.AspNetCoreHostingEnvironment.EnsureApplicationMainUrl(Uri currentApplicationUrl)
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Steps to reproduce

There's no easy way to reproduce the issue as it is a concurrency problem, but it should be possible to verify by looking at the code in question.

### Expected result / actual result

The `_applicationUrls` collection in `AspNetCoreHostingEnvironment` should either be replaced with a thread-safe collection variant concurrency control logic should be implemented when adding a new URL.

I think these should then prevent any such exception from happening.

**Comment by bergmania** [comment]
Thanks for reporting.. Should be fixed in https://github.com/umbraco/Umbraco-CMS/pull/10785
