### ISSUE TITLE
Cannot copy page with Block List block with property that 'looks like' JSON

### ISSUE THREAD

**Issue by rbottema** [umbraco/Umbraco-CMS#10879]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.15.1

### Bug summary

When trying to copy a page that contains a Block List block that contains a property that 'looks like' JSON (according to the `DetectIsJson` method), an error is thrown.

### Specifics

The copy action will fail with the stack trace below. It is caused by [the logic](https://github.com/umbraco/Umbraco-CMS/blob/release-8.15.1/src/Umbraco.Web/Compose/BlockEditorComponent.cs#L95-L129) going through all properties in order to properly copy them (probably related to making sure the GUIDs are unique). In order to properly handle nested blocks, it tries to parse the value as JSON if the value looks like JSON according to the [DetectIsJson method](https://github.com/umbraco/Umbraco-CMS/blob/release-8.15.1/src/Umbraco.Core/StringExtensions.cs#L147-L153). However, if the value is not actually JSON, this will throw an exception causing the entire copy action to fail.

Because of the lenient nature of the detect method, it also sees values like '[PLACEHOLDER]' or even '[FOO] bar [BAZ]' as JSON, basically any string that starts and ends with `{}` or `[]` brackets. Looking at the rest of the logic, the `Parse` should probably be wrapped in a try-catch (due to a lack of `TryParse` method on `JToken`) and ignore any `JsonReaderException` thrown, as the functionality only needs to do something if the value was an actual JSON object. If that is the correct approach, I can put together a PR for that.

```
Newtonsoft.Json.JsonReaderException: Error parsing boolean value. Path '', line 1, position 2.
   at Newtonsoft.Json.JsonTextReader.ParseTrue() in /_/Src/Newtonsoft.Json/JsonTextReader.cs:line 2403
   at Newtonsoft.Json.JsonTextReader.ParseValue() in /_/Src/Newtonsoft.Json/JsonTextReader.cs:line 1680
   at Newtonsoft.Json.JsonTextReader.Read() in /_/Src/Newtonsoft.Json/JsonTextReader.cs:line 419
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options) in /_/Src/Newtonsoft.Json/Linq/JContainer.cs:line 729
   at Newtonsoft.Json.Linq.JArray.Load(JsonReader reader, JsonLoadSettings settings) in /_/Src/Newtonsoft.Json/Linq/JArray.cs:line 138
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings) in /_/Src/Newtonsoft.Json/Linq/JToken.cs:line 2133
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings) in /_/Src/Newtonsoft.Json/Linq/JToken.cs:line 2183
   at Umbraco.Web.Compose.BlockEditorComponent.RecursePropertyValues(IEnumerable`1 blockData, Func`1 createGuid) in D:\a\1\s\src\Umbraco.Web\Compose\BlockEditorComponent.cs:line 114
   at Umbraco.Web.Compose.BlockEditorComponent.UpdateBlockListRecursively(BlockEditorData blockListData, Func`1 createGuid) in D:\a\1\s\src\Umbraco.Web\Compose\BlockEditorComponent.cs:line 81
   at Umbraco.Web.Compose.BlockEditorComponent.ReplaceBlockListUdis(String rawJson, Func`1 createGuid) in D:\a\1\s\src\Umbraco.Web\Compose\BlockEditorComponent.cs:line 52
   at Umbraco.Web.Compose.BlockEditorComponent.ReplaceBlockListUdis(String rawJson, Boolean onlyMissingUdis) in D:\a\1\s\src\Umbraco.Web\Compose\BlockEditorComponent.cs:line 33
   at Umbraco.Core.PropertyEditors.ComplexPropertyEditorContentEventHandler.UpdatePropertyValues(IEnumerable`1 props, Boolean onlyMissingKeys) in D:\a\1\s\src\Umbraco.Core\PropertyEditors\ComplexPropertyEditorContentEventHandler.cs:line 62
   at Umbraco.Core.PropertyEditors.ComplexPropertyEditorContentEventHandler.ContentService_Copying(IContentService sender, CopyEventArgs`1 e) in D:\a\1\s\src\Umbraco.Core\PropertyEditors\ComplexPropertyEditorContentEventHandler.cs:line 36
   at Umbraco.Core.Events.TypedEventHandler`2.Invoke(TSender sender, TEventArgs e)
   at Umbraco.Core.Events.QueuingEventDispatcherBase.DispatchCancelable[TSender,TArgs](TypedEventHandler`2 eventHandler, TSender sender, TArgs args, String eventName) in D:\a\1\s\src\Umbraco.Core\Events\QueuingEventDispatcherBase.cs:line 54
   at Umbraco.Core.Services.Implement.ContentService.Copy(IContent content, Int32 parentId, Boolean relateToOriginal, Boolean recursive, Int32 userId) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 2189
   at Umbraco.Web.Editors.ContentController.PostCopy(MoveOrCopy copy) in D:\a\1\s\src\Umbraco.Web\Editors\ContentController.cs:line 1716
```

### Steps to reproduce

- Install fresh 8.15.1 site with StarterKit
- Create element type. Add a single Textstring property.
- Create Block List data type. Add the element type we just created as possible block.
- On the Home document type (can be any), add a new property with the data type we just created.
- On the homepage, add a single block in our property and give it the title `[test]`. (some other test cases: `[test] test [test]` and `{test}`) Save.
- Try to create a copy of the homepage. Above error occurs.

### Expected result / actual result

Be able to copy the page without any errors.

---
_This item has been added to our backlog [AB#13401](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/13401)_

**Comment by nul800sebastiaan** [comment]
Interesting, definitely could be good to ignore properties that are being detected as JSON but then can't be parsed in `BlockEditorComponent.RecursePropertyValues` - just wondering if there's a risk of missing something then, but I guess not, you wouldn't be storing a UDI in something that's not JSON.. should be fine.
