### ISSUE TITLE
Umbraco v9 fails to start on Linux Azure App Service Plan

### ISSUE THREAD

**Issue by xelossan** [umbraco/Umbraco-CMS#11024]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc002

### Bug summary

Umbraco fails to start on Linux based web app on Azure (works fine on Windows). Am I missing some configuration or it doesn't support running on Linux plans?

### Steps to reproduce

I've created a new Umbraco project using the default template, installed it locally, added the necessary configuration for Azure Web App:

![image](https://user-images.githubusercontent.com/1189969/131977817-2d37fd99-7e0c-407e-a70a-177a5bd786e6.png)

and it works fine on App Service running on Windows plan, but after deploying to Linux-based plan, it fails to start and gives following error:

```
Unhandledexception. System.IO.IOException: Read-only file system
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Umbraco.Cms.Core.Composing.TypeLoader.GetFileBasePath()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypesHashFilePath()
   at Umbraco.Cms.Core.Composing.TypeLoader.get_CachedAssembliesHash()
   at Umbraco.Cms.Core.Composing.TypeLoader..ctor(ITypeFinder typeFinder, IRuntimeHash runtimeHash, IAppPolicyCache runtimeCache, DirectoryInfo localTempPath, ILogger`1 logger, IProfiler profiler, Boolean detectChanges, IEnumerable`1 assembliesToScan)
   at Umbraco.Cms.Core.Composing.TypeLoader..ctor(ITypeFinder typeFinder, IRuntimeHash runtimeHash, IAppPolicyCache runtimeCache, DirectoryInfo localTempPath, ILogger`1 logger, IProfiler profiler, IEnumerable`1 assembliesToScan)
   at Umbraco.Extensions.ServiceCollectionExtensions.AddTypeLoader(IServiceCollection services, Assembly entryAssembly, IHostingEnvironment hostingEnvironment, ILoggerFactory loggerFactory, AppCaches appCaches, IConfiguration configuration, IProfiler profiler)
   at Umbraco.Extensions.UmbracoBuilderExtensions.AddUmbraco(IServiceCollection services, IWebHostEnvironment webHostEnvironment, IConfiguration config)
   at MZ.Startup.ConfigureServices(IServiceCollection services) in C:\Users\tomas\Development\Umbraco9\MZ\Startup.cs:line 33
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at MZ.Program.Main(String[] args) in C:\Users\tomas\Development\Umbraco9\MZ\Program.cs:line 11
```

**Comment by nul800sebastiaan** [comment]
Looks like you need to set some permissions?

**Comment by nul800sebastiaan** [comment]
Does it work without updating the Host/Examine settings? And how are you deploying to App Service?

**Comment by xelossan** [comment]
Same error with default settings. I'm deploying from Visual Studio 2019, standard publish to App Service using Zip deploy.

![image](https://user-images.githubusercontent.com/1189969/131984406-d17152f6-1874-4092-862b-065676cb4090.png)

**Comment by nul800sebastiaan** [comment]
Thanks! We don't officially support Linux yet, so I can't really tell you what's going on at the moment. I am assuming it's some kind of permissions issue, but I can't be sure. I also don't know if Visual Studio's publisher has a way to anticipate what permissions certain folders need to have. I would encourage you to do some more investigating, look at logs on the server as well, it might give some clues of what's wrong.

**Comment by Shazwazza** [comment]
Isn't zip deploy read only? Umbraco cms isn't read only, it needs to write many files to disk.

**Comment by bielu** [comment]
@xelossan that is actually thing which I figure out, you need deploy with zip deploy, but you need turn off app setting run from package, then webapp will be not read only.
as example:
https://stackoverflow.com/questions/53630773/how-to-disable-read-only-mode-in-azure-function-app

**Comment by xelossan** [comment]
@bielu thanks for pointing me in the right direction :) changing the app setting wasn't enough, but publishing from VS Code did the trick, I guess it uses different settings than full VS under the hood. Looks like it's working fine now.

**Comment by Zeegaan** [comment]
Hello there! I spent most of my day smacking my head against the wall with this one 😢

But i did manage to get it to work atleast! It seemt like the others mentioned that the Azure Appservice on Linux is read-only,
so you'll have to manually configure that. 

With the very helpful link that @bielu provided, it seems that after publishing you have to delete the `WEBSITE_RUN_FROM_ZIP` or `WEBSITE_RUN_FROM_PACKAGE` configuration, but for me that didn't make it work either. 

I also had to add a `WEBSITE_RUN_FROM_ZIP or WEBSITE_RUN_FROM_PACKAGE` and set the value to `true` but atleast that made it work smoothly!

Seems like the `WEBSITE_RUN_FROM_ZIP` or `WEBSITE_RUN_FROM_PACKAGE` returns every time you publish though.. so for now you'd have to manually delete it from configuration every time you publish.

Hopefully my findings will help if anyone runs Umbraco with Azure Appservice on Linux 💪 

As a note though - this workaround was tested in both Visual studio & VS Code and both worked for me 👍
