### ISSUE TITLE
Umbraco Boot Fails: Unable to resolve type: Umbraco.Core.Services.ServiceContext

### ISSUE THREAD

**Issue by c-hurst** [umbraco/Umbraco-CMS#11043]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.12.2

### Bug summary

During application startup, after an app pool recycle, Umbraco failed to boot and hung on the Boot Failed screen. This is the first time this happened on a site that has been running for several weeks. This issue also happened with another site on the same version of Umbraco, but running on a different server.

This is the error logged in Umbraco:

`"Boot failed." (39711ms) [Timing "7c41b4b"]
-- | -- | -- | --
ExceptionUmbraco.Core.Exceptions.BootFailedException: A connection string is configured but Umbraco could not connect to the database.    at Umbraco.Core.RuntimeState.DetermineRuntimeLevel(IUmbracoDatabaseFactory databaseFactory) in D:\a\1\s\src\Umbraco.Core\RuntimeState.cs:line 188    at Umbraco.Core.Runtime.CoreRuntime.DetermineRuntimeLevel(IUmbracoDatabaseFactory databaseFactory, IProfilingLogger profilingLogger) in D:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 375    at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in D:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 179
`

### Specifics

I believe the error in the Umbraco log (connection string issue) is a red herring. Digging in the windows logs I discovered this happening:

`
Event code: 3008 
Event message: A configuration error has occurred. 
Event time: 9/6/2021 4:51:44 PM 
Event time (UTC): 9/6/2021 8:51:44 PM 
 
Exception information: 
    Exception type: ConfigurationErrorsException 
    Exception message: Exception has been thrown by the target of an invocation. (xxxxxxxxxxxxxx\website\web.config line 144)
   at System.Web.Security.Roles.Initialize()
   at System.Web.Security.RoleManagerModule.OnLeave(Object source, EventArgs eventArgs)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Exception has been thrown by the target of an invocation.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at System.Web.HttpRuntime.CreatePublicInstanceByWebObjectActivator(Type type)
   at System.Web.Configuration.ProvidersHelper.InstantiateProvider(ProviderSettings providerSettings, Type providerType)

Unable to resolve type: Umbraco.Core.Services.ServiceContext, service name: 
   at LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4754
   at LightInject.ServiceContainer.CreateDefaultDelegate(Type serviceType, Boolean throwError) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4705
   at LightInject.ServiceContainer.GetInstance(Type serviceType) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3437
   at Umbraco.Core.FactoryExtensions.GetInstance[T](IFactory factory) in D:\a\1\s\src\Umbraco.Core\FactoryExtensions.cs:line 23
   at Umbraco.Web.Security.Providers.MembersRoleProvider..ctor() in D:\a\1\s\src\Umbraco.Web\Security\Providers\MembersRoleProvider.cs:line 23
`

It appears that for some reason, the MembersRoleProvider could not obtain a ServiceContext.

This is the code that was executing:
`
        public MembersRoleProvider()
            : this(Current.Services.MemberService)
        {
        }
`

Current.Services.MemberService:

`        public static ServiceContext Services
            => Factory.GetInstance<ServiceContext>();
`

### Steps to reproduce

Unfortunately this appears to be very infrequent, random occurrence. So far I've seen it happen twice in total, on two different sites.

Could there be some race condition that causes the MemberRoleProvider to initialize before the Services have been injected?

### Expected result / actual result

Site should start after an application recycle.

**Comment by nul800sebastiaan** [comment]
Are you doing any integrations with Members in your custom code that is going to need the RoleProvider at some point during booting of the site? It seems like it's asking for an instance prematurely. 

This could happen when you have a Composer that is adding things a bit too early, adding an attribute to ensure that the composer gets added when Umbraco is ready is recommended: https://our.umbraco.com/Documentation/Implementation/Composing/#runtimelevel

Can you have a look and verify that?

Of course, it could also very well be that Umbraco actually had a problem connecting to the database, we have a retry strategy but we have to give up at some point.

**Comment by c-hurst** [comment]
@nul800sebastiaan Thanks for the reply. I appreciate it's a very difficult issue to investigate )) 

It's definitely possible that the DB was glitched, but we have several sites running off the same SQL server and they were running fine.

We don't use membership at all on our sites, but we do have a lot of composers and crazy customisations, and maybe one of those is accessing a service that happens to include the role provider? 

I'll run through them and check I haven't missed an attribute somewhere.
