### ISSUE TITLE
Could not find a datatype with identifier 0. Parameter name: id

### ISSUE THREAD

**Issue by ssplyuvrajsingh** [umbraco/Umbraco-CMS#11147]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.15.3

### Bug summary

Failed to build models. Could not find a datatype with identifier 0.

After deploying my changes at the dev site then getting an error on the dev site but the local system working fine.

### Specifics

Geeting error :-

Last generation failed with the following error: Failed to build models. Could not find a datatype with identifier 0. Parameter name: id

```
at Umbraco.Core.Models.PublishedContent.PublishedContentTypeFactory.GetDataType(Int32 id) at Umbraco.Core.Models.PublishedContent.PublishedPropertyType..ctor(String propertyTypeAlias, Int32 dataTypeId, Boolean isUserProperty, ContentVariation variations, PropertyValueConverterCollection propertyValueConverters, IPublishedModelFactory publishedModelFactory, IPublishedContentTypeFactory factory) at Umbraco.Core.Models.PublishedContent.PublishedPropertyType..ctor(IPublishedContentType contentType, PropertyType propertyType, PropertyValueConverterCollection propertyValueConverters, IPublishedModelFactory publishedModelFactory, IPublishedContentTypeFactory factory) at Umbraco.Core.Models.PublishedContent.PublishedContentTypeFactory.CreatePropertyType(IPublishedContentType contentType, PropertyType propertyType) at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext()
at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source) at Umbraco.Core.Models.PublishedContent.PublishedContentType..ctor(IContentTypeComposition contentType, IPublishedContentTypeFactory factory) at Umbraco.Core.Models.PublishedContent.PublishedContentTypeFactory.CreateContentType(IContentTypeComposition contentType) at Umbraco.ModelsBuilder.Embedded.UmbracoServices.GetTypes(PublishedItemType itemType, IContentTypeComposition[] contentTypes) at Umbraco.ModelsBuilder.Embedded.UmbracoServices.GetAllTypes() at Umbraco.ModelsBuilder.Embedded.Building.ModelsGenerator.GenerateModels() at Umbraco.ModelsBuilder.Embedded.BackOffice.ModelsBuilderDashboardController.BuildModels()
```

### Steps to reproduce

Failed to build models. Could not find a datatype with identifier 0.

**Comment by nul800sebastiaan** [comment]
Thanks @ssplyuvrajsingh - I found this: 

- https://our.umbraco.com/forum/umbraco-8/98226-failed-to-build-models
- https://our.umbraco.com/forum/using-umbraco-and-getting-started/102602-failed-to-build-models-could-not-find-a-datatype-with-identifier-88
- https://github.com/umbraco/Umbraco-CMS/issues/5386

This is something that seems to happen sporadically for some people but hasn't been reported for quite a while. Seems like there's something wrong in your site but it's not possible to guess what the problem is from this error. If you have steps to reproduce this error this would be great. Also, it's good to list an error, but please also tell us where you're seeing it so there's better clues of where to look.

**Comment by nul800sebastiaan** [comment]
Also: what modelsbuilder mode are you using?

**Comment by ssplyuvrajsingh** [comment]
> Also: what modelsbuilder mode are you using?

<add key="Umbraco.ModelsBuilder.ModelsMode" value="PureLive"/>

**Comment by ssplyuvrajsingh** [comment]
> Also: what modelsbuilder mode are you using?

<add key="Umbraco.ModelsBuilder.ModelsMode" value="PureLive"/>

**Comment by ssplyuvrajsingh** [comment]
> Also: what modelsbuilder mode are you using?

**Comment by ssplyuvrajsingh** [comment]
> Also: what modelsbuilder mode are you using?

<add key="Umbraco.ModelsBuilder.ModelsMode" value="PureLive"/>

**Comment by nul800sebastiaan** [comment]
Do you have any more info please? Just going by an error message is not enough to be able to find the cause of the problem. Describe what steps you took exactly, where you see errors, anything you might have observed that is strange other than this error, when did it still work, what did you do before it stopped working, etc.

**Comment by ssplyuvrajsingh** [comment]
This issue was resolved by Umbraco support.
Last message by Umbraco support see that -:

Yes just go an update
﻿
﻿Our developers attached Deploy to the project locally and the issue is with the member type UDA. They've recently made some changes with the sorting and it seems to have caused some issues.
﻿
﻿We have fixed that and the new member type has been extracted.
﻿
﻿Now there is another issue with dictionary items. Locally we removed the first UDA files to see if it was the only issue but then there was another dictionary item issue.
﻿
Some artifacts collide on unique identifiers.
This means that they have different Udis, yet
they refer to the same unique Umbraco object
and therefore cannot be processed.
---------------------------------------------
Collisions for entity type "dictionary-item": 
  Collisions for unique identifier "USN Members Navigation Logout":
    Artifact: umb://dictionary-item/291b52b3175d45d1b87a4abe4436f4a4
    {DictionaryItem umb://dictionary-item/35dbf444046e477e8cbf4e2cd3cfd51b}

﻿If it's not visible in the Cloud portal then you can see it in Kudu for the Dev env.
﻿C:\home\site\wwwroot\data - deploy.log
﻿
So when we get those fixed then the models will also be build as it should
﻿
﻿Best,
-Dennis
