### ISSUE TITLE
Composition with BlockList property causing errors on document types that doesn't have this composition v9 rc-002

### ISSUE THREAD

**Issue by lkoruba** [umbraco/Umbraco-CMS#11177]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc002 and 9.0.0-rc003 and rc-004

### Bug summary

We have composition with Block List property called "blockModules" and it's attached to some content pages. 
We have also Global Settings document type which doesn't have this composition and on Save And Publish it throws an error  "One or more errors occurred. (The given key 'blockModules' was not present in the dictionary.)".

For test case I've also created document type with only textsring property but it throws exact same error. Document types are added on root level as Homepage doc type which has this property "blockModules". Not sure how it's relevant.

![image](https://user-images.githubusercontent.com/20399783/134473678-6e6a9ad2-df5d-4bb7-b492-df209265b4d4.png)

```
at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Umbraco.Cms.Core.Events.EventAggregator.Publish[TNotification](TNotification notification)
   at Umbraco.Cms.Core.Events.ScopedNotificationPublisher.ScopeExit(Boolean completed)
   at Umbraco.Cms.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)
   at Umbraco.Cms.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)
   at Umbraco.Cms.Core.Scoping.Scope.Dispose()
   at Umbraco.Cms.Core.Services.Implement.ContentService.SaveAndPublish(IContent content, String culture, Int32 userId)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PublishInternal(ContentItemSave contentItem, String defaultCulture, String cultureForInvariantErrors, Boolean& wasCancelled, String[]& successfulCultures)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PostSaveInternal(ContentItemSave contentItem, Func`2 saveMethod, Func`2 mapToDisplay)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PostSave(ContentItemSave contentItem)
   at lambda_method1170(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

### Steps to reproduce

1. Add a composition with Block List
2. Create document type A with this composition and add to the root.
3. Create another document B type without this composition.
4. Add B to the root and try to save it.
5. It should throw an error.

Homepage has blockModules and Global Settings doesn't. On Global Settings error occurs on save.

![image](https://user-images.githubusercontent.com/20399783/134508465-b577e17d-e980-41f3-a11f-4d9c20178aa1.png)

![image](https://user-images.githubusercontent.com/20399783/134508628-90caedf5-36df-4c60-b741-8e83222a034e.png)

**Comment by lkoruba** [comment]
It turned out it was internal issue but stack trace was confusing and misleading. After some hacky changes we managed to get to the problem but stack trace should be more specific.
