### ISSUE TITLE
[FIX available] Examine errors when upgrading from v9 rc003 to rc004

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#11179]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9.0.0-rc004

### Bug summary

Just putting this issue here and keeping it open for a while since people seems to run into this quite a bit. 

If you run into an application error after upgrading to rc004:

![image](https://user-images.githubusercontent.com/304656/134487696-904f2c72-8404-43d2-b6e0-df77f4519844.png)

```
System.Reflection.ReflectionTypeLoadException
  HResult=0x80131602
  Message=Could not load all types from "Umbraco.Examine.Lucene, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.TypeLoadException on Umbraco.Cms.Infrastructure.Examine.LuceneIndexDiagnostics: Method 'GetDocumentCountAsync' in type 'Umbraco.Cms.Infrastructure.Examine.LuceneIndexDiagnostics' from assembly 'Umbraco.Examine.Lucene, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
. System.TypeLoadException on Examine.Lucene.Providers.LuceneIndex: Method 'GetSearcher' in type 'Examine.Lucene.Providers.LuceneIndex' from assembly 'Examine.Lucene, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
. System.TypeLoadException on Examine.Lucene.Providers.LuceneIndex: Method 'GetSearcher' in type 'Examine.Lucene.Providers.LuceneIndex' from assembly 'Examine.Lucene, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
. System.TypeLoadException on Umbraco.Cms.Infrastructure.Examine.LuceneIndexDiagnostics: Method 'GetDocumentCountAsync' in type 'Umbraco.Cms.Infrastructure.Examine.LuceneIndexDiagnostics' from assembly 'Umbraco.Examine.Lucene, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
. System.TypeLoadException on Examine.Lucene.Providers.LuceneIndex: Method 'GetSearcher' in type 'Examine.Lucene.Providers.LuceneIndex' from assembly 'Examine.Lucene, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
. System.TypeLoadException on Examine.IndexOptions: Could not load type 'Examine.IndexOptions' from assembly 'Examine.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.

Method 'GetDocumentCountAsync' in type 'Umbraco.Cms.Infrastructure.Examine.LuceneIndexDiagnostics' from assembly 'Umbraco.Examine.Lucene, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'GetSearcher' in type 'Examine.Lucene.Providers.LuceneIndex' from assembly 'Examine.Lucene, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'GetSearcher' in type 'Examine.Lucene.Providers.LuceneIndex' from assembly 'Examine.Lucene, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'GetDocumentCountAsync' in type 'Umbraco.Cms.Infrastructure.Examine.LuceneIndexDiagnostics' from assembly 'Umbraco.Examine.Lucene, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'GetSearcher' in type 'Examine.Lucene.Providers.LuceneIndex' from assembly 'Examine.Lucene, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Could not load type 'Examine.IndexOptions' from assembly 'Examine.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.
  Source=Umbraco.Core
  StackTrace:
   at Umbraco.Cms.Core.Composing.TypeFinder.GetTypesWithFormattedException(Assembly a)
   at Umbraco.Cms.Core.Composing.TypeFinder.GetClassesWithBaseType(Type baseType, IEnumerable`1 assemblies, Boolean onlyConcreteClasses, Func`2 additionalFilter)
   at Umbraco.Cms.Core.Composing.TypeFinder.FindClassesOfType(Type assignTypeFrom, IEnumerable`1 assemblies, Boolean onlyConcreteClasses)
   at Umbraco.Extensions.TypeFinderExtensions.FindClassesOfType[T](ITypeFinder typeFinder, IEnumerable`1 assemblies, Boolean onlyConcreteClasses)
   at Umbraco.Cms.Core.Composing.TypeLoader.<>c__DisplayClass56_0`1.<GetTypes>b__0()
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternalLocked(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternal(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypes[T](Boolean cache, IEnumerable`1 specificAssemblies)
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilderExtensions.AddAllCoreCollectionBuilders(IUmbracoBuilder builder)
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder.AddCoreServices()
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder..ctor(IServiceCollection services, IConfiguration config, TypeLoader typeLoader, ILoggerFactory loggerFactory, IProfiler profiler, AppCaches appCaches, IHostingEnvironment hostingEnvironment)
   at Umbraco.Extensions.UmbracoBuilderExtensions.AddUmbraco(IServiceCollection services, IWebHostEnvironment webHostEnvironment, IConfiguration config)
   at Website.Startup.ConfigureServices(IServiceCollection services) in D:\01-Codigo\OTU\otu_enerTran9\src\Website\Startup.cs:line 53                                       
```

Then this is caused by an old version of Examine 2.0.0 being available previously in June on MyGet. It was accidentally not marked as a pre-release. It it possible that you accidentally got that version at some point and now it's stuck in your local NuGet cache on your machine.

To fix, you can run the following commands:

```
dotnet nuget locals all --clear
dotnet restore
dotnet build
dotnet run
```

### Steps to reproduce

Upgrade v9 to RC4

**Comment by nul800sebastiaan** [comment]
Will close this now that v9 is out and the reports of this bug have stopped.

**Comment by emmagarland** [comment]
Same here, thanks @nul800sebastiaan!
