### ISSUE TITLE
v9 RC4 fatal failure - cannot load Umbraco.Examine.Lucene 

### ISSUE THREAD

**Issue by JoseMarcenaro** [umbraco/Umbraco-CMS#11185]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc004

### Bug summary

A brand new 9.0.0-rc004 website built with VS or the command line fails to run with a fatal error loading the `Umbraco.Examine.Lucene` assembly.

### Specifics

```
System.Reflection.ReflectionTypeLoadException
  HResult=0x80131602
  Message=Could not load all types from "Umbraco.Examine.Lucene, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.TypeLoadException on Umbraco.Cms.Infrastructure.Examine.LuceneIndexDiagnostics: Method 'GetDocumentCountAsync' in type 'Umbraco.Cms.Infrastructure.Examine.LuceneIndexDiagnostics' from assembly 'Umbraco.Examine.Lucene, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
. System.TypeLoadException on Examine.Lucene.Providers.LuceneIndex: Method 'GetSearcher' in type 'Examine.Lucene.Providers.LuceneIndex' from assembly 'Examine.Lucene, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
. System.TypeLoadException on Examine.Lucene.Providers.LuceneIndex: Method 'GetSearcher' in type 'Examine.Lucene.Providers.LuceneIndex' from assembly 'Examine.Lucene, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
. System.TypeLoadException on Umbraco.Cms.Infrastructure.Examine.LuceneIndexDiagnostics: Method 'GetDocumentCountAsync' in type 'Umbraco.Cms.Infrastructure.Examine.LuceneIndexDiagnostics' from assembly 'Umbraco.Examine.Lucene, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
. System.TypeLoadException on Examine.Lucene.Providers.LuceneIndex: Method 'GetSearcher' in type 'Examine.Lucene.Providers.LuceneIndex' from assembly 'Examine.Lucene, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
. System.TypeLoadException on Examine.IndexOptions: Could not load type 'Examine.IndexOptions' from assembly 'Examine.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.

Method 'GetDocumentCountAsync' in type 'Umbraco.Cms.Infrastructure.Examine.LuceneIndexDiagnostics' from assembly 'Umbraco.Examine.Lucene, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'GetSearcher' in type 'Examine.Lucene.Providers.LuceneIndex' from assembly 'Examine.Lucene, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'GetSearcher' in type 'Examine.Lucene.Providers.LuceneIndex' from assembly 'Examine.Lucene, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'GetDocumentCountAsync' in type 'Umbraco.Cms.Infrastructure.Examine.LuceneIndexDiagnostics' from assembly 'Umbraco.Examine.Lucene, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'GetSearcher' in type 'Examine.Lucene.Providers.LuceneIndex' from assembly 'Examine.Lucene, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Could not load type 'Examine.IndexOptions' from assembly 'Examine.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.
  Source=Umbraco.Core
  StackTrace:
   at Umbraco.Cms.Core.Composing.TypeFinder.GetTypesWithFormattedException(Assembly a)
   at Umbraco.Cms.Core.Composing.TypeFinder.GetClassesWithBaseType(Type baseType, IEnumerable`1 assemblies, Boolean onlyConcreteClasses, Func`2 additionalFilter)
   at Umbraco.Cms.Core.Composing.TypeFinder.FindClassesOfType(Type assignTypeFrom, IEnumerable`1 assemblies, Boolean onlyConcreteClasses)
   at Umbraco.Extensions.TypeFinderExtensions.FindClassesOfType[T](ITypeFinder typeFinder, IEnumerable`1 assemblies, Boolean onlyConcreteClasses)
   at Umbraco.Cms.Core.Composing.TypeLoader.<>c__DisplayClass56_0`1.<GetTypes>b__0()
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternalLocked(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternal(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypes[T](Boolean cache, IEnumerable`1 specificAssemblies)
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilderExtensions.AddAllCoreCollectionBuilders(IUmbracoBuilder builder)
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder.AddCoreServices()
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder..ctor(IServiceCollection services, IConfiguration config, TypeLoader typeLoader, ILoggerFactory loggerFactory, IProfiler profiler, AppCaches appCaches, IHostingEnvironment hostingEnvironment)
   at Umbraco.Extensions.UmbracoBuilderExtensions.AddUmbraco(IServiceCollection services, IWebHostEnvironment webHostEnvironment, IConfiguration config)
   at Website.Startup.ConfigureServices(IServiceCollection services) in D:\01-Codigo\OTU\otu_enerTran9\src\Website\Startup.cs:line 53                                       
```

### Steps to reproduce

Create a new RC website from scratch:
```
dotnet new --install Umbraco.Templates::9.0.0-rc004
dotnet new umbraco -n Website
cd Website
dotnet run
```

### Expected result
The Umbraco installation should be launched

### Actual result
The app doesn't run - the exception listed above is thrown.

**Comment by JoseMarcenaro** [comment]
Note: the same happens when upgrading an existing website to RC4

**Comment by JoseMarcenaro** [comment]
It looks like this is a duplicate of #11179.
The same fix applies:
```
dotnet nuget locals all --clear
dotnet restore
dotnet build
dotnet run
```

**Comment by nul800sebastiaan** [comment]
Yep, that's what we've described in #11179  👍  Sorry for the trouble!
