### ISSUE TITLE
An error occurred while trying to Add language

### ISSUE THREAD

**Issue by codekenjin** [umbraco/Umbraco-CMS#11427]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.1

### Bug summary

An error occurred when clicked on Settings->Languages->Add language

### Specifics

URL:https://localhost:44303/umbraco#/settings/languages/edit/-1?create=true
Browsers: Chrome v94.0.4606.81 & Firefox v93.0

Error message:

Received an error from the server
An error occurred

An item with the same key has already been added. Key: pa
Exception Details
System.ArgumentException, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: An item with the same key has already been added. Key: pa
Stacktrace

at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)

   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)

   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)

   at Umbraco.Cms.Web.BackOffice.Controllers.LanguageController.GetAllCultures()

   at lambda_method911(Closure , Object , Object[] )

   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

### Steps to reproduce

Click on Settings->Languages->Add language

### Expected result / actual result

Expected result: A list of languages for choosing
Actual result: Error occurred, no language for choosing

**Comment by uppercuut** [comment]
**An item with the same key has already been added. Key: pa**

the language is already inserted.

is it shown in the list of languages ?

**Comment by codekenjin** [comment]
> **An item with the same key has already been added. Key: pa**
> 
> the language is already inserted.
> 
> is it shown in the list of languages ?

There is no language list to show for me and I tried to "Add language" before I add anything. So don't know why.

**Comment by codekenjin** [comment]
> Hi @codekenjin ..
> 
> Can you try to execute this on your setup
> 
> ```
> CultureInfo.GetCultures(CultureTypes.AllCultures)
>                 .Select(x=>x.Name)
>                 .Distinct()
>                 .Where(x => !x.IsNullOrWhiteSpace())
>                 .Select(x => new CultureInfo(x)) // important!
>                 .OrderBy(x => x.EnglishName)
>                 .ToDictionary(x => x.Name, x => x.EnglishName);
> ```
> 
> and ensure that do not fail, as I cannot reproduce your problem on my setup.

Hi bergmania,

May I know where I should put your script to execute? Thanks.

**Comment by bergmania** [comment]
@codekenjin It doesn't matter.. You could put in a template/view like this:

```
@using System.Globalization
<ul>
@foreach( var kvp in CultureInfo.GetCultures(CultureTypes.AllCultures)
                .Select(x=>x.Name)
                .Distinct()
                .Where(x => !x.IsNullOrWhiteSpace())
                .Select(x => new CultureInfo(x)) // important!
                .OrderBy(x => x.EnglishName)
                .ToDictionary(x => x.Name, x => x.EnglishName))
{
   <li>
       <ul>
           <li>@kvp.Key</li>
           <li>@kvp.Value</li>
       </ul>
       
   </li>             
}
</ul>
```

Ensure it does work and please post the outcome here :)
