### ISSUE TITLE
[The process cannot access the file] \umbraco\Data\TEMP\NuCache\NuCache.Content.db

### ISSUE THREAD

**Issue by Arextion** [umbraco/Umbraco-CMS#11559]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.1

### Bug summary

After sitting up site from Clean Blog V9 example project, creating compositions etc, i was about to create some content pages when i get this error in the backend.

I get another error in the frontend, probably related:
**ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'handle')**

I can see it's a problem that occurred before, but i haven't seen any reports for v9 and the steps to fix does not seem to work in v9 directly.

**The process cannot access the file** 
```
'C:\Git\Offtware\Web\CpsSolutions\CpsSolutions.Site\umbraco\Data\TEMP\NuCache\NuCache.Content.db' because it is being used by another process.

**Exception Details**
System.IO.IOException, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: The process cannot access the file 'C:\Git\Offtware\Web\CpsSolutions\CpsSolutions.Site\umbraco\Data\TEMP\NuCache\NuCache.Content.db' because it is being used by another process.

**Stacktrace**
at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at CSharpTest.Net.IO.TransactedCompoundFile..ctor(Options options)
   at CSharpTest.Net.Storage.BTreeFileStoreV2..ctor(Options options)
   at CSharpTest.Net.Collections.BPlusTree`2.OptionsV2.CreateStorage()
   at CSharpTest.Net.Collections.BPlusTree`2.NodeCacheBase..ctor(BPlusTreeOptions`2 options)
   at CSharpTest.Net.Collections.BPlusTree`2.NodeCacheNone..ctor(BPlusTreeOptions`2 options)
   at CSharpTest.Net.Collections.BPlusTree`2..ctor(BPlusTreeOptions`2 ioptions)
   at CSharpTest.Net.Collections.BPlusTree`2..ctor(OptionsV2 optionsV2)
   at Umbraco.Cms.Infrastructure.PublishedCache.DataSource.BTree.GetTree(String filepath, Boolean exists, NuCacheSettings settings, ContentDataSerializer contentDataSerializer)
   at Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotService.MainDomRegister()
   at Umbraco.Cms.Core.Runtime.MainDom.Register(Action install, Action release, Int32 weight)
   at Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotService.<EnsureCaches>b__48_0()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotService.EnsureCaches()
   at Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotService.CreatePublishedSnapshot(String previewToken)
   at Umbraco.Cms.Web.Common.UmbracoContext.UmbracoContext.<>c__DisplayClass11_0.<.ctor>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at Umbraco.Cms.Web.Common.UmbracoContext.UmbracoContext.get_PublishedSnapshot()
   at Umbraco.Cms.Web.Common.UmbracoContext.UmbracoContext.get_Content()
   at Umbraco.Cms.Core.Routing.AliasUrlProvider.GetOtherUrls(Int32 id, Uri current)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at Umbraco.Extensions.UrlProviderExtensions.GetContentUrlsAsync(IContent content, IPublishedRouter publishedRouter, IUmbracoContext umbracoContext, ILocalizationService localizationService, ILocalizedTextService textService, IContentService contentService, IVariationContextAccessor variationContextAccessor, ILogger`1 logger, UriUtility uriUtility, IPublishedUrlProvider publishedUrlProvider)
   at Umbraco.Cms.Web.BackOffice.Mapping.ContentMapDefinition.GetUrls(IContent source)
   at Umbraco.Cms.Web.BackOffice.Mapping.ContentMapDefinition.Map(IContent source, ContentItemDisplay target, MapperContext context)
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, Type sourceType, MapperContext context)
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, MapperContext context)
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, Action`1 f)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.MapToDisplay(IContent content, Action`1 contextOptions)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.MapToDisplay(IContent content)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.GetById(Int32 id)
   at lambda_method485(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

```

### Steps to reproduce

All i did was to install umbraco by the Clean Blog V9 example, setup compositions etc and got as far as to create content pages.

**Comment by Arextion** [comment]
Hmm. I temporarily made a composer to disable nuCache, it then worked. I then removed the composer again, and it still worked...

```
public class DisableNuCacheDatabaseComposer : IComposer
    {
        public void Compose(IUmbracoBuilder builder)
        {
            var settings = new Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotServiceOptions
            {
                IgnoreLocalDb = true
            };
            builder.Services.AddSingleton(settings);
        }
    }
```

**Comment by Arextion** [comment]
Nope, i was wrong. It doesn't work without the composer.

So, what is really wrong here?

**Comment by Arextion** [comment]
Any solution to this?

**Comment by Arextion** [comment]
Can't replicate anymore.

**Comment by rossparachute** [comment]
> Hmm. I temporarily made a composer to disable nuCache, it then worked. I then removed the composer again, and it still worked...
> 
> ```
> public class DisableNuCacheDatabaseComposer : IComposer
>     {
>         public void Compose(IUmbracoBuilder builder)
>         {
>             var settings = new Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotServiceOptions
>             {
>                 IgnoreLocalDb = true
>             };
>             builder.Services.AddSingleton(settings);
>         }
>     }
> ```



- Umbraco v10.8.4 (legacy app)
- Hangfire v1.8.0-beta4
- Hosted on Azure WebApps

For any poor souls in the future, adding in @Arextion 's composer was the only thing that sorted this for us. Head scratcher.

Without that all content nodes in the admin would fail to load as "_NuCache.Content.db is locked by another process_".  

Another thing of note, was setting the _LocalTempStorageLocation_ to "Default" instead of the [advised](https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/fundamentals/setup/server-setup/azure-web-apps) "EnvironmentTemp".

You'll need to make sure your Azure env var _WEBSITE_RUN_FROM_PACKAGE_ is set to "**0**" (or removed) as Umbraco needs to be able to write to disk. Zip deploy is what we use for our publish method and will make sure the web app is writable once deployed from Azure DevOps to your Azure Deploy Slot and WebApp.

**Azure Umbraco Config** 

```
  {
    "name": "UMBRACO__CMS__Examine__LuceneDirectoryFactory",
    "value": "SyncedTempFileSystemDirectoryFactory",
    "slotSetting": false
  },
  {
    "name": "UMBRACO__CMS__Global__MainDomLock",
    "value": "FileSystemMainDomLock",
    "slotSetting": false
  },
  {
    "name": "UMBRACO__CMS__Hosting__LocalTempStorageLocation",
    "value": "Default",
    "slotSetting": false
  },
```
