### ISSUE TITLE
Nullreference error when saving document type changes after upgrading from 9.0.1 to 9.1.1

### ISSUE THREAD

**Issue by stefanie27** [umbraco/Umbraco-CMS#11694]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.1

### Bug summary

After upgrade from 9.0.1 to 9.1.1 nullreference error when saving document type changes

### Specifics

Error:

An error occurred
Object reference not set to an instance of an object.

Exception Details

```
System.NullReferenceException, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: Object reference not set to an instance of an object.

at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentTypeRepository.PersistHistoryCleanup(IContentType entity)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentTypeRepository.PersistUpdatedItem(IContentType entity)
   at Umbraco.Cms.Core.Cache.FullDataSetRepositoryCachePolicy`2.Update(TEntity entity, Action`1 persistUpdated)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.EntityRepositoryBase`2.Save(TEntity entity)
   at Umbraco.Cms.Core.Services.Implement.ContentTypeServiceBase`2.Save(TItem item, Int32 userId)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentTypeController.<PostSave>b__30_1(IContentType type)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentTypeControllerBase`1.PerformPostSave[TContentTypeDisplay,TContentTypeSave,TPropertyType](TContentTypeSave contentTypeSave, Func`2 getContentType, Action`1 saveContentType, Action`1 beforeCreateNew)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentTypeController.PostSave(DocumentTypeSave contentTypeSave)
   at lambda_method1386(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

### Steps to reproduce

- Upgrade to latest release 9.1.1
- In Umbraco CMS go to Settings and under Document Types select an existing document type and click Save

### Expected result / actual result

Saving changes without issues

**Comment by stefanie27** [comment]
I added two changes to prevent the error. But I don't understand, why the HistoryCleanup object is null.

**Umbraco.Infrastructure\Persistence\Repositories\Implement\ContentTypeRepository.cs**

![image](https://user-images.githubusercontent.com/9352024/143270740-822bac73-a467-44b5-919d-bae42b21565a.png)

**Umbraco.Core\Models\Mapping\ContentTypeMapDefinition.cs**

![image](https://user-images.githubusercontent.com/9352024/143270911-f74570d0-d2b0-4731-94f9-ae0db06ad50b.png)

**Comment by bergmania** [comment]
This should only be possible if they client side files are cached from 9.0.1.

Are you sure the client side files are not cached?

**Comment by ronaldbarendse** [comment]
This issue is fixed in PR https://github.com/umbraco/Umbraco-CMS/pull/11660#pullrequestreview-812539345 (that will be merged up to v9) 👍🏻

**Comment by p-m-j** [comment]
With current js bundles this object is always posted.

Backoffice doesn't invalidate smidge bundles correctly between versions which can be tracked here https://github.com/umbraco/Umbraco-CMS/issues/11698

That doesn't excuse the web api endpoints / services not being defensive enough as our javascript is potentially not the only client of the web api endpoints / services which as Ronald mentioned fixes have been completed and are pending merge from v8 -> v9

**Comment by stefanie27** [comment]
Hi @bergmania, Is there a way to get the client side files for 9.1.1? 

FYI: I did a couple of troubleshooting steps, i.e. deleted temp files, refreshed memory cache, database cache within CMS, hard refresh browser cache

My upgrade process from 9.0.1 to 9.1.1: I upgraded via nuget and then was prompted the upgrade in CMS. I can see the new table umbracoContentVersionCleanupPolicy in DB.
