### ISSUE TITLE
Umbraco scheduled publish error

### ISSUE THREAD

**Issue by LuisCoder** [umbraco/Umbraco-CMS#11731]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.9.1

### Bug summary

I have an issue with unpublishing nodes via schedule. All nodes i try to unpublish via shedule seem to give an error. This does not happen in our stage environment, but it happens in our production environment.

### Specifics

Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Core.Persistence.Repositories.Implement.DocumentRepository.IsPathPublished(IContent content) in D:\a\1\s\src\Umbraco.Core\Persistence\Repositories\Implement\DocumentRepository.cs:line 890
   at Umbraco.Core.Services.Implement.ContentService.IsPathPublished(IContent content) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 749
   at Umbraco.Core.Services.Implement.ContentService.StrategyCanPublish(IScope scope, IContent content, Boolean checkPath, IReadOnlyList`1 culturesPublishing, IReadOnlyCollection`1 culturesUnpublishing, EventMessages evtMsgs, ContentSavingEventArgs savingEventArgs, IReadOnlyCollection`1 allLangs) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 2731
   at Umbraco.Core.Services.Implement.ContentService.CommitDocumentChangesInternal(IScope scope, IContent content, ContentSavingEventArgs saveEventArgs, IReadOnlyCollection`1 allLangs, Int32 userId, Boolean raiseEvents, Boolean branchOne, Boolean branchRoot) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 1151
   at Umbraco.Core.Services.Implement.ContentService.PerformScheduledPublishingExpiration(DateTime date, List`1 results, EventMessages evtMsgs, Lazy`1 allLangs) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 1416
   at Umbraco.Core.Services.Implement.ContentService.PerformScheduledPublish(DateTime date) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 1373
   at Umbraco.Web.Scheduling.ScheduledPublishing.PerformRun() in D:\a\1\s\src\Umbraco.Web\Scheduling\ScheduledPublishing.cs:line 68

### Steps to reproduce

I don't know the exact steps that gives this exact error. All i try to do is to unpublish nodes via a schedule time and day.

**Comment by nul800sebastiaan** [comment]
Sorry @LuisCoder for the late reply, I can't say I recall seeing this error before but this looks similar: https://github.com/umbraco/Umbraco-CMS/issues/10161 - though we never could reproduce and it seems to have fixed itself. Unfortunately 8.9.1 is a rather old version so I would encourage you to test this on 8.17 instead to see if it's still an issue, if you can still reproduce there we might have more clues on what to  look in to. For now I'll close this issue though and we can re-open it when if we know more.
