### ISSUE TITLE
Scheduled publish fails when multiple pages are published - Umbraco 7.15.6

### ISSUE THREAD

**Issue by merly-cortez** [umbraco/Umbraco-CMS#11740]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

7.15.6

### Bug summary

When scheduling publish of multiple pages, it is failing

### Specifics

These are the errors from the logs

An unhandled exception occurred while parsing content
System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Core.Scoping.Scope.<>c__DisplayClass70_0.<RobustExit>b__2()
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)
   at Umbraco.Core.Scoping.Scope.RobustExit(Boolean completed, Boolean onException)
   at Umbraco.Core.Scoping.Scope.DisposeLastScope()
   at Umbraco.Core.Scoping.Scope.Dispose()
   at Umbraco.Core.Persistence.UnitOfWork.ScopeUnitOfWork.DisposeResources()
   at Umbraco.Core.DisposableObjectSlim.Dispose(Boolean disposing)
   at Umbraco.Core.DisposableObjectSlim.Dispose()
   at 

Followed by WARN messages
Missed ScopeContext Object 8592fc95

### Steps to reproduce

Schedule about 15 pages to be published at the same date and time. At the time the publishing is set, this error occurs and publishing is failing.

### Expected result / actual result

All scheduled pages should have been published.

**Comment by emma-hq** [comment]
Hiya @merly-cortez 

Thanks for reporting but we're no longer releasing bug fixes for v7 - for more info on that, take a look [here](https://umbraco.com/products/knowledge-center/long-term-support-and-end-of-life/umbraco-7-end-of-life-eol/). 

If you need a workaround, head over to the [forum ](https://our.umbraco.com/forum/)and ask for advice. I'm sure someone will be happy to give you some input. 

Emma
