### ISSUE TITLE
"[Umbraco.Web.Scheduling.IBackgroundTask] " Task has failed

### ISSUE THREAD

**Issue by afinn-tech** [umbraco/Umbraco-CMS#11760]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.1

### Bug summary

"[Umbraco.Web.Scheduling.IBackgroundTask] " Task has failed , i thought this issue was resolved with 8.12 
ref ticket #9872 / #9684
It seems to be still an issue in latest release on deleting a member

### Steps to reproduce

Delete Member , error in log as above 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Examine.MemberValueSetBuilder.<GetValueSets>d__1.MoveNext() in D:\a\1\s\src\Umbraco.Examine\MemberValueSetBuilder.cs:line 23
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Umbraco.Web.Search.ExamineComponent.DeferedReIndexForMember.<>c__DisplayClass4_0.<Execute>b__0() in D:\a\1\s\src\Umbraco.Web\Search\ExamineComponent.cs:line 715
   at Umbraco.Web.Scheduling.SimpleTask.Run() in D:\a\1\s\src\Umbraco.Web\Scheduling\SimpleTask.cs:line 21
   at Umbraco.Web.Scheduling.BackgroundTaskRunner`1.<RunAsync>d__40.MoveNext() in D:\a\1\s\src\Umbraco.Web\Scheduling\BackgroundTaskRunner.cs:line 562

**Comment by emma-hq** [comment]
Hey @afinn-tech 

Thanks for reporting and linking the original issues too. I'll have a look at this and let you know what we come up with. Updates will be here!

Emma

**Comment by ulfmollerstrom** [comment]
@emma-hq 
Any update on this?

**Comment by kjac** [comment]
Hi everyone. 

Sorry for the late response. This is no longer an issue in V10, the Examine re-indexing runs smoothly without errors when deleting a member. 

Here's a screencast from V10.3.2:

[11760.webm](https://user-images.githubusercontent.com/7405322/211854884-c028dafe-3f78-466f-bee2-6381d2618b76.webm)
