### ISSUE TITLE
Issue when enabling Check box property as variant: The existing DocumentCultureVariationDto was not found for node XXXX and language X

### ISSUE THREAD

**Issue by HalldorLyngmo** [umbraco/Umbraco-CMS#11771]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

Umbraco 8.17.1

### Bug summary

Here's the scenario, I've got a doctype that has "Allow vary by culture" enabled. There is one property, Check box, that doesn't have variants enabled so I decide to change that. 

Save the Check box property type, everything is fine. Save the document type and there is an exception:
`The existing DocumentCultureVariationDto was not found for node 1065 and language 1`

On the project, I've got two languages:

- English with id 1 (default)
- Danish with id 2

Node 1065 has only been saved in one language, Danish. If I create an English version and save it. Then go back to the document type and change the property to a variant, I can save the document type without an exception

### Specifics

The issue seems to originate from the Checkbox property value being saved in the DB when it shouldn't. This value should be coming from the default language version of the node. But since the property has the value 0 by default it still gets saved.

![image](https://user-images.githubusercontent.com/42831978/146531038-43f805e4-4bc0-47d1-bfa3-7beb0e9587bc.png)

Then when changing the property to be a variant it tries to convert it to the default language but since there isn't a Default language version of the node it fails to find the correct information.

```
Exception Details
Umbraco.Core.Exceptions.PanicException: The existing DocumentCultureVariationDto was not found for node 1066 and language 1

at Umbraco.Core.Persistence.Repositories.Implement.ContentTypeRepositoryBase`1.RenormalizeDocumentEditedFlags(IReadOnlyCollection`1 propertyTypeIds, IReadOnlyCollection`1 contentTypeIds)
   at Umbraco.Core.Persistence.Repositories.Implement.ContentTypeRepositoryBase`1.MovePropertyTypeVariantData(IDictionary`2 propertyTypeChanges, IEnumerable`1 impacted)
   at Umbraco.Core.Persistence.Repositories.Implement.ContentTypeRepositoryBase`1.PersistUpdatedBaseContentType(IContentTypeComposition entity)
   at Umbraco.Core.Persistence.Repositories.Implement.ContentTypeRepository.PersistUpdatedItem(IContentType entity)
   at Umbraco.Core.Cache.FullDataSetRepositoryCachePolicy`2.Update(TEntity entity, Action`1 persistUpdated)
   at Umbraco.Core.Services.Implement.ContentTypeServiceBase`3.Save(TItem item, Int32 userId)
   at Umbraco.Web.Editors.ContentTypeControllerBase`1.PerformPostSave[TContentTypeDisplay,TContentTypeSave,TPropertyType](TContentTypeSave contentTypeSave, Func`2 getContentType, Action`1 saveContentType, Action`1 beforeCreateNew)
   at Umbraco.Web.Editors.ContentTypeController.PostSave(DocumentTypeSave contentTypeSave)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

### Steps to reproduce

Umbraco project running latest v8 (not tested on v9 yet)

1. Create a document type that's a variant
2. Create one check box (true/false) property and make it non-variant
![image](https://user-images.githubusercontent.com/42831978/146532458-ba2f1930-818b-40f3-88bb-98a072da209b.png)

3. Add a second language to the project
![image](https://user-images.githubusercontent.com/42831978/146532540-2ba0827d-c30b-4d25-9751-594d735934f8.png)

4. Create a node with the document type in the second language which should not be the default.
![image](https://user-images.githubusercontent.com/42831978/146532625-3844a335-2b91-4a99-8f9b-d5754c7d0a89.png)

5. Go back to the document type and change the property to be a variant
![image](https://user-images.githubusercontent.com/42831978/146532708-b995d1c8-e0b5-422d-86f8-2edd8c5f2ba0.png)

6. Then save the document type and there should be an exception:

### Desired result
When you save the node in the non-default language it should not save the checkbox property value in the DB. This would be consistent with most other properties from what I can see. 
Thus eliminating a potential issue with converting the value when the property is made variant

### Expected Result
No exception when saving the document type

### Actual Result
Exception because of inconsistent behavior with property values in the DB.

---
_This item has been added to our backlog [AB#15943](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/15943)_

**Comment by emma-hq** [comment]
Hey @HalldorLyngmo 

Thanks for all the info here 😁 I'll reproduce and label. Lots to work with.

emma

**Comment by nul800sebastiaan** [comment]
I can repro on 8.17 and 8.13 but not on 8.11 so something seems to have happened along the way. 

This is the short repro, the important part that tripped me up for a bit was to create the node with the non-default language only, so it "inherits" the checkbox from the default language (which.. doesn't exist).

https://user-images.githubusercontent.com/304656/147926510-7dc248cc-98bd-4736-9ee0-17eec417a7f4.mp4

**Comment by nul800sebastiaan** [comment]
The same error occurs in v9.1.0.

**Comment by nielslynggaard** [comment]
We urgently need a fix for this. Is there a workaround to reset the faulty values so that we can adjust the document-types?

**Comment by nielslynggaard** [comment]
Also; The same error persists on the "Slider" datatype.

**Comment by HalldorLyngmo** [comment]
Hi @nielslynggaard it should be possible to change the property back to being invariant as a workaround. 

If it's a Cloud project and the above doesn't help, then please reach out to our support and we'll take a closer look 🙂

**Comment by nielslynggaard** [comment]
Yeah, sorry if I was unclear. The issue we were facing was the other way around. We had a few properties that weren't setup to vary by culture and we couldn't change that. The solution for us was to delete the properties on the live environment and re-create the same properties but with vary by culture on.

**Comment by HalldorLyngmo** [comment]
@nul800sebastiaan 

> I can repro on 8.17 and 8.13 but not on 8.11 so something seems to have happened along the way.

I think this change might have inadvertently introduced the issue - https://github.com/umbraco/Umbraco-CMS/issues/10572

**Comment by craigFactory73** [comment]
I have the same problem on umbraco 8.16.0 . 
I do not have any checkboxes on the doc type. It contains only the following data types:
- Textstring
- RTE
- MultiUrlPicker
- EmailAddress

**Comment by TheBekker** [comment]
I can add that the problem i also occurring on Umbraco 8.18.3.
Trying to change a MultiUrlPicker on a composition (its the only prop on the comp)

My work around was to delete the node referenced in the error. But of course not a great solution :)

**Comment by FransdeJong** [comment]
Any update on this issue? I'm running in to it right now and it blocks an update for our client

**Comment by enemyss** [comment]
Experiencing same on 11.0.0

**Comment by kjac** [comment]
I can reproduce this on V10 as well. I don't think this is tied to any specific property editor but rather to the content itself. 

A possible workaround might be to save the affected content nodes in their missing languages. Not necessarily a great workaround, and also rather tedious if the problem is widespread, but nevertheless may be a workaround to prevent data loss.

I'll see if we can push this into one of the upcoming sprints. In the mean time, if someone wants to have a crack at it, please feel free to give it a go. I'll mark it as up for grabs.

**Comment by lars-erik** [comment]
I was just able to bypass this on 8.16 by doing a manual SQL update to the property rows.

Ex:  
`update [umbracoPropertyData] set languageId = 1 where propertyTypeId = @propTypeId`

I could now save the doctype with the property as a variant.  
After this, all content of non-default language was unpublished and unavailable in the cache.  
Clicking from the bottom and up under Settings\Published Status seemed to make everything OK after that.  
(I guess in essence rebuilding the DB-cache)

To early to mention any consequences, but so far so good. 🙈

**Comment by sniffdk** [comment]
We are seeing this issue as well on an Umbraco 11.2.0 installation.
It would be nice to see a solution implemented to this soon, we are closing in on 1½ years for this bug to run 🙈

**Comment by sniffdk** [comment]
@lars-erik did you ever run into any unforeseen consequences here by any chance? 😅

**Comment by lars-erik** [comment]
> @lars-erik did you ever run into any unforeseen consequences here by any chance? 😅

Not yet. 😄🤞

**Comment by sniffdk** [comment]
> > @lars-erik did you ever run into any unforeseen consequences here by any chance? 😅
> 
> Not yet. 😄🤞

Good to hear, will need to try the same workaround soon then 🤞 thx 😃

**Comment by ksolberg** [comment]
Same here, basically about to adjust a composable property to allow vary by culture on an existing site with quite a bit of content. Sounds like a common scenario so a little surprised this bug still exists.

**Comment by thomashdk** [comment]
Still no solution for this ? 
Umbraco 12.3.5

**Comment by thomashdk** [comment]
Still a issue in Umbraco 13.1.1

Anyone found a workaround ?

**Comment by thomashdk** [comment]
> `update [umbracoPropertyData] set languageId = 1 where propertyTypeId = @propTypeId`

@lars-erik  how did you find what propertyfield caused the issue ? :)

**Comment by lars-erik** [comment]
> @lars-erik how did you find what propertyfield caused the issue ? :)

TBH I don't even remember doing it, but I imagine I may have queried the cmsPropertyData table and looked for languageId = null.

**Comment by khraibani** [comment]
Same here Umbraco v8.18.12

**Comment by garpunkal** [comment]
We're experiencing the same issue in V11. Not sure running a SQL script against a database in production would be safe.

**Comment by gardarthorsteins** [comment]
This is still an issue, is anyone from Umbraco looking at this ? @nul800sebastiaan  ?

**Comment by thomashdk** [comment]
> > `update [umbracoPropertyData] set languageId = 1 where propertyTypeId = @propTypeId`
> 
> @lars-erik how did you find what propertyfield caused the issue ? :)

I have this issue again...  In V13.

Now when I run the update I get this error:

`Cannot insert duplicate key row in object 'dbo.umbracoPropertyData' with unique index 'IX_umbracoPropertyData_VersionId'. The duplicate key value is (33000, 319, 2, <NULL>).
`

Really strange.. Last I had the issue I could run the update just fine..

**Comment by thomashdk** [comment]
> We're experiencing the same issue in V11. Not sure running a SQL script against a database in production would be safe.

Did you find a workaround ?

**Comment by JoaoDiogoVicenteHenrques** [comment]
still an issue on 13.5.3.

The only workaround I know is to create another property to replace the one you want to vary by culture, but you will lose all the content data of that property.

**Comment by OsaidM** [comment]
Still Facing the same issue on 13.5.2.0, cant seem to find a fix to it

**Comment by Questo** [comment]
For me it's not a checkbox, but a Block list data type. I can on my local development machine make the property be cultured varied or not, but am unable to sync this settings using uSync to my stage/test environment.

and I cannot do the change manually, by just clicking the "Allow culture variation" checkbox in my test environment. I can save, but the loading spinner spins for an eternity then it fails. tells me to look in the logs for more info but no logs are present.

Using Umbraco 13

**Comment by mateusz-domanski** [comment]
The problem still persists in Umbraco 13.10.0

**Comment by thomashdk** [comment]
Anyone found a workaround ? Still a issue in 13.10.1

**Comment by andersreus** [comment]
Hi @thomashdk can you check if you have this setting enabled in your appsettings file `AllowEditInvariantFromNonDefault`?
It is set to false by default, and by setting this to true, I no longer encounter the issue (v.13.11)

**Comment by nikolajlauridsen** [comment]
Just reproduced this in V17, so it's still an issue

**Comment by skttl** [comment]
I just got that in V17 too.

Had a block list set to share between cultures. When unticking that and saving I got the error message.

When looking at the nodeId mentioned, I could see that the node wasn't created in the default language, but only had variants for other languages. Tried creating a variant for the default language, and then updated the document type again. Then I just got another nodeId with the same problem.

**Comment by sniffdk** [comment]
Will this be a contender for "Longest running bug" in Umbraco? 😆

**Comment by skttl** [comment]
> Will this be a contender for "Longest running bug" in Umbraco? 😆

Must have been in V8 from the start :)

**Comment by sniffdk** [comment]
According to @nul800sebastiaan it was introduced between version 8.11 and 8.13, so it is at least older than April 22 2021 💪

**Comment by AndyButland** [comment]
Fixed via https://github.com/umbraco/Umbraco-CMS/pull/21182 for 17.1 and 16.5
