### ISSUE TITLE
Publishing several document types at the same scheduled time results in document types not being saved in the cache

### ISSUE THREAD

**Issue by RasmusUmbraco** [umbraco/Umbraco-CMS#11848]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17

### Bug summary

Using the schedule feature to publish more document types at the same time will publish all the document types, but only save the first document type in the cache.

### Steps to reproduce

Use the scheduling feature to schedule publishing of more than one document type at the same date and time.
![image](https://user-images.githubusercontent.com/88326257/149126369-40c41716-460a-4810-b9db-421e499451a5.png)

First document type - published and cached:
![image](https://user-images.githubusercontent.com/88326257/149126789-d1bf18ee-18e6-4828-abc8-c116af31aaca.png)

Second document type - published but not cached:
![image](https://user-images.githubusercontent.com/88326257/149126838-02842c21-a1e7-4c01-af4e-fe3f96b65a69.png)

I have reproduced this on V8.15 as well.

**Comment by nul800sebastiaan** [comment]
Not sure what to tell you I'm afraid, but I gave it a go on 8.17 and this all works as it should. Maybe we need more steps to reproduce so if you can reproduce it on a clean install then please add steps to follow. Also have a look at any errors in the log, they might tell you something? Not sure. I forgot to put a transition in the following video but after scheduling both I waited a few minutes and checked both nodes to see if they got published properly, which they did.

https://user-images.githubusercontent.com/304656/149322124-976d3766-6033-486e-b479-a4c91526592a.mp4


I'll close this for now until we have some more info on how to reproduce the problem.

**Comment by tombille** [comment]
@nul800sebastiaan
Hi Sebastiaan.

We have this occurring on one of our cloud-projects. 

It throws this error in the log:

`
Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at LightInject.Web.PerWebRequestScopeManager.GetOrAddScope() in C:\projects\lightinject-web\build\tmp\Net46\Binary\LightInject.Web\LightInject.Web.cs:line 148
   at LightInject.Web.PerWebRequestScopeManager.get_CurrentScope() in C:\projects\lightinject-web\build\tmp\Net46\Binary\LightInject.Web\LightInject.Web.cs:line 129
   at DynamicMethod(Object[] )
   at LightInject.ServiceContainer.GetInstance(Type serviceType) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3442
   at Umbraco.Core.Composing.LightInject.LightInjectContainer.GetInstance(Type type) in D:\a\1\s\src\Umbraco.Core\Composing\LightInject\LightInjectContainer.cs:line 111
   at Umbraco.Core.FactoryExtensions.GetInstance[T](IFactory factory) in D:\a\1\s\src\Umbraco.Core\FactoryExtensions.cs:line 23
   at Umbraco.Web.Runtime.WebInitialComposer.<>c.<Compose>b__0_6(IFactory factory) in D:\a\1\s\src\Umbraco.Web\Runtime\WebInitialComposer.cs:line 122
   at Umbraco.Core.Composing.LightInject.LightInjectContainer.<>c__DisplayClass20_0`1.<Register>b__0(IServiceFactory f) in D:\a\1\s\src\Umbraco.Core\Composing\LightInject\LightInjectContainer.cs:line 172
   at DynamicMethod(Object[] )
   at LightInject.ServiceContainer.GetInstance(Type serviceType) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3442
   at Umbraco.Core.Composing.LightInject.LightInjectContainer.GetInstance(Type type) in D:\a\1\s\src\Umbraco.Core\Composing\LightInject\LightInjectContainer.cs:line 111
   at Umbraco.Core.FactoryExtensions.GetInstance[T](IFactory factory) in D:\a\1\s\src\Umbraco.Core\FactoryExtensions.cs:line 23
   at Umbraco.Deploy.Cloud.LiveEditing.EventSubscriber.GetHubAndHelper(IHubContext& hub, UmbracoHelper& helper)
   at Umbraco.Deploy.Cloud.LiveEditing.EventSubscriber.ContentService_Published(IContentService sender, PublishEventArgs`1 e)
   at Umbraco.Core.Events.TypedEventHandler`2.Invoke(TSender sender, TEventArgs e)
   at Umbraco.Core.Events.EventDefinition`2.RaiseEvent() in D:\a\1\s\src\Umbraco.Core\Events\EventDefinition.cs:line 69
   at Umbraco.Core.Events.QueuingEventDispatcher.ScopeExitCompleted() in D:\a\1\s\src\Umbraco.Core\Events\QueuingEventDispatcher.cs:line 23
   at Umbraco.Core.Events.QueuingEventDispatcherBase.ScopeExit(Boolean completed) in D:\a\1\s\src\Umbraco.Core\Events\QueuingEventDispatcherBase.cs:line 337
   at Umbraco.Core.Scoping.Scope.<>c__DisplayClass85_0.<RobustExit>b__1() in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 667
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 705
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 709
   at Umbraco.Core.Scoping.Scope.RobustExit(Boolean completed, Boolean onException) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 653
   at Umbraco.Core.Scoping.Scope.DisposeLastScope() in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 633
   at Umbraco.Core.Scoping.Scope.Dispose() in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 555
   at Umbraco.Core.Services.Implement.ContentService.PerformScheduledPublishingRelease(DateTime date, List`1 results, EventMessages evtMsgs, Lazy`1 allLangs) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 1547
   at Umbraco.Core.Services.Implement.ContentService.PerformScheduledPublish(DateTime date) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 1395
   at Umbraco.Web.Scheduling.ScheduledPublishing.PerformRun() in D:\a\1\s\src\Umbraco.Web\Scheduling\ScheduledPublishing.cs:line 68
`

**Comment by nul800sebastiaan** [comment]
@tombille - sure, have you checked if you have any event handlers, and why they would be failing with a null reference error? 🙈

**Comment by nul800sebastiaan** [comment]
Sorry, I did glance over the fact that this was on Cloud, I can reproduce this easily on a very simple setup: 

https://user-images.githubusercontent.com/304656/149359388-247adf34-c629-4440-996b-174e8f23267b.mp4

I'll move this to the Deploy issue tracker since there seems to be something there that's going wrong specifically in Deploy. Not sure if the Deploy team is aware yet but with a simple reproduction they might be able to find a cause quite easily 🤞
