### ISSUE TITLE
Daily boot failure "No index found by name ExternalIndex."

### ISSUE THREAD

**Issue by Wiggee11** [umbraco/Umbraco-CMS#11908]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.0

### Bug summary

We have a live application running 8.17.0 with additional properties added to the external index.
Self-hosted in IIS (not load-balanced), it is set to recycle daily at 4pm. Overlapped Recycling is disabled.
Every day, the app fails to boot with the error "No index found by name ExternalIndex.". It then manages to restart after a few attempts and is OK.
Every 7-10 days this boot failure explodes and continually repeats until the application/app pool is manually shut down and recycled.

### Specifics

At 4pm, the app starts to reboot and then we get a SQL timeout exception:
```
System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TrySetMetaData(_SqlMetaDataSet metaData, Boolean moreInfo)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172
   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd)
   at NPoco.Database.<QueryImp>d__164`1.MoveNext()
   at Umbraco.Core.Persistence.NPocoDatabaseExtensions.<QueryPaged>d__8`1.MoveNext() in D:\a\1\s\src\Umbraco.Core\Persistence\NPocoDatabaseExtensions.cs:line 56
   at Umbraco.Web.PublishedCache.NuCache.DataSource.DatabaseDataSource.<GetAllContentSources>d__13.MoveNext() in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\DataSource\DatabaseDataSource.cs:line 238
   at Umbraco.Web.PublishedCache.NuCache.ContentStore.SetAllFastSortedLocked(IEnumerable`1 kits, Boolean fromDb) in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\ContentStore.cs:line 696
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.LoadContentFromDatabaseLocked(IScope scope, Boolean onStartup) in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\PublishedSnapshotService.cs:line 406
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.LockAndLoadContent(Func`2 action) in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\PublishedSnapshotService.cs:line 381
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.<EnsureCaches>b__36_0() in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\PublishedSnapshotService.cs:line 277
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.EnsureCaches() in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\PublishedSnapshotService.cs:line 210
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.Notify(JsonPayload[] payloads) in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\PublishedSnapshotService.cs:line 946
   at Umbraco.Web.Cache.DomainCacheRefresher.Refresh(JsonPayload[] payloads) in D:\a\1\s\src\Umbraco.Web\Cache\DomainCacheRefresher.cs:line 44
   at Umbraco.Core.Sync.ServerMessengerBase.Deliver[TPayload](ICacheRefresher refresher, TPayload[] payload) in D:\a\1\s\src\Umbraco.Core\Sync\ServerMessengerBase.cs:line 298
   at Umbraco.Web.Cache.DistributedCache.RefreshByPayload[TPayload](Guid refresherGuid, TPayload[] payload) in D:\a\1\s\src\Umbraco.Web\Cache\DistributedCache.cs:line 83
   at Umbraco.Web.Cache.DistributedCacheExtensions.RefreshDomainCache(DistributedCache dc, IDomain domain) in D:\a\1\s\src\Umbraco.Web\Cache\DistributedCacheExtensions.cs:line 251
   at Umbraco.Web.Cache.DistributedCacheBinder.DomainService_Saved(IDomainService sender, SaveEventArgs`1 e) in D:\a\1\s\src\Umbraco.Web\Cache\DistributedCacheBinder_Handlers.cs:line 265
   at Umbraco.Core.Events.EventDefinition`2.RaiseEvent() in D:\a\1\s\src\Umbraco.Core\Events\EventDefinition.cs:line 71
   at Umbraco.Core.Events.QueuingEventDispatcher.ScopeExitCompleted() in D:\a\1\s\src\Umbraco.Core\Events\QueuingEventDispatcher.cs:line 29
   at Umbraco.Core.Events.QueuingEventDispatcherBase.ScopeExit(Boolean completed) in D:\a\1\s\src\Umbraco.Core\Events\QueuingEventDispatcherBase.cs:line 338
   at Umbraco.Core.Scoping.Scope.<>c__DisplayClass85_0.<RobustExit>b__1() in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 667
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 705
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 710
   at Umbraco.Core.Scoping.Scope.Dispose() in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 557
   at Umbraco.Core.Services.Implement.DomainService.Save(IDomain domainEntity) in D:\a\1\s\src\Umbraco.Core\Services\Implement\DomainService.cs:line 101
   at uSync8.ContentEdition.Serializers.DomainSerializer.SaveItem(IDomain item)
   at uSync8.Core.Serialization.SyncSerializerRoot`1.Deserialize(XElement node, SyncSerializerOptions options)
   at uSync8.BackOffice.SyncHandlers.SyncHandlerRoot`2.DeserializeItem(XElement node, SyncSerializerOptions options)
   at uSync8.BackOffice.SyncHandlers.SyncHandlerRoot`2.ImportElement(XElement node, String filename, HandlerSettings settings, uSyncImportOptions options)
ClientConnectionId:9275d98b-5dbd-4a0f-945b-ac80291c6096
Error Number:-2,State:0,Class:11
```

Which is immediately followed by a Fatal Panic Exception:
```
System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TrySetMetaData(_SqlMetaDataSet metaData, Boolean moreInfo)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172
   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd)
   at NPoco.Database.<QueryImp>d__164`1.MoveNext()
   at Umbraco.Core.Persistence.NPocoDatabaseExtensions.<QueryPaged>d__8`1.MoveNext() in D:\a\1\s\src\Umbraco.Core\Persistence\NPocoDatabaseExtensions.cs:line 56
   at Umbraco.Web.PublishedCache.NuCache.DataSource.DatabaseDataSource.<GetAllContentSources>d__13.MoveNext() in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\DataSource\DatabaseDataSource.cs:line 238
   at Umbraco.Web.PublishedCache.NuCache.ContentStore.SetAllFastSortedLocked(IEnumerable`1 kits, Boolean fromDb) in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\ContentStore.cs:line 696
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.LoadContentFromDatabaseLocked(IScope scope, Boolean onStartup) in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\PublishedSnapshotService.cs:line 406
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.LockAndLoadContent(Func`2 action) in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\PublishedSnapshotService.cs:line 381
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.<EnsureCaches>b__36_0() in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\PublishedSnapshotService.cs:line 277
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.EnsureCaches() in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\PublishedSnapshotService.cs:line 210
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.Notify(JsonPayload[] payloads) in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\PublishedSnapshotService.cs:line 946
   at Umbraco.Web.Cache.DomainCacheRefresher.Refresh(JsonPayload[] payloads) in D:\a\1\s\src\Umbraco.Web\Cache\DomainCacheRefresher.cs:line 44
   at Umbraco.Core.Sync.ServerMessengerBase.Deliver[TPayload](ICacheRefresher refresher, TPayload[] payload) in D:\a\1\s\src\Umbraco.Core\Sync\ServerMessengerBase.cs:line 298
   at Umbraco.Web.Cache.DistributedCache.RefreshByPayload[TPayload](Guid refresherGuid, TPayload[] payload) in D:\a\1\s\src\Umbraco.Web\Cache\DistributedCache.cs:line 83
   at Umbraco.Web.Cache.DistributedCacheExtensions.RefreshDomainCache(DistributedCache dc, IDomain domain) in D:\a\1\s\src\Umbraco.Web\Cache\DistributedCacheExtensions.cs:line 251
   at Umbraco.Web.Cache.DistributedCacheBinder.DomainService_Saved(IDomainService sender, SaveEventArgs`1 e) in D:\a\1\s\src\Umbraco.Web\Cache\DistributedCacheBinder_Handlers.cs:line 265
   at Umbraco.Core.Events.EventDefinition`2.RaiseEvent() in D:\a\1\s\src\Umbraco.Core\Events\EventDefinition.cs:line 71
   at Umbraco.Core.Events.QueuingEventDispatcher.ScopeExitCompleted() in D:\a\1\s\src\Umbraco.Core\Events\QueuingEventDispatcher.cs:line 29
   at Umbraco.Core.Events.QueuingEventDispatcherBase.ScopeExit(Boolean completed) in D:\a\1\s\src\Umbraco.Core\Events\QueuingEventDispatcherBase.cs:line 338
   at Umbraco.Core.Scoping.Scope.<>c__DisplayClass85_0.<RobustExit>b__1() in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 667
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 705
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 710
   at Umbraco.Core.Scoping.Scope.Dispose() in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 557
   at Umbraco.Core.Services.Implement.DomainService.Save(IDomain domainEntity) in D:\a\1\s\src\Umbraco.Core\Services\Implement\DomainService.cs:line 101
   at uSync8.ContentEdition.Serializers.DomainSerializer.SaveItem(IDomain item)
   at uSync8.Core.Serialization.SyncSerializerRoot`1.Deserialize(XElement node, SyncSerializerOptions options)
   at uSync8.BackOffice.SyncHandlers.SyncHandlerRoot`2.DeserializeItem(XElement node, SyncSerializerOptions options)
   at uSync8.BackOffice.SyncHandlers.SyncHandlerRoot`2.ImportElement(XElement node, String filename, HandlerSettings settings, uSyncImportOptions options)
ClientConnectionId:9275d98b-5dbd-4a0f-945b-ac80291c6096
Error Number:-2,State:0,Class:11
```

We then get a Boot Failed error:
```
Umbraco.Core.Exceptions.BootFailedException: Boot failed. ---> System.InvalidOperationException: No index found by name ExternalIndex.
   at Application.Search.SearchComponent.Initialize() in ...\src\Application.Search\SearchComponent.cs:line 55
   at Umbraco.Core.Composing.ComponentCollection.Initialize() in D:\a\1\s\src\Umbraco.Core\Composing\ComponentCollection.cs:line 32
   at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in D:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 219
   --- End of inner exception stack trace ---
```

We then get a Unhandled exception error which repeats:
```
Umbraco.Core.Exceptions.BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.

-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.InvalidOperationException: No index found by name ExternalIndex.
   at Application.Search.SearchComponent.Initialize() in ...\src\Application.Search\SearchComponent.cs:line 55
   at Umbraco.Core.Composing.ComponentCollection.Initialize() in D:\a\1\s\src\Umbraco.Core\Composing\ComponentCollection.cs:line 32
   at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in D:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 219
   at Umbraco.Core.Exceptions.BootFailedException.Rethrow(BootFailedException bootFailedException) in D:\a\1\s\src\Umbraco.Core\Exceptions\BootFailedException.cs:line 64
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

### Steps to reproduce

**The SearchComposer where the SearchComponent referenced in the errors is registered:**
```
namespace Application.Search
{
    [RuntimeLevel(MinLevel = RuntimeLevel.Run)]
    public class SearchComposer : IUserComposer
    {
        public void Compose(Composition composition)
        {
            composition.Components().Append<SearchComponent>();
        }
    }
}
```

**And our custom SearchComponent, transforming the ExternalIndex with additional properties:**
1. Combining fields into a single field for easy searching, as per official training and documentation.
2. Calculating whether a node's path is published in a culture (due to an earlier Umbraco bug where nodes are included in the index regardless of the state of the published path)
```
namespace Application.Search
{
    public class SearchComponent : IComponent
    {
        private readonly IExamineManager _examineManager;
        private readonly IScopeProvider _scopeProvider;
        private readonly IUmbracoContextFactory _contextFactory;
        private readonly ILogger _logger;

        public SearchComponent(IExamineManager examineManager, IScopeProvider scopeProvider, IUmbracoContextFactory contextFactory, ILogger logger)
        {
            _examineManager = examineManager;
            _scopeProvider = scopeProvider;
            _contextFactory = contextFactory;
            _logger = logger;
        }

        public void Initialize()
        {
            if (!_examineManager.TryGetIndex(Umbraco.Core.Constants.UmbracoIndexes.ExternalIndexName, out var index))
                throw new InvalidOperationException($"No index found by name {Umbraco.Core.Constants.UmbracoIndexes.ExternalIndexName}.");

            if (!(index is BaseIndexProvider indexProvider))
                throw new InvalidOperationException("Could not cast index.");

            indexProvider.TransformingIndexValues += IndexProviderTransformingIndexValues;
        }

        private void IndexProviderTransformingIndexValues(object sender, IndexingItemEventArgs e)
        {
            if (e.ValueSet.Category == IndexTypes.Content)
            {
                try
                {
                    // Stuffing all text content into a single indexable "contents" field for easy searching
                    var combinedFields = new StringBuilder();

                    foreach (var fieldValues in e.ValueSet.Values)
                    {
                        foreach (var value in fieldValues.Value)
                        {
                            if (value != null)
                                combinedFields.AppendLine(value.ToString());
                        }
                    }

                    e.ValueSet.Add(Constants.ContentsIndexField, combinedFields.ToString());
                }
                catch (Exception ex)
                {
                    _logger.Error<SearchComponent>(ex, "Error combining fields for {ValueSetId}", e.ValueSet.Id);
                }

                try
                {
                    e.ValueSet.Add("PathIsPublished_en-gb", PathIsPublished(e.ValueSet.Id, "en-GB"));
                    e.ValueSet.Add("PathIsPublished_zh-hans", PathIsPublished(e.ValueSet.Id, "zh-Hans"));
                }
                catch (Exception ex)
                {
                    _logger.Error<SearchComponent>(ex, "Error determining path is published for node {NodeId}.", e.ValueSet.Id);
                }
            }
        }

        private bool PathIsPublished(string idString, string culture)
        {
            if (int.TryParse(idString, out var id))
            {
                using (var scope = _scopeProvider.CreateScope(autoComplete: true))
                {
                    using (var contextReference = _contextFactory.EnsureUmbracoContext())
                    {
                        var node = contextReference.UmbracoContext.Content.GetById(id);
                        if (node == null)
                            return false;

                        // Check node and all ancestors are published in requested Culture
                        return node.IsPublished(culture) && node.Ancestors().All(x => x.IsPublished(culture));
                    }
                }
            }

            return false;
        }

        public void Terminate() { }
    }
}
```

**Trimmed out superfluous code, but line 55 reported in the error is:**
```
if (!_examineManager.TryGetIndex(Umbraco.Core.Constants.UmbracoIndexes.ExternalIndexName, out var index))
                throw new InvalidOperationException($"No index found by name {Umbraco.Core.Constants.UmbracoIndexes.ExternalIndexName}.");
```

Which is being thrown before the index is transformed.

**Relevant web.config settings:**
```
<add key="Umbraco.Core.MainDom.Lock" value="SqlMainDomLock" />
```

We are not setting `Umbraco.Core.LocalTempStorage` to respect the default value (Umbraco cache file will be stored in App_Data and the DistCache and PluginCache folders will be stored in the App_Data/TEMP folder).

We are not setting `<add key="Umbraco.Examine.LuceneDirectoryFactory" value="Examine.LuceneEngine.Directories.SyncTempEnvDirectoryFactory, Examine" />` because it is not hosted in Azure or using EnvironmentTemp.

### Expected result / actual result

Every time the app pool recycles it should boot fine and rebuild the index.

**Comment by Zeegaan** [comment]
Hey @Wiggee11 As it's a hard one to reproduce and we haven't heard from you in a while (our fault for getting back to you late).
I am going to go ahead and close this for now 👍 
Please do not hesitate to re-open if this is still an issue 🐛
