### ISSUE TITLE
Application throw exception "An item with the same key has already been added. Key: global"

### ISSUE THREAD

**Issue by a-t-k** [umbraco/Umbraco-CMS#11997]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.2

### Bug summary

After "Upgrading Umbraco" from V8.17.2 to V9.2.0 application throw exception  "An item with the same key has already been added. Key: global" and stop execution.

### Specifics

Version 8.17.2 works fine. After upgrade it is not runable any more. Version 9.2 throw this exception on start in Umbraco.Cms.Core.Models.PropertyGroupCollection class on inserting new Item with Add(PropertyGroup item). In the method item will be added to dictionary with "base.Add(item);" and this cause exception, because in the database table was two same group alias stored. 

Why can this happen? How can 2 same group alliases stored in the database?

and here is the problem:

On version 8.17.1 In the settings in "Document Types" its possible create "Tabs" and "groups". Both of them user same group alliases. Bug happen when new "Tab" has same allias as "group". Alliases will be set automaticaly. No chance to change it.

![image](https://user-images.githubusercontent.com/14151950/153829498-a36ce9df-1948-4e53-9a6a-729cfb736258.png)

### Steps to reproduce

Version 8.17.1 or 8.17.2
Create new "group" in document type section
Create new "tab" with the same name as group in document type section
Save it
Start upgrade to version 9.2
After upgrade the application try to start.
Excpectioon will be thrown "An item with the same key has already been added. Key: global"

### Expected result / actual result

On migration to version 9 add unique check for group alliases. when two same are stored then change one to new unique allias and inform user.

**Comment by nul800sebastiaan** [comment]
Thanks for the report @a-t-k! This seems very strange as both on v8 and v9 it is perfectly fine to have a tab and a group with the same name. They are stored with a different alias though. I would expect you to have problems with v8 as well if the alias for the tab and group are the same in the database, here is how it looks like for me:

![image](https://user-images.githubusercontent.com/304656/157451854-0e234721-dba8-4bea-8ce1-240a4e7b847d.png)

Unfortunately I just can't see how the alias could be the same, I've tried creating a group/tab in different order, renaming the group and tab and trying to trick it by moving the property between the group and tab and then renaming it but in the database the alias is always unique. 

Finally, I ended up making the aliases the same by directly editing the database and then each time I saved the doctype again, it would correct the alias. As the very last step, I renamed the alias in the database (so they were both `global` and then restarted the application pool. Then the complete site fails with a `An item with the same key has already been added.` error.

So I'm pretty sure it's not something that Umbraco has caused, in fact, your v8 site  is probably having some problems already, I would recommend you update the alias in the database before your upgrade so you can complete the upgrade and prevent future collision problems.

I'll close this for now, apologies for the late reply.

**Comment by jomehmet** [comment]
Hi  @nul800sebastiaan we got this same Exception after migrating from Umbraco 8.18.3 -> Umbraco 9.5.0

In our case we were having two different document types where both had the same name on a Tab: SEO
On one of them we had both a Group called SEO and a Tab called SEO, while on the other we only had a Tab called SEO.

I will add diff of the revision files for the two documents that was related to this issue.

## Git diff 1
```
diff --git a/data/revision/document-type__b61dc59d7efd4625ba59c7852f1c6239.uda b/data/revision/document-type__b61dc59d7efd4625ba59c7852f1c6239.uda
index 9189e72..3840892 100644
--- a/data/revision/document-type__b61dc59d7efd4625ba59c7852f1c6239.uda
+++ b/data/revision/document-type__b61dc59d7efd4625ba59c7852f1c6239.uda
@@ -1,67 +1,67 @@
 {
-  "Name": "ListContent",
-  "Alias": "listContent",
+  "Name": "SEO Visibility Settings",
+  "Alias": "seoVisibilitySettings",
   "DefaultTemplate": null,
   "AllowedTemplates": [],
   "HistoryCleanup": {
     "PreventCleanup": false,
     "KeepAllVersionsNewerThanDays": null,
     "KeepLatestVersionPerDayForDays": null
   },
   "Icon": "icon-defrag",
   "Thumbnail": "folder.png",
   "Description": null,
   "IsContainer": false,
   "Permissions": {
     "AllowVaryingByCulture": false,
     "AllowVaryingBySegment": false,
     "AllowedAtRoot": false,
     "IsElementType": true,
     "AllowedChildContentTypes": []
   },
   "Parent": "umb://document-type-container/c0a14cb54e3c4d858c1c1ac8874ccad5",
   "CompositionContentTypes": [],
   "PropertyGroups": [
     {
       "Key": "b2691af3-f9e5-4be8-98bc-15af59aef2ab",
-      "Name": "SEO",
+      "Name": "Visibility Settings",
       "SortOrder": 0,
       "Type": 1,
-      "Alias": "seO",
+      "Alias": "visibilitySettings",
       "PropertyTypes": [
         {
           "Key": "1eeb761e-6a03-4c53-be45-163f3753cc3d",
-          "Alias": "listedContent",
+          "Alias": "contentIsVisible",
           "DataType": "umb://data-type/92897bc6a5f34ffeae27f2e7e33dda49",
           "Description": "Lorem ipsum....",
           "Mandatory": false,
-          "Name": "Listed Content",
+          "Name": "Content Is Visible",
           "SortOrder": 0,
           "Validation": null,
           "VariesByCulture": false,
           "VariesBySegment": false,
           "LabelOnTop": false,
           "MemberCanEdit": false,
           "ViewOnProfile": false,
           "IsSensitive": false
         }
       ]
     }
   ],
   "PropertyTypes": [],
   "Udi": "umb://document-type/b61dc59d7efd4625ba59c7852f1c6239",
   "Dependencies": [
     {
       "Udi": "umb://data-type/92897bc6a5f34ffeae27f2e7e33dda49",
       "Ordering": true,
       "Mode": 0
     },
     {
       "Udi": "umb://document-type-container/c0a14cb54e3c4d858c1c1ac8874ccad5",
       "Ordering": true,
       "Mode": 0
     }
   ],
   "__type": "Umbraco.Deploy,Umbraco.Deploy.Artifacts.ContentType.DocumentTypeArtifact",
   "__version": "4.6.0"
 }
\ No newline at end of file

```

## Git diff 2 that removed the issue:
```
diff --git a/data/revision/document-type__3a463891f8f14fe6ac0b4bb3fe3185ee.uda b/data/revision/document-type__3a463891f8f14fe6ac0b4bb3fe3185ee.uda
index 4d17023..89deba3 100644
--- a/data/revision/document-type__3a463891f8f14fe6ac0b4bb3fe3185ee.uda
+++ b/data/revision/document-type__3a463891f8f14fe6ac0b4bb3fe3185ee.uda
@@ -1,233 +1,233 @@
 {
   "Name": "SEO Base",
   "Alias": "sEOBase",
   "DefaultTemplate": null,
   "AllowedTemplates": [],
   "HistoryCleanup": {
     "PreventCleanup": false,
     "KeepAllVersionsNewerThanDays": null,
     "KeepLatestVersionPerDayForDays": null
   },
   "Icon": "icon-document",
   "Thumbnail": "folder.png",
   "Description": null,
   "IsContainer": false,
   "Permissions": {
     "AllowVaryingByCulture": false,
     "AllowVaryingBySegment": false,
     "AllowedAtRoot": false,
     "IsElementType": false,
     "AllowedChildContentTypes": []
   },
   "Parent": "umb://document-type-container/c0a14cb54e3c4d858c1c1ac8874ccad5",
   "CompositionContentTypes": [],
   "PropertyGroups": [
     {
       "Key": "59cc57e7-7774-4f59-b0e7-e3b153d14be4",
       "Name": "SEO",
       "SortOrder": 0,
       "Type": 1,
       "Alias": "seO",
       "PropertyTypes": []
     },
     {
       "Key": "8ff76862-1dd2-4d63-b2b6-5d9b72d4bbe5",
-      "Name": "SEO",
+      "Name": "SEO Settings",
       "SortOrder": 1,
       "Type": 0,
-      "Alias": "seO/sEO",
+      "Alias": "seO/seoSettings",
       "PropertyTypes": [
         {
           "Key": "2ed7f79f-6a6d-4b4e-b669-8f3c96287c6a",
           "Alias": "metaDescription",
           "DataType": "umb://data-type/0cc0eba1996042c9bf9b60e150b429ae",
           "Description": "This description is lorem ipsum",
           "Mandatory": true,
           "Name": "Description",
           "SortOrder": 1,
           "Validation": null,
           "VariesByCulture": false,
           "VariesBySegment": false,
           "LabelOnTop": false,
           "MemberCanEdit": false,
           "ViewOnProfile": false,
           "IsSensitive": false
         },
         {
           "Key": "54092780-a838-4efe-ba15-aa584e72d23b",
           "Alias": "metaPropertyTags",
           "DataType": "umb://data-type/8786bc4dca2d4159bab66c970045677b",
           "Description": null,
           "Mandatory": false,
           "Name": "metaPropertyTags",
           "SortOrder": 5,
           "Validation": null,
           "VariesByCulture": false,
           "VariesBySegment": false,
           "LabelOnTop": false,
           "MemberCanEdit": false,
           "ViewOnProfile": false,
           "IsSensitive": false
         },
         {
           "Key": "6331e01c-319f-4ec7-b8a6-86a07f996ae1",
           "Alias": "metaTitle",
           "DataType": "umb://data-type/0cc0eba1996042c9bf9b60e150b429ae",
           "Description": "Lorem ipsum...",
           "Mandatory": false,
           "Name": "Title",
           "SortOrder": 0,
           "Validation": null,
           "VariesByCulture": false,
           "VariesBySegment": false,
           "LabelOnTop": false,
           "MemberCanEdit": false,
           "ViewOnProfile": false,
           "IsSensitive": false
         },
         {
           "Key": "6cd2a21f-e728-4158-a7f0-ac79b810b514",
           "Alias": "aliasPath",
           "DataType": "umb://data-type/0cc0eba1996042c9bf9b60e150b429ae",
           "Description": "If you want to...",
           "Mandatory": false,
           "Name": "Alias Path",
           "SortOrder": 3,
           "Validation": null,
           "VariesByCulture": false,
           "VariesBySegment": false,
           "LabelOnTop": false,
           "MemberCanEdit": false,
           "ViewOnProfile": false,
           "IsSensitive": false
         },
         {
           "Key": "7be46ea7-b16b-4776-99cb-6935b0dd8293",
           "Alias": "featuredImage",
           "DataType": "umb://data-type/f24dd3c4705e44f385725117aa99e164",
           "Description": "Used when ...",
           "Mandatory": false,
           "Name": "Featured Image",
           "SortOrder": 2,
           "Validation": null,
           "VariesByCulture": false,
           "VariesBySegment": false,
           "LabelOnTop": false,
           "MemberCanEdit": false,
           "ViewOnProfile": false,
           "IsSensitive": false
         },
         {
           "Key": "8c153f65-f939-44cb-bbb9-7ae1df0cfd89",
           "Alias": "updateFrequency",
           "DataType": "umb://data-type/864a00b5508f456dbfb832e4ccfb1b65",
           "Description": "Sitemap - Defaults to monthly",
           "Mandatory": false,
           "Name": "Update frequency",
           "SortOrder": 8,
           "Validation": null,
           "VariesByCulture": false,
           "VariesBySegment": false,
           "LabelOnTop": false,
           "MemberCanEdit": false,
           "ViewOnProfile": false,
           "IsSensitive": false
         },
         {
           "Key": "c99ba68d-a820-4be9-89e2-53047c24219c",
           "Alias": "visibleOnSitemap",
           "DataType": "umb://data-type/c01a5fde2beb431ea60e7cc59347679d",
           "Description": "Lorem ipsum...",
           "Mandatory": false,
           "Name": "Visible on sitemap",
           "SortOrder": 6,
           "Validation": null,
           "VariesByCulture": false,
           "VariesBySegment": false,
           "LabelOnTop": false,
           "MemberCanEdit": false,
           "ViewOnProfile": false,
           "IsSensitive": false
         },
         {
           "Key": "de84c708-238d-44cb-a990-6f22833f409f",
           "Alias": "metaNameTags",
           "DataType": "umb://data-type/b9105f2ebd1e40ee8b029be74cdfe1e1",
           "Description": null,
           "Mandatory": false,
           "Name": "metaNameTags",
           "SortOrder": 4,
           "Validation": null,
           "VariesByCulture": false,
           "VariesBySegment": false,
           "LabelOnTop": false,
           "MemberCanEdit": false,
           "ViewOnProfile": false,
           "IsSensitive": false
         },
         {
           "Key": "fb3b7f14-7a46-46c6-a732-327426b1eb24",
           "Alias": "priorityOnSitemap",
           "DataType": "umb://data-type/adb5786ff4f7491699f59e317d7a4c5b",
           "Description": "Value between 0 and 1.0. Defaults to 0.5",
           "Mandatory": false,
           "Name": "Priority on sitemap",
           "SortOrder": 7,
           "Validation": null,
           "VariesByCulture": false,
           "VariesBySegment": false,
           "LabelOnTop": false,
           "MemberCanEdit": false,
           "ViewOnProfile": false,
           "IsSensitive": false
         }
       ]
     }
   ],
   "PropertyTypes": [],
   "Udi": "umb://document-type/3a463891f8f14fe6ac0b4bb3fe3185ee",
   "Dependencies": [
     {
       "Udi": "umb://data-type/0cc0eba1996042c9bf9b60e150b429ae",
       "Ordering": true,
       "Mode": 0
     },
     {
       "Udi": "umb://data-type/864a00b5508f456dbfb832e4ccfb1b65",
       "Ordering": true,
       "Mode": 0
     },
     {
       "Udi": "umb://data-type/8786bc4dca2d4159bab66c970045677b",
       "Ordering": true,
       "Mode": 0
     },
     {
       "Udi": "umb://data-type/adb5786ff4f7491699f59e317d7a4c5b",
       "Ordering": true,
       "Mode": 0
     },
     {
       "Udi": "umb://data-type/b9105f2ebd1e40ee8b029be74cdfe1e1",
       "Ordering": true,
       "Mode": 0
     },
     {
       "Udi": "umb://data-type/c01a5fde2beb431ea60e7cc59347679d",
       "Ordering": true,
       "Mode": 0
     },
     {
       "Udi": "umb://data-type/f24dd3c4705e44f385725117aa99e164",
       "Ordering": true,
       "Mode": 0
     },
     {
       "Udi": "umb://document-type-container/c0a14cb54e3c4d858c1c1ac8874ccad5",
       "Ordering": true,
       "Mode": 0
     }
   ],
   "__type": "Umbraco.Deploy,Umbraco.Deploy.Artifacts.ContentType.DocumentTypeArtifact",
   "__version": "4.6.0"
 }
\ No newline at end of file

```







## The Exception:
```
System.ArgumentException: An item with the same key has already been added. Key: sEO
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
at System.Collections.ObjectModel.KeyedCollection`2.AddKey(TKey key, TItem item)
at System.Collections.ObjectModel.KeyedCollection`2.InsertItem(Int32 index, TItem item)
at Umbraco.Cms.Core.Models.PropertyGroupCollection.InsertItem(Int32 index, PropertyGroup item)
at System.Collections.ObjectModel.Collection`1.Add(T item)
at Umbraco.Cms.Core.Models.PropertyGroupCollection.Add(PropertyGroup item)
at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentTypeCommonRepository.MapGroupsAndProperties(IDictionary`2 contentTypes)
at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentTypeCommonRepository.GetAllTypesInternal()
at Umbraco.Extensions.AppCacheExtensions.<>c__DisplayClass0_0`1.<GetCacheItem>b__0()
at Umbraco.Cms.Core.Cache.SafeLazy.<>c__DisplayClass1_0.<GetSafeLazy>b__0()
--- End of stack trace from previous location ---
at Umbraco.Cms.Core.Cache.ObjectCacheAppCache.Get(String key, Func`1 factory, Nullable`1 timeout, Boolean isSliding, String[] dependentFiles)
at Umbraco.Cms.Core.Cache.DeepCloneAppCache.Get(String key, Func`1 factory, Nullable`1 timeout, Boolean isSliding, String[] dependentFiles)
at Umbraco.Extensions.AppCacheExtensions.GetCacheItem[T](IAppPolicyCache provider, String cacheKey, Func`1 getCacheItem, Nullable`1 timeout, Boolean isSliding, String[] dependentFiles)
at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentTypeCommonRepository.GetAllTypes()
at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentTypeRepository.GetAllWithFullCachePolicy()
at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentTypeRepositoryBase`1.PerformGetAll(Int32[] ids)
at Umbraco.Cms.Core.Cache.FullDataSetRepositoryCachePolicy`2.GetAllCached(Func`2 performGetAll)
at Umbraco.Cms.Core.Cache.FullDataSetRepositoryCachePolicy`2.GetAll(TId[] ids, Func`2 performGetAll)
at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.EntityRepositoryBase`2.GetMany(TId[] ids)
at Umbraco.Cms.Core.Services.Implement.ContentTypeServiceBase`2.GetAll(Int32[] ids)
at Umbraco.Cms.Infrastructure.PublishedCache.DataSource.MsgPackContentNestedDataSerializerFactory.Create(ContentCacheDataSerializerEntityType types)
at Umbraco.Cms.Infrastructure.PublishedCache.Persistence.NuCacheContentRepository.Rebuild(IReadOnlyCollection`1 contentTypeIds, IReadOnlyCollection`1 mediaTypeIds, IReadOnlyCollection`1 memberTypeIds)
at Umbraco.Cms.Infrastructure.PublishedCache.Persistence.NuCacheContentService.Rebuild(IReadOnlyCollection`1 contentTypeIds, IReadOnlyCollection`1 mediaTypeIds, IReadOnlyCollection`1 memberTypeIds)
at Umbraco.Cms.Infrastructure.PublishedCache.Persistence.NuCacheContentService.RebuildDatabaseCacheIfSerializerChanged()
at Umbraco.Cms.Infrastructure.PublishedCache.NuCacheStartupHandler.Handle(UmbracoApplicationStartingNotification notification)
at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.<>c__DisplayClass0_0.<Handle>b__1(INotification theNotification)
at Umbraco.Cms.Core.Events.EventAggregator.PublishCore(IEnumerable`1 allHandlers, INotification notification)
at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.Handle(INotification notification, ServiceFactory serviceFactory, Action`2 publish)
at Umbraco.Cms.Core.Events.EventAggregator.PublishNotification(INotification notification)
at Umbraco.Cms.Core.Events.EventAggregator.PublishAsync[TNotification](TNotification notification, CancellationToken cancellationToken)
at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.StartAsync(CancellationToken cancellationToken, Boolean isRestarting)
at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.StartAsync(CancellationToken cancellationToken)
at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
at BN.Umbraco.Web.Program.Main(String[] args) in C:\bn\Bn.Umbraco\src\BN.Umbraco.Web\Program.cs:line 11```
