### ISSUE TITLE
Distributed Cache instructions not being processed

### ISSUE THREAD

**Issue by nzdev** [umbraco/Umbraco-CMS#12022]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.0

### Bug summary

Distributed Cache instructions not being processed.

### Specifics

`The Scope 79172c91-c5d3-4ff0-a35e-63db2d12bc09 being disposed is not the Ambient Scope 49df9006-f188-463c-98f2-2da0912d4235. This typically indicates that a child Scope was not disposed, or flowed to a child thread that was not awaited, or concurrent threads are accessing the same Scope (Ambient context) which is not supported. If using Task.Run (or similar) as a fire and forget tasks or to run threads in parallel you must suppress execution context flow with ExecutionContext.SuppressFlow() and ExecutionContext.RestoreFlow(). `

```
System.InvalidOperationException:
   at Umbraco.Cms.Core.Scoping.Scope.Dispose (Umbraco.Infrastructure, Version=9.3.0.0, Culture=neutral, PublicKeyToken=null)
   at Umbraco.Cms.Core.Services.Implement.CacheInstructionService.ProcessInstructions (Umbraco.Infrastructure, Version=9.3.0.0, Culture=neutral, PublicKeyToken=null)
   at Umbraco.Cms.Infrastructure.Sync.DatabaseServerMessenger.Sync (Umbraco.Infrastructure, Version=9.3.0.0, Culture=neutral, PublicKeyToken=null)
   at Umbraco.Cms.Infrastructure.HostedServices.ServerRegistration.InstructionProcessTask.PerformExecuteAsync (Umbraco.Infrastructure, Version=9.3.0.0, Culture=neutral, PublicKeyToken=null)

```

### Steps to reproduce

Make changes to content.
Stop the site
Delete umbraco's temp files
Start the site.

### Expected result / actual result

Distributed Cache instructions are processed.

**Comment by nzdev** [comment]
More logs

```
System.InvalidOperationException: There is already an open DataReader associated with this Command which must be closed first.
   at System.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)
   at System.Data.SqlClient.SqlCommand.ValidateCommand(Boolean async, String method)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 236
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd)
   at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.CacheInstructionRepository.GetPendingInstructions(Int32 lastId, Int32 maxNumberToRetrieve)
   at Umbraco.Cms.Core.Services.Implement.CacheInstructionService.ProcessDatabaseInstructions(CacheRefresherCollection cacheRefreshers, CancellationToken cancellationToken, String localIdentity, Int32& lastId)
   at Umbraco.Cms.Core.Services.Implement.CacheInstructionService.ProcessInstructions(CacheRefresherCollection cacheRefreshers, ServerRole serverRole, CancellationToken cancellationToken, String localIdentity, DateTime lastPruned, Int32 lastId)
   at Umbraco.Cms.Infrastructure.Sync.DatabaseServerMessenger.Sync()
   at Umbraco.Cms.Infrastructure.HostedServices.ServerRegistration.InstructionProcessTask.PerformExecuteAsync(Object state)
```

```
System.InvalidOperationException: This SqlTransaction has completed; it is no longer usable.
   at System.Data.SqlClient.SqlTransaction.ZombieCheck()
   at System.Data.SqlClient.SqlTransaction.get_IsolationLevel()
   at Umbraco.Cms.Core.Scoping.Scope.get_Database()
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.CacheInstructionRepository.GetPendingInstructions(Int32 lastId, Int32 maxNumberToRetrieve)
   at Umbraco.Cms.Core.Services.Implement.CacheInstructionService.ProcessDatabaseInstructions(CacheRefresherCollection cacheRefreshers, CancellationToken cancellationToken, String localIdentity, Int32& lastId)
   at Umbraco.Cms.Core.Services.Implement.CacheInstructionService.ProcessInstructions(CacheRefresherCollection cacheRefreshers, ServerRole serverRole, CancellationToken cancellationToken, String localIdentity, DateTime lastPruned, Int32 lastId)
   at Umbraco.Cms.Infrastructure.Sync.DatabaseServerMessenger.Sync()
   at Umbraco.Cms.Infrastructure.HostedServices.ServerRegistration.InstructionProcessTask.PerformExecuteAsync(Object state)
```

**Comment by nzdev** [comment]
This will be used for a load balanced setup eventually, however these exceptions are being thrown while running locally from visual studio as well as a single instance on azure app service.

**Comment by vsilvar** [comment]
I also saw a related error in our logs:
```
System.InvalidOperationException: The Scope 84aaffde-46e4-4e4c-b4aa-40ad53e4fe71 being disposed is not the Ambient Scope e612c717-002f-46dd-9644-f0a81d8e57be. This typically indicates that a child Scope was not disposed, or flowed to a child thread that was not awaited, or concurrent threads are accessing the same Scope (Ambient context) which is not supported. If using Task.Run (or similar) as a fire and forget tasks or to run threads in parallel you must suppress execution context flow with ExecutionContext.SuppressFlow() and ExecutionContext.RestoreFlow().
   at Umbraco.Cms.Core.Scoping.Scope.Dispose()
   at Umbraco.Cms.Core.Services.Implement.ContentVersionService.CleanupDocumentVersions(DateTime asAtDate)
   at Umbraco.Cms.Core.Services.Implement.ContentVersionService.PerformContentVersionCleanup(DateTime asAtDate)
   at Umbraco.Cms.Infrastructure.HostedServices.ContentVersionCleanup.PerformExecuteAsync(Object state)
   at Umbraco.Cms.Infrastructure.HostedServices.RecurringHostedServiceBase.ExecuteAsync(Object state)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

The worst part is that this causes the whole AppDomain to be terminated and the website to restart.
(`Unhandled exception in AppDomain (terminating).`)

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/12153, thank you for your report! 💪
