### ISSUE TITLE
SQL Server Compact timed out waiting for a lock

### ISSUE THREAD

**Issue by Ibrahimogod** [umbraco/Umbraco-CMS#12041]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.0.1

### Bug summary

`
 SQL Server Compact timed out waiting for a lock. The default lock time is 2000ms for devices and 5000ms for desktops. The default lock timeout can be increased in the connection string using the ssce: default lock timeout property. [ Session id = 4,Thread id = 21320,Process id = 13684,Table name = umbracoLock,Conflict type = x lock (s blocks),Resource = RID: 1196:2 ]
   at System.Data.SqlServerCe.SqlCeCommand.ProcessResults(Int32 hr)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommandText(IntPtr& pCursor, Boolean& isBaseTableCursor)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommand(CommandBehavior behavior, String method, ResultSetOptions options)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteNonQuery()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)
   at Umbraco.Cms.Persistence.SqlCe.SqlCeSyntaxProvider.ObtainWriteLock(IDatabase db, TimeSpan timeout, Int32 lockId)
   at Umbraco.Cms.Persistence.SqlCe.SqlCeSyntaxProvider.WriteLock(IDatabase db, Int32[] lockIds)
   at Umbraco.Cms.Core.Scoping.Scope.LockInner(IUmbracoDatabase db, Guid instanceId, Dictionary`2& locks, HashSet`1& locksSet, Action`2 obtainLock, Action`3 obtainLockTimeout, Nullable`1 timeout, Int32[] lockIds)
   at Umbraco.Cms.Core.Scoping.Scope.EagerWriteLockInner(IUmbracoDatabase db, Guid instanceId, Nullable`1 timeout, Int32[] lockIds)
   at Umbraco.Cms.Core.Scoping.Scope.EnsureDbLocks()
   at Umbraco.Cms.Core.Scoping.Scope.get_Database()
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.DocumentVersionRepository.DeleteVersions(IEnumerable`1 versionIds)
   at Umbraco.Cms.Core.Services.Implement.ContentVersionService.CleanupDocumentVersions(DateTime asAtDate)
   at Umbraco.Cms.Core.Services.Implement.ContentVersionService.PerformContentVersionCleanup(DateTime asAtDate)
   at Umbraco.Cms.Infrastructure.HostedServices.ContentVersionCleanup.PerformExecuteAsync(Object state)
   at Umbraco.Cms.Infrastructure.HostedServices.RecurringHostedServiceBase.ExecuteAsync(Object state)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.Data.SqlServerCe.SqlCeLockTimeoutException (0x80004005): SQL Server Compact timed out waiting for a lock. The default lock time is 2000ms for devices and 5000ms for desktops. The default lock timeout can be increased in the connection string using the ssce: default lock timeout property. [ Session id = 4,Thread id = 21320,Process id = 13684,Table name = umbracoLock,Conflict type = x lock (s blocks),Resource = RID: 1196:2 ]
   at System.Data.SqlServerCe.SqlCeCommand.ProcessResults(Int32 hr)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommandText(IntPtr& pCursor, Boolean& isBaseTableCursor)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommand(CommandBehavior behavior, String method, ResultSetOptions options)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteNonQuery()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)
   at Umbraco.Cms.Persistence.SqlCe.SqlCeSyntaxProvider.ObtainWriteLock(IDatabase db, TimeSpan timeout, Int32 lockId)
   at Umbraco.Cms.Persistence.SqlCe.SqlCeSyntaxProvider.WriteLock(IDatabase db, Int32[] lockIds)
   at Umbraco.Cms.Core.Scoping.Scope.LockInner(IUmbracoDatabase db, Guid instanceId, Dictionary`2& locks, HashSet`1& locksSet, Action`2 obtainLock, Action`3 obtainLockTimeout, Nullable`1 timeout, Int32[] lockIds)
   at Umbraco.Cms.Core.Scoping.Scope.EagerWriteLockInner(IUmbracoDatabase db, Guid instanceId, Nullable`1 timeout, Int32[] lockIds)
   at Umbraco.Cms.Core.Scoping.Scope.EnsureDbLocks()
   at Umbraco.Cms.Core.Scoping.Scope.get_Database()
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.DocumentVersionRepository.DeleteVersions(IEnumerable`1 versionIds)
   at Umbraco.Cms.Core.Services.Implement.ContentVersionService.CleanupDocumentVersions(DateTime asAtDate)
   at Umbraco.Cms.Core.Services.Implement.ContentVersionService.PerformContentVersionCleanup(DateTime asAtDate)
   at Umbraco.Cms.Infrastructure.HostedServices.ContentVersionCleanup.PerformExecuteAsync(Object state)
   at Umbraco.Cms.Infrastructure.HostedServices.RecurringHostedServiceBase.ExecuteAsync(Object state)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
`

### Steps to reproduce

I can't Find andy solution

**Comment by nul800sebastiaan** [comment]
Hi again @Ibrahimogod - you seem to be having a lot of problems with SQLCE 😅 

This sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 

Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
