### ISSUE TITLE
Umbraco TrueFalse property in a block migrated from V8 throws exception

### ISSUE THREAD

**Issue by nzdev** [umbraco/Umbraco-CMS#12074]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.1

### Bug summary

Umbraco TrueFalse property in a block migrated from V8 throws exception.

### Specifics

```
An error occurred
Cannot assign value "False" of type "System.String" to property "inactive" expecting type "System.Int32".

Exception Details
System.InvalidOperationException, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: Cannot assign value "False" of type "System.String" to property "inactive" expecting type "System.Int32".
Stacktrace
at Umbraco.Cms.Core.Models.Property.ThrowTypeException(Object value, Type expected, String alias) in D:\repos\Umbraco-CMS\src\Umbraco.Core\Models\Property.cs:line 495
   at Umbraco.Cms.Core.Models.Property.TryConvertAssignedValue(Object value, Boolean throwOnError, Object& converted) in D:\repos\Umbraco-CMS\src\Umbraco.Core\Models\Property.cs:line 455
   at Umbraco.Cms.Core.Models.Property.ConvertAssignedValue(Object value) in D:\repos\Umbraco-CMS\src\Umbraco.Core\Models\Property.cs:line 411
   at Umbraco.Cms.Core.Models.Property.SetValue(Object value, String culture, String segment) in D:\repos\Umbraco-CMS\src\Umbraco.Core\Models\Property.cs:line 354
   at Umbraco.Cms.Core.PropertyEditors.BlockEditorPropertyEditor.BlockEditorPropertyValueEditor.<ToEditor>g__MapBlockItemData|6_0(List`1 items, <>c__DisplayClass6_0& ) in D:\repos\Umbraco-CMS\src\Umbraco.Infrastructure\PropertyEditors\BlockEditorPropertyEditor.cs:line 141
   at Umbraco.Cms.Core.PropertyEditors.BlockEditorPropertyEditor.BlockEditorPropertyValueEditor.ToEditor(IProperty property, String culture, String segment) in D:\repos\Umbraco-CMS\src\Umbraco.Infrastructure\PropertyEditors\BlockEditorPropertyEditor.cs:line 181
   at Umbraco.Cms.Core.Models.Mapping.ContentPropertyBasicMapper`1.Map(IProperty property, TDestination dest, MapperContext context) in D:\repos\Umbraco-CMS\src\Umbraco.Core\Models\Mapping\ContentPropertyBasicMapper.cs:line 81
   at Umbraco.Cms.Core.Models.Mapping.ContentPropertyDisplayMapper.Map(IProperty originalProp, ContentPropertyDisplay dest, MapperContext context) in D:\repos\Umbraco-CMS\src\Umbraco.Core\Models\Mapping\ContentPropertyDisplayMapper.cs:line 30
   at Umbraco.Cms.Core.Models.Mapping.ContentPropertyMapDefinition.Map(IProperty source, ContentPropertyDisplay target, MapperContext context) in D:\repos\Umbraco-CMS\src\Umbraco.Core\Models\Mapping\ContentPropertyMapDefinition.cs:line 61
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.<>c__DisplayClass9_0`2.<Define>b__1(Object source, Object target, MapperContext context) in D:\repos\Umbraco-CMS\src\Umbraco.Infrastructure\Mapping\UmbracoMapper.cs:line 113
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, Type sourceType, MapperContext context) in D:\repos\Umbraco-CMS\src\Umbraco.Infrastructure\Mapping\UmbracoMapper.cs:line 215
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.Map[TSource,TTarget](TSource source, MapperContext context) in D:\repos\Umbraco-CMS\src\Umbraco.Infrastructure\Mapping\UmbracoMapper.cs:line 197
   at Umbraco.Cms.Core.Mapping.MapperContext.Map[TSource,TTarget](TSource source) in D:\repos\Umbraco-CMS\src\Umbraco.Core\Mapping\MapperContext.cs:line 67
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToList()
   at Umbraco.Cms.Core.Mapping.MapperContext.MapEnumerable[TSourceElement,TTargetElement](IEnumerable`1 source) in D:\repos\Umbraco-CMS\src\Umbraco.Core\Mapping\MapperContext.cs:line 124
   at Umbraco.Cms.Core.Models.Mapping.TabsAndPropertiesMapper.MapProperties(IContentBase content, List`1 properties, MapperContext context) in D:\repos\Umbraco-CMS\src\Umbraco.Core\Models\Mapping\TabsAndPropertiesMapper.cs:line 86
   at Umbraco.Cms.Core.Models.Mapping.TabsAndPropertiesMapper`1.Map(TSource source, MapperContext context) in D:\repos\Umbraco-CMS\src\Umbraco.Core\Models\Mapping\TabsAndPropertiesMapper.cs:line 131
   at Umbraco.Cms.Web.BackOffice.Mapping.ContentMapDefinition.Map(IContent source, ContentVariantDisplay target, MapperContext context) in D:\repos\Umbraco-CMS\src\Umbraco.Web.BackOffice\Mapping\ContentMapDefinition.cs:line 172
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.<>c__DisplayClass9_0`2.<Define>b__1(Object source, Object target, MapperContext context) in D:\repos\Umbraco-CMS\src\Umbraco.Infrastructure\Mapping\UmbracoMapper.cs:line 113
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, Type sourceType, MapperContext context) in D:\repos\Umbraco-CMS\src\Umbraco.Infrastructure\Mapping\UmbracoMapper.cs:line 215
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, MapperContext context) in D:\repos\Umbraco-CMS\src\Umbraco.Infrastructure\Mapping\UmbracoMapper.cs:line 161
   at Umbraco.Cms.Core.Mapping.MapperContext.Map[TTarget](Object source) in D:\repos\Umbraco-CMS\src\Umbraco.Core\Mapping\MapperContext.cs:line 41
   at Umbraco.Cms.Core.Models.Mapping.ContentVariantMapper.Map(IContent source, MapperContext context) in D:\repos\Umbraco-CMS\src\Umbraco.Core\Models\Mapping\ContentVariantMapper.cs:line 32
   at Umbraco.Cms.Web.BackOffice.Mapping.ContentMapDefinition.Map(IContent source, ContentItemDisplay target, MapperContext context) in D:\repos\Umbraco-CMS\src\Umbraco.Web.BackOffice\Mapping\ContentMapDefinition.cs:line 157
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.<>c__DisplayClass9_0`2.<Define>b__1(Object source, Object target, MapperContext context) in D:\repos\Umbraco-CMS\src\Umbraco.Infrastructure\Mapping\UmbracoMapper.cs:line 113
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, Type sourceType, MapperContext context) in D:\repos\Umbraco-CMS\src\Umbraco.Infrastructure\Mapping\UmbracoMapper.cs:line 215
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, MapperContext context) in D:\repos\Umbraco-CMS\src\Umbraco.Infrastructure\Mapping\UmbracoMapper.cs:line 161
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, Action`1 f) in D:\repos\Umbraco-CMS\src\Umbraco.Infrastructure\Mapping\UmbracoMapper.cs:line 150
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.MapToDisplay(IContent content, Action`1 contextOptions) in D:\repos\Umbraco-CMS\src\Umbraco.Web.BackOffice\Controllers\ContentController.cs:line 2463
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.MapToDisplay(IContent content) in D:\repos\Umbraco-CMS\src\Umbraco.Web.BackOffice\Controllers\ContentController.cs:line 2449
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.GetById(Int32 id) in D:\repos\Umbraco-CMS\src\Umbraco.Web.BackOffice\Controllers\ContentController.cs:line 323
   at lambda_method523(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

### Steps to reproduce

Create a document type in umbraco v8.16 with a blocklist and a block containing an Umbraco TrueFalse property.
Save a document with the block value set.
Migrate V8.16 database to v9
Try to edit the document in v9. The error throws

### Expected result / actual result

No error, property converted correctly.

**Comment by CarlSargunar** [comment]
Might try and grab this one if it's still needed

**Comment by CarlSargunar** [comment]
Could not replicate. Looks like it worked when I tried it

Steps :

- Install Umbraco v8.15.4
- Configure database with SQL Server
- Add relevant data types (Homepage with a blocklist, containing a true false data type)
- Create content and save
- Upgrade the site to Umbraco v9.5.4
- Update connectionstring to existing detabase
Could not replicate. Looks like it worked when I tried it

Steps :

- Install Umbraco v8.15.4
- Configure database with SQL Server
- Add relevant data types (Homepage with a blocklist, containing a true false data type)
- Create content and save
- Upgrade the site to Umbraco v9.5.4
- Compltete installation, Update connectionstring to existing database
- Edit existing content 

Resullt, No errors, No errors in log, Data was correctly loaded

**Comment by r-modica-cti** [comment]
We are receiving this error in Umbraco 13 when trying to re-index on a system that has been upgraded from Umbraco 8.

**Comment by lumimario** [comment]
I'm having the same problem upgrading a site from V16 to V17
