### ISSUE TITLE
Member External Login Autolinking NotImplementedException

### ISSUE THREAD

**Issue by jattwood** [umbraco/Umbraco-CMS#12118]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.1

### Bug summary

Sucessfully implmented external login provider for Members with Auth0. Auto linking works up until the point that the member is auto created, but then fails after user creation prior to login with: NotImplementedException: The method or operation is not implemented at Umbraco.Cms.Core.Security.UmbracoUserStore<TUser, TRole>.FindTokenAsync(TUser user, string loginProvider, string name, CancellationToken cancellationToken)

### Specifics

It's very difficult of course to describe the exact Auth0 configuration other than the fact that it's as "out of the box" as possible.
1) login controller routes correctly to Auth0
2) User is able to register and login to Auth0
3) Handoff back to umbraco creates the missing user via Member Autolinking
4) after user creation, the new user is not signed into Umbraco.

Web page displays:
![image](https://user-images.githubusercontent.com/6452616/157519629-bf2a3a0a-785d-4ea9-88db-6e31b0fb239a.png)

Other pages on the site show the user is not logged in:
```
@inject IMemberManager _memberManager;
 @_memberManager.IsLoggedIn()
```
Returns false

Stack Trace from Log:

```
System.NotImplementedException: The method or operation is not implemented.
   at Umbraco.Cms.Core.Security.UmbracoUserStore`2.FindTokenAsync(TUser user, String loginProvider, String name, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserStoreBase`5.SetTokenAsync(TUser user, String loginProvider, String name, String value, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.SetAuthenticationTokenAsync(TUser user, String loginProvider, String tokenName, String tokenValue)
   at Microsoft.AspNetCore.Identity.SignInManager`1.UpdateExternalAuthenticationTokensAsync(ExternalLoginInfo externalLogin)
   at Umbraco.Cms.Web.Website.Controllers.UmbExternalLoginController.ExternalLoginCallback(String returnUrl)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Umbraco.Cms.Web.Common.Middleware.BasicAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.BackOffice.Middleware.BackOfficeExternalLoginProviderErrorMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 121
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Steps to reproduce

You can try and set up autolinking via auth0 if you have time LOL. Here are my relevant classes. Maybe it's an implementation issue, but we get to the end of the autolinking without issue and it's a not implemented error. That said, I can't find it in the source code either...

```
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Umbraco.Cms.Core.DependencyInjection;
using Umbraco.Extensions;
using System;
using Microsoft.Extensions.Options;
using Umbraco.Cms.Core;
using Umbraco.Cms.Web.BackOffice.Security;

namespace Protean.Core.Extensions
{
    public static class UmbracoMemberAuth0Authentication
    {
        public static IUmbracoBuilder UseUmbracoMemberAuth0Authentication(this IUmbracoBuilder builder, IConfiguration config)
        {
            builder.Services.ConfigureOptions<Auth0MemberExternalLoginProviderOptions>();
            builder.AddMemberExternalLogins(logins =>

            logins.AddMemberLogin(
                memberAuthenticationBuilder =>
                {
                    memberAuthenticationBuilder.AddOpenIdConnect(
                        memberAuthenticationBuilder.SchemeForMembers(Auth0MemberExternalLoginProviderOptions.SchemeName),
                        options =>
                        {
                            // use cookies
                            options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;

                            // pass configured options along
                            options.Authority = config["Auth0:Authority"];
                            options.ClientId = config["Auth0:ClientId"];
                            options.ClientSecret = config["Auth0:ClientSecret"];

                            // Use the authorization code flow
                            options.ResponseType = OpenIdConnectResponseType.Code;
                            options.AuthenticationMethod = OpenIdConnectRedirectBehavior.RedirectGet;
                           
                            // map claims
                            options.TokenValidationParameters.NameClaimType = "name";
                            options.TokenValidationParameters.RoleClaimType = "role";

                            options.RequireHttpsMetadata = true;
                            options.GetClaimsFromUserInfoEndpoint = true;
                            options.SaveTokens = true;

                            // add scope https://auth0.com/docs/get-started/apis/scopes/sample-use-cases-scopes-and-claims
                            options.Scope.Clear();
                            options.Scope.Add("profile");//! this is important 
                            options.Scope.Add("openid");
                            options.Scope.Add("email");
                            options.Scope.Add("roles");
                            options.UsePkce = true;

                        }
                        );
                }
                )
            );

            return builder;
        }
    }
}
```

```
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Umbraco.Cms.Core;
using Umbraco.Cms.Web.Common.Security;

namespace Protean.Core.Extensions
{
    public class Auth0MemberExternalLoginProviderOptions : IConfigureNamedOptions<MemberExternalLoginProviderOptions>
    {
        public const string SchemeName = "Auth0";

        public void Configure(string name, MemberExternalLoginProviderOptions options)
        {
            if (name != Constants.Security.MemberExternalAuthenticationTypePrefix + SchemeName)
            {
                return;
            }

            Configure(options);
        }

        public void Configure(MemberExternalLoginProviderOptions options) =>

            options.AutoLinkOptions = new MemberExternalSignInAutoLinkOptions(
                       // Must be true for auto-linking to be enabled
                       autoLinkExternalAccount: true,

                       // Optionally specify the default culture to create
                       // the user as. If null it will use the default
                       // culture defined in the web.config, or it can
                       // be dynamically assigned in the OnAutoLinking
                       // callback.
                       defaultCulture: null,

                       // Optionally specify the default "IsApprove" status. Must be true for auto-linking.
                       defaultIsApproved: true,

                       // Optionally specify the member type alias. Default is "Member"
                       defaultMemberTypeAlias: "Member",

                       // Optionally specify the member groups names to add the auto-linking user to.
                       defaultMemberGroups: Array.Empty<string>()
                   )
            {
                // Optional callback
                OnAutoLinking = (autoLinkUser, loginInfo) =>
                       {
                           //var name = loginInfo.Principal?.Identity?.Name;
                           // You can customize the member before it's linked.
                           // i.e. Modify the member's groups based on the Claims returned
                           // in the externalLogin info
                       },
                OnExternalLogin = (user, loginInfo) =>
                {
                    //var name = loginInfo.Principal?.Identity?.Name;
                    // You can customize the member before it's saved whenever they have
                    // logged in with the external provider.
                    // i.e. Sync the member's name based on the Claims returned
                    // in the externalLogin info

                    return true; //returns a boolean indicating if sign in should continue or not.
                }
            };
    }
}

```
In my startup.cs

```
            services.AddUmbraco(_env, _config)
                .AddBackOffice()
                .AddWebsite()
                .AddComposers()
                .UseUmbracoMemberAuth0Authentication(_config)
                .Build();
```

### Expected result / actual result

After successfully creating the user via autolinking, I would expect the final sign-in and redirect to follow directly after.

**Comment by p-m-j** [comment]
Should all be resolved in 9.4.0 by https://github.com/umbraco/Umbraco-CMS/pull/12093

**Comment by jattwood** [comment]
Awesome. I did a few searches on open issues but did not spot this duplicate. Thanks.

**Comment by p-m-j** [comment]
9.4 rc is out https://www.nuget.org/packages/Umbraco.Cms/9.4.0-rc, if you have the time to try it out on a local clone it would be great to confirm it's all sorted, if not we can re-open this issue.

**Comment by jattwood** [comment]
Sure will do. I'll likely have an answer to you early next week.

**Comment by jattwood** [comment]
So I had a few minutes and upgraded to 9.4. All is working perfectly. Thank you!

![image](https://user-images.githubusercontent.com/6452616/157898707-fc50b818-4320-456c-97fe-3f30a4f8b5d4.png)

**Comment by p-m-j** [comment]
Awesome cheers!
