### ISSUE TITLE
Settings tabs doesn't work

### ISSUE THREAD

**Issue by bielu** [umbraco/Umbraco-CMS#12197]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4.2

### Bug summary

I tried to access umbraco settings section, and got welcomed with following error:
<img width="316" alt="image" src="https://user-images.githubusercontent.com/2244074/160842557-db54a7da-eff2-4bd6-8562-835ed36caa69.png">

### Specifics

Stack trace:
```
at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Umbraco.Cms.Web.BackOffice.Trees.ApplicationTreeController.GetApiControllerProxy(Type controllerType, String action, FormCollection querystring)
   at Umbraco.Cms.Web.BackOffice.Trees.ApplicationTreeController.GetRootNode(Tree tree, FormCollection querystring)
   at Umbraco.Cms.Web.BackOffice.Trees.ApplicationTreeController.TryGetRootNode(Tree tree, FormCollection querystring)
   at Umbraco.Cms.Web.BackOffice.Trees.ApplicationTreeController.GetApplicationTrees(String application, String tree, FormCollection queryStrings, TreeUse use)
   at lambda_method619(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

### Steps to reproduce

1) install 9.4.2
2) click on setting tabs

### Expected result / actual result

Settings tab works.

**Comment by nul800sebastiaan** [comment]
and here I was looking very hard to find 9.4.2 😅

**Comment by bielu** [comment]
> and here I was looking very hard to find 9.4.2 😅

it was available on prerelease nuget, but found it was ghost dlls in solution #HateWhenItHappen
