### ISSUE TITLE
Cannot generate model for type X because it is an element type, but its parent type Y is not

### ISSUE THREAD

**Issue by Nikkelmann** [umbraco/Umbraco-CMS#12251]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4.3

### Bug summary

Nesting an Element type in a Document Type (no template) causes the model builder to fail.

It gives the following message:
```
Failed to build models.
Cannot generate model for type 'frequentlyAskedQuestion' because it is an element type, but its parent type 'frequentlyAskedQuestionFolder' is not.

at Umbraco.Cms.Infrastructure.ModelsBuilder.Building.Builder.Prepare()
at Umbraco.Cms.Infrastructure.ModelsBuilder.Building.Builder..ctor(ModelsBuilderSettings config, IList`1 typeModels)
at Umbraco.Cms.Infrastructure.ModelsBuilder.Building.ModelsGenerator.GenerateModels()
at Umbraco.Cms.Web.BackOffice.ModelsBuilder.ModelsBuilderDashboardController.BuildModels()
```

It also does not allow me to pick the element type as a child note type when it is nested:
![image](https://user-images.githubusercontent.com/3674690/162980171-ae7c2ea0-7aae-4923-a6d8-e1f57a6aa447.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/3674690/162978422-29a1552d-a1d0-4ae8-a961-e244d81f9f52.png)

### 1
Create a document type without a template.
![image](https://user-images.githubusercontent.com/3674690/162979411-b5690113-5f02-40d5-af3e-1278eff40a46.png)

### 2
Create a document type without a template under the first document type.
Also note, list view is enabled for this document type.
![image](https://user-images.githubusercontent.com/3674690/162979518-136664de-eee8-4d1a-a28c-3de6e5280079.png)

### 3
Create an element type under the second document type.
![image](https://user-images.githubusercontent.com/3674690/162979620-185a1da5-8c71-4944-9ace-448726874ddb.png)

### Expected result / actual result

Either the backoffice should stop me from creating element types under document types or the model builder should generate the model as any normal type (regardless of nesting).

**Comment by bielu** [comment]
@Nikkelmann I think I have little different point of view on it, it should not allow you to create children with different boolean value for element type than parent, as if you look on class inheritance, as Elements and Content inherits from different base classes/interfaces and they can't have 2 base classes:
https://github.com/umbraco/Umbraco-CMS/blob/5bfab13dc5a268714aad2426a2b68ab5561a6407/src/Umbraco.Core/PublishedCache/PublishedElement.cs#L17
and 
https://github.com/umbraco/Umbraco-CMS/blob/5bfab13dc5a268714aad2426a2b68ab5561a6407/src/Umbraco.Core/Models/PublishedContent/PublishedContentBase.cs#L14
So yeah not really case which should be supported as c# doesnt support multiple inheritance of classes:
https://stackoverflow.com/questions/11134832/inherit-from-two-classes-in-c-sharp :)

**Comment by nikolajlauridsen** [comment]
Hey @Nikkelmann, sorry for the late reply, but I just got around to having a look at this. 

I must say that I agree with @bielu, as they said when you create a child document type, you'll inherit from the parent (the document type), this becomes problematic because the child (the element) type, isn't actually a document type, and therefore shouldn't be able to inherit from a document type. 

Now I  do agree that it would be nice if the option for creating an element type wasn't shown when you right-click a document type, so I'll leave this as up for grabs with the proposed solution being to remove the element type entry when right-clicking a document. 

Of course you could still go into the settings of the document type and convert it to an element type, which is fine IMO.

**Comment by kjac** [comment]
Following the discussion on #15604 we've taken steps to prevent this situation in V14+. As mentioned on #15604, we won't be porting it back to V13, so I'll go ahead and close this issue.
