### ISSUE TITLE
Surrogate pairs are not supported

### ISSUE THREAD

**Issue by jomehmet** [umbraco/Umbraco-CMS#12276]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4.3

### Bug summary

After the migration from 8.18.0 to 9.4.3 is done and the log outputs _Upgrade Completed_ it builds cache, but the app fails to start because of an exception:  _Surrogate pairs are not supported._

I've added the stack trace and the console outputs in the Specifics section.

### Output from the migration
```
[14:59:37 INF] Acquiring MainDom.
[14:59:37 INF] Acquired MainDom.
[14:59:38 INF] Starting unattended upgrade. [Timing d1d34bb]
[14:59:38 INF] Database upgrade started
[14:59:39 INF] Starting 'Umbraco.Core'...
[14:59:39 INF] At {03482BB0-CF13-475C-845E-ECB8319DBE3C}
[14:59:39 INF] Execute UpdateCmsPropertyGroupIdSeed
[14:59:39 INF] At {622E5172-42E1-4662-AD80-9504AF5A4E53}
[14:59:39 INF] Execute ExternalLoginTableIndexesFixup
[14:59:39 INF] SQL [0]: ALTER TABLE [umbracoExternalLogin] ALTER COLUMN [loginProvider] NVARCHAR(400) NOT NULL
[14:59:39 INF] SQL [1]: CREATE NONCLUSTERED INDEX [IX_umbracoExternalLogin_LoginProvider] ON [umbracoExternalLogin] ([loginProvider],[userId])
[14:59:39 INF] SQL [2]: CREATE NONCLUSTERED INDEX [IX_umbracoExternalLogin_ProviderKey] ON [umbracoExternalLogin] ([loginProvider],[providerKey])
[14:59:39 INF] At {10F7BB61-C550-426B-830B-7F954F689CDF}
[14:59:39 INF] Execute DictionaryTablesIndexes
[14:59:39 INF] SQL [3]: DROP INDEX [IX_cmsDictionary_key] ON [cmsDictionary]
[14:59:39 INF] SQL [4]: CREATE UNIQUE NONCLUSTERED INDEX [IX_cmsDictionary_key] ON [cmsDictionary] ([key])
[14:59:39 INF] SQL [5]: CREATE UNIQUE NONCLUSTERED INDEX [IX_cmsLanguageText_languageId] ON [cmsLanguageText] ([languageId],[UniqueId])
[14:59:39 INF] At {5AAE6276-80DB-4ACF-B845-199BC6C37538}
[14:59:39 INF] Execute MigrateLogViewerQueriesFromFileToDb
[14:59:39 INF] SQL [6]: CREATE TABLE [umbracoLogViewerQuery] ([id] INTEGER NOT NULL IDENTITY(1,1),[name] NVARCHAR(255) NOT NULL,[query] NVARCHAR(255) NOT NULL)
[14:59:39 INF] SQL [7]: ALTER TABLE [umbracoLogViewerQuery] ADD CONSTRAINT [PK_umbracoLogViewerQuery] PRIMARY KEY CLUSTERED ([id])
[14:59:39 INF] SQL [8]: CREATE UNIQUE NONCLUSTERED INDEX [IX_LogViewerQuery_name] ON [umbracoLogViewerQuery] ([name])
[14:59:39 INF] At {22D801BA-A1FF-4539-BFCC-2139B55594F8}
[14:59:39 INF] Execute ExternalLoginTableIndexes
[14:59:39 INF] At {50A43237-A6F4-49E2-A7A6-5DAD65C84669}
[14:59:39 INF] Execute ExternalLoginTokenTable
[14:59:39 INF] SQL [9]: CREATE TABLE [umbracoExternalLoginToken] ([id] INTEGER NOT NULL IDENTITY(1,1),[externalLoginId] INTEGER NOT NULL,[name] NVARCHAR(255) NOT NULL,[value] NVARCHAR(MAX) NOT NULL,[createDate] DATETIME NOT NULL CONSTRAINT [DF_umbracoExternalLoginToken_createDate] DEFAULT (GETDATE()))
[14:59:39 INF] SQL [10]: ALTER TABLE [umbracoExternalLoginToken] ADD CONSTRAINT [PK_umbracoExternalLoginToken] PRIMARY KEY CLUSTERED ([id])
[14:59:39 INF] SQL [11]: ALTER TABLE [umbracoExternalLoginToken] ADD CONSTRAINT [FK_umbracoExternalLoginToken_umbracoExternalLogin_id] FOREIGN KEY ([externalLoginId]) REFERENCES [umbracoExternalLogin] ([id])
[14:59:39 INF] SQL [12]: CREATE UNIQUE NONCLUSTERED INDEX [IX_umbracoExternalLoginToken_Name] ON [umbracoExternalLoginToken] ([externalLoginId],[name])
[14:59:39 INF] At {3D8DADEF-0FDA-4377-A5F0-B52C2110E8F2}
[14:59:39 INF] Execute MemberTableColumns
[14:59:40 INF] SQL [13]: ALTER TABLE [cmsMember] ADD [securityStampToken] NVARCHAR(255) NULL
[14:59:40 INF] SQL [14]: ALTER TABLE [cmsMember] ADD [emailConfirmedDate] DATETIME NULL
[14:59:40 INF] At {1303BDCF-2295-4645-9526-2F32E8B35ABD}
[14:59:40 INF] Execute AddPasswordConfigToMemberTable
[14:59:40 INF] SQL [15]: ALTER TABLE [cmsMember] ADD [passwordConfig] NVARCHAR(500) NULL
[14:59:40 INF] At {5060F3D2-88BE-4D30-8755-CF51F28EAD12}
[14:59:40 INF] Execute AddPropertyTypeGroupColumns
[14:59:42 ERR] Detected the same alias equivalentLanguages for different property group names ["Equivalent Languages", "Equivalent languages"], the migration added suffixes, but this might break backwards compatibility.
[14:59:43 ERR] Detected the same alias banner1 for different property group names ["Banner 1", "Banner1"], the migration added suffixes, but this might break backwards compatibility.
[14:59:44 ERR] Detected the same alias linkList for different property group names ["Link list", "Link List"], the migration added suffixes, but this might break backwards compatibility.
[14:59:44 INF] At {A2686B49-A082-4B22-97FD-AAB154D46A57}
[14:59:44 INF] Execute UmbracoServerColumn
[14:59:44 INF] SQL [16]: sp_rename 'umbracoServer.isMaster', 'isSchedulingPublisher', 'COLUMN'
[14:59:44 INF] SQL [17]: ALTER TABLE [umbracoServer] ALTER COLUMN [isSchedulingPublisher] BIT NOT NULL
[14:59:44 INF] At 5E02F241-5253-403D-B5D3-7DB00157E20F
[14:59:44 INF] Execute AddContentVersionCleanupFeature
[14:59:44 INF] At {8BAF5E6C-DCB7-41AE-824F-4215AE4F1F98}
[14:59:44 INF] Execute AddUserGroup2NodeTable
[14:59:44 INF] SQL [18]: CREATE TABLE [umbracoUserGroup2Node] ([userGroupId] INTEGER NOT NULL,[nodeId] INTEGER NOT NULL)
[14:59:44 INF] SQL [19]: ALTER TABLE [umbracoUserGroup2Node] ADD CONSTRAINT [PK_umbracoUserGroup2Node] PRIMARY KEY CLUSTERED ([userGroupId], [nodeId])
[14:59:44 INF] SQL [20]: ALTER TABLE [umbracoUserGroup2Node] ADD CONSTRAINT [FK_umbracoUserGroup2Node_umbracoUserGroup_id] FOREIGN KEY ([userGroupId]) REFERENCES [umbracoUserGroup] ([id])
[14:59:45 INF] SQL [21]: ALTER TABLE [umbracoUserGroup2Node] ADD CONSTRAINT [FK_umbracoUserGroup2Node_umbracoNode_id] FOREIGN KEY ([nodeId]) REFERENCES [umbracoNode] ([id])
[14:59:45 INF] SQL [22]: CREATE NONCLUSTERED INDEX [IX_umbracoUserGroup2Node_nodeId] ON [umbracoUserGroup2Node] ([nodeId])
[14:59:45 INF] At {0571C395-8F0B-44E9-8E3F-47BDD08D817B}
[14:59:45 INF] Execute AddDefaultForNotificationsToggle
[14:59:45 INF] SQL [23]: UPDATE umbracoUserGroup SET userGroupDefaultPermissions = userGroupDefaultPermissions + 'N' WHERE userGroupAlias IN ('admin', 'writer', 'editor')
[14:59:45 INF] At {AD3D3B7F-8E74-45A4-85DB-7FFAD57F9243}
[14:59:45 INF] Execute MovePackageXMLToDb
[14:59:45 INF] SQL [24]: CREATE TABLE [umbracoCreatedPackageSchema] ([id] INTEGER NOT NULL IDENTITY(1,1),[name] NVARCHAR(255) NOT NULL,[value] NVARCHAR(MAX) NOT NULL,[updateDate] DATETIME NOT NULL CONSTRAINT [DF_umbracoCreatedPackageSchema_updateDate] DEFAULT (GETDATE()),[packageId] UniqueIdentifier NOT NULL)
[14:59:45 INF] SQL [25]: ALTER TABLE [umbracoCreatedPackageSchema] ADD CONSTRAINT [PK_umbracoCreatedPackageSchema] PRIMARY KEY CLUSTERED ([id])
[14:59:45 INF] SQL [26]: CREATE UNIQUE NONCLUSTERED INDEX [IX_umbracoCreatedPackageSchema_Name] ON [umbracoCreatedPackageSchema] ([name])
[14:59:45 INF] At {A2F22F17-5870-4179-8A8D-2362AA4A0A5F}
[14:59:45 INF] Execute UpdateExternalLoginToUseKeyInsteadOfId
[14:59:45 INF] SQL [27]: DROP INDEX [IX_umbracoExternalLogin_LoginProvider] ON [umbracoExternalLogin]
[14:59:45 INF] SQL [28]: ALTER TABLE [umbracoExternalLogin] ADD [userOrMemberKey] UniqueIdentifier NULL
[14:59:45 INF] SQL [29]: UPDATE umbracoExternalLogin SET userOrMemberKey = CAST(CONVERT(char(8), CONVERT(BINARY(4), userId), 2) + '-0000-0000-0000-000000000000' AS UNIQUEIDENTIFIER)
[14:59:45 INF] SQL [30]: ALTER TABLE [umbracoExternalLogin] ALTER COLUMN [userOrMemberKey] UniqueIdentifier NOT NULL
[14:59:45 INF] SQL [31]: ALTER TABLE [umbracoExternalLogin] DROP COLUMN [userId];
[14:59:45 INF] SQL [32]: CREATE NONCLUSTERED INDEX [IX_umbracoExternalLogin_LoginProvider] ON [umbracoExternalLogin] ([loginProvider],[userOrMemberKey])
[14:59:45 INF] At {CA7A1D9D-C9D4-4914-BC0A-459E7B9C3C8C}
[14:59:45 INF] Execute AddTwoFactorLoginTable
[14:59:45 INF] SQL [33]: CREATE TABLE [umbracoTwoFactorLogin] ([id] INTEGER NOT NULL IDENTITY(1,1),[userOrMemberKey] UniqueIdentifier NOT NULL,[providerName] NVARCHAR(400) NOT NULL,[secret] NVARCHAR(400) NOT NULL)
[14:59:45 INF] SQL [34]: ALTER TABLE [umbracoTwoFactorLogin] ADD CONSTRAINT [PK_umbracoTwoFactorLogin] PRIMARY KEY CLUSTERED ([id])
[14:59:45 INF] SQL [35]: CREATE NONCLUSTERED INDEX [IX_umbracoTwoFactorLogin_userOrMemberKey] ON [umbracoTwoFactorLogin] ([userOrMemberKey])
[14:59:45 INF] SQL [36]: CREATE UNIQUE NONCLUSTERED INDEX [IX_umbracoTwoFactorLogin_ProviderName] ON [umbracoTwoFactorLogin] ([providerName],[userOrMemberKey])
[14:59:45 INF] At {0828F206-DCF7-4F73-ABBB-6792275532EB}
[14:59:45 INF] Execute AddScheduledPublishingLock
[14:59:45 INF] At {DBBA1EA0-25A1-4863-90FB-5D306FB6F1E1}
[14:59:45 INF] Execute UpdateRelationTypesToHandleDependencies
[14:59:45 INF] SQL [37]: ALTER TABLE [umbracoRelationType] ADD [isDependency] BIT NOT NULL CONSTRAINT [DF_umbracoRelationType_isDependency] DEFAULT ('0')
[14:59:45 INF] At {DED98755-4059-41BB-ADBD-3FEAB12D1D7B}
[14:59:45 INF] PostMigration: Umbraco.Cms.Infrastructure.Migrations.PostMigrations.DeleteLogViewerQueryFile.
[14:59:45 INF] Done (pending scope completion).
[14:59:46 INF] Database configuration status: <p>Upgrade completed!</p>
[14:59:46 INF] Unattended upgrade completed. (7021ms) [Timing d1d34bb]
[14:59:46 WRN] Database NuCache was serialized using 0. Currently configured NuCache serializer MessagePack. Rebuilding Nucache
[14:59:46 INF] Rebuilding NuCache database with MessagePack serializer [Timing b5ee7fb]
[14:59:54 INF] Completed. (8031ms) [Timing b5ee7fb]
```

### Stack trace
```
System.NotSupportedException
  HResult=0x80131515
  Message=Surrogate pairs are not supported.
  Source=Umbraco.Core
  StackTrace:
   at Umbraco.Cms.Core.Strings.DefaultShortStringHelper.CleanCodeString(String text, CleanStringType caseType, Char separator, String culture, Config config)
   at Umbraco.Cms.Core.Strings.DefaultShortStringHelper.CleanString(String text, CleanStringType stringType, String culture, Nullable`1 separator)
   at Umbraco.Cms.Core.Strings.DefaultShortStringHelper.CleanStringForUrlSegment(String text, String culture)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Umbraco.Extensions.ContentBaseExtensions.GetUrlSegment(IContentBase content, IShortStringHelper shortStringHelper, IEnumerable`1 urlSegmentProviders, String culture)
   at Umbraco.Cms.Infrastructure.PublishedCache.Persistence.NuCacheContentRepository.GetDto(IContentBase content, Boolean published, IContentCacheDataSerializer serializer)
   at Umbraco.Cms.Infrastructure.PublishedCache.Persistence.NuCacheContentRepository.RebuildContentDbCache(IContentCacheDataSerializer serializer, Int32 groupSize, IReadOnlyCollection`1 contentTypeIds)
   at Umbraco.Cms.Infrastructure.PublishedCache.Persistence.NuCacheContentRepository.Rebuild(IReadOnlyCollection`1 contentTypeIds, IReadOnlyCollection`1 mediaTypeIds, IReadOnlyCollection`1 memberTypeIds)
   at Umbraco.Cms.Infrastructure.PublishedCache.Persistence.NuCacheContentService.Rebuild(IReadOnlyCollection`1 contentTypeIds, IReadOnlyCollection`1 mediaTypeIds, IReadOnlyCollection`1 memberTypeIds)
   at Umbraco.Cms.Infrastructure.PublishedCache.Persistence.NuCacheContentService.RebuildDatabaseCacheIfSerializerChanged()
   at Umbraco.Cms.Infrastructure.PublishedCache.NuCacheStartupHandler.Handle(UmbracoApplicationStartingNotification notification)
   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.<>c__DisplayClass0_0.<Handle>b__1(INotification theNotification)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishCore(IEnumerable`1 allHandlers, INotification notification)
   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.Handle(INotification notification, ServiceFactory serviceFactory, Action`2 publish)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishNotification(INotification notification)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishAsync[TNotification](TNotification notification, CancellationToken cancellationToken)
   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.<StartAsync>d__22.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.<StartAsync>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at BN.Umbraco.Web.Program.Main(String[] args) in C:\bn\Bn.Umbraco\src\BN.Umbraco.Web\Program.cs:line 11

  This exception was originally thrown at this call stack:
    Umbraco.Cms.Core.Strings.DefaultShortStringHelper.CleanCodeString(string, Umbraco.Cms.Core.Strings.CleanStringType, char, string, Umbraco.Cms.Core.Strings.DefaultShortStringHelperConfig.Config)
    Umbraco.Cms.Core.Strings.DefaultShortStringHelper.CleanString(string, Umbraco.Cms.Core.Strings.CleanStringType, string, char?)
    Umbraco.Cms.Core.Strings.DefaultShortStringHelper.CleanStringForUrlSegment(string, string)
    System.Linq.Enumerable.SelectEnumerableIterator<TSource, TResult>.MoveNext()
    System.Linq.Enumerable.TryGetFirst<TSource>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource, bool>, out bool)
    Umbraco.Extensions.ContentBaseExtensions.GetUrlSegment(Umbraco.Cms.Core.Models.IContentBase, Umbraco.Cms.Core.Strings.IShortStringHelper, System.Collections.Generic.IEnumerable<Umbraco.Cms.Core.Strings.IUrlSegmentProvider>, string)
    Umbraco.Cms.Infrastructure.PublishedCache.Persistence.NuCacheContentRepository.GetDto(Umbraco.Cms.Core.Models.IContentBase, bool, Umbraco.Cms.Infrastructure.PublishedCache.DataSource.IContentCacheDataSerializer)
    Umbraco.Cms.Infrastructure.PublishedCache.Persistence.NuCacheContentRepository.RebuildContentDbCache(Umbraco.Cms.Infrastructure.PublishedCache.DataSource.IContentCacheDataSerializer, int, System.Collections.Generic.IReadOnlyCollection<int>)
    Umbraco.Cms.Infrastructure.PublishedCache.Persistence.NuCacheContentRepository.Rebuild(System.Collections.Generic.IReadOnlyCollection<int>, System.Collections.Generic.IReadOnlyCollection<int>, System.Collections.Generic.IReadOnlyCollection<int>)
    Umbraco.Cms.Infrastructure.PublishedCache.Persistence.NuCacheContentService.Rebuild(System.Collections.Generic.IReadOnlyCollection<int>, System.Collections.Generic.IReadOnlyCollection<int>, System.Collections.Generic.IReadOnlyCollection<int>)
    ...
    [Call Stack Truncated]
```

### Steps to reproduce

![image](https://user-images.githubusercontent.com/840606/164242365-99030bbe-8034-4430-8c50-569fc7dc6908.png)

### Expected result / actual result

Expecting the web app to start.

---
_This item has been added to our backlog [AB#19154](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/19154)_

**Comment by bergmania** [comment]
Hi @jomehmet 

Thanks for reporting.. 

What is the value of `text` on line `331` in the first screenshot?

**Comment by nathanwoulfe** [comment]
Hit the same issue after a migration, caused by emoji in content/media node names...

**Comment by jomehmet** [comment]
> Hi @jomehmet
> 
> Thanks for reporting..
> 
> What is the value of `text` on line `331` in the first screenshot?

This is a good question. I haven't figured out how to debug code located in Umbraco.Core. Currently I'm running the project cloned from Umbraco Cloud, and the file shown is opened from Umbraco-CMS repo with tag: release-9.4.3

Please give me a clue on how I can attach this to the debugger. I'm developing on VS 2022

**Comment by bergmania** [comment]
> Please give me a clue on how I can attach this to the debugger. I'm developing on VS 2022

I'm not completely sure when you use VS. But I would expect it to show the exception when debugging you project, and at that point, it should be possible to see the values of all the variables that are not gone due to the compiler optimization.

At least that is how it works with Rider.

**Comment by jomehmet** [comment]
Wow, Rider was amazing, just worked to debug out of the box. We have the same issue as @nathanwoulfe 
An emoji in the pathname/title gives the exception. Would it be better to replace the surrugate pair with empty string, so it dosen't crash this hard.

![image](https://user-images.githubusercontent.com/840606/164679266-d39038e5-1bf8-496f-b6c1-c302db0681a5.png)

**Comment by jomehmet** [comment]
Btw. does it mean that Umbraco 9 will crash entirely if someone ads an emoji in the title? If this is the case, there won't be any ways to edit the title except for going directly into the DB, which is not straight forward.

**Comment by bergmania** [comment]
Looks like that.. I just tested using "🎈🎈" and it fails, but it also fails on Umbraco 8, with the same exception. What emoji did you use? I wonder if it is only some that is an issue and I also do not understand why this should be different between V8 and V9. This code has not been changed since 2013 🙈 

I wonder what happens if we just replaced the exception with `continue`.

**Comment by nathanwoulfe** [comment]
I saw the issue in a 7-8 migration, which would be expected if that code hasn't changed since 2013 😊

Can't remember what the emoji was, I just removed it and re-ran the migration...

**Comment by ronaldbarendse** [comment]
The problem with the current implementation is that it uses `char` (a 16-bit value) to represent a single character, but that's not the case anymore for emojis and some other languages that require multiple `char`s  (surrogate pairs) to represent a single character.

.NET Core 3.0 introduced the [`Rune` struct](https://docs.microsoft.com/en-us/dotnet/api/system.text.rune) that correctly handles this, but that would require a complete rewrite of the `DefaultShortStringHelper` 😒

Some relevant links about this:
- https://github.com/dotnet/runtime/issues/23578
- https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-encoding-introduction
- https://www.meziantou.net/how-to-correctly-count-the-number-of-characters-of-a-string.htm
