### ISSUE TITLE
Distributed cache table deadlocking

### ISSUE THREAD

**Issue by OzoneNZ** [umbraco/Umbraco-CMS#12287]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4.0

### Bug summary

We've been running into a situation where our either our Umbraco scheduler or one of the replicas will throw an exception after hours/days of uptime:

```
[05:15:57 ERR] DISTRIBUTED CACHE IS NOT UPDATED. Failed to execute instructions (38219: '[{"RefreshType":4,"RefresherId":"6902e22c-9c10-483c-91f3-66b7cae9e2f5","GuidId":"00000000-0000-0000-0000-000000000000","IntId":0,"JsonIds":null,"JsonIdCount":1,"JsonPayload":"[{\"ItemType\":\"IContentType\",\"Id\":1651,\"ChangeTypes\":4}]"}]'). Instruction is being skipped/ignored
System.Data.SqlClient.SqlException (0x80131904): Transaction (Process ID 88) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
```

The flow-on effect of this is that our replica servers fall out-of-sync and serve up stale content because they fail to process the cache instructions

### Specifics

Some background on our hosting environment:

- 1 x Scheduling publisher instance running under Kubernetes
- 1 x Replica instance running under Kubernetes
- Azure SQL database (20 DTU)
- `Umbraco__CMS__Global__MainDomLock` is set to `SqlMainDomLock`

I've tested the below changes without any change in behaviour:

- Increasing `Umbraco__CMS__Global__SqlWriteLockTimeOut` to the maximum value of `00:00:20`
- Increasing `Umbraco__CMS__Global__DatabaseServerMessenger__TimeBetweenSyncOperations` to `00:01:00`
- Increasing `Umbraco__CMS__Global__DatabaseServerMessenger__TimeBetweenPruneOperations` to `00:05:00`
- Changing from Windows-based Docker containers to Alpine Linux
- Using a higher-performance Azure SQL database tier to rule out insufficient database resources

The SQL profiler shows these kinds of calls happening multiple times per second, unsure if this is related:

![image](https://user-images.githubusercontent.com/4223195/164574388-3955f636-e618-48c0-a5c8-78c7440ce989.png)

### Steps to reproduce

I'm not totally sure how to reproduce this other than describing our environment/setup, but it seems to happen completely randomly after several hours or days have passed

Full stack trace:

```
[05:15:57 ERR] DISTRIBUTED CACHE IS NOT UPDATED. Failed to execute instructions (38219: '[{"RefreshType":4,"RefresherId":"6902e22c-9c10-483c-91f3-66b7cae9e2f5","GuidId":"00000000-0000-0000-0000-000000000000","IntId":0,"JsonIds":null,"JsonIdCount":1,"JsonPayload":"[{\"ItemType\":\"IContentType\",\"Id\":1651,\"ChangeTypes\":4}]"}]'). Instruction is being skipped/ignored
System.Data.SqlClient.SqlException (0x80131904): Transaction (Process ID 88) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at System.Data.SqlClient.SqlCommand.CompleteExecuteScalar(SqlDataReader ds, Boolean returnSqlValue)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at NPoco.Database.ExecuteScalarHelper(DbCommand cmd)
   at NPoco.Database.ExecuteScalar[T](String sql, CommandType commandType, Object[] args)
   at Umbraco.Cms.Infrastructure.Persistence.SqlSyntax.SqlServerSyntaxProvider.ObtainReadLock(IDatabase db, Nullable`1 timeout, Int32 lockId)
   at Umbraco.Cms.Infrastructure.Persistence.SqlSyntax.SqlServerSyntaxProvider.ReadLock(IDatabase db, Int32[] lockIds)
   at Umbraco.Cms.Core.Scoping.Scope.LockInner(IUmbracoDatabase db, Guid instanceId, Dictionary`2& locks, HashSet`1& locksSet, Action`2 obtainLock, Action`3 obtainLockTimeout, Nullable`1 timeout, Int32[] lockIds)
   at Umbraco.Cms.Core.Scoping.Scope.EagerReadLockInner(IUmbracoDatabase db, Guid instanceId, Nullable`1 timeout, Int32[] lockIds)
   at Umbraco.Cms.Core.Scoping.Scope.EnsureDbLocks()
   at Umbraco.Cms.Core.Scoping.Scope.get_Database()
   at Umbraco.Cms.Core.Scoping.Scope.get_Database()
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentRepositoryBase`3.GetPage[TDto](IQuery`1 query, Int64 pageIndex, Int32 pageSize, Int64& totalRecords, Func`2 mapDtos, Sql`1 filter, Ordering ordering)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.DocumentRepository.GetPage(IQuery`1 query, Int64 pageIndex, Int32 pageSize, Int64& totalRecords, IQuery`1 filter, Ordering ordering)
   at Umbraco.Cms.Core.Services.Implement.ContentService.GetPagedOfTypes(Int32[] contentTypeIds, Int64 pageIndex, Int32 pageSize, Int64& totalRecords, IQuery`1 filter, Ordering ordering)
   at Umbraco.Cms.Infrastructure.Search.ContentTypeIndexingNotificationHandler.RefreshContentOfContentTypes(Int32[] contentTypeIds)
   at Umbraco.Cms.Infrastructure.Search.ContentTypeIndexingNotificationHandler.Handle(ContentTypeCacheRefresherNotification args)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishCore(IEnumerable`1 allHandlers, INotification notification)
   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.Handle(INotification notification, ServiceFactory serviceFactory, Action`2 publish)
   at Umbraco.Cms.Core.Events.EventAggregator.Publish[TNotification](TNotification notification)
   at Umbraco.Cms.Core.Services.Implement.CacheInstructionService.NotifyRefreshers(CacheRefresherCollection cacheRefreshers, IEnumerable`1 instructions, HashSet`1 processed, CancellationToken cancellationToken)
   at Umbraco.Cms.Core.Services.Implement.CacheInstructionService.ProcessDatabaseInstructions(CacheRefresherCollection cacheRefreshers, IReadOnlyCollection`1 instructionBatch, CacheInstruction instruction, HashSet`1 processed, CancellationToken cancellationToken, Int32& lastId)
ClientConnectionId:e8a48655-2ba1-429e-8f9c-b3faffc9b678
Error Number:1205,State:51,Class:13
ClientConnectionId before routing:912114a7-4f55-49d4-a933-a57b778513f6
```

**Comment by mistyn8** [comment]
We have the same issue of subscribers stop synching after running fine for days if not weeks.. But see no logs regarding distributed cache failures, also no errors regarding the CacheInstructionService. It just seems that the poling from the subscriber to the db has stopped?
We can see instructions going into the `dbo.umbracoCacheInstruction` table and `dbo.umbracoServer` reports 1 active schedulingpublisher and 1 active Subscriber both with recent `lastNotifiedDates`

Our setup is azure app_services with dedicated scheduling_publisher and subscriber server nodes set (subscriber is currently set to 1 instance but with the intention to set to autoscale), with the umbracoapplicationurl set to the `https://{scheduling_publisher_url}/umbraco`

Looking through the code.. there doesn't seem to be any logging for successfully `cacheinstruction` processing perhaps that could be added so that we at least get notifications to observe for when it stops?

**Comment by nikolajlauridsen** [comment]
Hey @OzoneNZ sorry for getting back to you so late, but can you confirm if this is still an issue on the latest 10? This does indeed seem like it might be hard to reproduce

**Comment by elit0451** [comment]
Hi again, 

Since we need more information to try to reproduce the issue and we haven't heard from you in two weeks, we would have to close this one. Feel free to reopen it if you are able to provide us with some more information 🙂
