### ISSUE TITLE
Bug when saving long values Checkbox property data

### ISSUE THREAD

**Issue by nickornotto** [umbraco/Umbraco-CMS#12284]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

Umbraco 8, Umbraco 9

### Bug summary

It is the issue with the umbraco 8/9 database schema.

Error thrown when saving a content containg the property data in the CMS:

> An error occurred
> String or binary data would be truncated. The statement has been terminated.
> 
> Exception Details
> System.Data.SqlClient.SqlException, System.Data.SqlClient, Version=4.6.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: String or binary data would be truncated. The statement has been terminated.
> Stacktrace
> at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
>    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
>    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
>    at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
>    at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
>    at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)
>    at NPoco.Database.<Update>b__208_0(String sql, Object[] args, Func`2 next)
>    at NPoco.Database.Update(String tableName, String primaryKeyName, Object poco, Object primaryKeyValue, IEnumerable`1 columns)
>    at NPoco.Database.Update(Object poco, Object primaryKeyValue, IEnumerable`1 columns)
>    at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentRepositoryBase`3.ReplacePropertyValues(TEntity entity, Int32 versionId, Int32 publishedVersionId, Boolean& edited, HashSet`1& editedCultures)
>    at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.DocumentRepository.PersistUpdatedItem(IContent entity)
>    at Umbraco.Cms.Core.Cache.DefaultRepositoryCachePolicy`2.Update(TEntity entity, Action`1 persistUpdated)
>    at Umbraco.Cms.Core.Services.Implement.ContentService.CommitDocumentChangesInternal(IScope scope, IContent content, EventMessages eventMessages, IReadOnlyCollection`1 allLangs, IDictionary`2 notificationState, Int32 userId, Boolean branchOne, Boolean branchRoot)
>    at Umbraco.Cms.Core.Services.Implement.ContentService.SaveAndPublish(IContent content, String culture, Int32 userId)
>    at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PublishInternal(ContentItemSave contentItem, String defaultCulture, String cultureForInvariantErrors, Boolean& wasCancelled, String[]& successfulCultures)
>    at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PostSaveInternal(ContentItemSave contentItem, Func`2 saveMethod, Func`2 mapToDisplay)
>    at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PostSave(ContentItemSave contentItem)
>    at lambda_method14741(Closure , Object )
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

Similar error thrown on trying to upgrade the database to Umbraco 8 / 9.

As specified in the issue: https://github.com/umbraco/Umbraco-CMS/issues/11810

### Specifics

It is the issue with the umbraco 8/9 database schema.

Basically in v7 the `checkboxlist `(`radiobuttonlist` and `dropdownlist `also) property data values are stored as datatype ids, eg.:

> 23478,23468,23467,23466,23472,23474,23469,23477,23475,23471,23470,23476,23473

However in Umbraco 8 it changed and the values are stored instead as property data values themselves, not their ids - that can make the value in the database longer - depending on what strings are used for values. 

This type of property data is stored in `varcharValue` column in `umbracoPropertyData `which is of type `nvarchar(512)` so any string that is longer than 512 is throwing an error that it will be truncated.

In my case I have (in Umbraco 9) values:

> ["Face masks required for travellers in public areas","Face masks required for guides in public areas","Face masks provided for travellers","Hand sanitiser available to travellers and staff","Social distancing enforced throughout experience","Regularly sanitised high-traffic areas","Gear/equipment sanitised between use","Transportation vehicles regularly sanitised","Guides required to regularly wash hands","Regular temperature checks for staff","Temperature checks for travellers upon arrival", "Paid stay-at-home policy for staff with symptoms"]

which makes it 498 characters and that fits into the `nvarchar(512)`

Just adding one more additional value, it does not fit anymore - and saving the content in Umbraco 9 throws an error as well. Since there is no limit on the number of characters or number of items for checkbox/ dropdown/ radiobutton data type values, this is a bug.

### Steps to reproduce

1. Add a checkbox  data type to Umbraco 8 or 9. Makes several values enough long that the combined length of characters of all items exceed 512.
2. Add content with the above data type.
3. Tick all the values in the data data in the content in the CMS and try to save the content.
4. The error will appear.

### Expected result / actual result

If the property data can have max 512 characters in the db then the data type should only allow values with the combined characters' length not exceeding 512.

Otherwise the property value should allow to save data correctly with more than 512 characters.

---
_This item has been added to our backlog [AB#32032](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/32032)_

**Comment by nikolajlauridsen** [comment]
Hey @nickornotto, first of sorry for the late answer, and thanks a lot for reporting.

I've had a look at reproducing this, and I can indeed reproduce it if I create a dropdown multiple with very long values. Fixing this will probably require some pretty extensive migration of the existing data, so I'll bring this back to the team to see how we'll go about doing this.

**Comment by KartikGolya24** [comment]
Hey @nikolajlauridsen , I have to upgrade my Umbraco project (Sprogklar) from v7 to v10. Firstly, I'm upgrading it to v8 by following this guide https://our.umbraco.com/documentation/Umbraco-Cloud/Upgrades/Migrating-from-7-to-8/ . While doing content migration from v7 to v8, I'm getting the same issue
![image](https://user-images.githubusercontent.com/110231046/217809910-bd7f1968-9837-48f8-a1c5-b459ce8a2d36.png)
Log File : [SprogklarLogFile09-02-2023.txt](https://github.com/umbraco/Umbraco-CMS/files/10696962/SprogklarLogFile09-02-2023.txt)

**Comment by mennomout** [comment]
@nikolajlauridsen This is issue that also persists in 10.5.1 and 11.3.1 and also applies to the `Umbraco.DropDown.Flexible` data type which probably works very similar to the `Umbraco.CheckBoxList`. We recently encountered a similar issue where one of our customers would like to select multiple longer values from a `Umbraco.DropDown.Flexible` but due to the 512 character limit got this same error.

**Comment by craigs100** [comment]
What's the likelihood of a fix appearing in the 12.1.1? Currently impacting a live site. Site's ok, just can't uSync back the checkboxlist as it's content is too large for configured storage. See previous post "uSync Fails to import long umbraco.checkboxlist".

**Comment by nikolajlauridsen** [comment]
Heya, I've marked this with sprint-candidate so that we can look at it in an upcoming sprint. 

Should be a matter of migrating it to use to Ntext/Nvarchar max instead so we don't have a 512 character limit 😄

**Comment by craigs100** [comment]
Any update on this? Have just uSynced a site off a SQLite DB to a SQL Server Express DB and the umbraco.checkboxlist data types are failing again :(  Is there a workaround I can apply to the live DB to accept the longer data type?
uSync error:-
`String or binary data would be truncated in table '6744_Umbraco_SE13.6744_myId.umbracoPropertyData', column 'varcharValue'. Truncated value: '[
  "Bath",
  "BBQ Grill",
  "BBQ Utensils",
  "Bed linen",
  "Carbon monoxide alarm",
  "Cleaning p'.
The statement has been terminated.`

**Comment by craigs100** [comment]
I'd just like to add that this is a huge "gotcha" when you develop against SQLite and deploy to SQL Server. It would be interesting to know how Umbraco Cloud handles this....... or does it? ;)
