### ISSUE TITLE
Smidge doesn't work for 3rd party resources referenced in a package manifest

### ISSUE THREAD

**Issue by jaandrews** [umbraco/Umbraco-CMS#12368]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4.3

### Bug summary

When I add an external resource to a package.manifest, the umbraco backoffice fails to load.

### Specifics

It threw the following error on startup.
```
Smidge.BundleNotFoundException: A bundle with the name:umbraco-backoffice-extensions-js could not be found. 
   at Smidge.SmidgeHelper.GenerateBundleUrlsAsync(String bundleName, String fileExt, Boolean debug)
   at Smidge.SmidgeHelper.GenerateJsUrlsAsync(String bundleName, Boolean debug)
   at Umbraco.Cms.Web.Common.RuntimeMinification.SmidgeRuntimeMinifier.GetJsAssetPathsAsync(String bundleName)
   at Umbraco.Extensions.RuntimeMinifierExtensions.GetScriptForLoadingBackOfficeAsync(IRuntimeMinifier minifier, GlobalSettings globalSettings, IHostingEnvironment hostingEnvironment, IManifestParser manifestParser)
   at Umbraco.Cms.Web.BackOffice.Controllers.BackOfficeController.Application()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Umbraco.Cms.Web.Common.Middleware.BasicAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.BackOffice.Middleware.BackOfficeExternalLoginProviderErrorMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 119
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Steps to reproduce

Create a package manifest that links to an external domain. Something along the lines of the example below.

```
{
    "javascript": [ "~/app_plugins/example/example-script.js", "https://example.com/example-script.js" ]
}
```

### Expected result / actual result

I expected it to inject the script like it does in umbraco 8, but instead it breaks the backoffice. Not sure that this is fixable though, as this may be a feature that's not supported in the Smidge package.

**Comment by KristofferEriksen** [comment]
Same error in Umbraco 10.3.2. Did you solve it?

**Comment by jaandrews** [comment]
I ended up loading the external files with a local script instead of directly putting them in the package manifest.

**Comment by KristofferEriksen** [comment]
Hey Jesse
Ok. I might do that as well, then. Thanks for your reply
/Kristoffer

**Comment by stodolos** [comment]
> I ended up loading the external files with a local script instead of directly putting them in the package manifest.

@jaandrews Which method did you use to reference the external files?

**Comment by jaandrews** [comment]
@stodolos Instead of directly adding the external scripts to the package manifest, I created another script that pulls them in. I then added that script to the package manifest and everything worked for my case.  In my case I just used vanilla javascript, but this can also be done in an angular element with
```javascript
assetsService.loadJs('some-script.js')
```
(see documentation [here](https://our.umbraco.com/apidocs/v8/ui/#/api/umbraco.services.assetsService))

The downside of this approach is that those external scripts won't be included in the bundle generated by umbraco, so they won't load quite as quickly and can lead to scripts loading out of order if that's not accounted for, since the scripts would be loaded aynchronously.

**Comment by Migaroez** [comment]
Hey @jaandrews, This is indeed a limitation of named bundles within Smidge. 

We might be able to pull the external files out of the manifest listings before we turn them into bundles and then add them as is to the output, but this might mess with ordering.

However we handle this, we should probably fail a bit more graceful with a nice log message and updated [docs](https://docs.umbraco.com/umbraco-cms/extending/property-editors/package-manifest)

**Comment by Migaroez** [comment]
Hey @jaandrews 

We have decided to not do any unconventional handling as this will most likely mess up ordering and probably make things worse.

We will be updating the docs to note the limitation.
