### ISSUE TITLE
Problem with the Std login Snippet

### ISSUE THREAD

**Issue by ygrave** [umbraco/Umbraco-CMS#12398]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.5.0

### Bug summary

I implemented the standaard login snipet of Umbraco but when I test this implementation, I received an error.
The error is:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'user')
   at Umbraco.Cms.Core.Security.ContentPermissions.CheckPermissions(Int32 nodeId, IUser user, IContent& contentItem, IReadOnlyList`1 permissionsToCheck)
   at Umbraco.Cms.Web.BackOffice.Authorization.ContentPermissionsQueryStringHandler.IsAuthorized(AuthorizationHandlerContext context, ContentPermissionsQueryStringRequirement requirement)
   at Umbraco.Cms.Web.BackOffice.Authorization.MustSatisfyRequirementAuthorizationHandler`1.HandleRequirementAsync(AuthorizationHandlerContext context, T requirement)
   at Microsoft.AspNetCore.Authorization.AuthorizationHandler`1.HandleAsync(AuthorizationHandlerContext context)
   at Microsoft.AspNetCore.Authorization.DefaultAuthorizationService.AuthorizeAsync(ClaimsPrincipal user, Object resource, IEnumerable`1 requirements)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthorizeAsync(AuthorizationPolicy policy, AuthenticateResult authenticationResult, HttpContext context, Object resource)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 121
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Forms.Web.HttpModules.ProtectFormUploadRequestsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

```
### Specifics

The url to test is: https://dev-kennisportaal.euwest01.umbraco.io/login
I tested with the browser MS Edge , version 101.0.1210.39
Also the support of Umbraco test this and received the same problem.
The error is:

```

<html>
<body>
<!--StartFragment--><div ng-if="log.Exception" class="ng-scope" style="color: rgb(0, 0, 0); font-family: Lato, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; border-left: 4px solid rgb(212, 32, 84);"><pre class="ng-binding" style="display: block; padding: 9.5px; margin: 0px 0px 10px; font-family: Lato, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; color: rgb(48, 48, 51); line-height: 20px; white-space: pre-wrap; overflow-x: auto; background-color: rgb(246, 244, 244); border: 1px solid rgb(216, 215, 217); border-radius: 3px;">System.ArgumentNullException: Value cannot be null. (Parameter 'user')
   at Umbraco.Cms.Core.Security.ContentPermissions.CheckPermissions(Int32 nodeId, IUser user, IContent&amp; contentItem, IReadOnlyList`1 permissionsToCheck)
   at Umbraco.Cms.Web.BackOffice.Authorization.ContentPermissionsQueryStringHandler.IsAuthorized(AuthorizationHandlerContext context, ContentPermissionsQueryStringRequirement requirement)
   at Umbraco.Cms.Web.BackOffice.Authorization.MustSatisfyRequirementAuthorizationHandler`1.HandleRequirementAsync(AuthorizationHandlerContext context, T requirement)
   at Microsoft.AspNetCore.Authorization.AuthorizationHandler`1.HandleAsync(AuthorizationHandlerContext context)
   at Microsoft.AspNetCore.Authorization.DefaultAuthorizationService.AuthorizeAsync(ClaimsPrincipal user, Object resource, IEnumerable`1 requirements)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthorizeAsync(AuthorizationPolicy policy, AuthenticateResult authenticationResult, HttpContext context, Object resource)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 121
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.&lt;&gt;c__DisplayClass6_1.&lt;&lt;UseMiddlewareInterface&gt;b__1&gt;d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.&lt;&gt;c__DisplayClass6_1.&lt;&lt;UseMiddlewareInterface&gt;b__1&gt;d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.&lt;&gt;c__DisplayClass6_1.&lt;&lt;UseMiddlewareInterface&gt;b__1&gt;d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Forms.Web.HttpModules.ProtectFormUploadRequestsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.&lt;&gt;c__DisplayClass6_1.&lt;&lt;UseMiddlewareInterface&gt;b__1&gt;d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)</pre></div>

Timestamp | 2022-05-13T12:55:54.6824668+00:00
-- | --
An unhandled exception has occurred while executing the request.
 
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware
800016b5-0000-b900-b63f-84710c7967bb
/umbraco/backoffice/umbracoapi/publicaccess/GetPublicAccess
4976
w3wp
118
1
ff5ad34531cf8f386fcfc4117c8633c7091508ee
wn1sdwk0000BI
ERROR

<!--EndFragment-->
</body>
</html>

```
### Steps to reproduce

1. go to the url: https://dev-kennisportaal.euwest01.umbraco.io/login
2. To test use the following:
2.1: user: testuser
2.2: ww: ZbvQ7Mvi!!

### Expected result / actual result

We want to be loggedin.

**Comment by nul800sebastiaan** [comment]
Hi there @ygrave - this sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 

Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍

Ps. in order for people to help you, make sure to add more details, like how are you setting up restricted access in the backoffice and did you make changes to the Partial View Snippet, how are you rendering the Login macro, etc.
