### ISSUE TITLE
Unable to add additional TinyMCE plugins

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco-CMS#12436]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.5.0

### Bug summary

When adding plugins within appsettings.json, an exception is thrown when loading the editor.

Example config:
```
        "Plugins": [
          "table"
        ]
```

Exception:
![image](https://user-images.githubusercontent.com/9937803/170352616-612117d5-a41d-41f5-bb3c-bce76c0d5efd.png)

![image](https://user-images.githubusercontent.com/9937803/170354866-46f04ef8-67fe-4fa6-8189-87c28e44f0e9.png)

```
System.InvalidOperationException, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: Cannot create instance of type 'System.String' because it is missing a public parameterless constructor.

at Microsoft.Extensions.Configuration.ConfigurationBinder.CreateInstance(Type type)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindDictionary(Object dictionary, Type dictionaryType, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance, Action`1 configureOptions)
   at Microsoft.Extensions.Options.NamedConfigureFromConfigurationOptions`1.<>c__DisplayClass1_0.<.ctor>b__0(TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Umbraco.Cms.Web.BackOffice.PropertyEditors.RichTextPreValueController.GetConfiguration()
   at lambda_method1020(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

### Steps to reproduce

Add a custom config to the RichTextEditor in appsettings.json

Load the Rich Text Editor Property in the CMS

### Expected result / actual result

The Rich Tect Editor to load with my custom settings

**Comment by jaandrews** [comment]
@AaronSadlerUK You likely need to serialize your "table_default_attributes" to a string. Pretty sure you are running into the same problem mentioned on [this thread](https://our.umbraco.com/forum/umbraco-9/106837-tinymceconfig-where-to-find-it-in-umbraco-9)

**Comment by AaronSadlerUK** [comment]
Same issue.

It feels like the controller is wrong in the core.

![image](https://user-images.githubusercontent.com/9937803/170339327-578c1f96-d2d0-4c90-8197-823e8f72427e.png)

**Comment by jaandrews** [comment]
I suspect the problem is caused by a problem elsewhere then, as I added that setting to a local umbraco installation as a test and it didn't cause any errors. Double checked the model in the umbraco code and it is a dictionary of strings (see [here](https://github.com/umbraco/Umbraco-CMS/blob/v9/9.5/src/Umbraco.Core/Configuration/Models/RichTextEditorSettings.cs#L84). Only other thing I can think of is that the CustomConfig isn't nested properly in appsettings.json. Should be something like
```
{
  "$schema": "./umbraco/config/appsettings-schema.json",
  "Serilog": {
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Warning",
        "Microsoft.Hosting.Lifetime": "Information",
        "System": "Warning"
      }
    }
  },
  "ConnectionStrings": {
    "umbracoDbDSN": ""
  },
  "Umbraco": {
    "CMS": {
      "Hosting": {
        "Debug": false
      },
      "Content": {
        "ContentVersionCleanupPolicy": {
          "EnableCleanup": true
        }
      },
      "Global": {
        "Id": "06d43292-1713-4156-86fd-6b35de98ab5f"
      },
      "RichTextEditor": {
        "CustomConfig": {
          "table_default_attributes": "{\"border\":\"0\",\"class\":\"table table-bordered nobottommargin\"}"
        }
      }
    }
  }
}
```

**Comment by AaronSadlerUK** [comment]
This is the full code.

When I add the "Plugins" piece I get a Json validation error, did you try with the inclusion of the "Plugins" object?

```
      "RichTextEditor": {
        "Plugins": [
          "table"
        ],
        "CustomConfig": {
          "table_default_attributes": "{\"border\":\"0\",\"class\":\"table table-bordered nobottommargin\"}"
        }
      }
```

![image](https://user-images.githubusercontent.com/9937803/170352616-612117d5-a41d-41f5-bb3c-bce76c0d5efd.png)

**Comment by jaandrews** [comment]
I didn't. Try serializing that array to a string like what was done for "table_default_attributes." This is likely a limitation of appsettings.json, as it expects key values to be paired with strings.

**Comment by jaandrews** [comment]
Schema seems to be broken there. Tested on my end and when it's an array it complains that it isn't a string, but when it's a string it complains that it's not an array. Is there a reason you are trying to add tables this way? There is a checkbox in the rich text editor data type that can enable it.
![rte-settings](https://user-images.githubusercontent.com/5932368/170356566-103e765b-9f04-4474-acdd-69640810e358.png)
If that works for your use case, then you can remove the problematic configuration.

**Comment by AaronSadlerUK** [comment]
Oh let me try that.

I didn't realise tables were enabled by default now, I swear in V8 they had to be explicitly enabled

**Comment by AaronSadlerUK** [comment]
I can confirm removing the "Plugins" part fixes my issue.

I will however leave this issue open due to the fact custom plugins cannot be added

**Comment by tormnator** [comment]
> Schema seems to be broken

I'm on V10 rc4, and the appsettings-schema.json seems to be broken for umbracoRichTextEditor/Plugins. 

```
"Plugins": {
  "description": "An array of TinyMCE Plugins to load such as 'paste', 'table'",
  "type": [
    "string"
  ]
},

```

Should maybe be like this:

```
"Plugins": {
  "description": "An array of TinyMCE Plugins to load such as 'paste', 'table'",
  "type": "array",
  "items": {
    "type": "string"
  }
},

```

**Comment by p-m-j** [comment]
As far as I can tell the only issue here is jsonschema being interpretted incorrectly.

Plugins is a string[] on the strongly typed class that this config section is bound to.

```json
{

  "Umbraco": {
    "CMS": {
      "RichTextEditor": {
        "Plugins": [ "foo", "bar", "baz" ]
      }
}
```
With this there are http requests to attempt to load these plugins.

**Comment by iOvergaard** [comment]
I believe this has been fixed for a while and at least works in the latest LTS (V13). We updated the docs to reflect how we expect you to work with built-in plugins as well as your own. [Read more on the Umbraco Docs](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/rte-plugins) and please check if the issue still persists.
