### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS on login admin page

### ISSUE THREAD

**Issue by denhaandrei** [umbraco/Umbraco-CMS#12458]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

Nuget Umbraco.Cms 9.4.3

### Bug summary

Can`t open the admin page https://***/umbraco but can use site content and open another pages configured in admin side

### Specifics

```
<html>
<body>
<!--StartFragment-->
**System.FormatException: Input string was not in a correct format.**
at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)   
at System.Convert.ToDecimal(String value, IFormatProvider provider)   
at System.String.System.IConvertible.ToDecimal(IFormatProvider provider)   
at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)   
at SixLabors.ImageSharp.Web.Commands.Converters.IntegralNumberConverter`1.ConvertFrom(CommandParser parser, CultureInfo culture, String value, Type propertyType)   
at Umbraco.Extensions.UmbracoBuilderExtensions.<>c__DisplayClass0_0.<AddUmbracoImageSharp>b__2(ImageCommandContext context)   
at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)   
at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)   
at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in **C:\\projects\\dotnet\\src\\MiniProfiler.AspNetCore\\MiniProfilerMiddleware.cs:line 119**   
at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)   
at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()

--- End of stack trace from previous location ---   
at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)   
at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()

--- End of stack trace from previous location ---   
at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)   
at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()

--- End of stack trace from previous location ---   
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
<!--EndFragment-->
</body>
</html>

```
### Steps to reproduce

build and publish on AWS docker
allow access to the wwwroot and Umbraco folders
open https://***/umbraco

**Comment by denhaandrei** [comment]
don`t want fix
