### ISSUE TITLE
Umbraco.Cms.Staticassets nuget missing target to copy backoffice static files to wwwroot

### ISSUE THREAD

**Issue by rogalmic** [umbraco/Umbraco-CMS#12531]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.0-rc4 (other rcs as well)

### Bug summary

Seems that the build target for static files copying is missing, it was there in versions 9 and 8.

### Specifics

In nuget cache, ".nuget\packages\umbraco.cms.staticassets\10.0.0-rc4\buildTransitive" folder does not seem to have the *.targets file, only props.

For reference see:
".nuget\packages\umbraco.cms.staticassets\9.3.1\buildTransitive"

### Steps to reproduce

In generic Umbraco 10, delete wwwroot/umbraco folder, clean Smidge cache and hard refresh backooffice site.

### Expected result / actual result

Hard refresh of backoffice without any cache works.

**Comment by p-m-j** [comment]
I may be misunderstanding the issue, but cms.staticassets is now a razor class library and so the JavaScript and css etc would only be output to wwwroot on publish.

Are these the files you meant or is this relating to something else?

**Comment by rogalmic** [comment]
If so, what is the preferred way of debugging locally?

**Comment by p-m-j** [comment]
I’d hope we provide source maps so debugging should be as easy as opening the development tools in a browser.

if you’re looking to hack on the cms project itself It might make more sense to clone the repo and run the web.ui project.

**Comment by rogalmic** [comment]
I mean following helloworld scenario:
- installing umbraco from scratch based on guide
- starting it from Visual Studio after rebuild (F5)

I assume the umbraco folder (static content) will not be in wwwroot and backoffice page will not show up properly, since it is copied only for publish(?).

**Comment by p-m-j** [comment]
Why do you need it to show up on the filesystem? What are you trying to acheive that isn't working?

**Comment by p-m-j** [comment]
In v10 those static assets are still served by the application just not from the projects wwwroot folder.

how did you setup your project is it from new using the rc dotnet new templates or have you upgraded a v9 project.

does a dotnet clean followed by a dotnet run fix it?

**Comment by rogalmic** [comment]
It started for me with this exception when opening backoffice:
```
System.IO.FileNotFoundException: No such file exists /umbraco/assets/css/umbraco.min.css (mapped from /umbraco/assets/css/umbraco.min.css)
File name: '/umbraco/assets/css/umbraco.min.css'
   at Smidge.SmidgeFileSystem.GetRequiredFileInfo(IWebFile webfile)
   at Smidge.FileProcessors.PreProcessManager.<>c__DisplayClass7_0.<ProcessFileImpl>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.CreateValue()
   at Smidge.FileProcessors.PreProcessManager.ProcessFileImpl(IWebFile file, BundleOptions bundleOptions, BundleContext bundleContext)
   at Smidge.FileProcessors.PreProcessManager.ProcessFile(IWebFile file, BundleOptions bundleOptions, BundleContext bundleContext)
   at Smidge.FileProcessors.PreProcessManager.ProcessAndCacheFileAsync(IWebFile file, BundleOptions bundleOptions, BundleContext bundleContext)
   at Smidge.Controllers.SmidgeController.Bundle(BundleRequestModel bundleModel)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Umbraco.Cms.Web.Common.Middleware.BasicAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.BackOffice.Middleware.BackOfficeExternalLoginProviderErrorMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, Boolean retry)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 119
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

I did all the usual cleaning, including nuget local cache. Then i noticed that this copy target was removed from v9 to v10.

I guess what I am aiming for is nice developer experience for first time debugging, since i can copy the files manually to wwwroot next to csproj.

**Comment by p-m-j** [comment]
Ahh good stuff, glad you sorted it.

For future ref this sort of stuff should be covered in the version specific upgrade steps for major versions. 

https://our.umbraco.com/documentation/Fundamentals/Setup/Upgrading/version-specific#steps-on-how-to-upgrade-using-visual-studio
