### ISSUE TITLE
Exception thrown when saving root content

### ISSUE THREAD

**Issue by vmachacek** [umbraco/Umbraco-CMS#12568]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.5.0

### Bug summary

After couple of round of abusing umbraco trying to write one the fly sitemap generator with trial and error I encountered unrecoverable issue - when I run `umbContext.UmbracoContext.Content.GetByRoute("/")` it returns null. 

The site on the `/` url works fine. 

And I get this exception when trying to save this content via backoffice 

```
at Umbraco.Cms.Infrastructure.PublishedCache.ContentCache.ApplyHideTopLevelNodeFromPath(IPublishedContent content, IList`1 segments, Boolean preview)
   at Umbraco.Cms.Infrastructure.PublishedCache.ContentCache.GetRouteByIdInternal(Boolean preview, Int32 contentId, Nullable`1 hideTopLevelNode, String culture)
   at Umbraco.Cms.Infrastructure.PublishedCache.ContentCache.<>c__DisplayClass14_0.<GetRouteById>b__0()
   at Umbraco.Extensions.AppCacheExtensions.<>c__DisplayClass5_0`1.<GetCacheItem>b__0()
   at Umbraco.Cms.Core.Cache.SafeLazy.<>c__DisplayClass1_0.<GetSafeLazy>b__0()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Core.Cache.FastDictionaryAppCache.Get(String cacheKey, Func`1 getCacheItem)
   at Umbraco.Extensions.AppCacheExtensions.GetCacheItem[T](IAppCache provider, String cacheKey, Func`1 getCacheItem)
   at Umbraco.Cms.Infrastructure.PublishedCache.ContentCache.GetRouteById(Boolean preview, Int32 contentId, String culture)
   at Umbraco.Cms.Infrastructure.PublishedCache.ContentCache.GetRouteById(Int32 contentId, String culture)
   at Umbraco.Cms.Core.Routing.RedirectTrackingHandler.StoreOldRoute(IContent entity, OldRoutesDictionary oldRoutes)
   at Umbraco.Cms.Core.Routing.RedirectTrackingHandler.StoreOldRoutes(IEnumerable`1 entities, IStatefulNotification notification)
   at Umbraco.Cms.Core.Routing.RedirectTrackingHandler.Handle(ContentPublishingNotification notification)
   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.<>c__DisplayClass0_0.<Handle>b__1(INotification theNotification)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishCore(IEnumerable`1 allHandlers, INotification notification)
   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.Handle(INotification notification, ServiceFactory serviceFactory, Action`2 publish)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishNotification(INotification notification)
   at Umbraco.Cms.Core.Events.EventAggregator.Publish[TNotification](TNotification notification)
   at Umbraco.Cms.Core.Events.ScopedNotificationPublisher.PublishCancelable(ICancelableNotification notification)
   at Umbraco.Cms.Core.Services.Implement.ContentService.StrategyCanPublish(IScope scope, IContent content, Boolean checkPath, IReadOnlyList`1 culturesPublishing, IReadOnlyCollection`1 culturesUnpublishing, EventMessages evtMsgs, IReadOnlyCollection`1 allLangs, IDictionary`2 notificationState)
   at Umbraco.Cms.Core.Services.Implement.ContentService.CommitDocumentChangesInternal(IScope scope, IContent content, EventMessages eventMessages, IReadOnlyCollection`1 allLangs, IDictionary`2 notificationState, Int32 userId, Boolean branchOne, Boolean branchRoot)
   at Umbraco.Cms.Core.Services.Implement.ContentService.SaveAndPublish(IContent content, String[] cultures, Int32 userId)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PublishInternal(ContentItemSave contentItem, String defaultCulture, String cultureForInvariantErrors, Boolean& wasCancelled, String[]& successfulCultures)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PostSaveInternal(ContentItemSave contentItem, Func`2 saveMethod, Func`2 mapToDisplay)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PostSave(ContentItemSave contentItem)
   at lambda_method979(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   ```
When I try to save any other page it works fine.. 

### Steps to reproduce

I guess this is specific to my setup, I don't know how I got into this state

### Expected result / actual result

I expect umbraco to save content normally and not to throw exception

**Comment by vmachacek** [comment]
More context: there was 2nd root content which was not published but its url was colliding with "main root content". The issue start happening when I deleted this 2nd content. When I removed it from recycle bin it started to work again

**Comment by vmachacek** [comment]
I was able to narrow it down to 2 lines of code which causing this issue and that is here 

```
using Microsoft.AspNetCore.Http;
using Umbraco.Cms.Core.Web;

namespace Websites.Shared;

public class SitemapMiddleware
{
    public SitemapMiddleware(RequestDelegate _)
    {
    }

    public async Task InvokeAsync(HttpContext context, IUmbracoContextFactory _umbracoContextFactory, IServiceProvider serviceProvider)
    {
        var umbContext = _umbracoContextFactory.EnsureUmbracoContext();
        var home = umbContext.UmbracoContext.Content.GetByRoute("/");
    }
}
```

Calling `umbContext.UmbracoContext.Content.GetByRoute("/");` will put umbraco into error state which i can only mitigate by restoring the database..

**Comment by vmachacek** [comment]
My question is how to best fetch all content and construct sitemap.xml on the fly without any content model or template or anything like that.. I tried `IPublishedContentQuery` but that would not return content which is multi-language.. I was using `publishedContentQuery.ContentAtRoot()`
