### ISSUE TITLE
CompleteInstallStep can block the installer UI uneccesarily for up to 100 seconds

### ISSUE THREAD

**Issue by p-m-j** [umbraco/Umbraco-CMS#12583]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.0 also v9

### Bug summary

On completing an install via the UI a http request is made from Umbraco.Cms.Core.Persistence.Repositories.InstallationRepository.SaveInstallLogAsync which is awaited all the way up the stack potentially resulting in a lengthy wait whilst having network issues (e.g. I spotted this on the DSB wifi).

There is no need for this to be blocking, it can be run in the background (or skipped entirely?)

### Specifics

```
[19:01:22 INF] Executing installation step: 'UmbracoVersion'. [Timing b597824]
[19:03:02 ERR] An error occurred in InstallStatus trying to check upgrades
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Umbraco.Cms.Core.Persistence.Repositories.InstallationRepository.SaveInstallLogAsync(InstallLog installLog)
   at Umbraco.Cms.Core.Services.InstallationService.LogInstall(InstallLog installLog)
   at Umbraco.Cms.Infrastructure.Install.InstallHelper.SetInstallStatusAsync(Boolean isCompleted, String errorMsg)
[19:03:02 INF] Step completed (100056ms) [Timing b597824]
```

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/12658
