### ISSUE TITLE
umbracoPropertyData - Arithmetic overflow error converting IDENTITY to data type int

### ISSUE THREAD

**Issue by DrKirk84** [umbraco/Umbraco-CMS#12661]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.6.1

### Bug summary

Hello

Yesterday one of our customer couldn't save or publish a node in Umbraco.
The id of the new record for the table dbo.umbracoPropertyData was bigger than the max int value.
We have reseeded the id of the table, but in my opinion it is just a (long) temporary solution.

Does anybody experienced this issue as well? What was your solution?

### Specifics

`System.Data.SqlClient.SqlException (0x80131904): Arithmetic overflow error converting IDENTITY to data type int.
Arithmetic overflow occurred.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172
   at NPoco.Database.ExecuteScalarHelper(DbCommand cmd)
   at NPoco.Database.InsertImp[T](PocoData pocoData, String tableName, String primaryKeyName, Boolean autoIncrement, T poco)
   at NPoco.Database.Insert[T](String tableName, String primaryKeyName, Boolean autoIncrement, T poco)
   at NPoco.Database.Insert[T](T poco)
   at Umbraco.Core.Persistence.Repositories.Implement.DocumentRepository.PersistUpdatedItem(IContent entity) in D:\a\1\s\src\Umbraco.Core\Persistence\Repositories\Implement\DocumentRepository.cs:line 609
   at Umbraco.Core.Cache.DefaultRepositoryCachePolicy`2.Update(TEntity entity, Action`1 persistUpdated) in D:\a\1\s\src\Umbraco.Core\Cache\DefaultRepositoryCachePolicy.cs:line 128
   at Umbraco.Core.Services.Implement.ContentService.CommitDocumentChangesInternal(IScope scope, IContent content, ContentSavingEventArgs saveEventArgs, IReadOnlyCollection`1 allLangs, Int32 userId, Boolean raiseEvents, Boolean branchOne, Boolean branchRoot) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 1230
   at Umbraco.Core.Services.Implement.ContentService.<PerformScheduledPublishInternal>d__59.MoveNext() in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 1421
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Umbraco.Core.Services.Implement.ContentService.PerformScheduledPublish(DateTime date) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 1363
   at Umbraco.Web.Scheduling.ScheduledPublishing.PerformRun() in D:\a\1\s\src\Umbraco.Web\Scheduling\ScheduledPublishing.cs:line 72
ClientConnectionId:7aa5af95-b92b-4b5f-8754-d5840839cccb
Error Number:8115,State:1,Class:16`

### Steps to reproduce

Fill the umbracoPropertyData with data, to reach max int value for id.

**Comment by nul800sebastiaan** [comment]
@DrKirk84 Hmm, that would indicate you have more than 2 billion rows (int.Max is 2147483647) in your `umbracoPropertyData` table? Seems like a lot! One recommendation I would have for v8 is to use Nexu - https://our.umbraco.com/packages/backoffice-extensions/nexu/ (version 2.3.x is meant for Umbraco 8).

This will delete old versions of property data from the database as configured. In v9 we have adopted this package code and built it into the CMS by default.

You will note that this doesn't help immediately since you're still at a very high identifier for the newest rows. I guess another reseed will work for that as well. However, the id row is used in other tables as a reference so you might actually have problems when reseeding, not sure how you did this in the first place.

A quick calculation, let's say your site has nodes with a total of 10000 properties on all nodes together, that would mean you would have to save ALL nodes 588 times (twice an hour) each day of the year to get up to int.Max.
Am I right in suspecting that you do a lot of automated updating of nodes? Each time you auto-save a node all of it's properties will be copied to a new version in this table, which then could lead to this problem. 

I don't know what the impact of changing the id column to bigint would be but my guess is that our code won't like it, we're not expecting a long in the code.

**Comment by DrKirk84** [comment]
@nul800sebastiaan thanks for your response. I did not know the backoffice extension. We are currently upgrading the site from umbraco 8 to 10. Hope we can migrate after reseeding. 

You are right, we have multiple jobs running every day or every 4 hours and the datatypes have a lot of properties. We could not really explain the huge amount.

**Comment by nul800sebastiaan** [comment]
FYI: I linked to Nexu but meant to link to UnVersion: https://our.umbraco.com/packages/website-utilities/unversion/

**Comment by nul800sebastiaan** [comment]
For the case of running multiple jobs: please consider if any of this data MUST be content editable. Maybe it needs to be but if nobody is ever going to edit the data in the backoffice then consider keep it as a seperate data store and query that instead. 

Even if it requires occasional edits, maybe you can use something like Konstrukt https://our.umbraco.com/packages/backoffice-extensions/konstrukt/ to edit the data in the custom data source.

**Comment by nul800sebastiaan** [comment]
Thanks again for the report @DrKirk84 - hope that my tips will help you out. I will be closing this issue now in the hopes that you're the only one (for now) who ran into it. I know we want to change our datalayer in the next few years and I've let the team know that people might run into integer limitations. I suspect we'll move away from integers completely anyway. Thanks again and good luck!
