### ISSUE TITLE
Packages > Create Package - "Failed to create package" when including media

### ISSUE THREAD

**Issue by AndyBoot** [umbraco/Umbraco-CMS#12728]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.1

### Bug summary

When creating a package bundle within the backoffice via Packages > Create Package I am given an error stating "Failed to create package" upon saving the configuration. It appears to work if I **do not** include media folders with the "include all child nodes" checkbox. 

### Specifics

This has previous been reported on the forum: https://our.umbraco.com/forum/using-umbraco-and-getting-started/109354-cant-create-a-package-in-umbraco-due-to-media-folder

**Exception Details**
`System.ArgumentNullException, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: Value cannot be null. (Parameter 'value')`

**Stacktrace**
```
at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.CreatedPackageSchemaRepository.<>c__DisplayClass34_0.<PackageMedia>g__OnSerializedMedia|0(IMedia media, XElement xmlMedia)
   at Umbraco.Cms.Core.Services.EntityXmlSerializer.Serialize(IMedia media, Boolean withDescendants, Action`2 onMediaItemSerialized)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.CreatedPackageSchemaRepository.<>c__DisplayClass34_0.<PackageMedia>b__1(IMedia media)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.CreatedPackageSchemaRepository.PackageMedia(PackageDefinition definition, XElement root)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.CreatedPackageSchemaRepository.ExportPackage(PackageDefinition definition)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.CreatedPackageSchemaRepository.SavePackage(PackageDefinition definition)
   at Umbraco.Cms.Core.Services.Implement.PackagingService.SaveCreatedPackage(PackageDefinition definition)
   at Umbraco.Cms.Web.BackOffice.Controllers.PackageController.PostSavePackage(PackageDefinition model)
   at lambda_method1010(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

### Steps to reproduce

Packages > Create Package

Select a media library folder

Save

### Expected result / actual result

No errors and a download option.

**Comment by nul800sebastiaan** [comment]
Thanks, this is fixed for 10.1.0 - https://github.com/umbraco/Umbraco-CMS/issues/12672
