### ISSUE TITLE
Get error on cancel saving document type

### ISSUE THREAD

**Issue by laputaworkuk** [umbraco/Umbraco-CMS#12732]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.1

### Bug summary

I create the document type which alias name as simplehomePage ,set as child of document type  and set this document type Allow vary by culture is true.
and then I create PageValidationNotificationHandler

Under Handler Method just make this code:
```
if (content.ContentType.Alias == "simplehomePage") {
			notification.CancelOperation(
				new EventMessage(
					"Publishing error",
					"You cannot save and publish this Home page",
					EventMessageType.Error));
		}
```
When I press save and publish , I've the error as below :
An error occurred
Input string was not in a correct format.

Stacktrace
```
at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int32.Parse(String s, IFormatProvider provider)
   at Umbraco.Extensions.ContentExtensions.<>c.<GetAncestorIds>b__8_1(String s)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.GetPublishedCulturesFromAncestors(IContent content)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.AddDomainWarnings(IContent persistedContent, String[] culturesPublished, SimpleNotificationModel globalNotifications)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PostSaveInternal[TVariant](ContentItemSave contentItem, Func`3 saveMethod, Func`2 mapToDisplay)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PostSave(ContentItemSave contentItem)
   at lambda_method1429(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

But if I turn "Allow vary by culture" to false, it's work

### Steps to reproduce

In settings,
Create the document type in this setting
Step 1:
![image](https://user-images.githubusercontent.com/109957839/180761023-a5e8cba3-cb1c-441c-b7f7-1ca1dee6378b.png)

step 2:
![image](https://user-images.githubusercontent.com/109957839/180760842-8d3d4a11-ad5f-469a-b3d3-bd14f8bdbb3b.png)

Step 3:
Create ContentSavingNotification as below code 

```
using Umbraco.Cms.Core.Events;
using Umbraco.Cms.Core.Notifications;
namespace UmbracoLite.web.Infrastructure.Handler;
public class PageValidationNotificationHandler : INotificationHandler<ContentSavingNotification> {
	public void Handle(ContentSavingNotification notification) {
		var content = notification.SavedEntities.FirstOrDefault();
		if (content.ContentType.Alias == "simpleHomePage") {
			notification.CancelOperation(
				new EventMessage(
					"Publishing error",
					"You cannot save and publish this Home page",
					EventMessageType.Error));
		}
	}
}
```
and then add code at startup configureservices
```
services.AddUmbraco(_env, _config)
			.AddBackOffice()
			.AddWebsite()
			.AddComposers()
			.AddNotificationHandler<ContentSavingNotification, PageValidationNotificationHandler>()
			.Build();

```

Step 4:
![image](https://user-images.githubusercontent.com/109957839/180761755-4197ef5f-af18-406e-bb9a-712c878c164a.png)
create the parent document type , and under parent create the child document type 
and then click save and publish
![image](https://user-images.githubusercontent.com/109957839/180762131-7ab43212-4847-4091-ad3d-23647fa943d6.png)

### Expected result / actual result

We expected user will show this error as below
![image](https://user-images.githubusercontent.com/109957839/180762403-39d2ba7d-549e-483b-b21a-af7b7722459e.png)

but it throw ThrowOverflowOrFormatException

**Comment by laputaworkuk** [comment]
Hi ,
It fix , thanks for your help 
but can I know how to upgrade to my umbraco 

Thank you

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/12733

**Comment by mayhammf** [comment]
HI @Zeegaan, 
This still seems to be an issue. 
Attempting to cancel a content saving operation throws this exception: 
```
at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Umbraco.Extensions.ContentExtensions.<>c.<GetAncestorIds>b__19_1(String s)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.AddDomainWarnings(IContent persistedContent, String[] culturesPublished, SimpleNotificationModel globalNotifications)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PostSaveInternal[TVariant](ContentItemSave contentItem, Func`3 saveMethod, Func`2 mapToDisplay)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PostSave(ContentItemSave contentItem)
   at lambda_method1623(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

Looking at the [implementation ](https://github.com/umbraco/Umbraco-CMS/blob/b69afe81f3f6fcd37480b3b0295a62af44ede245/src/Umbraco.Core/Extensions/ContentExtensions.cs#L272)of the extension method `GetAncestorIds`, it seems like the `null` check is not enough as the `Path` property on the `IContent` item in `ContentSavingNotification.SavedEntities` is set to an empty string and not a `null`. 

We ended up setting the `Path` to `null` before calling `CancelOperation` on the `ContentSavingNotification`  as a workaround. 

I'm not 100% certain what the implications are, but would it be an option to check if `Path` IsNullOrWhiteSpace`  before calling split instead of just doing a null check?

**Comment by Zeegaan** [comment]
Hey @mayhammf That seems like an error yes!
I was trying to replicate this by following the above steps, but i cannot reproduce your issue 🤔 
Could you tell me your setup & steps so i can reproduce? 🙏

**Comment by mayhammf** [comment]
Hi @Zeegaan 
Please find attached sample project. 
[TestUmbraco.zip](https://github.com/umbraco/Umbraco-CMS/files/9908211/TestUmbraco.zip)

To make things easy, i included the db (admin credentials can be found in the readme.txt file in the root)

To reproduce the issue, create a new node of type Page under the existing Home node and call the new node "test" 
The `CustomContentSavingNotification` under `StrictNodeNameComposer` (can be found in Startup.cs) will cancel the operation due to the node called "test". 
<img width="516" alt="image" src="https://user-images.githubusercontent.com/5937658/199192211-accf7647-39d1-4bdd-a009-e15a9b98fd3f.png">

You will get the error: 
<img width="466" alt="image" src="https://user-images.githubusercontent.com/5937658/199192287-46e50616-18fb-4d10-8ade-d526ace7d30d.png">

To test the workaround i mentioned in my previous comment, enable line 33 under Startup.cs. You will notice that you are able to cancel the saving operation without issues.
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/5937658/199192507-f2bff001-a6e7-4321-92bd-74014b9f1c38.png">

I hope this helps reproducing the issue.

**Comment by Zeegaan** [comment]
@mayhammf Big help thanks! Managed to finally reproduce taking a look at your setup, and it seems to matter to have the root node published in both languages 🤔

**Comment by mayhammf** [comment]
@Zeegaan You are right, the issue occurs only when the root is published in 2 or more languages and only when _creating_ a new node when clicking "_Save and Publish_" and not just save. 

Looking at the stacktrace, i can see that the method in question `GetAncestorIds` is called by `AddDomainWarnings` which exits in case there are less than 2 published culture both on the node level or higher in the tree which explains why the issue is visible only when there more than one published cultures. (see [here] (https://github.com/umbraco/Umbraco-CMS/blob/release-10.3.2/src/Umbraco.Web.BackOffice/Controllers/ContentController.cs#L1711))


I would say that the issue is in two places: 
1. `GetAncestorIds`: This should not fail (or at least not like this) in case the Path prop is an empty string, it should either check for both null and empty string before attempting to split or it should throw a better exception in case the Path prop is never expected to be an empty string. 
2. It seems like the Path prop gets assigned at a later step in the saving and publishing new nodes "pipeline", a stage which gets skipped in case the saving operation is cancelled. However, the `PublishInternal` in `ContentController` is not considering the cancelation before invoking `AddDomainWarnings` (see the [exact line](https://github.com/umbraco/Umbraco-CMS/blob/release-10.3.2/src/Umbraco.Web.BackOffice/Controllers/ContentController.cs#L1057) here where this happens)

**Comment by nikolajlauridsen** [comment]
Fixed in #13340 👍
