### ISSUE TITLE
Unit test failure in Umbraco10  but work in Umbraco9

### ISSUE THREAD

**Issue by laputaworkuk** [umbraco/Umbraco-CMS#12755]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v10.01

### Bug summary

Hi All,

I write a simple function of unit test as below, it work on Umbraco v8 without error
```
[Fact]
		public void MyCodeTest() {
			var parentAlias = "parentAlias";
			var testParentCode = new Mock<IPublishedContent>();
			var testParentCodeProperty = new Mock<IPublishedProperty>();
			var cultureCodeElement = new List<IPublishedElement>();
			testParentCodeProperty.Setup(s => s.Alias).Returns(parentAlias);
			testParentCodeProperty.Setup(s => s.GetValue(null, null)).Returns(cultureCodeElement);
			testParentCodeProperty.Setup(s => s.HasValue(null, null)).Returns(true);
			testParentCode.Setup(s => s.GetProperty(parentAlias)).Returns(testParentCodeProperty.Object);

			var testSiteNode = new Mock<IWebNode>();
			testSiteNode.Setup(x => x.FromNodePath(It.IsAny<string>())).Returns(testParentCode.Object);

			var resultNode = testSiteNode.Object.FromNodePath(parentAlias);
			var result = resultNode?.Value(parentAlias) as IEnumerable<IPublishedElement>;
			result.Should().NotBeNull();
		}
```
when I copy this code into Umbraco 10, when go to` var result = resultNode?.Value(parentAlias) as IEnumerable<IPublishedElement>;`, it throw exception :
```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Umbraco.Extensions.FriendlyPublishedContentExtensions' threw an exception.
  Source=Umbraco.Web.Common
  StackTrace:
   at Umbraco.Extensions.FriendlyPublishedContentExtensions.get_PublishedValueFallback()
   at Umbraco.Extensions.FriendlyPublishedContentExtensions.Value(IPublishedContent content, String alias, String culture, String segment, Fallback fallback, Object defaultValue)


  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ArgumentNullException: Value cannot be null. (Parameter 'provider')
```
Can anyone tell me the different between two version

### Steps to reproduce

The main code 
```
[Fact]
		public void MyCodeTest() {
			var parentAlias = "parentAlias";
			var testParentCode = new Mock<IPublishedContent>();
			var testParentCodeProperty = new Mock<IPublishedProperty>();
			var cultureCodeElement = new List<IPublishedElement>();
			testParentCodeProperty.Setup(s => s.Alias).Returns(parentAlias);
			testParentCodeProperty.Setup(s => s.GetValue(null, null)).Returns(cultureCodeElement);
			testParentCodeProperty.Setup(s => s.HasValue(null, null)).Returns(true);
			testParentCode.Setup(s => s.GetProperty(parentAlias)).Returns(testParentCodeProperty.Object);

			var testSiteNode = new Mock<IWebNode>();
			testSiteNode.Setup(x => x.FromNodePath(It.IsAny<string>())).Returns(testParentCode.Object);

			var resultNode = testSiteNode.Object.FromNodePath(parentAlias);
			var result = resultNode?.Value(parentAlias) as IEnumerable<IPublishedElement>;
			result.Should().NotBeNull();
		}
```
Just assume it have no error to return value

### Expected result / actual result

Just assume it have no error to return value

**Comment by kjac** [comment]
Hi @laputaworkuk,

Thank you for reaching out - and sorry it took us so long to respond 🙈 

These kinds of questions really do belong at the forum: https://our.umbraco.com/forum

You may also find some useful info at the docs site: https://docs.umbraco.com/umbraco-cms/implementation/unit-testing

And finally Dennis Adolfi has a lot of good stuff to get you started as well - for example: https://adolfi.dev/blog/unit-testing-in-umbraco-9-10-x/

**Comment by sekmenhuseyin** [comment]
Hi there,
I need to write some unit tests but we still got this error. I use these packages and this code. nothing else
. umbraco v12.2.0
. xunit v2.5.3
. NSubstitute v5.1.0

```
var content = Substitute.For<IPublishedContent>();
content.Value<string>("title").Returns("Title");
```

![image](https://github.com/umbraco/Umbraco-CMS/assets/1363876/85257fb3-d3d2-4837-9d52-e18c9ee29015)
