### ISSUE TITLE
Cannot delete a member if they have rows in umbracoExternalLoginToken

### ISSUE THREAD

**Issue by jbreuer** [umbraco/Umbraco-CMS#12864]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.1.0

### Bug summary

If you login with an external member their tokens are stored in the umbracoExternalLoginToken table. If you want to delete a member which has rows in this table you'll get an error.

### Specifics

This is the error in the logs:

```
Microsoft.Data.SqlClient.SqlException (0x80131904): The DELETE statement conflicted with the REFERENCE constraint "FK_umbracoExternalLoginToken_umbracoExternalLogin_id". The conflict occurred in database "Umbraco-OpenIdConnect-Example-source", table "dbo.umbracoExternalLoginToken", column 'externalLoginId'.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 281
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<ExecuteNonQuery>b__32_0() in C:\data\inetpub\umbraco-cms\src\Umbraco.Infrastructure\Persistence\FaultHandling\RetryDbConnection.cs:line 167
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass38_0`1.<Execute>b__0() in C:\data\inetpub\umbraco-cms\src\Umbraco.Infrastructure\Persistence\FaultHandling\RetryDbConnection.cs:line 193
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in C:\data\inetpub\umbraco-cms\src\Umbraco.Infrastructure\Persistence\FaultHandling\RetryPolicy.cs:line 179
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f) in C:\data\inetpub\umbraco-cms\src\Umbraco.Infrastructure\Persistence\FaultHandling\RetryDbConnection.cs:line 190
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteNonQuery() in C:\data\inetpub\umbraco-cms\src\Umbraco.Infrastructure\Persistence\FaultHandling\RetryDbConnection.cs:line 167
   at NPoco.Database.<>c__DisplayClass296_0.<ExecuteNonQueryHelper>b__0()
   at NPoco.Database.ExecutionHook[T](Func`1 action)
   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)
ClientConnectionId:8446086e-2d69-481c-a67d-e380d9673a40
Error Number:547,State:0,Class:16
```

### Steps to reproduce

Login with a member from an external provider with auto link enabled. Then try to delete that member in the backoffice.

### Expected result / actual result

They member should be delete including the rows in the umbracoExternalLoginToken.

**Comment by nikolajlauridsen** [comment]
Fixed #12872, thanks for the awesome work with all the reports 💪
