### ISSUE TITLE
PublishedContentQuery "can't convert search results to member instances" on using the MemberIndex

### ISSUE THREAD

**Issue by deekoulos** [umbraco/Umbraco-CMS#13001]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.0

### Bug summary

Hi there,

i am migrating from umbraco 8 to 10 and now i am facing this error:

```
System.NotSupportedException: 'Cannot convert search results to member instances'

   at Umbraco.Extensions.ExamineExtensions.ToPublishedSearchResults(IEnumerable`1 results, IPublishedSnapshot snapshot)
   at Feedbax.Core.Helpers.MemberHelper.GetMemberByReviewKey(String key, String[] fields) in C:\Users\armin\source\repos\Feedbax-Core\Feedbax.Core\Helpers\MemberHelper.cs:line 143
   at Feedbax.Core.Controllers.Render.SubmitReviewController.Index() in C:\Users\armin\source\repos\Feedbax-Core\Feedbax.Core\Controllers\Render\SubmitReviewController.cs:line 72
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
```

This exception is triggered by this peace of code which worked in u8:

```
var index = _indexHelper.GetMemberIndex();

        var booleanOperation = index.Searcher
            .CreateQuery("member")
            .ManagedQuery(key, fields);

var member = _publishedContentQuery.Search(booleanOperation, 0, int.MaxValue, out _)
            .Select(x => x.Content as Member)
            .Single();
```

key is a guid
fields is ["reviewItems"]

when i test the search query in umbraco backoffice > settings > examine management > member index:

`reviewItems:0122c909-34ea-4410-8523-e2f5688f7778
`
i get the correct result, but this is not working in code for some reasons and seems to be a bug?

I also tried to make the search call even simpler as followed:

`var member2 = _publishedContentQuery.Search(booleanOperation, 0, int.MaxValue, out _);
`
same exception.

using Umbraco 10.2.0

### Steps to reproduce

<img width="842" alt="image" src="https://user-images.githubusercontent.com/55948134/190237993-0780e77a-cb96-46db-9981-3e8e72d59c9f.png">

**Comment by deekoulos** [comment]
I tried very simple queries like

```
var query = index.Searcher
            .CreateQuery ("member")
            .Field("nodeName", "asd");
```

none worked. It seems like the injected publishedContentQuery can't return results from the member index. 

Without this working the whole member index is useless which is highly used in our v8 Solution. Migrating to v10 is blocked by this issue.

Any idea, anyone?

**Comment by nul800sebastiaan** [comment]
This duplicates: #12891
