### ISSUE TITLE
Publish content return error  Umbraco.Cms.Infrastructure.HostedServices.ServerRegistration.InstructionProcessTask

### ISSUE THREAD

**Issue by laputaworkuk** [umbraco/Umbraco-CMS#13352]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v10.2

### Bug summary

When I publish content
it show 
Server error: Contact administrator, see log for full details.
`One or more errors occurred. (Exceptions were thrown by listed actions. (Specified argument was out of the range of valid values. (Parameter 'length')))
`
can I know how to fix it

### Steps to reproduce

Click any document and click and save publish
and then in logviewer it show

```
System.AggregateException: One or more errors occurred. (Exceptions were thrown by listed actions. (Specified argument was out of the range of valid values. (Parameter 'length')))
 ---> System.AggregateException: Exceptions were thrown by listed actions. (Specified argument was out of the range of valid values. (Parameter 'length'))
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at CSharpTest.Net.IO.TransactedCompoundFile.Write(UInt32 handle, Byte[] bytes, Int32 offset, Int32 length)
   at CSharpTest.Net.Storage.BTreeFileStoreV2.Update[T](IStorageHandle handleIn, ISerializer`1 serializer, T node)
   at CSharpTest.Net.Collections.BPlusTree`2.NodeCacheBase.SaveChanges(NodePin pin)
   at CSharpTest.Net.Collections.BPlusTree`2.NodeTransaction.PerformCommit()
   at CSharpTest.Net.Collections.BPlusTree`2.Insert[T](NodePin thisLock, TKey key, T& value, NodePin parent, Int32 parentIx)
   at CSharpTest.Net.Collections.BPlusTree`2.Insert[T](NodePin thisLock, TKey key, T& value, NodePin parent, Int32 parentIx)
   at CSharpTest.Net.Collections.BPlusTree`2.Insert[T](NodePin thisLock, TKey key, T& value, NodePin parent, Int32 parentIx)
   at CSharpTest.Net.Collections.BPlusTree`2.Insert[T](NodePin thisLock, TKey key, T& value, NodePin parent, Int32 parentIx)
   at CSharpTest.Net.Collections.BPlusTree`2.AddEntry[T](TKey key, T& info)
   at Umbraco.Cms.Infrastructure.PublishedCache.ContentStore.Release(WriteLockInfo lockInfo, Boolean commit)
   at Umbraco.Cms.Core.Scoping.ScopeContext.ScopeExit(Boolean completed)
   --- End of inner exception stack trace ---
   at Umbraco.Cms.Core.Scoping.ScopeContext.ScopeExit(Boolean completed)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.<>c__DisplayClass100_0.<RobustExit>g__HandleScopeContext|2()
   at Umbraco.Cms.Infrastructure.Scoping.Scope.TryFinally(Action[] actions)
   --- End of inner exception stack trace ---
   at Umbraco.Cms.Infrastructure.Scoping.Scope.TryFinally(Action[] actions)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.Dispose()
   at Umbraco.Cms.Infrastructure.Services.CacheInstructionService.ProcessInstructions(CacheRefresherCollection cacheRefreshers, ServerRole serverRole, CancellationToken cancellationToken, String localIdentity, DateTime lastPruned, Int32 lastId)
   at Umbraco.Cms.Infrastructure.Sync.DatabaseServerMessenger.Sync()
   at Umbraco.Cms.Infrastructure.HostedServices.ServerRegistration.InstructionProcessTask.PerformExecuteAsync(Object state)
```

and appsetting 
 "CMS": {
      "Global": {
        "Id": "138d56c8-d6fb-4e98-85ca-06267e80bbb5",
        "SanitizeTinyMce": false,
        "MainDomLock": "SqlMainDomLock"
      },
      "Hosting": {
	      "LocalTempStorageLocation": "EnvironmentTemp"
      },
      "Examine": {
	      "LuceneDirectoryFactory": "SyncedTempFileSystemDirectoryFactory"
      },

**Comment by bergmania** [comment]
Hi @laputaworkuk...

Seems to be a bug deep inside the B+ Tree implementation. 
I think, to be able to reproduce, we will need the exact content you try to publish

**Comment by elit0451** [comment]
Hey there @laputaworkuk,

Unfortunately, we would have to close your issue because we haven't heard from you in more than 14 days and we were unable to reproduce it.
