### ISSUE TITLE
System.IO.FileNotFoundException : Could not load file or assembly 'WindowsBase, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specifie

### ISSUE THREAD

**Issue by croban** [umbraco/Umbraco-CMS#13440]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

Adding ABCPdf Nuget package breaks Umbraco.

```
System.IO.FileNotFoundException : Could not load file or assembly 'WindowsBase, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Umbraco.Cms.Core.Composing.ReferenceResolver.GetReferences(Assembly assembly)+MoveNext()
   at Umbraco.Cms.Core.Composing.ReferenceResolver.Resolve(Assembly assembly)
   at Umbraco.Cms.Core.Composing.ReferenceResolver.ResolveAssemblies()
   at Umbraco.Cms.Core.Composing.FindAssembliesWithReferencesTo.Find()
   at Umbraco.Cms.Core.Composing.DefaultUmbracoAssemblyProvider.get_Assemblies()
   at Umbraco.Cms.Core.Composing.TypeFinder.GetFilteredAssemblies(IEnumerable`1 excludeFromResults, String[] exclusionFilter)
   at Umbraco.Cms.Core.Composing.TypeFinder.get_AssembliesToScan()
   at Umbraco.Cms.Core.Composing.TypeLoader.get_AssembliesToScan()
   at Umbraco.Cms.Core.Composing.TypeLoader.<>c__DisplayClass21_0`1.<GetTypes>b__0()
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternalLocked(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternal(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypes[T](Boolean cache, IEnumerable`1 specificAssemblies)
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilderExtensions.AddAllCoreCollectionBuilders(IUmbracoBuilder builder)
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder.AddCoreServices()
```

### Steps to reproduce

Add ABCPdf 12.4 Nuget package and try to start Umbraco.

**Comment by Zeegaan** [comment]
Hey, @croban thanks for reporting this! 
This happens because, in our TypeFinder class, we have an internal property called `KnownAssemblyExclusionFilter` that filters out known assemblies, this is not extensible, but it really should be!
It would make sense with a method where you could add your own assemblies, like `WindowsBase` 👍
Therefore I am marking this up for grabs if someone wants to add that 😁

**Comment by FransdeJong** [comment]
This would be a lifesaver for easy pdf generation

**Comment by wvankesteren-ax** [comment]
Is there any update regarding this issue?

Please also update the documentation will information + examples about all TypeFinder settings, including this new one:
https://docs.umbraco.com/umbraco-cms/reference/configuration/typefindersettings

We have a customer upgrading to Umbraco 10.6.1 with usage of the ABCPdf package.

We hope that this will be fixed in Umbraco v10 very soon!

**Comment by Zeegaan** [comment]
There is an open PR to fix this issue, so when that gets merged, hopefully this will be fixed 👍
