### ISSUE TITLE
Slow performance and deadlocks in SignInAsync during high load (v.10–13–?)

### ISSUE THREAD

**Issue by Abrissirba** [umbraco/Umbraco-CMS#13768]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.1

### Bug summary

We experiencing deadlocks in the database when lots of members sign in at the same time. During peaks we have around 100 sign ins a minute. We use umbracos default membership provider. The sign ins get very slow and we also see deadlocks in the logs.

### Specifics

Setting the logger in debug mode locally I got the following two stacktraces. 

```
Microsoft.Data.SqlClient.SqlException (0x80131904): Transaction (Process ID 81) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)
   at Umbraco.Cms.Persistence.SqlServer.Services.SqlServerDistributedLockingMechanism.SqlServerDistributedLock.ObtainWriteLock()
   at Umbraco.Cms.Persistence.SqlServer.Services.SqlServerDistributedLockingMechanism.SqlServerDistributedLock..ctor(SqlServerDistributedLockingMechanism parent, Int32 lockId, DistributedLockType lockType, TimeSpan timeout)
   at Umbraco.Cms.Persistence.SqlServer.Services.SqlServerDistributedLockingMechanism.WriteLock(Int32 lockId, Nullable`1 obtainLockTimeout)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.ObtainWriteLock(Int32 lockId, Nullable`1 timeout)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.LockInner(Guid instanceId, Dictionary`2& locks, HashSet`1& locksSet, Action`2 obtainLock, Nullable`1 timeout, Int32 lockId)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.EagerWriteLockInner(Guid instanceId, Nullable`1 timeout, Int32[] lockIds)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.EnsureDbLocks()
   at Umbraco.Cms.Infrastructure.Scoping.Scope.get_Database()
   at Umbraco.Cms.Infrastructure.Scoping.Scope.get_Database()
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.MemberRepository.PersistUpdatedItem(IMember entity)
   at Umbraco.Cms.Core.Cache.DefaultRepositoryCachePolicy`2.Update(TEntity entity, Action`1 persistUpdated)
   at Umbraco.Cms.Core.Services.MemberService.Save(IMember member)
   at Umbraco.Cms.Core.Security.MemberUserStore.UpdateAsync(MemberIdentityUser user, CancellationToken cancellationToken)
ClientConnectionId:27b072f9-dd7a-40fb-8c14-93950869d88c
Error Number:1205,State:51,Class:13
```

```
at System.Environment.get_StackTrace()at 
Umbraco.Cms.Infrastructure.Persistence.UmbracoDatabase.OnException(Exception ex)at 
NPoco.Database.OnExceptionInternal(Exception exception)at 
NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)at 
Umbraco.Cms.Persistence.SqlServer.Services.SqlServerDistributedLockingMechanism.SqlServerDistributedLock.ObtainWriteLock()at 
Umbraco.Cms.Persistence.SqlServer.Services.SqlServerDistributedLockingMechanism.SqlServerDistributedLock..ctor(SqlServerDistributedLockingMechanism parent, Int32 lockId, DistributedLockType lockType, TimeSpan timeout)at 
Umbraco.Cms.Persistence.SqlServer.Services.SqlServerDistributedLockingMechanism.WriteLock(Int32 lockId, Nullable`1 obtainLockTimeout)at 
Umbraco.Cms.Infrastructure.Scoping.Scope.ObtainWriteLock(Int32 lockId, Nullable`1 timeout)at 
Umbraco.Cms.Infrastructure.Scoping.Scope.LockInner(Guid instanceId, Dictionary`2& locks, HashSet`1& locksSet, Action`2 obtainLock, Nullable`1 timeout, Int32 lockId)at 
Umbraco.Cms.Infrastructure.Scoping.Scope.EagerWriteLockInner(Guid instanceId, Nullable`1 timeout, Int32[] lockIds)at 
Umbraco.Cms.Infrastructure.Scoping.Scope.EnsureDbLocks()at 
Umbraco.Cms.Infrastructure.Scoping.Scope.get_Database()at 
Umbraco.Cms.Infrastructure.Scoping.Scope.get_Database()at 
Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.MemberRepository.PersistUpdatedItem(IMember entity)at 
Umbraco.Cms.Core.Cache.DefaultRepositoryCachePolicy`2.Update(TEntity entity, Action`1 persistUpdated)at 
Umbraco.Cms.Core.Services.MemberService.Save(IMember member)at 
Umbraco.Cms.Core.Security.MemberUserStore.UpdateAsync(MemberIdentityUser user, CancellationToken cancellationToken)at 
Microsoft.AspNetCore.Identity.UserManager`1.UpdateUserAsync(TUser user)at 
System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)at 
Microsoft.AspNetCore.Identity.UserManager`1.UpdateUserAsync(TUser user)at 
Microsoft.AspNetCore.Identity.UserManager`1.UpdateAsync(TUser user)at 
Umbraco.Cms.Web.Common.Security.UmbracoSignInManager`1.HandleSignIn(TUser user, String username, SignInResult result)at 
System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)at 
Umbraco.Cms.Web.Common.Security.UmbracoSignInManager`1.HandleSignIn(TUser user, String username, SignInResult result)at 
Umbraco.Cms.Web.Common.Security.UmbracoSignInManager`1.SignInWithClaimsAsync(TUser user, AuthenticationProperties authenticationProperties, IEnumerable`1 additionalClaims)at 
System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)at 
Umbraco.Cms.Web.Common.Security.UmbracoSignInManager`1.SignInWithClaimsAsync(TUser user, AuthenticationProperties authenticationProperties, IEnumerable`1 additionalClaims)at 
Microsoft.AspNetCore.Identity.SignInManager`1.SignInAsync(TUser user, AuthenticationProperties authenticationProperties, String authenticationMethod)at 
Microsoft.AspNetCore.Identity.SignInManager`1.SignInAsync(TUser user, Boolean isPersistent, String authenticationMethod)at 
XXX.Web.Business.Helpers.AuthenticationHelper.SignInToUmbracoAsync(LoginResult clientLogin) in AuthenticationHelper.cs:line 232at 
```

### Steps to reproduce

I can recreate it locally by using a load testing framework (we used https://locust.io/). 

---
_This item has been added to our backlog AB#52361_

**Comment by strudland** [comment]
I just wanted to affirm that we are also encountering the same challenges.

**Comment by Migaroez** [comment]
Hey @Abrissirba & @strudland, sorry for the late reply, this one has seemed to have slipped trough the cracks.

I will speak to the team on how we are going to approach this one and get back to you asap.

**Comment by Migaroez** [comment]
Was able to partially reproduce this on latest v10 (10.7.0)
No deadlock errors but the amount of total requests went from 9452 (for just requesting the login page) to 614 passed 126 failed for when logging in then login out members with the following k9 stage configuration. This results in 45 succeeded and 123 failed login attempts.
```
	stages: [
		{ duration: '10s', target: 10 },
		{ duration: '10s', target: 30 },
		{ duration: '10s', target: 50 },
		{ duration: '60s', target: 100 },
		{ duration: '20s', target: 200 },
		{ duration: '10s', target: 30 },
		{ duration: '10s', target: 10 },
	],
```

full test code and setup instructions included in
[13768.zip](https://github.com/umbraco/Umbraco-CMS/files/12802624/13768.zip)

**Comment by Migaroez** [comment]
✅ Reproduced in v11 (11.6.0)
[v12results.zip](https://github.com/umbraco/Umbraco-CMS/files/12803265/v12results.zip)

**Comment by Migaroez** [comment]
✅ Reproduced in v12 (12.2.0)

[v12results.zip](https://github.com/umbraco/Umbraco-CMS/files/12803484/v12results.zip)

Finally was able to capture an error on SqlLite, but it doesn't show in the logs as the app kills itself

```
Umbraco.Cms.Core.DistributedLocking.Exceptions.DistributedWriteLockTimeoutException: Failed to acquire write lock for id: -341.
   at Umbraco.Cms.Persistence.Sqlite.Services.SqliteDistributedLockingMechanism.SqliteDistributedLock.ObtainWriteLock() in C:\Repos\Umbraco-CMS-V12\src\Umbraco.Cms.Persistence.Sqlite\Services\SqliteDistributedLockingMechanism.cs:line 175
   at Umbraco.Cms.Persistence.Sqlite.Services.SqliteDistributedLockingMechanism.SqliteDistributedLock..ctor(SqliteDistributedLockingMechanism parent, Int32 lockId, DistributedLockType lockType, TimeSpan timeout) in C:\Repos\Umbraco-CMS-V12\src\Umbr
aco.Cms.Persistence.Sqlite\Services\SqliteDistributedLockingMechanism.cs:line 82
   at Umbraco.Cms.Persistence.Sqlite.Services.SqliteDistributedLockingMechanism.WriteLock(Int32 lockId, Nullable`1 obtainLockTimeout) in C:\Repos\Umbraco-CMS-V12\src\Umbraco.Cms.Persistence.Sqlite\Services\SqliteDistributedLockingMechanism.cs:line
51
   at Umbraco.Cms.Core.Scoping.LockingMechanism.ObtainWriteLock(Int32 lockId, Nullable`1 timeout) in C:\Repos\Umbraco-CMS-V12\src\Umbraco.Core\Scoping\LockingMechanism.cs:line 98
   at Umbraco.Cms.Core.Scoping.LockingMechanism.LockInner(Guid instanceId, Dictionary`2& locks, HashSet`1& locksSet, Action`2 obtainLock, Nullable`1 timeout, Int32 lockId) in C:\Repos\Umbraco-CMS-V12\src\Umbraco.Core\Scoping\LockingMechanism.cs:lin
e 172
   at Umbraco.Cms.Core.Scoping.LockingMechanism.EagerWriteLockInner(Guid instanceId, Nullable`1 timeout, Int32[] lockIds) in C:\Repos\Umbraco-CMS-V12\src\Umbraco.Core\Scoping\LockingMechanism.cs:line 74
   at Umbraco.Cms.Core.Scoping.LockingMechanism.EagerWriteLock(Guid instanceId, Nullable`1 timeout, Int32[] lockIds) in C:\Repos\Umbraco-CMS-V12\src\Umbraco.Core\Scoping\LockingMechanism.cs:line 54
   at Umbraco.Cms.Core.Scoping.CoreScope.EagerWriteLock(Int32[] lockIds) in C:\Repos\Umbraco-CMS-V12\src\Umbraco.Core\Scoping\CoreScope.cs:line 202
   at Umbraco.Cms.Infrastructure.HostedServices.ScheduledPublishing.PerformExecuteAsync(Object state) in C:\Repos\Umbraco-CMS-V12\src\Umbraco.Infrastructure\HostedServices\ScheduledPublishing.cs:line 116

```

**Comment by jesperordrup** [comment]
reproduced in 12.3.3

**Comment by ronaldbarendse** [comment]
I've seen the `Failed to acquire write lock for id: -341.` error a few times while doing large content deployments/publishes on SQLite as well. I believe the issue is caused by the fact SQLite can only have a single concurrent writable transaction, as mentioned in this comment:

https://github.com/umbraco/Umbraco-CMS/blob/4aa0378431202152fad74c53456ad04adab8174f/src/Umbraco.Cms.Persistence.Sqlite/Services/SqliteDatabaseCreator.cs#L19-L38

Because the `ScheduledPublishing` background job takes an eager write lock on `Constants.Locks.ScheduledPublishing`, it will completely block any other write transaction or needs to wait until the current write transaction has completed, with the potential to timeout either transaction.

It probably doesn't help that the scope in this background job uses `autoComplete: true` since it got refactored in v12:
https://github.com/umbraco/Umbraco-CMS/blob/c30ffa9ac3ae9c12508242855c63208567c55eb9/src/Umbraco.Infrastructure/BackgroundJobs/Jobs/ScheduledPublishingJob.cs#L68

Besides ensuring this explicitly completes the scope (using `scope.Complete();`), I'm not sure how we can actually fix the issue. We still want to ensure all scheduled content is published on time, so the background job needs to run every minute... But maybe we can avoiding the need to take the write lock every minute?

The same probably also applies to members: every sign-in currently updates the members `LastLoginDateUtc`, `AccessFailedCount` (if it was more than 0) and security stamp (if `AllowConcurrentLogins` is disabled), which takes a write lock on `Constants.Locks.MemberTree`...

**Comment by jemayn** [comment]
Any updates on this one?

We are seeing it when we reach about 100 concurrent members logging in. I've tried reproducing on a fresh site with k6 similar to @Migaroez and it is quite easy to hit.

This is on a 13.7.2 site with a SQL Server db just simply hitting a surface controller endpoint like this:

```csharp
[HttpPost]
[IgnoreAntiforgeryToken]
public async Task<IActionResult> HandleDirectLogin([FromBody]DirectLoginModel model)
{
    if (string.IsNullOrWhiteSpace(model.Email) || string.IsNullOrWhiteSpace(model.Password))
    {
        return Unauthorized("Invalid email or password");
    }

    SignInResult result = await _memberSignInManager.PasswordSignInAsync(
        model.Email,
        model.Password,
        false,
        true
    );

    if (result.Succeeded)
    {
        return Ok();
    }
    
    return Unauthorized("Invalid email or password");
}
```

This happens both locally and on the Azure site, both running a SQL Server db.

**Comment by AndyButland** [comment]
Here's my findings from some investigation this morning in trying to replicate the deadlock issue, which I'm afraid I wasn't able to do.  I've adapted what's been posted above from @Migaroez and @jemayn.

Running locally with SQL Express, a clean Umbraco 13.latest and 1000 members created using the script @Migaroez provided above.

Using this k6 script (also adapted from the one @Migaroez prepared earlier):

```
import { check, sleep } from "k6";
import exec from 'k6/execution';
import http from "k6/http";

export const options = {
	stages: [
		{ duration: '10s', target: 10 },
		{ duration: '10s', target: 30 },
		{ duration: '10s', target: 50 },
		{ duration: '60s', target: 100 },
		{ duration: '20s', target: 200 },
		{ duration: '10s', target: 30 },
		{ duration: '10s', target: 10 },
	],
};

export default function() {
  const params = {
    headers: {
      'Content-Type':'application/json'
    }
  };

  const res = http.post(
    "https://localhost:44331/umbraco/surface/MemberLogin/HandleDirectLogin",
    JSON.stringify({
      "Email": `test${exec.vu.idInTest}@test.test`,
      "Password": `test${exec.vu.idInTest}@test.test`
    }),
    params);
  check(res, {
    "is status 200": (r) => r.status === 200
  });
  sleep(0.1);
};
```

And hitting this endpoint:

```
using Microsoft.AspNetCore.Mvc;
using Umbraco.Cms.Core.Cache;
using Umbraco.Cms.Core.Logging;
using Umbraco.Cms.Core.Routing;
using Umbraco.Cms.Core.Services;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Infrastructure.Persistence;
using Umbraco.Cms.Web.Common.Security;
using Umbraco.Cms.Web.UI.Models;
using Umbraco.Cms.Web.Website.Controllers;

namespace Umbraco.Cms.Web.UI.Controllers
{
    public class MemberLoginController : SurfaceController
    {
        private readonly IMemberSignInManager _memberSignInManager;

        public MemberLoginController(IUmbracoContextAccessor umbracoContextAccessor, IUmbracoDatabaseFactory databaseFactory, ServiceContext services, AppCaches appCaches, IProfilingLogger profilingLogger, IPublishedUrlProvider publishedUrlProvider, IMemberSignInManager memberSignInManager) : base(umbracoContextAccessor, databaseFactory, services, appCaches, profilingLogger, publishedUrlProvider)
        {
            _memberSignInManager = memberSignInManager;
        }

        [HttpPost]
        [IgnoreAntiforgeryToken]
        public async Task<IActionResult> HandleDirectLogin([FromBody] DirectLoginModel model)
        {
            if (string.IsNullOrWhiteSpace(model.Email) || string.IsNullOrWhiteSpace(model.Password))
            {
                return Unauthorized("Invalid email or password");
            }

            Microsoft.AspNetCore.Identity.SignInResult result = await _memberSignInManager.PasswordSignInAsync(
                model.Email,
                model.Password,
                false,
                true
            );

            if (result.Succeeded)
            {
                return Ok();
            }

            return Unauthorized("Invalid email or password");
        }
    }
}
```

Gives the following results:

```
         /\      Grafana   /‾‾/
    /\  /  \     |\  __   /  /
   /  \/    \    | |/ /  /   ‾‾\
  /          \   |   (  |  (‾)  |
 / __________ \  |_|\_\  \_____/

     execution: local
        script: C:\Repos\Umbraco\Umbraco.Cms-V13\tools\load-test-member-login.js
        output: -

     scenarios: (100.00%) 1 scenario, 200 max VUs, 2m40s max duration (incl. graceful stop):
              * default: Up to 200 looping VUs for 2m10s over 7 stages (gracefulRampDown: 30s, gracefulStop: 30s)

  █ TOTAL RESULTS

    checks_total.......................: 3568    27.329347/s
    checks_succeeded...................: 100.00% 3568 out of 3568
    checks_failed......................: 0.00%   0 out of 3568

    ✓ is status 200

    HTTP
    http_req_duration.......................................................: avg=2.67s min=84.87ms  med=2.16s max=11.14s p(90)=5.47s p(95)=6.35s
      { expected_response:true }............................................: avg=2.67s min=84.87ms  med=2.16s max=11.14s p(90)=5.47s p(95)=6.35s
    http_req_failed.........................................................: 0.00%  0 out of 3568
    http_reqs...............................................................: 3568   27.329347/s

    EXECUTION
    iteration_duration......................................................: avg=2.79s min=185.05ms med=2.27s max=11.25s p(90)=5.6s  p(95)=6.47s
    iterations..............................................................: 3568   27.329347/s
    vus.....................................................................: 11     min=1         max=200
    vus_max.................................................................: 200    min=200       max=200

    NETWORK
    data_received...........................................................: 2.9 MB 22 kB/s
    data_sent...............................................................: 563 kB 4.3 kB/s


running (2m10.6s), 000/200 VUs, 3568 complete and 0 interrupted iterations
default ✓ [======================================] 000/200 VUs  2m10s
```

So no failures.

Just cross-checking I see 948 records in `umbracoAudit` for "member save" events.  Given the script ran for 2m 10s that's simulated 7.3 logins a second.  Maybe we could push this further but that would seem to me a fairly high level of traffic to see in the wild - i.e. 7+ users logging in every second.  Of course in reality there'll be other requests to handle - not just a login endpoint.

Could well be I've missed something here - it's the first time I've looked at using k6 - but you mentioned @jemayn that this was quite easy to hit running using SQL Server locally.  Would you mind having a look over the above to see what I've done please, and see what might be different from your setup and replication of the deadlocks issue? Thanks.

**Comment by jemayn** [comment]
Hey @AndyButland 

I will try to setup a reproduceable example and get back to you. Thanks for looking into this!

**Comment by umbracocommunity** [comment]
This issue has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/limits-on-concurrent-api-requests-for-umbraco-13-5-3/3361/7

**Comment by jemayn** [comment]
Hey @AndyButland 

I saw you made some changes in #19308, and I went ahead and compared with current 13.8.1 on my test project.

For both tests I ran with this slow ramp up to help pinpoint when any issues would start surfacing:
```js
export let options = {
    stages: [
        { duration: '10s', target: 15 },
        { duration: '10s', target: 20 },
        { duration: '120s', target: 30 },
        { duration: '120s', target: 50 },
        { duration: '120s', target: 70 },
        { duration: '120s', target: 90 },
        { duration: '60s', target: 15 },
        { duration: '10s', target: 0 },
    ]
};
```
## 13.8.1 code
With the 13.8.1 code I started getting errors like this one at around 15-20 vus and seemed to get it pr vu every second so I had thousands at the end of the test:

![Image](https://github.com/user-attachments/assets/cd4cf838-e155-4f26-aea8-3505e098bea4)

Final result of the test:

![Image](https://github.com/user-attachments/assets/66dfa09c-4bb7-4a8c-8351-b4a3e5f479aa)

## With #19308 Nuget packages

With this I had no errors until it scaled up to ~90 concurrent logins, where it seemed the index triggered it:

![Image](https://github.com/user-attachments/assets/ea2cd6c8-53fb-4a58-881b-b9d62af81ce7)

The results numbers also looked much better! Do note that because the avg duration was faster we had way more total requests. It had that one error at 90 concurrent users which skews the max to a 60s timeout, but the average durations were so much better otherwise!

![Image](https://github.com/user-attachments/assets/fe461d01-a2e8-49ba-99a8-ff4c7816ca8a)

**Comment by AndyButland** [comment]
Thanks @jemayn - that looks promising.  I was going to reach out to you once I had this work reviewed to ask to see if you could verify seeing some improvement, so thanks for proactively doing this anyway.

**Comment by AndyButland** [comment]
Resolved via https://github.com/umbraco/Umbraco-CMS/pull/19308 and targeted for 13.9 and 16.1.

**Comment by Gbhilton** [comment]
This doesn't seem to have fixed our issue. I applied the 13.9 updates. I hit the site with 100 members to create accounts concurrently and it threw deadlock errors constantly. This was run on production and dev, in dev a lot of new unhandled errors appeared after the update as well. These new unhandled exceptions were all timeout/deadlock related. The site is unusable during this time that the accounts are being created/attempting to use the site. 

@jemayn, can you confirm if this fixed your issue, I believe from what I am reading we are having very similar issues with almost identical set ups for account creation. 

We made a post here about it a while ago. 
https://forum.umbraco.com/t/limits-on-concurrent-api-requests-for-umbraco-13-5-3/3361

**Comment by AndyButland** [comment]
This update is specifically related to logging in members @Gbhilton, not creating them.  The issue comes from a member save operation, that's a relatively "heavy" thing to do.  Members in Umbraco are variations on content, so they have all the same set up for properties, locking etc. that saving documents in the backoffice do.

For logging in, we recognised that really we could by-pass this, as we are only saving a couple of fields in a single database table, so could do that in a more streamlined way.  Creating members is a different scenario - it would seem that we can't avoid a full save of the member entity in that instance.

**Comment by Gbhilton** [comment]
Is there any updates planned for creation of members? Right now, if we have a member created once every few seconds, the site is still inoperable unfortunately because it's hung up on the account creation. I was sending 1 account every 2 seconds or so and trying to have someone use our site and it was hanging/loading constantly.

**Comment by AndyButland** [comment]
I don't see anything in the medium term for significant updates to members that would resolve this I'm afraid.  As noted above, Umbraco members are currently very much based on content, with the overhead that entails.

**Comment by marius-ruhrmann-syzygy** [comment]
I can only agree with @Gbhilton and @Abrissirba. If several hundred users log in at the same time or even if new users join, the Umbraco system crashes. This should definitely not be the case and is actually unacceptable for scalable solutions. It would be great if you could add this to the roadmap. We would highly appreciate it!

Furthermore, this issue shouldn't be closed.
