### ISSUE TITLE
TinyMCE Link Picker - empty link throws JS error

### ISSUE THREAD

**Issue by leekelleher** [umbraco/Umbraco-CMS#13860]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.1.0

### Bug summary

When using the TinyMCE rich-text editor, adding an _empty_ link will cause a JavaScript error.

![Screenshot 2023-02-20 130721](https://user-images.githubusercontent.com/209066/220117373-7cd04f75-5646-4b88-bd42-b1544e0378ef.png)

### Specifics

The JavaScript error appears to be on a string split...

```
TypeError: Cannot read properties of undefined (reading 'split')
    at Object.insertLinkInEditor (umbraco.services.min.js?d=638124951150000000:1:102047)
    at Object.submit (umbraco.services.min.js?d=638124951150000000:1:107192)
    at Object.submit (umbraco.controllers.min.js?d=638124951150000000:1:202421)
    at fn (eval at compile (angular.js:16548:15), <anonymous>:4:232)
    at d.<computed> [as action] (angular.js:11517:22)
    at UmbButtonController.clickButton (umbraco.directives.min.js?d=638124951150000000:1:66004)
    at fn (eval at compile (angular.js:16548:15), <anonymous>:4:245)
    at e (angular.js:29123:13)
    at b.$eval (angular.js:19523:16)
    at b.$apply (angular.js:19622:20)
```

The corresponding source code can be found here: https://github.com/umbraco/Umbraco-CMS/blob/release-11.1.0/src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js#L1165

### Steps to reproduce

- From a TinyMCE RTE, press the Link button. 🔗
- The Link Picker side panel should open.
- Without doing anything else, press the "Submit" button.
- Nothing happens. e.g. the side panel doesn't close.
- In the browser's dev-tools console, there is the JavaScript error.

### Expected result / actual result

You may ask why would a content author press the Submit button (and not the Cancel) for an empty link - _I asked myself the same question._ But it seems that with if you take the same steps with a regular URL Picker editor, the side-panel will close gracefully with no JavaScript errors. I'd expect the same within the RTE.

**Comment by Zeegaan** [comment]
I can definitely reproduce this one 👍 Seems like a missing NullOrEmpty check somewhere 🙈 
Marking this as up for grabs 🙌
