### ISSUE TITLE
Exception is thrown when trying to add property with identical alias to composition

### ISSUE THREAD

**Issue by PeterKvayt** [umbraco/Umbraco-CMS#14099]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.0

### Bug summary

When I have 2 compositions, which are already used in one doc type and I add property to composition with the same property alias which already exists in other used composition, I got an exception with stack trace.

It would be great to get nice error page with explanation why we can't save composition with this property.

### I did not test this case in other versions, but Im quite sure that this will reproduced in 10.x version
![image](https://user-images.githubusercontent.com/45105665/231970372-86836c52-1221-43ed-b112-d6ac75446645.png)

at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentTypeControllerBase`1.AddCompositionValidationErrors[TContentTypeSave,TPropertyType](TContentTypeSave contentTypeSave, IEnumerable`1 duplicatePropertyTypeAliases, IEnumerable`1 invalidPropertyGroupAliases)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentTypeControllerBase`1.CreateCompositionValidationExceptionIfInvalid[TContentTypeSave,TPropertyType,TContentTypeDisplay](TContentTypeSave contentTypeSave, TContentType composition)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentTypeControllerBase`1.PerformPostSave[TContentTypeDisplay,TContentTypeSave,TPropertyType](TContentTypeSave contentTypeSave, Func`2 getContentType, Action`1 saveContentType, Action`1 beforeCreateNew)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentTypeController.PostSave(DocumentTypeSave contentTypeSave)
   at lambda_method3740(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

### Steps to reproduce

1. Create composition "Test" doc type with group name "Foo" with propetry "Bar" with editor Umbraco.TrueFalse
2. Create usual doc type "Doc" with template
3. Add composition "Test" to "Doc"
4. Create copy of "Test" composition, then you will get "Test (copy)"
5. Remove property "Bar" from "Test (copy)"
6. Add composition "Test (cope)" to "Doc"
7. Add property "Bar" (exactly the same as in the first step) to "Test (copy)"
8. Try to save changes

### Expected result / actual result

**Expected result**: there is an error message that we create property with the same alias name with already exists in used doc type.

**Actual result**: there is an exception while trying to save changes.

**Comment by elit0451** [comment]
Hi @PeterKvayt 👋 
Thanks for reaching out and for the detailed steps for reproducing your issue 💪 When I tried your scenario on a fresh Umbraco 11.3 installation, I was getting validation errors that point to the problem pretty clearly, _as you can see in the video below_. Wasn't it the same for you or perhaps I am missing something?

https://user-images.githubusercontent.com/21998037/232459861-3fc4a541-d40c-4eae-b029-f2347cec818b.mp4

**Comment by PeterKvayt** [comment]
Hi @elit0451!
Yes, you are right, it's works fine, may be it was my fault. I will investigate it more deeply later.
Anyway thanks!
