### ISSUE TITLE
UnattendedInstaller broken

### ISSUE THREAD

**Issue by netcompany-runeviumsondergaard** [umbraco/Umbraco-CMS#14110]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.0

### Bug summary

In 11.2.2 everything is working as it should. On an empty database Umbraco tries to find the relevant database from the umbracoDbDSN env variable and when it isn't found the database is created, no problem.
In 11.3.0 something is now broken and I just get an error. The only thing I changed is the version. 

I know for sure the env variable is still used and is valid, as the error I get when changing it to something invalid is different. 

### Specifics

Output in terminal:
2023-04-17 15:22:23 Error Number:4060,State:1,Class:11
2023-04-17 15:22:23 Unhandled exception. Umbraco.Cms.Core.Exceptions.BootFailedException: A connection string is configured but Umbraco could not connect to the database.
2023-04-17 15:22:23    at Umbraco.Cms.Infrastructure.Runtime.RuntimeState.DetermineRuntimeLevel()
2023-04-17 15:22:23    at Umbraco.Cms.Infrastructure.Install.UnattendedInstaller.HandleAsync(RuntimeUnattendedInstallNotification notification, CancellationToken cancellationToken)
2023-04-17 15:22:23    at Umbraco.Cms.Core.Events.NotificationAsyncHandlerWrapperImpl`1.<>c__DisplayClass0_0.<HandleAsync>b__1(INotification theNotification, CancellationToken theToken)
2023-04-17 15:22:23    at Umbraco.Cms.Core.Events.EventAggregator.PublishCoreAsync(IEnumerable`1 allHandlers, INotification notification, CancellationToken cancellationToken)
2023-04-17 15:22:23    at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.StartAsync(CancellationToken cancellationToken, Boolean isRestarting)
2023-04-17 15:22:23    at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.StartAsync(CancellationToken cancellationToken)
2023-04-17 15:22:23    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
2023-04-17 15:22:23    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2023-04-17 15:22:23    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2023-04-17 15:22:23    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
2023-04-17 15:22:23    at UmbracoPOC.Program.Main(String[] args) in /src/UmbracoPOC/Program.cs:line 8
2023-04-17 15:22:23 [13:22:23 ERR] Unhandled exception in AppDomain (terminating).
2023-04-17 15:22:23 Umbraco.Cms.Core.Exceptions.BootFailedException: A connection string is configured but Umbraco could not connect to the database.
2023-04-17 15:22:23    at Umbraco.Cms.Infrastructure.Runtime.RuntimeState.DetermineRuntimeLevel()
2023-04-17 15:22:23    at Umbraco.Cms.Infrastructure.Install.UnattendedInstaller.HandleAsync(RuntimeUnattendedInstallNotification notification, CancellationToken cancellationToken)
2023-04-17 15:22:23    at Umbraco.Cms.Core.Events.NotificationAsyncHandlerWrapperImpl`1.<>c__DisplayClass0_0.<HandleAsync>b__1(INotification theNotification, CancellationToken theToken)
2023-04-17 15:22:23    at Umbraco.Cms.Core.Events.EventAggregator.PublishCoreAsync(IEnumerable`1 allHandlers, INotification notification, CancellationToken cancellationToken)
2023-04-17 15:22:23    at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.StartAsync(CancellationToken cancellationToken, Boolean isRestarting)
2023-04-17 15:22:23    at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.StartAsync(CancellationToken cancellationToken)
2023-04-17 15:22:23    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
2023-04-17 15:22:23    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2023-04-17 15:22:23    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2023-04-17 15:22:23    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
2023-04-17 15:22:23    at UmbracoPOC.Program.Main(String[] args) in /src/UmbracoPOC/Program.cs:line 8

### Steps to reproduce

Run Umbraco from scratch and use a MSSQL database.
I run it in docker and my docker compose state:
            ConnectionStrings__umbracoDbDSN: "Server=umbraco-db;Database=umbracoDb;User Id=sa;Password=yourStrong(!)Password;"
            ConnectionStrings__umbracoDbDSN_ProviderName: "Microsoft.Data.SqlClient"
 

### Expected result / actual result

Umbraco should recreate a new empty database allowing Usync to add content. 

---
_This item has been added to our backlog [AB#28820](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/28820)_

**Comment by NC-RVSO** [comment]
I am running it with these:
            ConnectionStrings__umbracoDbDSN: "Server=umbraco-db;Database=umbracoDb;User Id=sa;Password=yourStrong(!)Password;"
            ConnectionStrings__umbracoDbDSN_ProviderName: "Microsoft.Data.SqlClient"
            And the database is running in another docker container :)

**Comment by Zeegaan** [comment]
Thanks for the info! I can definitely reproduce this, seems like a regression to me! 

To anyone wondering how to setup SqlServer on docker i followed this article: https://www.sqlservercentral.com/articles/docker-desktop-on-windows-10-for-sql-server-step-by-step

**Comment by NC-RVSO** [comment]
@ronaldbarendse I agree the new behavior is more correct. Maybe the error message should be more informative? It could mention the InstallMissingDatabase property.

**Comment by kjac** [comment]
Closing as the PR was merged 😄
