### ISSUE TITLE
Update from 10.4.2 to 10.5.0

### ISSUE THREAD

**Issue by thomashdk** [umbraco/Umbraco-CMS#14145]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.2  -> 10.5.0

### Bug summary

After updating from 10.4.2 to 10.5.0, I'm getting this issue:
```
Umbraco.Cms.Core.Exceptions.BootFailedException: An error occurred while running the unattended upgrade.
The database configuration failed with the following message: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId". The conflict occurred in database "Kommuneplatformen-umb10-new", table "dbo.cmsContentType", column 'nodeId'.
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId". The conflict occurred in database "Platformen, table "dbo.cmsContentType", column 'nodeId'.
```

### Specifics

- Maybe linked to this: https://github.com/umbraco/Umbraco-CMS/pull/12684

### Steps to reproduce

- Have a running UMB 10.4.2 - Upgrade to 10.5.0
- on the startup the unattended upgrade will fail  with this message:

`Umbraco.Cms.Core.Exceptions.BootFailedException: An error occurred while running the unattended upgrade.
The database configuration failed with the following message: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId". The conflict occurred in database "Kommuneplatformen-umb10-new", table "dbo.cmsContentType", column 'nodeId'.
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId". The conflict occurred in database "Platformen, table "dbo.cmsContentType", column 'nodeId'.`

### Expected result / actual result

Upgrade and the solution should start up again.

**Comment by Zeegaan** [comment]
@thomashdk What database provider are you using here ? 😁

**Comment by thomashdk** [comment]
> @thomashdk What database provider are you using here ? 😁

Hi 
I'm using Microsoft SQL Server 2019 Versions

**Comment by thomashdk** [comment]
![image](https://user-images.githubusercontent.com/6445636/233983183-d05495f7-c7c8-409c-aeba-7a2971961be8.png)

**Comment by thomashdk** [comment]
I deleted the dbo.umbracoContentVersionCleanupPolicy. That did the trick

**Comment by Zeegaan** [comment]
Hmmm I cannot reproduce this 🤔 
This is me trying to upgrade a 10.4.2 site (with just 1 contenttype & 1 content node) to a 10.5.0 and that's working fine 🤔 
![image](https://user-images.githubusercontent.com/70372949/233987064-a433924e-9712-4937-a8fb-e5ea0614f178.png)
Did you have any custom cleanup policy setup for a specific content type? 😅

**Comment by thomashdk** [comment]
I'm getting this error also:


@MessageTemplate | Error occurred executing {WorkItem}.


```
System.NotSupportedException: Variation "da,<null>" is not supported by the property type.
   at Umbraco.Cms.Core.Models.Property.SetValue(Object value, String culture, String segment)
   at Umbraco.Cms.Core.PropertyEditors.NestedPropertyIndexValueFactoryBase`2.GetNestedResults(String keyPrefix, String 
      culture, String segment, Boolean published, IDictionary`2 propertyTypeDictionary, TItem 
   nestedContentRowValue)+MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Umbraco.Cms.Core.PropertyEditors.NestedPropertyIndexValueFactoryBase`2.Handle(TSerialized 
   deserializedPropertyValue, IProperty property, String culture, String segment, Boolean published)
   at Umbraco.Cms.Core.PropertyEditors.JsonPropertyIndexValueFactoryBase`1.GetIndexValues(IProperty property, String 
   culture, String segment, Boolean published)
   at Umbraco.Cms.Infrastructure.Examine.BaseValueSetBuilder`1.AddPropertyValue(IProperty property, String culture, String 
   segment, IDictionary`2 values)
   at Umbraco.Cms.Infrastructure.Examine.ContentValueSetBuilder.GetValueSetsEnumerable(IContent[] content, Dictionary`2 
   creatorIds, Dictionary`2 writerIds)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Umbraco.Cms.Infrastructure.Examine.ContentIndexPopulator.IndexPublishedContent(Int32 contentParentId, Int32 
   pageIndex, Int32 pageSize, IReadOnlyList`1 indexes)
   at Umbraco.Cms.Infrastructure.Examine.ContentIndexPopulator.PopulateIndexes(IReadOnlyList`1 indexes)
   at Umbraco.Cms.Infrastructure.Examine.IndexPopulator.Populate(IIndex[] indexes)
   at Umbraco.Cms.Infrastructure.Examine.ExamineIndexRebuilder.RebuildIndex(String indexName, TimeSpan delay, 
   CancellationToken cancellationToken)
   at Umbraco.Cms.Infrastructure.Examine.ExamineIndexRebuilder.<>c__DisplayClass9_1.<RebuildIndex>b__1()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext 
   executionContext, ContextCallback callback, Object state)
   --- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of stack trace from previous location ---
   at Umbraco.Cms.Infrastructure.HostedServices.QueuedHostedService.BackgroundProcessing(CancellationToken 
   stoppingToken)
```

**Comment by thomashdk** [comment]
Found workaround here:
https://github.com/umbraco/Umbraco-CMS/issues/14096
