### ISSUE TITLE
Running migrations for custom DbContext not working with SQLite

### ISSUE THREAD

**Issue by Mantus667** [umbraco/Umbraco-CMS#14267]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.0-rc1

### Bug summary

I followed the steps in the documentation to create custom database tables via EF Core.
The one information missing is the actual connection string and the database provider which should be used and is necessary in the `AddUmbracoEFCoreContext<>()` method. So I used `var connectionString = _config.GetUmbracoConnectionString(out var providerName);` to get the connection string and provider name from the appsettings.

When my NotificationAsyncHandler is called and the database should execute the migrations using `await _customDbContext.Database.MigrateAsync(cancellationToken);` I get the following exception:

`
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool)
   at Microsoft.Data.Sqlite.SqliteConnectionPool.GetConnection()
   at Microsoft.Data.Sqlite.SqliteConnectionFactory.GetConnection(SqliteConnection outerConnection)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CreateAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at Umbraco12Test.EFCoreTest.RunBlogCommentsMigration.HandleAsync(UmbracoApplicationStartedNotification notification, CancellationToken cancellationToken)
`

 

### Steps to reproduce

Follow the instructions on the documentation site: https://docs.umbraco.com/umbraco-cms/v/12.latest/tutorials/getting-started-with-entity-framework-core

### Expected result / actual result

I would expect the database to run all migrations and create the tables defined in the migration.
I get an error during the migration that the database can't be accessed.

**Comment by Zeegaan** [comment]
Hey @Mantus667, this error often occurs when the database is unable to be found, what does your connection string look like 🕵️

**Comment by Mantus667** [comment]
It's basically the default one that Umbraco creates if you run a fresh install with SQLite:
`
"ConnectionStrings": {
    "umbracoDbDSN": "Data Source=|DataDirectory|/Umbraco.sqlite.db;Cache=Shared;Foreign Keys=True;Pooling=True",
    "umbracoDbDSN_ProviderName": "Microsoft.Data.Sqlite"
  }
`

**Comment by Zeegaan** [comment]
@Mantus667 sorry, I meant the connection string you pass when you register EFCore 😁

**Comment by Mantus667** [comment]
@Zeegaan the same. :) But based on that question I guess that you need a specific connection string for the ef core stuff? And based on that you can't work on the same database that is used by umbraco? As my thought was to work on the same sqlite database and create tables there with ef core

**Comment by Zeegaan** [comment]
Yes that was my concern, the umbraco connection string contains `|DataDirectory|`, which is an umbraco concept, therefore it did not work.
We have remedied this in rc2 with this PR: https://github.com/umbraco/Umbraco-CMS/pull/14278, so this should be fixed 👍
