### ISSUE TITLE
Publish scheduling fails when users language is set to Danish

### ISSUE THREAD

**Issue by SonniTost** [umbraco/Umbraco-CMS#14306]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.5.0

### Bug summary

When users try to use the schedule function on a document - then the date format throws an Newtonsoft.Json error when the users press Schedule.

### Specifics

It happens when the users' language is set to Danish. It seems that it does not happen when the users' language is set to English.

It could be related to this https://github.com/umbraco/Umbraco-CMS/issues/3075

### Steps to reproduce

Open a page
Instead of pressing Save and publish - click the arrow and select Schedule
Set some dates and press Schedule.
- This usually throws an error
Click Shedule again (either change the dates or do nothing) and press Schedule
- This throws an error

https://github.com/umbraco/Umbraco-CMS/assets/66302306/b38316e1-8a4f-464c-8ce1-d5e567b873b7

## Expected
A schedule is created for the page (either publish or expire)

## Actual
Throws a Newtonsoft.Json error - Could not convert string to DateTime: 2023-05-30 12.00.00. Path 'variants[0].releaseDate', line 1, position 8119. (Please note the . in the time format)

An error occurred
Could not convert string to DateTime: 2023-05-30 12.00.00. Path 'variants[0].releaseDate', line 1, position 8119.

Undtagelsesdetaljer
Newtonsoft.Json.JsonReaderException, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed: Could not convert string to DateTime: 2023-05-30 12.00.00. Path 'variants[0].releaseDate', line 1, position 8119.

Stacktrace
at Newtonsoft.Json.JsonReader.ReadDateTimeString(String s)
   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsDateTime()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Umbraco.Cms.Web.BackOffice.ModelBinders.ContentModelBinderHelper.BindModelFromMultipartRequestAsync[T](IJsonSerializer jsonSerializer, IHostingEnvironment hostingEnvironment, ModelBindingContext bindingContext)
   at Umbraco.Cms.Web.BackOffice.ModelBinders.ContentItemBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value, Object container)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

![image](https://github.com/umbraco/Umbraco-CMS/assets/66302306/f9e90074-9546-4e4d-93d8-a0b42209670f)

**Comment by elit0451** [comment]
Hi @SonniTost 👋 
Thanks for reaching out. I've tried to reproduce your issue, but as you can see in the video below, I don't get the same error as you 🤷‍♀️ 

Can you help me figure out what I might be doing wrong? 🙂 

https://github.com/umbraco/Umbraco-CMS/assets/21998037/54df008f-9a73-4d77-9621-b14ede6a4559

**Comment by elit0451** [comment]
Thanks for clarifying @SonniTost 

I can indeed reproduce. I will mark it as up for grabs as we would like some help with it 🙂

**Comment by Danielh21** [comment]
Hi.

We are experiencing something related . In the "Info" tab, we can see that the "Created date" is displayed as "invalid date" when the CMS language is Danish here is the video:

https://github.com/umbraco/Umbraco-CMS/assets/15868547/0279fccc-3291-4da3-ac0e-bf921759274b

**Comment by elit0451** [comment]
Great insight @emmagarland, thanks for that 🙌

**Comment by calixuss** [comment]
I am working on it :)

**Comment by miguelcrpinto** [comment]
This is a frontend issue. Whenever there's already a date/time set for the scheduled publish and that date/time is not modified, the frontend is sending the time with . as unit separator instead of : 

See screenshot below:
![image](https://github.com/umbraco/Umbraco-CMS/assets/8625173/2f5fa9e4-2c72-49b1-933e-9161ae25b608)


JSON posted by the frontend:
```
{
    "id": 1059,
    "contentTypeAlias": "contentPage",
    "parentId": -1,
    "action": "schedule",
    "variants": [
        {
            "name": "Content created in danish (1)",
            "properties": [
                {
                    "id": 9,
                    "alias": "body",
                    "value": "<p>dummy</p>"
                }
            ],
            "culture": null,
            "segment": null,
            "publish": false,
            "save": true,
            "releaseDate": null,
            "expireDate": "2023-06-23 13.25.00"
        }
    ],
    "expireDate": null,
    "releaseDate": null,
    "templateAlias": null
}
```

Notice the "13.25.00" in the expireDate vs the expected "13:25:00"

**Comment by miguelcrpinto** [comment]
After further investigation, it seems that the time is being formatted in the backend in the response of the Get By Id API (/umbraco/backoffice/umbracoapi/content/GetById?id={node id}).

See the attached response examples in PT and in DA.
[Portuguese response example.txt](https://github.com/umbraco/Umbraco-CMS/files/11769504/Portuguese.response.example.txt)

[Danish response example.txt](https://github.com/umbraco/Umbraco-CMS/files/11769503/Danish.response.example.txt)

**Comment by miguelcrpinto** [comment]
I figured out the issue.

In the JsonDateTimeFormatAttribute we are adding a IsoDateTimeConverter with a specific time format (the one expected by the frontend) but without specifying the culture. Whenever no culture is provided the IsoDateTimeConverter uses the CurrentCulture ("da-DK" in this case). In .Net Core the when you do a DateTime ToString("yyyy-MM-dd HH:mm:ss", new CultureInfo("da-DK")) it seems to ignore the format and just use the format from the provided culture.

**Comment by miguelcrpinto** [comment]
Created PR [14400](https://github.com/umbraco/Umbraco-CMS/pull/14400) to fix this issue.

**Comment by emmagarland** [comment]
> Created PR [14400](https://github.com/umbraco/Umbraco-CMS/pull/14400) to fix this issue. 

Amazing stuff!

**Comment by calixuss** [comment]
> Created PR [14400](https://github.com/umbraco/Umbraco-CMS/pull/14400) to fix this issue.

Awesome work @miguelcrpinto 
I would need to find other issue to contribute to :)

**Comment by miguelcrpinto** [comment]
For those interested in knowing more about this behavior, [here's the official documentation from Microsoft](https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#timeSeparator).

**Comment by emmagarland** [comment]
Thanks @miguelcrpinto! 

The related PR #14400 has now been merged. Thanks @SonniTost for raising this issue. 

Best 

Emma

**Comment by SonniTost** [comment]
@nul800sebastiaan this fix is super relevant for our client - but they are running on Umbraco 10. Could this be cherry picked for 10.6?

**Comment by Zeegaan** [comment]
@SonniTost Yep I've cherry-picked it to the 10.6 release branch, so the fix will make it in 🚀
