### ISSUE TITLE
Rebuilding of External Index, following upgrade

### ISSUE THREAD

**Issue by pritesh-tailor** [umbraco/Umbraco-CMS#14560]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1

### Bug summary

Since we upgraded to the recent security patch release, going from 10.4.2, the external index doesn't seem to be indexing particular pages and we've been getting the following error, 'System.InvalidOperationException: Cannot assign value "20/01/2023 09:00:00" of type "System.String" to property "openingTime" expecting type "System.DateTime".' Full stack trace in the specifics. 

### Specifics

The indexes aren't being correctly built, either on start up or when you use the 'Rebuild index' functionality within 'Settings', 'Examine Management', 'External Index'. The issue can be bypassed when you 'Publish with descendants' on the parent content.  The full stack trace of the error is...

`System.InvalidOperationException: Cannot assign value "20/01/2023 09:00:00" of type "System.String" to property "openingTime" expecting type "System.DateTime".
   at Umbraco.Cms.Core.Models.Property.ThrowTypeException(Object value, Type expected, String alias)
   at Umbraco.Cms.Core.Models.Property.TryConvertAssignedValue(Object value, Boolean throwOnError, Object& converted)
   at Umbraco.Cms.Core.Models.Property.SetValue(Object value, String culture, String segment)
   at Umbraco.Cms.Core.PropertyEditors.NestedPropertyIndexValueFactoryBase`2.GetNestedResults(String keyPrefix, String culture, String segment, Boolean published, IDictionary`2 propertyTypeDictionary, TItem nestedContentRowValue, IEnumerable`1 availableCultures)+MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Umbraco.Cms.Core.PropertyEditors.NestedPropertyIndexValueFactoryBase`2.Handle(TSerialized deserializedPropertyValue, IProperty property, String culture, String segment, Boolean published, IEnumerable`1 availableCultures)
   at Umbraco.Cms.Core.PropertyEditors.JsonPropertyIndexValueFactoryBase`1.GetIndexValues(IProperty property, String culture, String segment, Boolean published, IEnumerable`1 availableCultures)
   at Umbraco.Cms.Infrastructure.Examine.BaseValueSetBuilder`1.AddPropertyValue(IProperty property, String culture, String segment, IDictionary`2 values, IEnumerable`1 availableCultures)
   at Umbraco.Cms.Infrastructure.Examine.ContentValueSetBuilder.GetValueSetsEnumerable(IContent[] content, Dictionary`2 creatorIds, Dictionary`2 writerIds)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Umbraco.Cms.Infrastructure.Examine.ExamineUmbracoIndexingHandler.DeferedReIndexForContent.<>c__DisplayClass6_0.<Execute>b__0(CancellationToken cancellationToken)
   at Umbraco.Cms.Infrastructure.HostedServices.QueuedHostedService.BackgroundProcessing(CancellationToken stoppingToken)`

### Steps to reproduce

1. Create a **'Page'** document type.
2. Create a **'Day'** document type' that will be used in a block list editor. The document type should be setup as an 'element type' and the 'Allow vary by culture' should **not** be set.
3. Add **two** date time properties of '**Opening Times**' and '**Closing Times**' to the 'Day' document type. The format of the date time properties should be configured as **'HH:mm'**
4. Create an '**Opening Times**' Block list, composed of the '**Day**' document type.
5. On the '**Page**' document type, give it the property '**Opening Times**' and assign it the newly created '**Opening Hours'** block list
6. In the content section, set up the '**page**' content and then add multiple '**day**' elements to the block list. The times can be configured with '09:00' and '17:00'.
7. Publish the content.
8. Go to 'Settings', 'Examine Management', 'External Indexes', 'Rebuild Index' and check the logs for the error highlighted above.
9. Clear the \umbraco\Data\TEMP\ExamineIndexes' and then re-start the application. Go to 'Settings', 'Examine Management', 'External Indexes' and attempt to search for the piece of content that was setup, using the content name'

### Expected result / actual result

Expected: Index runs without issue and you can search for the content by name within 'Settings', 'Examine Management', 'External Index' inside of Umbraco.
Actual: After a while, we sometimes get the message 'The process is taking longer than expected, check the Umbraco log to see if there have been any errors during this operation.' We can't find the content when you search for the content by name within 'Settings', 'Examine Management', 'External Index' inside of Umbraco.

**Comment by Zeegaan** [comment]
Heyo! 👋 
Unfortunately, I cannot reproduce this, below is an attached GIF of my setup.
Is there something wrong with my setup? 🤔 
![RebuildingExternal](https://github.com/umbraco/Umbraco-CMS/assets/70372949/ef0e109f-8355-4fdc-bb2a-b646708eebb6)

This is on 10.6.1
![image](https://github.com/umbraco/Umbraco-CMS/assets/70372949/05678d24-9f7c-4e25-8205-937061dbda51)

**Comment by pritesh-tailor** [comment]
Hi @Zeegaan ,

The language has been set to English (United Kingdom) in our Umbraco project. However, we have deployed the security patch, the odd thing is, it appears to be fine on the live and staging environments. It's just locally and on our test environment where the issue seems to still be there.

Thanks,
Pritesh

**Comment by pritesh-tailor** [comment]
I suspect it had something to do with a corrupted database, as a few database seems to be fine. I'll close this issue.
