### ISSUE TITLE
Could not load file or assembly exception when running integration test from Rider/Resharper

### ISSUE THREAD

**Issue by kedde** [umbraco/Umbraco-CMS#14598]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

umbraco 11.4.2

### Bug summary

I'm getting the following error when running an integration test using where I'm using JetBrains Rider 2023.1.4 I'm getting the following exception
        
``` 
OneTimeSetUp: System.IO.FileNotFoundException : Could not load file or assembly 'ReSharperTestRunner, Version=2.11.1.99, Culture=neutral, PublicKeyToken=5c492ec4f3eccde3'. The system cannot find the file specified.

-----

System.IO.FileNotFoundException : Could not load file or assembly 'ReSharperTestRunner, Version=2.11.1.99, Culture=neutral, PublicKeyToken=5c492ec4f3eccde3'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Umbraco.Cms.Core.Composing.ReferenceResolver.ResolveAssemblies()
   at Umbraco.Cms.Core.Composing.FindAssembliesWithReferencesTo.Find()
   at Umbraco.Cms.Core.Composing.DefaultUmbracoAssemblyProvider.get_Assemblies()
   at Umbraco.Cms.Core.Composing.TypeFinder.GetAllAssemblies()
   at Umbraco.Cms.Core.Composing.TypeFinder.GetFilteredAssemblies(IEnumerable`1 excludeFromResults, String[] exclusionFilter)
   at Umbraco.Cms.Core.Composing.TypeFinder.get_AssembliesToScan()
   at Umbraco.Cms.Core.Composing.TypeLoader.get_AssembliesToScan()
   at Umbraco.Cms.Core.Composing.TypeLoader.<>c__DisplayClass21_0`1.<GetTypes>b__0()
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternalLocked(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternal(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypes[T](Boolean cache, IEnumerable`1 specificAssemblies)
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilderExtensions.AddAllCoreCollectionBuilders(IUmbracoBuilder builder)
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder.AddCoreServices()
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder..ctor(IServiceCollection services, IConfiguration config, TypeLoader typeLoader, ILoggerFactory loggerFactory, IProfiler profiler, AppCaches appCaches, IHostingEnvironment hostingEnvironment)
   at Umbraco.Extensions.UmbracoBuilderExtensions.AddUmbraco(IServiceCollection services, IWebHostEnvironment webHostEnvironment, IConfiguration config)
   at umb.web.Startup.ConfigureServices(IServiceCollection services) in C:\git\umbraco-upgrade-project\src\umb.web\Startup.cs:line 37
   at Store.Core.Tests.TestIntegrationServiceProvider..ctor() in C:\git\umbraco-upgrade-project\tests\Store.Core.Tests\TestIntegrationServiceProvider.cs:line 36
   at Store.Core.Tests.ProductServiceTests..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Rider is trying to use  'ReSharperTestRunner' and the TypeFinder class is not filtering the DLL out(only the 32 bit version) see. Would it possible to remove the 32 from KnownAssemblyExclusionFilter to exclude any ReSharperTestRunner dlls?

[TypeFinder.cs:37](https://github.com/umbraco/Umbraco-CMS/blob/1527b2577e7273157cfede70444c65f838a87225/src/Umbraco.Core/Composing/TypeFinder.cs#L37)

Don't know it is because of I'm using a new version of Rider and resharper or it the configuration of my test project.  

### Specifics

Running the test is not possible from Rider and resharper - It's possible using the CLI and running "dotnet test" or using Visual studios built in test explorer. 

### Steps to reproduce

Create a new test project that reference an umbraco project, the running the test that uses the startup file in the umbraco project - something like this:

```
        var services = new ServiceCollection();
        var root = @"C:\git\umbraco-upgrade-project\src\umb.web";
        IWebHostEnvironment testWebHostEnvironment = new TestWebHostEnvironment
        {
            ApplicationName = "umb.web",
            ContentRootPath = root,
            EnvironmentName = "Development",
            WebRootPath = @"C:\path\umb.web\wwwroot\",
            ContentRootFileProvider = new PhysicalFileProvider(root),
            WebRootFileProvider = new CompositeFileProvider()
        };
        
        IConfiguration config = new ConfigurationBuilder()
            // .SetBasePath(root)
            .AddJsonFile("appsettings.json")    
            // root + Path.DirectorySeparatorChar +
            .Build();

        services.AddSingleton(config);
        services.AddSingleton(testWebHostEnvironment);
        var startup = new Startup(testWebHostEnvironment, config);
        startup.ConfigureServices(services);
        
        ServiceProvider = services
            .BuildServiceProvider();
                    var productService = ServiceProvider.GetService<IProductService>();

```

### Expected result / actual result

Should be possible to run from Rider and resharper

**Comment by kjac** [comment]
Hi @kedde,

I see no problem with that 😄 as long as the tests still run. And I reckon they would without the 64bit version of the ReSharper test runner too 😆 

You're more than welcome to submit a PR. I believe it can be fixed by removing "32" from the "ReSharperTestRunner32" entry, since we look for assemblies that starts with the given entries. A PR will implicitly prove if the tests can run without the test runner 👍

**Comment by Amalie-Wowern** [comment]
Looking at this

**Comment by mikecp** [comment]
H @kedde ,

It would be great if you could have a quick look at the PR from @Amalie-Wowern to see if it solves your problem  😁

Cheers!

**Comment by umbracocommunity** [comment]
This issue has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/xunit-v3-webapplicationfactory-and-umbraco-how-to-make-this-work/4553/1

**Comment by benmccallum** [comment]
It's nasty, but it does let you work around having to wait for Umbraco to keep extending the disallow list which is fragile. 😅 

Their `TypeFinder` class currently has a TODO to kill it off, so no point beating a dead horse, and when it goes, will just need to remove this (or you could try-catch it, but I'd prefer it to fail loudly for a cleanup).

```csharp
using System.Reflection;
using System.Runtime.CompilerServices;
using Umbraco.Cms.Core.Composing;

internal static class ModuleInitializer
{
    [ModuleInitializer]
    internal static void Initialize()
    {
        PatchUmbracoTypeFinderExclusions();
    }

    // Umbraco's TypeFinder.KnownAssemblyExclusionFilter has NUnit/Moq entries but no xunit/Verify
    // entries (cf. umbraco/Umbraco-CMS#14906 for the pattern). ReferenceResolver.GetReferences()
    // calls Assembly.Load() on every referenced asm not in the filter — fails on xunit.v3 runtime
    // assets that aren't listed in deps.json. Drop this once Umbraco's filter covers xunit.
    // IMPORTANT: If Umbraco kill this TypeFinder off like they've indicated, hopefully this workaround
    // can just be removed
    private static void PatchUmbracoTypeFinderExclusions()
    {
        var field = typeof(TypeFinder).GetField(
            "KnownAssemblyExclusionFilter",
            BindingFlags.Static | BindingFlags.NonPublic);
        if (field?.GetValue(null) is not string[] current)
        {
            return;
        }

        // Add anything your test project is loading that's choking things up
        var extended = current
            .Concat(["xunit,", "xunit.", "Verify,", "Verify."])
            .ToArray();

        field.SetValue(null, extended);
    }
}

```
