### ISSUE TITLE
Issuu embed does not work

### ISSUE THREAD

**Issue by jojo308** [umbraco/Umbraco-CMS#14759]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.2

### Bug summary

The Issuu oembed provider does not work. When retrieving data via the embed option in a richtext editor, it displays the following error: "Could not embed media - please ensure the URL is valid".

I also tested this on version 12.1.2 and 10.6.1 and it doesn't work on those versions either.

### Specifics

By checking the logs, you can see the following stack trace caused by the Issuu oembed provider:

`System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at Umbraco.Cms.Core.Media.EmbedProviders.OEmbedProviderBase.GetXmlResponse(String url)
   at Umbraco.Cms.Core.Media.EmbedProviders.Issuu.GetMarkup(String url, Int32 maxWidth, Int32 maxHeight)
   at Umbraco.Cms.Web.BackOffice.PropertyEditors.RteEmbedController.GetEmbed(String url, Int32 width, Int32 height)`

After some debugging I discovered the response in the [DownloadResponse](https://github.com/umbraco/Umbraco-CMS/blob/v11/dev/src/Umbraco.Core/Media/EmbedProviders/OEmbedProviderBase.cs#L53) method is always `""` because every request to issuu.com returns a 406 error. I tried to create my own oembed provider ([IssuuEmbed.cs](https://github.com/umbraco/Umbraco-CMS/files/12501808/IssuuEmbed.txt)) and I managed to get a 200 response. However, the content is not displayed on the actual page.

### Steps to reproduce

1. Click the embed option in a richtext editor
2. Paste any valid URL from an Issuu source (e.g. https://issuu.com/educationry/docs/educationry-a40529.docx)
3. Click retrieve
4. The Issuu provider is not able to retrieve the content

### Expected result / actual result

The Issuu content should be displayed in the preview and on the page it is embedded in.

**Comment by andr317c** [comment]
Hey!
I'm just letting you know I was able to reproduce your issue. I have linked this issue in a PR which fixes the issue! 😄

**Comment by jojo308** [comment]
Hi!
That's great to hear. Thanks for fixing the issue.

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14777
