### ISSUE TITLE
'Umbraco.Commerce.Cms.Web.Api.Storefront.ValueConverters.StorefrontPricePropertyValueConverter' has already been detected as a converter for that property, and only one converter can exist for a property.

### ISSUE THREAD

**Issue by konius** [umbraco/Umbraco-CMS#14760]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.1.2

### Bug summary

Umbraco models fail to generate and there is a runtime error after upgrading to latest Umbraco Commerce 12.1.0.

```
Last generation failed with the following error:
Failed to build models.
Type 'Umbraco.Commerce.Cms.ValueConverters.PricePropertyValueConverter' cannot be an IPropertyValueConverter for property 'price' of content type 'productOptions' because type 'Umbraco.Commerce.Cms.Web.Api.Storefront.ValueConverters.StorefrontPricePropertyValueConverter' has already been detected as a converter for that property, and only one converter can exist for a property.

at Umbraco.Cms.Core.Models.PublishedContent.PublishedPropertyType.InitializeLocked()
at Umbraco.Cms.Core.Models.PublishedContent.PublishedPropertyType.Initialize()
at Umbraco.Cms.Core.Models.PublishedContent.PublishedPropertyType.get_ModelClrType()
at Umbraco.Cms.Infrastructure.ModelsBuilder.UmbracoServices.GetTypes(PublishedItemType itemType, IContentTypeComposition[] contentTypes)
at Umbraco.Cms.Infrastructure.ModelsBuilder.UmbracoServices.GetAllTypes()
at Umbraco.Cms.Infrastructure.ModelsBuilder.Building.ModelsGenerator.GenerateModels()
at Umbraco.Cms.Web.BackOffice.ModelsBuilder.ModelsBuilderDashboardController.BuildModels()
```

![image](https://github.com/umbraco/Umbraco-CMS/assets/3933562/c6d94d8f-871d-47e2-a330-01ed34fb19c1)

### Specifics

Umbraco CMS 12.1.2
Umbraco Commerce 12.1.0

### Steps to reproduce

Install both versions.

### Expected result / actual result

Site to run without any errors.

**Comment by mattbrailsford** [comment]
Thanks for reporting @konius I believe I know what the issue is here and will take a look at a solution.

In the meantime, I think a workaround might be to register the StorefrontAPI dependencies as documented here https://docs.umbraco.com/umbraco-commerce/reference/storefront-api#register-the-storefront-api-dependencies and that should resolve it as installing the storefront API dependencies should remove the old value converters.
