### ISSUE TITLE
Deleting members with multiple external login providers throws sql exception

### ISSUE THREAD

**Issue by MartenOlofsson** [umbraco/Umbraco-CMS#14841]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.1.1

### Bug summary

I have multiple external login providers enabled. We allow users to login using either of of those login providers no matter what was used the first time. So far everything works. When deleting a member with more than one present in the umbracoExternalLogin database table an error is thrown:

`Microsoft.Data.SqlClient.SqlException (0x80131904): Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.`

If I manually remove one of the items in the umbracoExternalLogin table, the member can be removed as expected.

### Specifics

![image](https://github.com/umbraco/Umbraco-CMS/assets/1032662/d46bed5f-7b78-404d-8463-d051bde61a52)

### Steps to reproduce

Create a member with two or more enabled loginProviders.
Delete that member (using the umbraco UI or via IMemberManager DeleteAsync) - an error is thrown (IdentityErrorUserStore)

### Expected result / actual result

Expected: The member is expected to be deleted without any issues.
Actual: The member is not deleted and an SQL error is thrown.

**Comment by kjac** [comment]
Hi @MartenOlofsson,

Thank you for reaching out 👍 

I can't seem to reproduce this. I've tried both V10 and V12. 

Given a member with these entries in `umbracoExternalLogin`:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/0c3fee9d-ab53-4b35-84b2-a4a9a58d8350)

...the member deletes just fine from the backoffice, and upon deletion the entries are gone from the table.

Can you shed a little more light on how to reproduce this?

**Comment by MartenOlofsson** [comment]
@kjac thanks for replying!

I'm using umbraco 12.1.1 - it seems that there has been recent changes to member specific functions recently, are you running that version also?

This is my database table:

![image](https://github.com/umbraco/Umbraco-CMS/assets/1032662/e7e107ca-670a-4196-85f3-9a10fdf54d4c)

And if I remove one of these entries the member is deleted without issues. 

(My cmcMember table only contains one item.)

**Comment by MartenOlofsson** [comment]
A little more context:

This is the sql that's causing the issue:

`delete FROM umbracoExternalLoginToken WHERE externalLoginId = (SELECT id FROM umbracoExternalLogin WHERE userOrMemberKey = (SELECT uniqueId from umbracoNode where id = '1244'))` 

Executed in "PersistDeletedItem" in "EntityRepositoryBase"

since I have two umbracoExternalLogin entries in my database the subquery:

`(SELECT id FROM umbracoExternalLogin WHERE userOrMemberKey = (SELECT uniqueId from umbracoNode where id = '1244'))`

will return two id's which is the root if the issue I'm experiencing. 

This would work:

`delete FROM umbracoExternalLoginToken WHERE externalLoginId in (SELECT id FROM umbracoExternalLogin WHERE userOrMemberKey = (SELECT uniqueId from umbracoNode where id = '1244'))`

**Comment by kjac** [comment]
Hi @MartenOlofsson,

I have tested on the latest V10 and V12. Perhaps an upgrade to V12.2 fixes your issue?

**Comment by MartenOlofsson** [comment]
@kjac The code in the MemberRepository has not been changed since april.

It's these two rows that seems to be problematic, at least for me:

`$"DELETE FROM {Constants.DatabaseSchema.Tables.ExternalLoginToken} WHERE externalLoginId = (SELECT id FROM {Constants.DatabaseSchema.Tables.ExternalLogin} WHERE userOrMemberKey = (SELECT uniqueId from {Constants.DatabaseSchema.Tables.Node} where id = @id))",
            $"DELETE FROM {Constants.DatabaseSchema.Tables.ExternalLogin} WHERE userOrMemberKey = (SELECT uniqueId from {Constants.DatabaseSchema.Tables.Node} where id = @id)",`

Line 551 in "MemberRepository".

Perhaps I'm missing something but I cannot see how that code could ever work if there are more than one external logins connected to the user?

Best,
Mårten

**Comment by kjac** [comment]
Hi again @MartenOlofsson,

Can you trigger the issue by manually adding additional lines to `umbracoExternalLogin` in your DB?

**Comment by MartenOlofsson** [comment]
Sorry for the late reply.

Yes I can!

**Comment by sebastian-eksponent** [comment]
We've also started experiencing this issue with a platform with multiple providers.
Has there been more research done on this outside of this ticket and maybe a workaround explored?

Our solution is on V13 and the behavior is the same as Marten describes.
The query shown in comment: https://github.com/umbraco/Umbraco-CMS/issues/14841#issuecomment-1744715171, returns more results causing the rest to fail.

<img width="601" height="470" alt="Image" src="https://github.com/user-attachments/assets/6b3bdd99-f172-4cd2-a3fb-5c4400095ea0" />

<p></p>

<img width="725" height="746" alt="Image" src="https://github.com/user-attachments/assets/b9c4c1d7-7bcb-4b3c-be9a-69893dfece67" />

<p></p>

<details><summary>Umbraco Server Info</summary>

```
Category | Data
-- | --
Server OS | Debian GNU/Linux 12 (bookworm)
Server Framework | .NET 8.0.21
Default Language | da-DK
Umbraco Version | 13.13.0
Current Culture | en-US
Current UI Culture | en-US
Current Webserver | Kestrel
Models Builder Mode | Nothing
Runtime Mode | Production
Debug Mode | False
Database Provider | Microsoft.Data.SqlClient
Current Server Role | Single
Browser | Firefox 146.0
Browser (user agent) | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:146.0) Gecko/20100101 Firefox/146.0
``` 

</details> 

<p></p>

<details><summary>Delete Member StackTrace</summary>

```
Microsoft.Data.SqlClient.SqlException (0x80131904): Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.EntityRepositoryBase`2.PersistDeletedItem(TEntity entity)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.MemberRepository.PersistDeletedItem(IMember entity)
   at Umbraco.Cms.Core.Cache.DefaultRepositoryCachePolicy`2.Delete(TEntity entity, Action`1 persistDeleted)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.EntityRepositoryBase`2.Delete(TEntity entity)
   at Umbraco.Cms.Core.Services.MemberService.DeleteLocked(ICoreScope scope, IMember member, EventMessages evtMsgs, IDictionary`2 notificationState)
   at Umbraco.Cms.Core.Services.MemberService.Delete(IMember member)
   at Umbraco.Cms.Web.BackOffice.Controllers.MemberController.DeleteByKey(Guid key)
   at lambda_method13380(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
ClientConnectionId:REDACTED
Error Number:512,State:1,Class:16
ClientConnectionId before routing:REDACTED
Routing Destination:REDACTED
``` 

</details>

**Comment by MartenOlofsson** [comment]
@sebastian-eksponent I don't know if this is still relevant since the project where I got this issue is not alive anymore. What I ended up doing was this:

```
// TODO: This should be removed and instead fixed in the umbraco project. See: https://github.com/umbraco/Umbraco-CMS/issues/14841
public class SqlFixedMemberRepository : MemberRepository
{
    public SqlFixedMemberRepository(IScopeAccessor scopeAccessor, AppCaches cache,
        ILogger<MemberRepository> logger, IMemberTypeRepository memberTypeRepository,
        IMemberGroupRepository memberGroupRepository, ITagRepository tagRepository,
        ILanguageRepository languageRepository, IRelationRepository relationRepository,
        IRelationTypeRepository relationTypeRepository, IPasswordHasher passwordHasher,
        PropertyEditorCollection propertyEditors,
        DataValueReferenceFactoryCollection dataValueReferenceFactories,
        IDataTypeService dataTypeService, IJsonSerializer serializer,
        IEventAggregator eventAggregator,
        IOptions<MemberPasswordConfigurationSettings> passwordConfiguration) : base(scopeAccessor,
        cache, logger, memberTypeRepository, memberGroupRepository, tagRepository,
        languageRepository, relationRepository, relationTypeRepository, passwordHasher,
        propertyEditors, dataValueReferenceFactories, dataTypeService, serializer, eventAggregator,
        passwordConfiguration)
    {
    }

    protected override IEnumerable<string> GetDeleteClauses()
    {
        var list = new List<string>
        {
            "DELETE FROM umbracoUser2NodeNotify WHERE nodeId = @id",
            "DELETE FROM umbracoUserGroup2Node WHERE nodeId = @id",
            "DELETE FROM umbracoUserGroup2NodePermission WHERE nodeId = @id",
            "DELETE FROM umbracoRelation WHERE parentId = @id",
            "DELETE FROM umbracoRelation WHERE childId = @id",
            "DELETE FROM cmsTagRelationship WHERE nodeId = @id",
            "DELETE FROM " + Constants.DatabaseSchema.Tables.PropertyData +
            " WHERE versionId IN (SELECT id FROM " + Constants.DatabaseSchema.Tables.ContentVersion +
            " WHERE nodeId = @id)",
            $"DELETE FROM {Constants.DatabaseSchema.Tables.ExternalLoginToken} WHERE externalLoginId in (SELECT id FROM {Constants.DatabaseSchema.Tables.ExternalLogin} WHERE userOrMemberKey = (SELECT uniqueId from {Constants.DatabaseSchema.Tables.Node} where id = @id))",
            $"DELETE FROM {Constants.DatabaseSchema.Tables.ExternalLogin} WHERE userOrMemberKey = (SELECT uniqueId from {Constants.DatabaseSchema.Tables.Node} where id = @id)",
            "DELETE FROM cmsMember2MemberGroup WHERE Member = @id",
            "DELETE FROM cmsMember WHERE nodeId = @id",
            "DELETE FROM " + Constants.DatabaseSchema.Tables.ContentVersion + " WHERE nodeId = @id",
            "DELETE FROM " + Constants.DatabaseSchema.Tables.Content + " WHERE nodeId = @id",
            "DELETE FROM umbracoNode WHERE id = @id"
        };
        return list;
    }

```

Then I just registered IMemberRepository -> SqlFixedMemberRepository in the IOC.

**Comment by sebastian-eksponent** [comment]
Thank you @MartenOlofsson!

Will definitely give it a try.

**Comment by AndyButland** [comment]
Fixed via https://github.com/umbraco/Umbraco-CMS/pull/21625 for 17.2.

**Comment by sebastian-eksponent** [comment]
Awesome!

@AndyButland will this fix be back-ported to V13 as well or only kept for V17?

**Comment by AndyButland** [comment]
We aren't intending that @sebastian-eksponent, as 13 is now in "security phase" for support (see schedule [here](https://umbraco.com/products/knowledge-center/long-term-support-and-end-of-life/)).
