### ISSUE TITLE
[BUG]: Couldn't complete unattended migration from Umbraco 12 to Umbraco 14. 

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco-CMS#14861]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco 14 Preview 3

### Bug summary

Having run into #14860 attempting an attended migration I switched to an unattended one.  That ran, but I got an error with one of the migration steps.  There looks to be an issue with the [AddGuidsToUserGroups migration](https://github.com/umbraco/Umbraco-CMS/blob/v14/dev/src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/AddGuidsToUserGroups.cs).

### Specifics

Error reported in the UI is:

```
BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details. -> Umbraco.Cms.Core.Exceptions.BootFailedException: An error occurred while running the unattended upgrade. The database configuration failed with the following message: The given key 'ID' was not present in the dictionary.
```

And in the logs:

```
System.Collections.Generic.KeyNotFoundException: The given key 'ID' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NPoco.Database.<>c__DisplayClass233_0.<GetPrimaryKeyValues>b__2(String x)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](TSource[] source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at NPoco.Database.GetPrimaryKeyValues(Database database, PocoData pocoData, String primaryKeyName, Object primaryKeyValueOrPoco, Boolean isPoco)
   at NPoco.Database.UpdateStatements.PrepareUpdate(Database database, PocoData pd, String tableName, String primaryKeyName, Object poco, Object primaryKeyValue, IEnumerable`1 columns)
   at NPoco.Database.UpdateImpAsync(String tableName, String primaryKeyName, Object poco, Object primaryKeyValue, IEnumerable`1 columns, Boolean sync)
   at NPoco.AsyncHelper.RunSync[T](Task`1 task)
   at NPoco.Database.Update(String tableName, String primaryKeyName, Object poco, Object primaryKeyValue, IEnumerable`1 columns)
   at NPoco.Database.Update(Object poco, Object primaryKeyValue, IEnumerable`1 columns)
   at NPoco.Database.Update(Object poco)
   at Umbraco.Cms.Infrastructure.Migrations.Upgrade.V_14_0_0.AddGuidsToUserGroups.MigrateSqlServer()
   at Umbraco.Cms.Infrastructure.Migrations.Upgrade.V_14_0_0.AddGuidsToUserGroups.Migrate()
   at Umbraco.Cms.Infrastructure.Migrations.MigrationBase.Run()
   at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.RunMigration(Type migrationType, MigrationContext context)
   at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.RunUnscopedMigration(Type migrationType, MigrationPlan plan)
at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.RunMigrationPlan(MigrationPlan plan, String fromState)
```

If I run a database script like the following to make the updates, and thus effectively skip this migration step, the migration as a whole works OK.

```
ALTER TABLE umbracoUserGroup
ADD [key] uniqueidentifier NOT NULL DEFAULT NEWID()
GO

CREATE NONCLUSTERED INDEX IX_umbracoUserGroup_userGroupKey ON dbo.umbracoUserGroup (
	[key]
) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

UPDATE umbracoUserGroup SET [key] = 'E5E7F6C8-7F9C-4B5B-8D5D-9E1E5A4F7E4D' WHERE userGroupAlias = 'admin'
UPDATE umbracoUserGroup SET [key] = '9FC2A16F-528C-46D6-A014-75BF4EC2480C' WHERE userGroupAlias = 'writer'
UPDATE umbracoUserGroup SET [key] = '44DC260E-B4D4-4DD9-9081-EEC5598F1641' WHERE userGroupAlias = 'editor'
UPDATE umbracoUserGroup SET [key] = 'F2012E4C-D232-4BD1-8EAE-4384032D97D8' WHERE userGroupAlias = 'translator'
UPDATE umbracoUserGroup SET [key] = '8C6AD70F-D307-4E4A-AF58-72C2E4E9439D' WHERE userGroupAlias = 'sensitiveData'
GO
```

### Steps to reproduce

Upgrade an Umbraco 12 site to Umbraco 14 using unattended migrations.

### Expected result / actual result

Migration should complete without error.

**Comment by elit0451** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14945
