### ISSUE TITLE
Webp Images exported from Photoshop throwing error;

### ISSUE THREAD

**Issue by vaskinhu** [umbraco/Umbraco-CMS#15007]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.7.0

### Bug summary

Hi Guys,

When images in .webp format are exported from Photoshop and uploaded into Umbraco an error is thrown and causes the Type, Width, Height, Size, Type not to be fulfilled;

Attached is a zip with an example image:

[autousados-senhoracarro-i-hero-products-922x1144.zip](https://github.com/umbraco/Umbraco-CMS/files/13040427/autousados-senhoracarro-i-hero-products-922x1144.zip)

### Specifics

`SixLabors.ImageSharp.ImageFormatException: Unexpected chunk followed VP8X header
   at SixLabors.ImageSharp.Formats.Webp.WebpThrowHelper.ThrowImageFormatException(String errorMessage)
   at SixLabors.ImageSharp.Formats.Webp.WebpDecoderCore.ReadVp8XHeader()
   at SixLabors.ImageSharp.Formats.Webp.WebpDecoderCore.ReadVp8Info()
   at SixLabors.ImageSharp.Formats.Webp.WebpDecoderCore.Identify(BufferedReadStream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Identify(IImageDecoderInternals decoder, Configuration configuration, Stream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.Webp.WebpDecoder.Identify(Configuration configuration, Stream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Image.InternalIdentity(Stream stream, Configuration config, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Image.<>c__DisplayClass108_0.<Identify>b__0(Stream s)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration configuration, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Identify(Configuration configuration, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Identify(Configuration configuration, Stream stream)
   at Umbraco.Cms.Infrastructure.Media.ImageSharpDimensionExtractor.GetDimensions(Stream stream)
   at Umbraco.Cms.Core.Media.UploadAutoFillProperties.SetProperties(IContentBase content, ImagingAutoFillUploadField autoFillConfig, String filepath, Stream filestream, String culture, String segment)
   at Umbraco.Cms.Core.Media.UploadAutoFillProperties.Populate(IContentBase content, ImagingAutoFillUploadField autoFillConfig, String filepath, String culture, String segment)`

### Steps to reproduce

Upload an image in webp format exported from photoshop;

**Comment by vaskinhu** [comment]
I tested it on Umbraco V12.2.0 and it works, this may be because you guys updated SixLabors.ImageSharp package on that version.

**Comment by Zeegaan** [comment]
@vaskinhu I was just about to type this, this was a bug with ImageSharp itself, and is fixed in their 3.0 version 🚀 
We cannot upgrade this for v10, as that would be breaking, and as such my solution would be to upgrade 😁
