### ISSUE TITLE
Backofftice timout exception alert

### ISSUE THREAD

**Issue by nick-hoang** [umbraco/Umbraco-CMS#15079]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.2.0

### Bug summary

After logged in to the Backoffice and inactive for over 20 minutes, I got this exception alert when select a different node
![Screenshot_2](https://github.com/umbraco/Umbraco-CMS/assets/4602123/7c804af3-a0f9-4edd-979c-75439988b849)

it looks pretty bad for the client perspective I think. 

### Specifics

/umbraco
Not browser specific

### Steps to reproduce

 Access /umbraco v12.2.0
    Login.
    Wait for more than 20 minutes
    Select a different node

### Expected result / actual result

EXPECTED RESULT - No alerts, just redirect user to the login form or display a nicer alert box
ACTUAL RESULT - Alert error box be show that looks like a system error happened

**Comment by andr317c** [comment]
Hey! Thanks for reporting this issue! I tried reproducing on V12.2.0, but I was redirected to the login page without getting any error message. Can you try to reproduce this on a clean install? 😄

**Comment by nick-hoang** [comment]
Hi @andr317c You're right, it doesn't happen on a clean v12.2.0 install but happen on my app, below is my exception details I got:
`System.ArgumentNullException: Value cannot be null. (Parameter 'user')
   at Umbraco.Cms.Core.Security.ContentPermissions.CheckPermissions(Int32 nodeId, IUser user, IContent& contentItem, IReadOnlyList`1 permissionsToCheck)
   at Umbraco.Cms.Web.BackOffice.Authorization.ContentPermissionsQueryStringHandler.IsAuthorized(AuthorizationHandlerContext context, ContentPermissionsQueryStringRequirement requirement)
   at Umbraco.Cms.Web.BackOffice.Authorization.MustSatisfyRequirementAuthorizationHandler`1.HandleRequirementAsync(AuthorizationHandlerContext context, T requirement)
   at Microsoft.AspNetCore.Authorization.AuthorizationHandler`1.HandleAsync(AuthorizationHandlerContext context)
   at Microsoft.AspNetCore.Authorization.DefaultAuthorizationService.AuthorizeAsync(ClaimsPrincipal user, Object resource, IEnumerable`1 requirements)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthorizeAsync(AuthorizationPolicy policy, AuthenticateResult authenticationResult, HttpContext context, Object resource)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 114
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, Boolean retry)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

HEADERS
=======
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Connection: close
Cookie: UMB_UPDCHK=1; umb_installId=4beb61b9-65eb-43b4-a277-0b702827ce63; .AspNetCore.Antiforgery.64nf2yIB94k=CfDJ8GDOm7OIXZJNu0xfL-GAc0jLtvj9BlnSsS22gv8LITj6AEDN0sFDk_Kk6VLSR3xqBqCNcLD7xdo4wp600nLPP7NnsPe-_n1Ko3SV_5KeLhxMexOxA17VY-a78CDYUZ4QbyVZKU1DwyzvPWyNpTtN1xA; .AspNetCore.Antiforgery.3wXncq8Yxa4=CfDJ8L5oBINkDipKod7TMWl_EETRecpEr4W6OtndwVkKV0wlUJREFSAOAsHB9N7ue21QQ7WaG44Y0roly2VqDi1_0qVMZEWM_m7a1VK1uEF9anJ7b4tXb2__xhbKntfC7KlV69TJUKng8t1lb58nqm1zFP8; UMB_SESSION=CfDJ8FRM9ip4yjpNk03CwI%2BDagKmpKdlF%2FKcUM1F15npsujHB%2BSSp8D28T79GBYsz8fuD%2Fw%2FdrC%2BcKtbz%2BmQPUmhTKp0uGxayhSMyTxhAPCs3GblZW8kp0tBHIq2lAkLoTB6%2B2KnpGSu%2BgdHfwvVkec1Sx6xpAIksZp4%2BPdN9%2BfnocPd; Easybrew_UCONTEXT=CfDJ8FRM9ip4yjpNk03CwI-DagJPKHWIRvenf-ZjpTrxRkTn3WCVbRrknN-iaEBs1iyC2EL9ClrQntglqp6ppvrJtqb_UFXkRKrI06wR_QBfPRPbW5Eq7eDLE1kKwtK7LGSuKXWLXVJwvCll5CBvJCgRbCFB1o0vuy1JWOd1rKbEPpCTXUTgOlaZWLlnTMKmw2NtJoEgyT-WOinhdSqIfoaIOaexv4ZEhrBG6XBdfIyl3hqU2ntOtO8onBPrvZbdXLuN5p5QKN50Wk9ow7KKQg1RhS2_Um5sKbIKn-WKUMnJkww8xJKlT7sfL2TbWTYYN8ZwfFLjdgL2I8L9rFUykReNQo-z_IIdxaXNe8bsV16flL5Khux8QIYwPH8hhMoYXwiHtb6EQPAJ7jFh6Z2P75cNiTm6D3qSSD7ugKrzCMMcp02Nfio-QCiSyi5RZSZ_tOGtFUquY7out_0X26RY0a-K3F_ECRijuBPc9VsyhVd1_7saBWWq8IAVzfQnUgmBUEyH9kaugTIdYxrgbslnpwzv4tmBoGzZQjzEwV5EUPYqDwDAYPIyIR0iW_zrPd8QAL2KGVW2jq08hwZQdGBYVUHJn6nLnhpn3TU3PUcnah9O4Omk5K_Akb8Kr-sVjcYqj6BSGtcsHWaBZltTu1YIlP_XQRT4ZrPgwz6yRSCXKJIKzkyMF5sFgDY7AOe-xayMR19pYUOaU63uKyp3O2TAtIm_Lb1ysjTt1t5IAIn5J9JcB3IVanf_CmDfUcBNDSWVBJ6blUpsjw6B5kCxVGNxAXxJrwtb28LHBKBbudyR2DqqV-2sV0ZxGckjiSO3nJ9H0O6SvgaNSX4jaW6XHqk1P1XMGX-ohPkoNnwI4tCNVP2ITvf42D2QKDX5uM1NUvWk70tt1MKMS0bAN6CXE591A7ASw-ESSGDyq0QhtXHziyzuZfnjUZvbRLae1gk3-3aqnh8_PbCUK-iFut_Ilx0iicqOeY8gMRTVhxcuh1ZaDINs2SElLruM69Ao2Xzn1mSBpqpT4bqw064NZPQyTajBgwrNB2k967o-gzZaU5GJaoc8G7ATTs_GaFC8GUfXeCWGQ4LxsjOQnNjoAuobJNCbOagaDVEE02BUIS-uS6o-VLs4QsivYIBS2Ckhv07VMx-2xUY1tP6SxL_veioZnvsBdy7HCuuagJE6Kxlqk-PRXH38b3j1AY9tcZ0-Vq7ZIRGv7GEgWqymdY7EwDg4uePJHUUlkDD7LgtmguFexm1BGWC0F0AYRKbUhy6mvuJFDIgTVzLLu6ru4G21i_cMBFGJWMXxjHfddd3OHbdgmuuC-iB5Npxx9ISsrHTfzXIYR-CzD5dbkgRtdlTkV5W79u3LEET_UfZTC-ffaeQu0idrEsb4C_mRJPY0WKLdpO1Defeh_s2Kas8HewbL4pkQUd5D1mOjsf0mHURDeHpdbHnhWPzXHm6GHrwU4QwSsjTD92_PT-Em3nM45M7I_w46WoirsQRhFpw4XL6PFbdh3vvdw9GILqtuvn-4KyWhpgT0-lebylvtEY0ZJo7MBfIPqz1FLrOUqbKJmSFxN5gm6BiymcP3BiwXlM6zQ4XFU2uiGtLgrDdp9B_g-JLXteO_8qscqcjJa8wB4E710C0kfvDX6AxDt7AMeGrlhL2-twGrZ7awTc8R06-TMZGBqKDOPas0ZueMAxmxRxaxrbAnR0qpdsdmSxRFvVNWgqVNKosAiPYa0ZyeRN_WUSciLNh9mi23m5QetC_IC3_iCVfmppZcrIGA6Mg9qBRCBhOit8P_PTOkzDRRb-8WJPFIlXtQmtR8KOIiABdD8PzIM_vJvKkW6pyRn4BGM8zCGAugR11-HUiG5Y69xTbQruB1gwQkD4ZGILiHKIup7nqw8Sj-7wkV-i1rmj-GVftYutiK55lD3Gv5TUyCjNPIGfo-G0nPkoxZd9ppmLXX0NsFQprdrBIP6E_n24kvIs_XVpa5GUKGJOgFfdufYZWtlKlhx0JqRjU-gI-uld5tqqx5GqV1z7_gtOOhhIxGBbLzySOIQU6oHgqssyD-ocTPQkDfY1nndTPJ6MjYL8Te2VuTvDQ9IP-BEqqsZyGxCnddHbLg312AMfKAkn7tn3sSH94uaSzRj6rm90hEfOYLAtES3nAa5C1hIyCGWI-qwojO6UDdbHRMD34_O1E5AzQ64qvElAUxnDwTYzSiePfPN2BEX77HZ4NfYkfOqkYks3OXBZ_7bPJFet-lAJ2efPrpGymTJw0pKJImx6Ut0Wo3QkuzkUP-dRGYAwFeatKcLAEHPR2bcYpe-K4rRZzlwWzL1khFaHFPS7_hUJNZvGLdmHLY2V-4Dfh3y2Gly7ufhNBDRj4zmf2rfAu43p6Om0X-XVUW5x_51yTKrLPfe_WdyWQx2I56Un3u7dhHJulxyhk6zmzvFyzPu0Z4U_jCeR6frQuqCwdfXS51GumuhsGlbHUuPwJWv-4xwKsJDjZVhCncTuCE2Y3mbuNyZRxCBT_9v9IiX0SZo8ibkyY3_iNzK8ZbLpD7y2GePNvsWVhieK1LQh6z_z2ZBc9NjulkLXeggyX7ux3-4Uo158sBTQgI8HGO9dqXamLJra02qbCePkDJ9vF-wgd9OON_rsEZFaWu-aSBW-9BkFzyaU8uqxbDRyLGp7nOFKYvD0t8DAKWC51aKFkIfJDgY_NGSPNgRhq7I9VNk1JpaQ5PRdwrFZDBBKdyIthOtLXs74GPT6m7fTreQfee0Ex8C3u-hjNLCCPChCRbswCstlxbKpZfyf5_WSWVDmMzQj5lyS2hdMiqcqYEMzvypupWPLjU3kkHks61WqveVQfTPV2uoSmJLoE9MXhZiiuwMZl6C7wjdyN6ie1wGJ94d4kP_Vo6GJuKep8aExrhiRllJLFDdS3oTJ2TTJcFr6icdCzyo_S3RdxEYrvO7o4I0dlu16v76epYkEOvFiPnkm5TBzRbAFxdlUDZinH846jxOxaBxWY7f-UbrA4DcV2otmbJSYGuA0Oreb1pV0Wg76l2MIR7XmTkh_a-psnQz7vGR55ZLM5J4nwS_v1y7UrMtC7lOGfc6y-HuA; UMB-XSRF-V=CfDJ8F4VwpWcK8JNt1NtoQUgHcxe1fmZeB01gwq_s1bqOcLhxWCp-O9qnn0FixldI8y84A4szyBgWkl9c-PoZ9T2Qp_ji2_7B-H1KlrFEbP6Nj7J9xl9Ui2iUC46oRHrtVloYnk9lZ7YqEpUyYMsSOWWNE4; UMB-XSRF-TOKEN=CfDJ8F4VwpWcK8JNt1NtoQUgHcyS4MueC-v_97xMadDsAcypzA3TQIUwt5Zxs6j3mD57dNTN2DRGEbh7f1Z_d0n-9TP0MHQlGYxEDmG0O1rWbQNJLFLBtbCezAlRAhW8-KKAqtPdyBOLWLmnd5OgtiIjotYwtqk_IsG8smEtwPGCyo39tMmlFZnVrisKW9l0qZcPEw
Host: localhost:44367
Referer: https://localhost:44367/umbraco
TE: trailers
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0
x-requested-with: XMLHttpRequest
x-umb-segment: null
x-umb-xsrf-token: CfDJ8F4VwpWcK8JNt1NtoQUgHcyS4MueC-v_97xMadDsAcypzA3TQIUwt5Zxs6j3mD57dNTN2DRGEbh7f1Z_d0n-9TP0MHQlGYxEDmG0O1rWbQNJLFLBtbCezAlRAhW8-KKAqtPdyBOLWLmnd5OgtiIjotYwtqk_IsG8smEtwPGCyo39tMmlFZnVrisKW9l0qZcPEw
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
sec-gpc: 1
`
My app was upgraded from v9, do you think there's some missing things by that process? or any suggestion to investigate?

**Comment by andr317c** [comment]
Hey again,
I tried upgrading a version 9.5.4 site to 12.2.0. But it worked as intended 🙁 So I'm not really sure how you are getting the issue. Did you run into the same issue with Timeout on your v 9 site?

**Comment by kjac** [comment]
Hi all,

This issue has gone quite stale and no similar issues reports have been made, so I'm closing this issue for now.

Please feel free to reopen with additional steps to recreate 👍
