### ISSUE TITLE
Process cannot access NuCache.Content.db during umbraco 13 upgrade

### ISSUE THREAD

**Issue by jaandrews** [umbraco/Umbraco-CMS#15634]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.3

### Bug summary

When I run the installer to upgrade the database from 11.4.2 to 13.0.3, I get an error saying NuCache.Content.db is being used by another process. I was able to resolve the issue locally by deleting the folder, but I don't have access to this directory in the production environment (azure in my case) and so can't apply that fix.

### Steps to reproduce

1. Create an umbraco 11.4.2 project.
2. Upgrade it to umbraco 13.0.3, by manually updating the Umbraco.Cms packagte reference in the csproj file (I wasn't able to use the nuget package manager in my case, as there were other libraries that shared dependencies with Umbraco.Cms, so it would always block the upgrade).
3. Log into umbraco and run through the upgrade process.

**Comment by lauraneto** [comment]
Just wanted to drop a note that I had a similar issue to this and reported it here: https://github.com/umbraco/Umbraco-CMS/issues/14863
HQ mentioned they fixed the initial issue, but it seems that even with `ShowMaintenancePageWhenInUpgradeState` set to `true` it still happens.
I recently released an upgrade to Azure and restarting the web app(s) manually, after deploying the code, fixed it for me. (the nucache files are deleted when there is a web app restart, but not a deployment)

**Comment by jaandrews** [comment]
@lauraneto Thanks for the tip. That fixed it for me.

I'll hold off on closing this issue, since the root cause hasn't been resolved, but the restart is a simple workaround for the issue in the meantime.

**Comment by rpjengaard** [comment]
I have the same issue going from 10.6.1 -> 12

**Comment by AquaLes** [comment]
We are experiencing the same error with Umbraco Version 13.4.1 hosted in Azure.
We have tried:

- Restarting the Umbraco app service

- Tried deleting the NuCache folder

- Deleted the entire Umbraco directory and redeploying over and nothing seems to fix this error.

- We attempted to use our stage database in our production environment to rule out database issues with our production environment.

This is taking down our production environment and we need this fixed as soon as possible. We have not made any changes to our instance either.

**Comment by kjac** [comment]
Hi everyone.

I am sorry to hear you've got issues with the local NuCache DB files.

If anyone can provide a DB with the issue present and steps for reproduction locally, it would be greatly appreciated.

**Comment by AquaLes** [comment]
We have an issue transferring with Umbraco Deploy. We were instructed to discontinue the use of NuCache last year.

error:

e1241a67 - Executing, 10%
e1241a67 - Executing, 10% - Get remote session
e1241a67 - Executing, 20% - Create manifest on source
e1241a67 - Executing, 25% - Review manifest on target
e1241a67 - Executing, 80% - Exception!
e1241a67 - Executing, 80% - Abort remote session
e1241a67 - Failed, 80% - Total time 00:00:00.236.

-- EXCEPTION ---------------------------------------------------
(proper exception traces at the end of this log)
System.InvalidOperationException: There is no current work.
Umbraco.Deploy.Infrastructure.Exceptions.RemoteApiException: The remote API has thrown an exception.
----------------------------------------------------------------

EXCEPTION:

Umbraco.Deploy.Infrastructure.Exceptions.RemoteApiException: The remote API has thrown an exception.
at Umbraco.Deploy.Infrastructure.Http.DeployHttpClient.SucceedOrThrow(HttpResponseMessage result, CancellationToken token)
at Umbraco.Deploy.Infrastructure.Http.DeployHttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken token)
at Umbraco.Deploy.Infrastructure.Http.DeployHttpClient.SendAsync(HttpRequestMessage request, CancellationToken token)
at Umbraco.Deploy.Infrastructure.Environments.RemoteUmbracoEnvironment.ReviewManifestAsync(Guid sessionId, Manifest manifest, CancellationToken token)
at Umbraco.Deploy.Infrastructure.Work.WorkItems.DeployRestoreWorkItemBase.NegotiateManifest(Manifest manifest, IEnumerable`1 exclude, Nullable`1 batchIndex, Nullable`1 numberOfBatches)
at Umbraco.Deploy.Infrastructure.Work.WorkItems.SourceDeployWorkItem.ProceedToPackage(IEnumerable`1 items, Nullable`1 batchIndex, Nullable`1 numberOfBatches)
at Umbraco.Deploy.Infrastructure.Work.WorkItems.SourceDeployWorkItem.ExecuteAsyncSub(IEnumerable`1 items, Nullable`1 batchIndex, Nullable`1 numberOfBatches, CancellationToken token)
at Umbraco.Deploy.Infrastructure.Work.WorkItems.SourceDeployWorkItem.ExecuteAsyncSub(IEnumerable`1 items, Nullable`1 batchIndex, Nullable`1 numberOfBatches, CancellationToken token)
at Umbraco.Deploy.Infrastructure.Work.WorkItems.SourceDeployWorkItem.ExecuteForItems(IEnumerable`1 items, Nullable`1 batchIndex, Nullable`1 numberOfBatches, CancellationToken token)
at Umbraco.Deploy.Infrastructure.Work.WorkItems.SourceDeployWorkItem.ExecuteForItems(IEnumerable`1 items, CancellationToken token)
at Umbraco.Deploy.Infrastructure.Work.WorkItems.SourceDeployWorkItem.ExecuteAsync(IWorkContext context, CancellationToken token)

REMOTE:
System.InvalidOperationException: There is no current work.

at Umbraco.Deploy.Infrastructure.Environments.CurrentEnvironment.ValidateSession(Guid sessionId)
at Umbraco.Deploy.Infrastructure.Environments.EnvironmentController.BeginReviewManifest(SessionActionModel`1 model)
at lambda_method27075(Closure, Object, Object[])
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.&lt;InvokeNextExceptionFilterAsync&gt;g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)





Thanks in advance,



Les Wafford

Software Development Manager

[cid:4bbb09d2-5d1c-4549-b84c-a54046a75c48]



 Mobile. 317-649-2766

aquafinance.com<http://www.aquafinance.com/>



Aqua Finance, Inc.

One Corporate Drive

Suite 300, PO Box 844
Wausau, WI 54402-0844



[cid:27fabb41-802d-4388-8993-a11a577ce66d]



________________________________
