### ISSUE TITLE
"Could not find file" error with ExternalIndex - cannot rebuild

### ISSUE THREAD

**Issue by kmai-universe** [umbraco/Umbraco-CMS#15961]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.1.0

### Bug summary

ExternalIndex does not exists in the \Data\TEMP\ExamineIndexes folder. When i goto the synchronization settings in Umbraco backend and opens the ExternalIndex it states the following error:

`Could not find file 'C:\Windows\TEMP\ExamineIndexes\db54d6a2928214e00581c19fa50a0ed6\ExternalIndex\_65.si'. It may not be possible to rebuild the index. Please try deleting the entire ExternalIndex folder and then attempt to rebuild it again.`

All other indexes rebuilds fine and are working. They are all located directly inside the ExamineIndexes folder like this:

- \ExamineIndexes\UmbracoFormsRecordsIndex
- \ExamineIndexes\MembersIndex
- \ExamineIndexes\InternalIndex

If i hit the Rebuild index button it fails with the following error:

`System.IO.FileNotFoundException: Could not find file 'C:\Windows\TEMP\ExamineIndexes\db54d6a2928214e00581c19fa50a0ed6\ExternalIndex\_65.si'.
File name: 'C:\Windows\TEMP\ExamineIndexes\db54d6a2928214e00581c19fa50a0ed6\ExternalIndex\_65.si'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable 1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable 1 unixCreateMode)
   at Lucene.Net.Store.SimpleFSDirectory.OpenInput(String name, IOContext context)
   at Lucene.Net.Codecs.Lucene46.Lucene46SegmentInfoReader.Read(Directory dir, String segment, IOContext context)
   at Lucene.Net.Index.SegmentInfos.Read(Directory directory, String segmentFileName)
   at Lucene.Net.Index.SegmentInfos.FindSegmentsFileAnonymousClass.DoBody(String segmentFileName)
   at Lucene.Net.Index.SegmentInfos.FindSegmentsFile.Run(IndexCommit commit)
--- End of stack trace from previous location ---
   at Lucene.Net.Index.SegmentInfos.FindSegmentsFile.Run(IndexCommit commit)
   at Lucene.Net.Index.SegmentInfos.Read(Directory directory)
   at Lucene.Net.Index.IndexWriter..ctor(Directory d, IndexWriterConfig conf)
   at Examine.Lucene.Providers.LuceneIndex.CreateIndexWriter(Directory d)
   at Examine.Lucene.Providers.LuceneIndex.CreateIndexWriterInternal()
   at Examine.Lucene.Providers.LuceneIndex.get_IndexWriter()
   at Examine.Lucene.Providers.LuceneIndex.GetDocumentCount()
   at Umbraco.Cms.Web.BackOffice.Controllers.ExamineManagementController.CreateModel(IIndex index)`

And of course it gives a "file not found" exception as the file doesn't exist! I also don't know why it wants to look inside "\ExamineIndexes\db54d6a2928214e00581c19fa50a0ed6\ExternalIndex\" and not "\ExamineIndexes\ExternalIndex" like the other indexes.

I tried manually creating the db54.. folder with and without the \ExternalIndex but this does not fix the problem.

As stated above, the other indexes rebuilds fine so it has proper file access to the location (it has also been working before).

### Specifics

I created a forum post here on the same issue before i created this bug report:
https://our.umbraco.com/forum/using-umbraco-and-getting-started/113836-externalindex-corrupted-wrong-path

### Steps to reproduce

Log into umbraco backend, navigate to Synchronization settings, click on ExternalIndex, observe error at the top. Fails if you hit "Rebuild  index" button.

**Comment by kmai-universe** [comment]
Issue was solved by upgrading to Umbraco 13.2.2
