### ISSUE TITLE
v14-rc1 : Checkbox and, Dropdown lists in cause "JSON" error when saving/loading a content page.

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#16080]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc1

### Bug summary

Pages containing checkbox lists throw an error and not load once a items have been selected in the list

```
'S' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
A fatal server error occurred. If this continues, please reach out to your administrator.
```

### Specifics

Looks like there is a parsing error with the data that the checkbox, dropdown or radio button lists store.

### Steps to reproduce

- Create a checkbox list datatype with multiple (e.g 4) options
- Create a new document type containing a checkbox list property
- Create a page with the new doctype
- Pick one or more values from the checkbox
- Save

**Comment by elit0451** [comment]
Hi there @KevinJump 👋 

Thanks for reaching out! I can indeed reproduce this, we will have a look 🙂 

Here is the error from the logs:
```
System.Text.Json.JsonException: 'S' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: 'S' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Umbraco.Cms.Infrastructure.Serialization.SystemTextJsonSerializerBase.Deserialize[T](String input) in /UmbracoCMS/src/Umbraco.Infrastructure/Serialization/SystemTextJsonSerializerBase.cs:line 17
   at Umbraco.Cms.Core.PropertyEditors.MultipleValueEditor.ToEditor(IProperty property, String culture, String segment) in /UmbracoCMS/src/Umbraco.Infrastructure/PropertyEditors/MultipleValueEditor.cs:line 45
```

**Comment by kjac** [comment]
Good stuff! Fixed in https://github.com/umbraco/Umbraco-CMS/pull/16132

**Comment by KevinJump** [comment]
Hi, Juist to confirm this isn't in RC2 ?
