### ISSUE TITLE
v14-rc1 - Setting the Image Upload Folder on a Rich Text Editor causes content save to fail.

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#16083]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc1

### Bug summary

Settings a Image upload folder on a Rich text editor datatype, and then attempting to save content using that Rich text editor fails. 

### Specifics

When you save the UI hangs (spinning buttons) and the following error is in the logs.

```
 An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The configuration for data type -87 : Umbraco.RichText is invalid (see inner exception). Please fix the configuration and ensure it is valid. The site may fail to start and / or load data types and run.
 ---> System.InvalidOperationException: Failed to parse configuration "System.Collections.Generic.Dictionary`2[System.String,System.Object]" as "RichTextConfiguration" (see inner exception).
 ---> System.FormatException: String "069ef55e-6a88-4deb-9d2c-60df36b6eece" is not a valid udi.
   at Umbraco.Cms.Core.UdiParser.ParseInternal(String s, Boolean tryParse, Boolean knownTypes, Udi& udi)
   at Umbraco.Cms.Core.UdiParser.Parse(String s)
   at Umbraco.Cms.Infrastructure.Serialization.JsonUdiConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.ReadAsObject(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.CastingConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
....
```

_It looks like this is because the Image Upload load folder property stores the GUID of the media folder - but the validation of the page is expecting it to be a UDI ?_ 

### Steps to reproduce

- Create a new rich text editor data type
- Add a 'Image upload folder` to the configuration
- Add the editor to a document type
- create or save a content item using that document type.

- observer the hand.
- view the logs

### Expected result / actual result

Should save.

**Comment by elit0451** [comment]
Hi there @KevinJump 👋 

Thanks for reaching out! I can indeed reproduce this, we will have a look 🙂

**Comment by kjac** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/16138
