### ISSUE TITLE
Schedule publish jobs cannot get value of a multi-lingual item and nothing ever publishes

### ISSUE THREAD

**Issue by kmeilander** [umbraco/Umbraco-CMS#16224]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.2.2

### Bug summary

Schedule publish jobs cannot get value of a multi-lingual item, and if this occurs, it throws an exception in the schedule publish flow and prevents any item from being published.

This actually came about with an Umbraco Commerce issue with the stock handler, but after further testing it looks like it's a commerce issue.

### Specifics

Here is the full error for Umbraco Commerce:
System.ArgumentNullException: Value cannot be null. (Parameter 'key1')
at Umbraco.Cms.Infrastructure.PublishedCache.Property.GetValue(String culture, String segment)
at Umbraco.Extensions.PublishedPropertyExtension.Value[T](IPublishedProperty property, IPublishedValueFallback publishedValueFallback, String culture, String segment, Fallback fallback, T defaultValue)
at Umbraco.Commerce.Cms.Helpers.PublishedContentHelper.GetPropertyValue[T](IPublishedProperty prop, String culture, Fallback fallback)
at Umbraco.Commerce.Cms.Helpers.PublishedContentHelper.GetNodePropertyValue[T](IPublishedContent productNode, IPublishedElement productVariantNode, String propertyAlias, String languageIsoCode, Func`2 ancestorSelector, Boolean recursive, Func`2 hasValueCheck, VariantFallbackBehavior variantFallbackBehavior)
at Umbraco.Commerce.Cms.Finders.UmbracoPublishedContentStoreFinder.FindStoreByPublishedContent(IPublishedContent node)
at Umbraco.Commerce.Cms.Finders.UmbracoPublishedContentStoreFinder.FindStore(Int32 nodeId)
at Umbraco.Commerce.Cms.Services.UmbracoStoreService.FindStoreByNodeId(Int32 nodeId)
at Umbraco.Commerce.Cms.PropertyEditors.Stock.UmbracoStockSynchronizer.Synchronize(IContent content, SynchronizeAttempt attempt)
at Umbraco.Commerce.Cms.Events.Notification.Handlers.SynchronizeUmbracoStockOnSaving.Handle(ContentSavingNotification notification)
at Umbraco.Cms.Core.Events.INotificationHandler`1.Handle(IEnumerable`1 notifications)
at Umbraco.Cms.Core.Events.EventAggregator.PublishCore[TNotification](IEnumerable`1 allHandlers, IEnumerable`1 notifications)
at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.Handle[TNotification,TNotificationHandler](IEnumerable`1 notifications, ServiceFactory serviceFactory, Action`2 publish)
at Umbraco.Cms.Core.Events.EventAggregator.PublishNotifications[TNotification,TNotificationHandler](IEnumerable`1 notifications)
at Umbraco.Cms.Core.Events.EventAggregator.Publish[TNotification,TNotificationHandler](IEnumerable`1 notifications)
at Umbraco.Cms.Core.Events.ScopedNotificationPublisher`1.PublishCancelable(ICancelableNotification notification)
at Umbraco.Cms.Core.Services.ContentService.PerformScheduledPublishingRelease(DateTime date, List`1 results, EventMessages evtMsgs, Lazy`1 allLangs)
at Umbraco.Cms.Core.Services.ContentService.PerformScheduledPublish(DateTime date)
at Umbraco.Cms.Infrastructure.BackgroundJobs.Jobs.ScheduledPublishingJob.RunJobAsync()
​
I have also isolated the issue  using the Umbraco Demo Store.  See https://github.com/umbraco/Umbraco.Commerce.DemoStore/compare/main...kmeilander:Umbraco.Commerce.DemoStore:breaking-publish-demo

I initially thought it was a Umbraco Commerce bug, but it appears to be an Umbraco issue.

### Steps to reproduce

1. Setup a site with a node that allows vary by culture. Add a property.  Setup multiple languages in the install.
2. Create a new ContentSavingNotification handler.
3. From the handler, load the content and attempt to get the property value.  
4. In the Backoffice, create a new item of that doc type. And set any content item to be scheduled in the future.

### Expected result / actual result

EXPECTED: That content item will be published when the time comes.

ACTUAL: The handler will be called with the schedule publish, and will throw an exception trying to load the value.  And since the exception fails in the handle the content is never published.   This will break for all scheduled published items.

**Comment by kmeilander** [comment]
I looked into things a little bit and i think it has something to do with the published request not being able to find the culture for the item.    

The handler works fine for the Umbraco user, but the Umbraco Schedule publish handler it fails for some reason.   But if i specify the culture in the GetValue("en") call, it works as expected (see my Umbraco Demo store fork)

(i think this is where it's going)
https://github.com/umbraco/Umbraco-CMS/blob/b0b2b597403bb381c23ff47f2b1ffc8aeaab1dc0/src/Umbraco.PublishedCache.NuCache/Property.cs#L271

**Comment by jveer** [comment]
We have the same issue, although I don't have a fix for the issue itself.. we were able to get rid of the errors in the logs by removing the scheduled publication as the nodes were already published in our case.

To find the scheduled publications, we used this SQL query:
```
SELECT 
    [umbracoContentSchedule].[nodeId],
    [umbracoContentSchedule].[languageId],
    [umbracoContentSchedule].[date],
    [umbracoContentSchedule].[action],
    [umbracoNode].[text],
    [cmsContentType].[alias]
FROM [dbo].[umbracoContentSchedule]
    LEFT JOIN [UmbracoNode] ON [UmbracoNode].[id] = [umbracoContentSchedule].[nodeId]
    LEFT JOIN [umbracoContent] ON [umbracoContent].[nodeId] = [UmbracoNode].[id]
    LEFT JOIN [cmsContentType] ON [cmsContentType].[nodeId] = [umbracoContent].[contentTypeId]
ORDER BY [date] desc
```

We had different document types with a scheduled publication, but only the Umbraco Commerce products threw the exception.

Some more details about our setup, in case someone starts working on this ticket:
- The `Product` document type **is** varying by culture
  - The `Variants` property on this document type is **not** varying by culture
- The `Variant` document type is **not** varying by culture
- There's only 1 language configured in Umbraco

**Comment by j-allgulin** [comment]
We also experience the same issue. We noticed that scheduled jobs are failing whenever it tries to publish them and the logs are piling up, as shown in previous comments. We solved if for now by removing the tasks and the logs are now gone. 

In this project we are running with Umbraco 13.6.0 and Commerce 13.1.10 and have two languages configured.
I wanted to see if the behavior was only related for products. I tried to schedule another document type for publishing but that also failed. Both of them are vary by culture, so maybe it's related to that.
