### ISSUE TITLE
XPathValue must be an XPathNavigator or a string

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#16238]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.3.0

### Bug summary

After upgrading from Umbraco v12.3.9 to v13.3.0 most seems to work correct.
However I content pages in backoffice I get the following error, which seems to be related to XPath of pickers.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/ef5a9572-f811-4968-9e2a-4d1a1efc0006)

```
at Umbraco.Cms.Core.Xml.XPath.NavigableNavigator.MoveToFirstChildProperty()
   at Umbraco.Cms.Core.Xml.XPath.NavigableNavigator.MoveToFirstChild()
   at MS.Internal.Xml.XPath.XPathDescendantIterator.MoveNext()
   at MS.Internal.Xml.XPath.DescendantQuery.Advance()
   at MS.Internal.Xml.XPath.XPathSelectionIterator.MoveNext()
   at Umbraco.Cms.Infrastructure.PublishedCache.ContentCache.GetSingleByXPath(XPathNodeIterator iterator)
   at Umbraco.Cms.Infrastructure.PublishedCache.ContentCache.GetSingleByXPath(Boolean preview, String xpath, XPathVariable[] vars)
   at Umbraco.Cms.Core.PublishedCache.PublishedCacheBase.GetSingleByXPath(String xpath, XPathVariable[] vars)
   at Umbraco.Cms.Infrastructure.PublishedContentQuery.ItemByXPath(String xpath, XPathVariable[] vars, IPublishedCache cache)
   at Umbraco.Cms.Infrastructure.PublishedContentQuery.ContentSingleAtXPath(String xpath, XPathVariable[] vars)
   at Umbraco.Cms.Web.BackOffice.Controllers.EntityController.GetByXPath(String query, Int32 nodeContextId, Nullable`1 parentId, UmbracoEntityTypes type)
   at lambda_method7749(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

### Steps to reproduce

Access content page with pickers using XPath.

**Comment by bjarnef** [comment]
It seems to be related to this issue here https://github.com/umbraco/Umbraco-CMS/issues/15647 reported by @marcemarc

**Comment by marcemarc** [comment]
@bjarnef it's probably this:

https://github.com/umbraco/Umbraco-CMS/pull/16121

Basically the RTE got changed and fangled so that it no longer just stores a string, it's more complex, has 'blocks' ... and so when that property hits the XPath it's not a string anymore, @nul800sebastiaan  has fixed it for the 404 page, wonder if it is the same kinda thing for the picker?

**Comment by nielslyngsoe** [comment]
I'm closing this issue as the affected features and versions are no longer present in the Umbraco CMS. (V.13 is in the security phase and not receiving new updates unless it is regarding security)

This feature has been replaced in newer versions and therefor not relevant in those versions.

Thanks for taking the time to report it in the first place — we do appreciate it, even when we can't get every issue over the finish line.
