### ISSUE TITLE
"Unexpected character encountered while parsing value" on save and publish

### ISSUE THREAD

**Issue by kows** [umbraco/Umbraco-CMS#16288]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.3.0

### Bug summary

When trying to save or save and publish I get an error modal.

### Specifics

Received an error from the server
An error occurred
Unexpected character encountered while parsing value: U. Path '', line 0, position 0.

```c#
Exception Details
Newtonsoft.Json.JsonReaderException, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed: Unexpected character encountered while parsing value: U. Path '', line 0, position 0.

at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Umbraco.Cms.Core.Models.Blocks.BlockEditorDataConverter.Deserialize(String json)
   at Umbraco.Cms.Core.PropertyEditors.BlockEditorValues.DeserializeAndClean(Object propertyValue)
   at Umbraco.Cms.Core.PropertyEditors.BlockEditorPropertyValueEditor.FromEditor(ContentPropertyData editorValue, Object currentValue)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentControllerBase.MapPropertyValuesForPersistence[TPersisted,TSaved](TSaved contentItem, ContentPropertyCollectionDto dto, Func`3 getPropertyValue, Action`3 savePropertyValue, String culture)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.MapValuesForPersistence(ContentItemSave contentSave)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PostSaveInternal[TVariant](ContentItemSave contentItem, Func`3 saveMethod, Func`2 mapToDisplay)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PostSave(ContentItemSave contentItem)
   at lambda_method2196(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   ```

### Steps to reproduce

There are actually two flows in which this occurs.
Setup: 
- document type with block list editor which contains data (not empty).
- using a handler for SendingContentNotification
a) mark the block list property as readonly
or b) remove the block list property from the tab.Properties to "hide" it

With this setup, if you try to save or save and publish, it is actually trying to process `Umbraco.Blocklist` as value iso the actual data.

### Expected result / actual result

A readonly/hidden block list editor does not block save / save and publish.

**Comment by Migaroez** [comment]
Hey @kows do I understand correctly that

If you manipulate the content model in SendingContentNotification by either
- marking a blocklist based property as readonly
- or make the property not belong to any propertycollections
And then save OR Save & publish, you get the error you described?

**Comment by kows** [comment]
Yes and the block list editor must contain data for it to happen.

``` C#
internal sealed class SendingContentNotificationHandler()
	: INotificationHandler<SendingContentNotification>
{
	public void Handle(SendingContentNotification notification)
	{
		if (notification.Content.ContentTypeAlias.Equals(Website.ModelTypeAlias))
		{
			foreach (ContentVariantDisplay variant in notification.Content.Variants)
			{
                                //exclude 'groupToHideAlias' tab/group which contains a blocklist editor
				variant.Tabs = variant.Tabs.Where(x => !x.Alias.InvariantEquals("groupToHideAlias"));
			}
		}

		if (notification.Content.ContentTypeAlias.Equals(ContentPage.ModelTypeAlias))
		{
			foreach (ContentVariantDisplay variant in notification.Content.Variants)
			{
				//making all editors on tabs readonly except 'Generic'
				foreach (Tab<ContentPropertyDisplay> tab in variant.Tabs.Where(t => t.Type == "Tab"))
				{
					foreach (ContentPropertyDisplay prop in tab.Properties ?? [])
					{
						prop.Readonly = true;
					}
				}
			}
		}
	}
}
```

**Comment by kows** [comment]
@Migaroez 
whenever you want to tie security towards specific properties?
There's even a package out there: https://marketplace.umbraco.com/package/our.umbraco.community.adminonlyproperty
Kind of weird to say `Because the system was not purposefully designed to handle this kind of manipulation, I am going to close this bug report.` if you have a `Readonly` flag.

**Comment by Migaroez** [comment]
I do not deem setting an outbound (display) model flag as a way of enforcing security

To make something truly secure (in an editing context), you need to control the inbound flow, and the outbound just to be friendly. If you only control the outbound, you end up with security by obscurity as shown in the video below. To save time I used the package you linked with 2 users. But it should (and I am pretty sure it will) work the same with marking it read-only as I tested the client's behaviour regarding payload construction previously.

https://github.com/umbraco/Umbraco-CMS/assets/6025797/f0f10bd0-efc5-4abe-962a-e0accb54cb7e

With `purposefully designed` I meant: I do not think all possible outcomes were considered when a feature was build that gave you the outbound model and just said "hey, update this however you want".

I can only guess as I was not a core developer at the time, but I believe the intent was that if you were to change anything or all things on an outbound model, you would make sure it wouldn't brake things when the client then send it back. And I am pretty sure that there was no clear intent to allow this feature to make implementers make things "more secure" (as per previous statement and example)
