### ISSUE TITLE
Error on creating a custom section on Umbraco 13

### ISSUE THREAD

**Issue by addin-dev-24** [umbraco/Umbraco-CMS#16337]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco 13

### Bug summary

I am following the below guideline for creating an new section on Umbraco 13.

https://docs.umbraco.com/umbraco-cms/extending/section-trees/sections

When I follow the exact same steps, I am getting an error on admin side(when logged in)

When navigating to : {domain}/umbraco

### Steps to reproduce

Implement a custom section as mentioned below
https://docs.umbraco.com/umbraco-cms/extending/section-trees/sections 
Navigate to the admin page. 

### Expected result / actual result

**Expected:**
View new custom section on admin panel

**Actual:**
Error when logged in to the admin.

![image](https://github.com/umbraco/Umbraco-CMS/assets/170021715/d2e11414-59ee-4c3b-8865-25bcf9312fe4)

`at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Umbraco.Cms.Core.Services.DashboardService.GetDashboards(IUser currentUser)
   at Umbraco.Cms.Web.BackOffice.Controllers.SectionController.GetSections()
   at lambda_method201(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)`

**Comment by rammi987** [comment]
Hello @addin-dev-24,
Did you follow the step for adding both the "package.manifest" and the the "C# type registering" 

The error means there are two or more sections with the same alias, so in the case where you meaby have done both of the above the package.manifest register a section with alias "myFavouriteThings" and the the "C# type registering" come and try also and makes the exception.

If in case you have both, try to delete one of them and see if it solves the issue? Or check your Dependecy injections, see if you meaby accidentally registered the same class twice :)

**Comment by addin-dev-24** [comment]
> Hello @addin-dev-24, Did you follow the step for adding both the "package.manifest" and the the "C# type registering"
> 
> The error means there are two or more sections with the same alias, so in the case where you meaby have done both of the above the package.manifest register a section with alias "myFavouriteThings" and the the "C# type registering" come and try also and makes the exception.
> 
> If in case you have both, try to delete one of them and see if it solves the issue? Or check your Dependecy injections, see if you meaby accidentally registered the same class twice :)


The above response is correct. I was registering the custom section twice in the code. closing the bug. sorry for the inconvenience.
