### ISSUE TITLE
An unhandled exception has occurred while executing the request.

### ISSUE THREAD

**Issue by NijasHameed** [umbraco/Umbraco-CMS#16783]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.3.2

### Bug summary

I'm continuously encountering the following error in the logs and am unsure of its cause. Recently, I upgraded Umbraco from version 10 to 13, and since then, this error has persisted. However, it doesn't appear to affect any user interface features so far. Anyone you have any idea what might be causing this error and how to fix it? I am currently using Umbraco 13.3.2.

### Specifics

System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.GetApplicationUrlFromCurrentRequest(HttpRequest request)
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, Boolean retry)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
![Screenshot 2024-07-17 124321](https://github.com/user-attachments/assets/f6ab9ae5-c83d-45e3-b068-0d5ec5dbb1bd)

### Steps to reproduce

I just upgraded from umbraco 10 to umbraco 13.3.2

**Comment by rbottema** [comment]
When you click the log entry, it should open revealing more details. Is there a `Uri` property there and if so, can you share that? Hopefully that sheds some more light on the issue.

**Comment by NijasHameed** [comment]
![Screenshot 2024-07-17 130314](https://github.com/user-attachments/assets/153f5318-6462-4075-ac71-c9f25c81c022)

This is what is further detailed in the log entry

**Comment by bergmania** [comment]
Hi thanks for reporting. 
I dont think we can fix it without knowning what url your solution is hosted on. There must be some interesting characters.

I think it is a workaround, just to follow best practices and set the application url in config. https://docs.umbraco.com/umbraco-cms/extending/health-check/guides/fixedapplicationurl

**Comment by RazerPie** [comment]
Here again. At least in my case, the problem was that Docker was opening the application port (5000) on all network interfaces by default. Docker modifies iptables directly and bypasses UFW, meaning that blocking the port with UFW alone does not prevent external access.

As a result, bots were able to send unexpected payloads which were not meant for an HTTP server to port 5000, causing the URI parser to fail.

Fix:
The solution was to explicitly bind the port to localhost only, ensuring that external connections cannot reach it.

Old version:
`-port: "5000:8080"`

New version
`-port: "127.0.0.1:5000:8080"`

This ensures that port 5000 is only accessible from localhost, preventing external connections.

**Comment by mnsos-dauger** [comment]
For anyone who gets here because they are seeing this issue in IIS: I've found that I will see these (hundreds or thousands a day) if there is an IP only binding on the site in IIS. It happens even if you have a binding with a hostname and an IP only binding. Only using bindings with hostnames solves the issue. It's not ideal, but that's the only "fix" I've found. FWIW the site I'm seeing this on is Umbraco 13.5.2. The errors will start happening right on startup.
