### ISSUE TITLE
Saving doctype gives error The given key 'ID' was not present in the dictionary.

### ISSUE THREAD

**Issue by thomashdk** [umbraco/Umbraco-CMS#16931]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.4.0

### Bug summary

When saving doctype, a error are showed.
`The given key '3952' was not present in the dictionary.`

Some of the node using this doctype can't be opened.
Looks like it's some nodes that don't have a culture version of the default language, but only a EN version in this case, and not a DK version.

### Specifics

When saving doctype, a error are showed.

`The given key '3952' was not present in the dictionary.`

`System.Collections.Generic.KeyNotFoundException, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: The given key '3952' was not present in the dictionary.`

**StackTrace**:

``` at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentRepositoryBase`3.GetPropertyCollections[T](List`1 temps)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.DocumentRepository.MapDtosToContent(List`1 dtos, Boolean withCache, Boolean loadProperties, Boolean loadTemplates, Boolean loadVariants)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.DocumentRepository.<GetPage>b__56_0(List`1 x)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentRepositoryBase`3.GetPage[TDto](IQuery`1 query, Int64 pageIndex, Int32 pageSize, Int64& totalRecords, Func`2 mapDtos, Sql`1 filter, Ordering ordering)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.DocumentRepository.GetPage(IQuery`1 query, Int64 pageIndex, Int32 pageSize, Int64& totalRecords, IQuery`1 filter, Ordering ordering)
   at Umbraco.Cms.Infrastructure.PublishedCache.Persistence.NuCacheContentRepository.RebuildContentDbCache(IContentCacheDataSerializer serializer, Int32 groupSize, IReadOnlyCollection`1 contentTypeIds)
   at Umbraco.Cms.Infrastructure.PublishedCache.Persistence.NuCacheContentRepository.Rebuild(IReadOnlyCollection`1 contentTypeIds, IReadOnlyCollection`1 mediaTypeIds, IReadOnlyCollection`1 memberTypeIds)
   at Umbraco.Cms.Infrastructure.PublishedCache.Persistence.NuCacheContentService.Rebuild(IReadOnlyCollection`1 contentTypeIds, IReadOnlyCollection`1 mediaTypeIds, IReadOnlyCollection`1 memberTypeIds)
   at Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotService.Rebuild(IReadOnlyCollection`1 contentTypeIds, IReadOnlyCollection`1 mediaTypeIds, IReadOnlyCollection`1 memberTypeIds)
   at Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotServiceEventHandler.Handle(ContentTypeRefreshedNotification notification)
   at Umbraco.Cms.Core.Events.INotificationHandler`1.Handle(IEnumerable`1 notifications)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishCore[TNotification](IEnumerable`1 allHandlers, IEnumerable`1 notifications)
   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.Handle[TNotification,TNotificationHandler](IEnumerable`1 notifications, ServiceFactory serviceFactory, Action`2 publish)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishNotifications[TNotification,TNotificationHandler](IEnumerable`1 notifications)
   at Umbraco.Cms.Core.Events.EventAggregator.Publish[TNotification,TNotificationHandler](IEnumerable`1 notifications)
   at Umbraco.Cms.Core.Services.ContentTypeServiceBase`2.Save(TItem item, Int32 userId)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentTypeController.<PostSave>b__34_1(IContentType type)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentTypeControllerBase`1.PerformPostSave[TContentTypeDisplay,TContentTypeSave,TPropertyType](TContentTypeSave contentTypeSave, Func`2 getContentType, Action`1 saveContentType, Action`1 beforeCreateNew)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentTypeController.PostSave(DocumentTypeSave contentTypeSave)
   at lambda_method78454(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)```
   
   
   Some nodes that are using that doctype gives that same error, and is not possible to open in the backoffice 
   This error is just showing:
   
![image](https://github.com/user-attachments/assets/6d47b142-d0bc-43e5-b7e2-7ec7df77876e)

And the log:

![image](https://github.com/user-attachments/assets/1b687268-7851-4555-a623-fddcd9c3beb5)

```
System.Collections.Generic.KeyNotFoundException: The given key '3952' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentRepositoryBase`3.GetPropertyCollections[T](List`1 temps)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.DocumentRepository.MapDtoToContent(DocumentDto dto)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.DocumentRepository.PerformGet(Int32 id)
   at Umbraco.Cms.Core.Cache.DefaultRepositoryCachePolicy`2.Get(TId id, Func`2 performGet, Func`2 performGetAll)
   at Umbraco.Cms.Core.Services.ContentService.GetById(Int32 id)
   at Umbraco.Cms.Core.Security.ContentPermissions.CheckPermissions(Int32 nodeId, IUser user, IContent& contentItem, IReadOnlyList`1 permissionsToCheck)
   at Umbraco.Cms.Web.BackOffice.Authorization.ContentPermissionsQueryStringHandler.IsAuthorized(AuthorizationHandlerContext context, ContentPermissionsQueryStringRequirement requirement)
   at Umbraco.Cms.Web.BackOffice.Authorization.MustSatisfyRequirementAuthorizationHandler`1.HandleRequirementAsync(AuthorizationHandlerContext context, T requirement)
   at Microsoft.AspNetCore.Authorization.AuthorizationHandler`1.HandleAsync(AuthorizationHandlerContext context)
   at Microsoft.AspNetCore.Authorization.DefaultAuthorizationService.AuthorizeAsync(ClaimsPrincipal user, Object resource, IEnumerable`1 requirements)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthorizeAsync(AuthorizationPolicy policy, AuthenticateResult authenticationResult, HttpContext context, Object resource)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 112
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, Boolean retry)
   at Umbraco.Forms.Web.HttpModules.ProtectFormUploadRequestsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Core.Middleware.WebPMiddleware.Invoke(HttpContext httpContext) in C:\Dev\client\Core\Middleware\WebPMiddleware.cs:line 33
   at Core.Customheaders.CustomHeaders.InvokeAsync(HttpContext context) in C:\Dev\client\Core\Customheaders\Header.cs:line 39
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
   ```
   
Looks like it's some nodes that don't have a culture version of the default language, but only a EN version in this case, and not a DK version.

### Steps to reproduce

Not sure how to reproduce this. 

We are using the same code base on diffrent clients, and havn't seen this error at our other clients.

### Expected result / actual result

Being able to update and save the doctype.

And being able to open and edit the nodes.

**Comment by thomashdk** [comment]
It's not possible to rebuild the index without getting the same error:

```System.Collections.Generic.KeyNotFoundException: The given key '3952' was not present in the dictionary.
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentRepositoryBase`3.GetPropertyCollections[T](List`1 temps)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.DocumentRepository.MapDtosToContent(List`1 dtos, Boolean withCache, Boolean loadProperties, Boolean loadTemplates, Boolean loadVariants)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.DocumentRepository.<GetPage>b__56_0(List`1 x)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentRepositoryBase`3.GetPage[TDto](IQuery`1 query, Int64 pageIndex, Int32 pageSize, Int64& totalRecords, Func`2 mapDtos, Sql`1 filter, Ordering ordering)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.DocumentRepository.GetPage(IQuery`1 query, Int64 pageIndex, Int32 pageSize, Int64& totalRecords, IQuery`1 filter, Ordering ordering)
   at Umbraco.Cms.Core.Services.ContentService.GetPagedLocked(IQuery`1 query, Int64 pageIndex, Int32 pageSize, Int64& totalChildren, IQuery`1 filter, Ordering ordering)
   at Umbraco.Cms.Core.Services.ContentService.GetPagedDescendants(Int32 id, Int64 pageIndex, Int32 pageSize, Int64& totalChildren, IQuery`1 filter, Ordering ordering)
   at Umbraco.Cms.Infrastructure.Examine.ContentIndexPopulator.IndexAllContent(Int32 contentParentId, Int32 pageIndex, Int32 pageSize, IReadOnlyList`1 indexes)
   at Umbraco.Cms.Infrastructure.Examine.ContentIndexPopulator.PopulateIndexes(IReadOnlyList`1 indexes)
   at Umbraco.Cms.Infrastructure.Examine.IndexPopulator.Populate(IIndex[] indexes)
   at Umbraco.Cms.Infrastructure.Examine.ExamineIndexRebuilder.RebuildIndexes(Boolean onlyEmptyIndexes, TimeSpan delay, CancellationToken cancellationToken)```

**Comment by thomashdk** [comment]
Getting the node from the cache with UmbracoHelper works.

Getting the node with contentservice gives the same error.

**Comment by thomashdk** [comment]
I endend up Deleting from this table where the id's it complained about was.

Delete [umbracoPropertyData]
  Where propertyTypeId IN (3952, 3955, 3964, 3963, 4241, 4244, 4253, 4252);
  
  Fixed my issue  :)
