### ISSUE TITLE
Unable to change installation administrator's password

### ISSUE THREAD

**Issue by nackler** [umbraco/Umbraco-CMS#16943]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.1

### Bug summary

Unable to change the umbraco administrator password. This is the main admin username/password that is configured during an initial install.

### Specifics

Logged in to the backoffice as the original administrator.

Tried to change my own password by clicking my user-icon in the top right corner and choosing 'Change Password'.  I was prompted for my old and new passwords. After submitting the form the dialog disappears with no confirmation that the password was changed. Nothing in the logs, no browser console error.

When I log out, then try to log in again using the new password it is evident that the new password was not saved.

I also tried changing my own password by going in to the 'Users' section of the backoffice, clicking my name to drill into my user details, then choosing 'change password' from that screen. When doing it this way, even though I enter my old password in the field provided, I get a visible error in the bottom right hand corner and in the javascript console

{
    "type": "Error",
    "title": "Old password required",
    "status": 400,
    "detail": "The old password is required to change your own password.",
    "operationStatus": "SelfOldPasswordRequired"
}

If I log in as a different user in the administrators group, the original 'admin user' doesn't show up in the list of editable users so I cannot try changing its password 

### Steps to reproduce

Log in to the backoffice as the original installation admin user
Attempt to change your own password by choosing 'Change Password' from your profile dropdown in the top right corner.
Enter the old and new passwords, submit the form.
Log out.
Log in using the new password.

### Expected result / actual result

Expected to be able to login using the new password. 
Instead, the old password was the only password that worked.

**Comment by nackler** [comment]
I have seen articles suggesting that to change this original admin password the trick is to change the configured connection string in appsettings to an empty string ("").  When I do this my site does not run but I get an error in my logs.  Perhaps some piece of middleware is getting in the way before that workflow can kick in.  
```

{"@t":"2024-08-21T18:27:42.0270162Z","@mt":"An unhandled exception has occurred while executing the request.","@l":"Error","@x":"System.InvalidOperationException: The factory has not been configured with a proper connection string.
   at Umbraco.Cms.Infrastructure.Persistence.UmbracoDatabaseFactory.Initialize()   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Umbraco.Cms.Infrastructure.Persistence.UmbracoDatabaseFactory.EnsureInitialized()   at Umbraco.Cms.Infrastructure.Persistence.UmbracoDatabaseFactory.CreateDatabase()
   at Umbraco.Cms.Infrastructure.Scoping.Scope.get_Database()   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.CacheInstructionRepository.Exists(Int32 id)
   at Umbraco.Cms.Infrastructure.Services.CacheInstructionService.IsColdBootRequired(Int32 lastId)   at Umbraco.Cms.Infrastructure.Sync.SyncBootStateAccessor.InitializeColdBootState(Int32 lastId)
   at Umbraco.Cms.Infrastructure.Sync.SyncBootStateAccessor.<GetSyncBootState>b__8_0()   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at System.Threading.LazyInitializer.EnsureInitialized[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)   at Umbraco.Cms.Infrastructure.Sync.SyncBootStateAccessor.GetSyncBootState()
   at Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotService.<EnsureCaches>b__56_0()   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at System.Threading.LazyInitializer.EnsureInitialized[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotService.EnsureCaches()   at Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotService.CreatePublishedSnapshot(String previewToken)
   at Umbraco.Cms.Web.Common.UmbracoContext.UmbracoContext.<>c__DisplayClass12_0.<.ctor>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()   at Umbraco.Cms.Web.Common.UmbracoContext.UmbracoContext.get_PublishedSnapshot()
   at Umbraco.Cms.Web.Common.UmbracoContext.UmbracoContext.get_Content()   at Umbraco.Cms.Web.Website.Routing.UmbracoRouteValueTransformer.TransformAsync(HttpContext httpContext, RouteValueDictionary values)
   at Microsoft.AspNetCore.Mvc.Routing.DynamicControllerEndpointMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|10_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\\projects\\dotnet\\src\\MiniProfiler.AspNetCore\\MiniProfilerMiddleware.cs:line 112
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)","@tr":"f175bcce1d73a25f1714a7a2cd04549e","@sp":"3cdf909d19ed0aee","EventId":{"Id":1,"Name":"UnhandledException"},"SourceContext":"Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware","RequestId":"0HN621RNQKNVU:00000427","RequestPath":"/umbraco/management/api/v1/server/status","ConnectionId":"0HN621RNQKNVU","ProcessId":21680,"ProcessName":"SomeCompany.Public.Web","ThreadId":22,"ApplicationId":"d1898851af5beed01f3fcfa9e5d9bbb2a1b7f431","MachineName":"PC1124","Log4NetLevel":"ERROR"}

```

**Comment by nackler** [comment]
Just getting to the installation page has only been part of the problem.  I need to use a connection string for this connection. but when I enter one I keep getting an immediate error when clicking install.  I can get through the installer using 'SQL Server' as my connection type, with or without integrated security, but if I choose 'Custom' as my connection type and enter my connection string I get the following error:

![image](https://github.com/user-attachments/assets/d5ad34c3-08af-426c-95c1-caf9a08d6b60)

Obviously there is a database name provided in that connection string. It is just a simple example. Any connection string fails with the same message.

**Comment by NguyenThuyLan** [comment]
Hi @nackler , thank you for reporting this issue. I can see there are a lot of issues in one here 😥
1. Can not change password when click "Change password"  by clicking my user-icon in the top right corner
2. Got error when click change password on User section
3. Validation error "No valid database selected"

For the docs https://docs.umbraco.com/umbraco-cms/reference/security/reset-admin-password, You only need to use it when you forget the password for the super admin account specifically. So if you remember your password and want to change it, you can still use the button "Change password" (of course, we will fix it)

**Comment by madsrasmussen** [comment]
Fixed in: https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2244

**Comment by umbracocommunity** [comment]
This issue has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/after-upgrading-from-13-13-0-to-17-2-2-backoffice-password-changes-silently-fail-to-persist/7694/1
