### ISSUE TITLE
Codespace doesnt fails on creation

### ISSUE THREAD

**Issue by Matthew-Wise** [umbraco/Umbraco-CMS#17015]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.x

### Bug summary

Tried to use GitHub Codespaces, it looks like it needs updating for 14 log snippets below of the errors

Looks to be the dotnet version and the git submodule

```
2024-09-06 07:48:20.093Z: dotnet build umbraco.sln && dotnet dev-certs https --trust
2024-09-06 07:48:20.361Z: The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'build' does not exist.
  * You intended to execute a .NET SDK command:
      A compatible .NET SDK was not found.

Requested SDK version: 8.0.300
global.json file: /workspace/global.json

2024-09-06 07:48:20.362Z: Installed SDKs:
6.0.414 [/usr/share/dotnet/sdk]
7.0.410 [/usr/share/dotnet/sdk]

Install the [8.0.300] .NET SDK or update [/workspace/global.json] to match an installed SDK.

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
2024-09-06 07:48:20.367Z: updateContentCommand failed with exit code 145. Skipping any further user-provided commands.

2024-09-06 07:48:20.370Z: Error: Command failed: /bin/sh -c dotnet build umbraco.sln && dotnet dev-certs https --trust
2024-09-06 07:48:20.370Z:     at b7 (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:235:130)
2024-09-06 07:48:20.371Z: {"outcome":"error","message":"Command failed: /bin/sh -c dotnet build umbraco.sln && dotnet dev-certs https --trust","description":"The updateContentCommand in the devcontainer.json failed.","containerId":"6b9681ea75266368adae9400993e4d150dd9e12b712c6235dbc865e3743079a0"}
2024-09-06 07:48:20.371Z:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-09-06 07:48:20.374Z:     at async Am (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:4483)
2024-09-06 07:48:20.374Z:     at async Xw (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:3828)
2024-09-06 07:48:20.374Z:     at async $w (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:2904)
2024-09-06 07:48:20.374Z:     at async fa (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:2438)
2024-09-06 07:48:20.374Z:     at async ctA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:410:3710)
2024-09-06 07:48:20.374Z:     at async YtA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:482:3944)
2024-09-06 07:48:20.375Z:     at async eB (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:482:4886)
2024-09-06 07:48:20.375Z:     at async prA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:663:200)
2024-09-06 07:48:20.387Z: devcontainer process exited with exit code 1

====================================== ERROR ====================================
2024-09-06 07:48:20.387Z: Failed to create container.
```

### Steps to reproduce

Try load a codespace

**Comment by iOvergaard** [comment]
Hello @Matthew-Wise, thanks for reporting this.

I think this is a good candidate for hacktoberfest, so I'll go ahead and mark the issue as up for grabs, so we can get some help resolving this. It looks like @lauraneto may have had an idea how to fix it in their own fork - that could be a hint to whoever wants to fix it here.

**Comment by iOvergaard** [comment]
I took a stab at this over on the [feature/devcontainer-net90](https://github.com/umbraco/Umbraco-CMS/tree/v15/feature/devcontainer-net90) branch, but Microsoft seems not to have updated their image to .NET 9 as it still shows 9.0.100-rc2, which is incompatible with the current global.json file.

I also experimented spinning up all the docker-compose services (really just smtp4dev) as a devcontainer codespaces dependency instead ([courtesy of @warrenbuckley it seems](https://github.com/warrenbuckley/codespace-features)) and it seems to work, so maybe we can avoid the `Dockerfile` and `docker-compose.yml` altogether. However, I am not sure if it just spins up the same way in vscode as it would in a Codespace. More testing is needed.

**Comment by warrenbuckley** [comment]
I haven't looked at this for a while and the last time I did, I was actively working at HQ.
I may give it a go when I get some free time, but don't hold your breath waiting for me though...

**Comment by iOvergaard** [comment]
Hi again,
We're closing this issue as the affected version has since gone out of support.
That doesn't necessarily mean the problem is gone, but a lot has changed in the codebase since this was reported, and we're no longer shipping fixes for this version. If you're still seeing this on a currently supported version, please open a new issue referencing this one with updated reproduction steps, and we'll happily take a look.

**Comment by warrenbuckley** [comment]
I would imagine this still errors or is a problem for the latest versions @iOvergaard 
If it has been fixed since then or if the CMS/HQ no longer want to support it probably best to remove it from the repo altogether.

**Comment by iOvergaard** [comment]
@warrenbuckley We don't have any Codespaces on the main branch, at least. But there is a devcontainer, which I believe Codespaces also use as does VS Code, if you clone it down. That is outdated in terms of dotnet versions. Is that what you are referring to?

**Comment by warrenbuckley** [comment]
@iOvergaard Yes its the devcontainer not working correctly unless it has been fixed now?
So when someone clicks to create a Codespace from the Github repo it will create/use the devcontainer and its that which is failing.
