### ISSUE TITLE
[BUG] Editing default member type doesn't work when over 500 members exist

### ISSUE THREAD

**Issue by nymwo** [umbraco/Umbraco-CMS#17046]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

When having over 500 members, editing and saving the default member type fails and generates an error. The error indicates that RefreshMemberOfMemberTypes calls MemberService.GetAll with an invalid skip value.

### Specifics

The exception:

```
An unhandled exception has occurred while executing the request.
System.AggregateException: One or more errors occurred. (Invalid skip/take, Skip must be a multiple of take - i.e. skip = 10, take = 5)
 ---> System.ArgumentException: Invalid skip/take, Skip must be a multiple of take - i.e. skip = 10, take = 5
   at Umbraco.Cms.Core.PaginationHelper.ConvertSkipTakeToPaging(Int32 skip, Int32 take, Int64& pageNumber, Int32& pageSize)
   at Umbraco.Cms.Core.Services.IMemberService.GetAll(Int32 skip, Int32 take, Int64& totalRecords, String orderBy, Direction orderDirection, String memberTypeAlias, String filter)
   at Umbraco.Cms.Infrastructure.Search.ContentTypeIndexingNotificationHandler.RefreshMemberOfMemberTypes(Int32[] memberTypeIds)
   at Umbraco.Cms.Infrastructure.Search.ContentTypeIndexingNotificationHandler.Handle(ContentTypeCacheRefresherNotification args)
   at Umbraco.Cms.Core.Events.INotificationHandler`1.Handle(IEnumerable`1 notifications)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishCore[TNotification](IEnumerable`1 allHandlers, IEnumerable`1 notifications)
   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.Handle[TNotification,TNotificationHandler](IEnumerable`1 notifications, ServiceFactory serviceFactory, Action`2 publish)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishNotifications[TNotification,TNotificationHandler](IEnumerable`1 notifications)
   at Umbraco.Cms.Core.Events.EventAggregator.Publish[TNotification,TNotificationHandler](IEnumerable`1 notifications)
   at Umbraco.Cms.Core.Events.EventAggregator.Publish[TNotification](TNotification notification)
   at Umbraco.Cms.Core.Cache.CacheRefresherBase`1.OnCacheUpdated(CacheRefresherNotification notification)
   at Umbraco.Cms.Core.Cache.PayloadCacheRefresherBase`2.Refresh(TPayload[] payloads)
   at Umbraco.Cms.Core.Cache.ContentTypeCacheRefresher.Refresh(JsonPayload[] payloads)
   at Umbraco.Cms.Infrastructure.Sync.ServerMessengerBase.DeliverLocal[TPayload](ICacheRefresher refresher, TPayload[] payload)
   at Umbraco.Cms.Infrastructure.Sync.ServerMessengerBase.Deliver[TPayload](ICacheRefresher refresher, TPayload[] payload)
   at Umbraco.Cms.Infrastructure.Sync.ServerMessengerBase.QueueRefresh[TPayload](ICacheRefresher refresher, TPayload[] payload)
```

### Steps to reproduce

1. Have over 500 members
2. Try to edit and save the member type "Member" in Backoffice

**Comment by NguyenThuyLan** [comment]
Hi @nymwo , thanks for reporting the issue.
I was not able to reproduce it. I tried on v14.31. and v15

https://github.com/user-attachments/assets/e779010f-4018-46fa-8a72-caa9de4e0a99

I will close this because I couldn't reproduce it

**Comment by nymwo** [comment]
This is still a problem for my project. Do I have to create a new issue?

I was able to reproduce the bug in a new Umbraco 14.3.1 project. The error message in the backoffice UI is different, but the logged error is the same (Invalid skip/take):

![image](https://github.com/user-attachments/assets/9018f0d1-c798-412d-b1cc-97cb1fb6d255)

**Comment by NguyenThuyLan** [comment]
Sorry @nymwo , I will check it again for you

**Comment by NguyenThuyLan** [comment]
I was able to reproduce on v15.1.1 and v14.3.1
Although the data is still saved, the response returned from the update /umbraco/management/api/v1/member-type/{id} member type API is incorrect.
<img width="1085" alt="image" src="https://github.com/user-attachments/assets/2dc632de-78db-4efc-a29b-67498cf5ba0f" />
<img width="1262" alt="image" src="https://github.com/user-attachments/assets/fe95cde8-31d1-4da5-9fff-9b216f47bf8e" />

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/18069 🚀

**Comment by nymwo** [comment]
Great! Are you planning on fixing this in Umbraco 14 as well?

**Comment by Zeegaan** [comment]
@nymwo No we are not. Our stance for 14 in particular, is that if its not a regression issue, it will not be fixed in 14 specifically. 
I would urge you to upgrade to 15 if you need this, as the upgrade should not be difficult.

The stance is due to multiple reasons (such as the frontend having an entirely different repo, making it impossible to cherry-pick fixes).
