### ISSUE TITLE
Upgrading v10 to v13 causes sql timeout exception during migration on azure

### ISSUE THREAD

**Issue by deMD** [umbraco/Umbraco-CMS#17224]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13

### Bug summary

When trying to upgrade Umbraco to v13 in azure we get a timeout exception during v12 migration script "V_12_0_0.UseNvarcharInsteadOfNText"

### Specifics

When trying to upgrade Umbraco to v13 in azure we get a timeout exception during v12 migration script "V_12_0_0.UseNvarcharInsteadOfNText" as per logs: 
```
Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
Operation cancelled by user.
The statement has been terminated.
 ---> System.ComponentModel.Win32Exception (258): The wait operation timed out.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 261
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<ExecuteNonQuery>b__32_0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass38_0`1.<Execute>b__0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteNonQuery()
   at NPoco.Database.<>c__DisplayClass296_0.<ExecuteNonQueryHelper>b__0()
   at NPoco.Database.ExecutionHook[T](Func`1 action)
   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)
   at NPoco.Database.Execute(Sql Sql)
   at Umbraco.Cms.Infrastructure.Migrations.Upgrade.V_12_0_0.UseNvarcharInsteadOfNText.MigrateNtextColumn[TDto](String columnName, String tableName, Expression`1 fieldSelector, Boolean nullable)
   at Umbraco.Cms.Infrastructure.Migrations.Upgrade.V_12_0_0.UseNvarcharInsteadOfNText.Migrate()
   at Umbraco.Cms.Infrastructure.Migrations.MigrationBase.Run()
   at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.RunMigration(Type migrationType, MigrationContext context)
   at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.RunScopedMigration(Type migrationType, MigrationPlan plan)
   at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.RunMigrationPlan(MigrationPlan plan, String fromState)
   ```
   
   We have tried to edit the connection timeout in the connection string, as it seems the timeout occurs after 30 seconds but that doesn't seem to work. Scaling the DB up all the way to a SKU of S7 also doesn't work.
   
It seems PR mentioned in https://github.com/umbraco/Umbraco-CMS/issues/13354 was reverted in V11, is their any other way to increate the command timeout during migrations?

### Steps to reproduce

Update an existing v10 site to v13. I don't know if the amount of content matters, but that could have an impact on execution performance.

**Comment by deMD** [comment]
Update, setting the connection timeout does also update the command timeout still, but even at 2 minutes the migration times out...

**Comment by tbolon** [comment]
Perhaps if you could identify the impacted column, try migrating the columns from NTEXT to NVARCHAR(MAX) manually outside the app the impacted columns? So the migration will be a noop and succeed?

The migrated columns are listed in https://github.com/umbraco/Umbraco-CMS/blob/v13/contrib/src/Umbraco.Infrastructure/Migrations/Upgrade/V_12_0_0/UseNvarcharInsteadOfNText.cs.

I *think* ntext and nvarchar(max) are compatible for every operation, so you could migrate the column before running the upgrade scripts.

**Comment by deMD** [comment]
I found out what the issue was and do feel like this is something that should somehow be mitigated and/or documented. The issue was with the PropertyData table. This table contains all values for all properties across all versions for said property, which in this case was a table containing 61k records. In this case I could clean up the versions so the table could be updated. Though in some jurisdictions you are not allowed to delete data for an extended period of time (even if you have a backup) so this is not always an option.

We also figured out that setting the connection string timeout to a high enough value also changes the command timeout, though that still seems like a bad workaround as they are two completely different concepts (but at least it wasn't reverted).

It would be nice if Umbraco could optimize migrations based on the recommended Azure database Tier (DTU S2) and set the command timeout to a more sensible value when doing (potentially) heavy migrations  (f.e. altering column types for large tables). Next to that also consider adding a separate setting to override the command timeout.
