### ISSUE TITLE
v15: Publish content gives "Could not find a datatype.." after adding Block Grid

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#17229]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v15-rc1

### Bug summary

I've created a new instance of v15-rc1, setup models builder and added a simple Block Grid with just one block that uses a element type called "Text" that hosts a RTE.

The error message says to restart which does work but it seems quite broken having to restart after changes like this.

### Specifics

When saving the content after adding the Block Grid I get this error

![image](https://github.com/user-attachments/assets/f8a42801-80c0-4d75-9e51-46b568f9c625)

Here the error details

```
One or more compilation references may be missing. If you're seeing this in a published application, set 'CopyRefAssembliesToPublishDirectory' to true in your project file to ensure files in the refs directory are published.

{
    "type": "Error",
    "title": "Could not find a datatype with identifier 1067. (Parameter 'id')",
    "status": 500,
    "detail": "   at Umbraco.Cms.Core.Models.PublishedContent.PublishedContentTypeFactory.GetDataType(Int32 id)\r\n   at Umbraco.Cms.Core.Models.PublishedContent.PublishedPropertyType..ctor(String propertyTypeAlias, Int32 dataTypeId, Boolean isUserProperty, ContentVariation variations, PropertyValueConverterCollection propertyValueConverters, IPublishedModelFactory publishedModelFactory, IPublishedContentTypeFactory factory)\r\n   at Umbraco.Cms.Core.Models.PublishedContent.PublishedPropertyType..ctor(IPublishedContentType contentType, IPropertyType propertyType, PropertyValueConverterCollection propertyValueConverters, IPublishedModelFactory publishedModelFactory, IPublishedContentTypeFactory factory)\r\n   at Umbraco.Cms.Core.Models.PublishedContent.PublishedContentTypeFactory.CreatePropertyType(IPublishedContentType contentType, IPropertyType propertyType)\r\n   at Umbraco.Cms.Core.Models.PublishedContent.PublishedContentType.<>c__DisplayClass2_0.<.ctor>b__0(IPropertyType x)\r\n   at System.Linq.Enumerable.IteratorSelectIterator`2.ToListNoPresizing()\r\n   at System.Linq.Enumerable.IteratorSelectIterator`2.ToList()\r\n   at Umbraco.Cms.Core.Models.PublishedContent.PublishedContentType..ctor(IContentTypeComposition contentType, IPublishedContentTypeFactory factory)\r\n   at Umbraco.Cms.Core.Models.PublishedContent.PublishedContentTypeFactory.CreateContentType(IContentTypeComposition contentType)\r\n   at Umbraco.Cms.Core.PublishedCache.PublishedContentTypeCache.CreatePublishedContentType(PublishedItemType itemType, Int32 id)\r\n   at Umbraco.Cms.Core.PublishedCache.PublishedContentTypeCache.Get(PublishedItemType itemType, Int32 id)\r\n   at Umbraco.Cms.Infrastructure.HybridCache.Factories.PublishedContentFactory.ToIPublishedContent(ContentCacheNode contentCacheNode, Boolean preview)\r\n   at Umbraco.Cms.Infrastructure.HybridCache.Services.DocumentCacheService.GetByIdAsync(Int32 id, Boolean preview)\r\n   at Umbraco.Cms.Infrastructure.HybridCache.DocumentCache.GetByIdAsync(Int32 id, Boolean preview)\r\n   at Umbraco.Cms.Infrastructure.HybridCache.DocumentCache.GetById(Int32 contentId)\r\n   at Umbraco.Cms.Infrastructure.Routing.RedirectTracker.StoreOldRoute(IContent entity, Dictionary`2 oldRoutes)\r\n   at Umbraco.Cms.Core.Routing.RedirectTrackingHandler.StoreOldRoutes(IEnumerable`1 entities, IStatefulNotification notification)\r\n   at Umbraco.Cms.Core.Routing.RedirectTrackingHandler.Handle(ContentPublishingNotification notification)\r\n   at Umbraco.Cms.Core.Events.INotificationHandler`1.Handle(IEnumerable`1 notifications)\r\n   at Umbraco.Cms.Core.Events.EventAggregator.PublishCore[TNotification](IEnumerable`1 allHandlers, IEnumerable`1 notifications)\r\n   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.Handle[TNotification,TNotificationHandler](IEnumerable`1 notifications, ServiceFactory serviceFactory, Action`2 publish)\r\n   at Umbraco.Cms.Core.Events.EventAggregator.PublishNotifications[TNotification,TNotificationHandler](IEnumerable`1 notifications)\r\n   at Umbraco.Cms.Core.Events.EventAggregator.Publish[TNotification,TNotificationHandler](IEnumerable`1 notifications)\r\n   at Umbraco.Cms.Core.Events.EventAggregator.Publish[TNotification](TNotification notification)\r\n   at Umbraco.Cms.Core.Events.ScopedNotificationPublisher`1.PublishCancelable(ICancelableNotification notification)\r\n   at Umbraco.Cms.Core.Services.ContentService.Publish(IContent content, String[] cultures, Int32 userId)\r\n   at Umbraco.Cms.Core.Services.ContentPublishingService.PublishAsync(Guid key, CultureAndScheduleModel cultureAndSchedule, Guid userKey)\r\n   at Umbraco.Cms.Api.Management.Controllers.Document.PublishDocumentController.Publish(CancellationToken cancellationToken, Guid id, PublishDocumentRequestModel requestModel)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Umbraco.Cms.Web.Common.Middleware.BasicAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Umbraco.Cms.Api.Management.Middleware.BackOfficeExternalLoginProviderErrorMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)\r\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\r\n   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\\projects\\dotnet\\src\\MiniProfiler.AspNetCore\\MiniProfilerMiddleware.cs:line 112\r\n   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)",
    "instance": "ArgumentException"
}
```

Also my models-folder got wiped and contained a `models.err`-file:
```
Failed to build Live models.
Could not find a datatype with identifier 1067. (Parameter 'id')

   at Umbraco.Cms.Core.Models.PublishedContent.PublishedContentTypeFactory.GetDataType(Int32 id)
   at Umbraco.Cms.Core.Models.PublishedContent.PublishedPropertyType..ctor(String propertyTypeAlias, Int32 dataTypeId, Boolean isUserProperty, ContentVariation variations, PropertyValueConverterCollection propertyValueConverters, IPublishedModelFactory publishedModelFactory, IPublishedContentTypeFactory factory)
   at Umbraco.Cms.Core.Models.PublishedContent.PublishedPropertyType..ctor(IPublishedContentType contentType, IPropertyType propertyType, PropertyValueConverterCollection propertyValueConverters, IPublishedModelFactory publishedModelFactory, IPublishedContentTypeFactory factory)
   at Umbraco.Cms.Core.Models.PublishedContent.PublishedContentTypeFactory.CreatePropertyType(IPublishedContentType contentType, IPropertyType propertyType)
   at Umbraco.Cms.Core.Models.PublishedContent.PublishedContentType.<>c__DisplayClass2_0.<.ctor>b__0(IPropertyType x)
   at System.Linq.Enumerable.IteratorSelectIterator`2.ToListNoPresizing()
   at System.Linq.Enumerable.IteratorSelectIterator`2.ToList()
   at Umbraco.Cms.Core.Models.PublishedContent.PublishedContentType..ctor(IContentTypeComposition contentType, IPublishedContentTypeFactory factory)
   at Umbraco.Cms.Core.Models.PublishedContent.PublishedContentTypeFactory.CreateContentType(IContentTypeComposition contentType)
   at Umbraco.Cms.Infrastructure.ModelsBuilder.UmbracoServices.GetTypes(PublishedItemType itemType, IContentTypeComposition[] contentTypes)
   at Umbraco.Cms.Infrastructure.ModelsBuilder.UmbracoServices.GetAllTypes()
   at Umbraco.Cms.Infrastructure.ModelsBuilder.Building.ModelsGenerator.GenerateModels()
   at Umbraco.Cms.Infrastructure.ModelsBuilder.AutoModelsNotificationHandler.GenerateModelsIfRequested()

```

### Steps to reproduce

* Setup new V15-rc1
* Setup Models Builder (SourceCodeAuto)
* Create a "Home" document type (allow at root etc)
* Create a node in the content-section using this Content Type, save and publish
* Create Element Type called "Text", add RTE to element type
* Create Data Type called "Block Grid", add "Text" element type as allowed block.
* Add "Block Grid" to the "Home" Document Type
* Go back to to Content, open "Home", add a block and "Save and Publish"

### Expected result / actual result

Models should be generated and Home page published.

**Comment by Zeegaan** [comment]
I suspect this will be fixed by https://github.com/umbraco/Umbraco-CMS/pull/17180 🤔

**Comment by Zeegaan** [comment]
Yep tested with this fix applied, and the issue no longer persists, I will go ahead and close this 😁
