### ISSUE TITLE
V14 media drag and drop upload returns error in console, for folder 

### ISSUE THREAD

**Issue by davidkosir2** [umbraco/Umbraco-CMS#17493]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.1

### Bug summary

Drag and drop works for .txt files. Tried to upload .bacpac file and returns this error in console (F12):

Uncaught (in promise) TypeError: e.createReader is not a function
    at Je._mkdir (index.js:2913:1635)
    at Je._getAllEntries (index.js:2913:1446)
    at Je._onDrop (index.js:2913:2515)

Uploading whole folder with files does not show any errors, just ignores the action.

![image](https://github.com/user-attachments/assets/7e687c83-0723-4593-b6f1-c94ecb53c9e0)

### Specifics

https://{domain}/umbraco/section/media/view/media/collection/grid

### Steps to reproduce

- Install Umbraco 14.3.1 project
- Go to Media tab
- Open Developer console (F12)
- Drag and drop .bacpac file to dropoff zone
- Drag and drop whole Folder to dropoff zone

### Expected result / actual result

When uploading .bacpac file, returns error in console, when uploading folder, no errors expected anywhere.

---
_This item has been added to our backlog AB#46446_

**Comment by iOvergaard** [comment]
The issue with uploading a folder should be resolved in 15.1.0 with #16484. What remains is then to make sure the UX is better for file types that may not be supported and/or do not have a direct mapping to any media item.

**Comment by iOvergaard** [comment]
This is fixed with #18113 for version 15.3.
