### ISSUE TITLE
Data migration failed from v13 to v14

### ISSUE THREAD

**Issue by ssplyuvrajsingh** [umbraco/Umbraco-CMS#17628]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.5.2

### Bug summary

**Error while migrating data from v13 to v14**

```
Plan Umbraco.Core failed at step {1A0FBC8A-6FC6-456C-805C-B94816B2E570}
System.Text.Json.JsonException: Expected start object
   at Umbraco.Cms.Infrastructure.Serialization.JsonBlockValueConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.ReadAsObject(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.CastingConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Umbraco.Cms.Infrastructure.Serialization.SystemTextJsonSerializerBase.Deserialize[T](String input)
   at Umbraco.Cms.Core.Models.Blocks.BlockEditorDataConverter`2.Deserialize(String json)
   at Umbraco.Cms.Core.PropertyEditors.BlockEditorValues`2.DeserializeAndClean(Object propertyValue)
   at Umbraco.Cms.Core.PropertyEditors.BlockEditorPropertyValueEditor`2.GetAllPropertyValues(Object value)+MoveNext()
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at Umbraco.Cms.Core.PropertyEditors.BlockEditorPropertyValueEditor`2.GetReferences(Object value)+MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Umbraco.Cms.Core.PropertyEditors.DataValueReferenceFactoryCollection.GetReferencesEnumerable(IDataEditor dataEditor, IEnumerable`1 values)+MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToHashSet[TSource](IEnumerable`1 source, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToHashSet[TSource](IEnumerable`1 source)
   at Umbraco.Cms.Core.PropertyEditors.DataValueReferenceFactoryCollection.GetReferences(IDataEditor dataEditor, IEnumerable`1 values)
   at Umbraco.Cms.Core.PropertyEditors.DataValueReferenceFactoryCollection.GetAllReferences(IPropertyCollection properties, PropertyEditorCollection propertyEditors)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentRepositoryBase`3.PersistRelations(TEntity entity)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.DocumentRepository.PersistUpdatedItem(IContent entity)
   at Umbraco.Cms.Core.Cache.DefaultRepositoryCachePolicy`2.Update(TEntity entity, Action`1 persistUpdated)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.EntityRepositoryBase`2.Save(TEntity entity)
   at Umbraco.Cms.Core.Services.ContentService.SaveBlueprint(IContent content, Int32 userId)
   at Umbraco.Cms.Infrastructure.Migrations.Upgrade.V_14_0_0.MoveDocumentBlueprintsToFolders.Migrate()
   at Umbraco.Cms.Infrastructure.Migrations.MigrationBase.Run()
   at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.RunMigration(Type migrationType, MigrationContext context)
   at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.RunScopedMigration(Transition transition, MigrationPlan plan)
   at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.RunMigrationPlan(MigrationPlan plan, String fromState)
[17:28:24 ERR] Database configuration failed
System.Text.Json.JsonException: Expected start object
   at Umbraco.Cms.Infrastructure.Serialization.JsonBlockValueConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.ReadAsObject(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.CastingConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Umbraco.Cms.Infrastructure.Serialization.SystemTextJsonSerializerBase.Deserialize[T](String input)
   at Umbraco.Cms.Core.Models.Blocks.BlockEditorDataConverter`2.Deserialize(String json)
   at Umbraco.Cms.Core.PropertyEditors.BlockEditorValues`2.DeserializeAndClean(Object propertyValue)
   at Umbraco.Cms.Core.PropertyEditors.BlockEditorPropertyValueEditor`2.GetAllPropertyValues(Object value)+MoveNext()
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at Umbraco.Cms.Core.PropertyEditors.BlockEditorPropertyValueEditor`2.GetReferences(Object value)+MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Umbraco.Cms.Core.PropertyEditors.DataValueReferenceFactoryCollection.GetReferencesEnumerable(IDataEditor dataEditor, IEnumerable`1 values)+MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToHashSet[TSource](IEnumerable`1 source, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToHashSet[TSource](IEnumerable`1 source)
   at Umbraco.Cms.Core.PropertyEditors.DataValueReferenceFactoryCollection.GetReferences(IDataEditor dataEditor, IEnumerable`1 values)
   at Umbraco.Cms.Core.PropertyEditors.DataValueReferenceFactoryCollection.GetAllReferences(IPropertyCollection properties, PropertyEditorCollection propertyEditors)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentRepositoryBase`3.PersistRelations(TEntity entity)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.DocumentRepository.PersistUpdatedItem(IContent entity)
   at Umbraco.Cms.Core.Cache.DefaultRepositoryCachePolicy`2.Update(TEntity entity, Action`1 persistUpdated)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.EntityRepositoryBase`2.Save(TEntity entity)
   at Umbraco.Cms.Core.Services.ContentService.SaveBlueprint(IContent content, Int32 userId)
   at Umbraco.Cms.Infrastructure.Migrations.Upgrade.V_14_0_0.MoveDocumentBlueprintsToFolders.Migrate()
   at Umbraco.Cms.Infrastructure.Migrations.MigrationBase.Run()
   at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.RunMigration(Type migrationType, MigrationContext context)
   at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.RunScopedMigration(Transition transition, MigrationPlan plan)
   at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.RunMigrationPlan(MigrationPlan plan, String fromState)
[17:28:24 ERR] Failed DatabaseUpgradeStep, with the message: The database failed to upgrade. ERROR: The database configuration failed with the following message: Expected start object
 Please check log file for additional information (can be found in 'LoggingSettings.Directory')
```

### Steps to reproduce

![image](https://github.com/user-attachments/assets/394a308e-4fbb-4f57-ae72-95cbea4e2dca)

**Comment by bergmania** [comment]
Hi @ssplyuvrajsingh 

Thanks for reporting.
It looks like you have some blueprints/ Content templates, that contain some unexpected data in some block based types. Are you able to save all the blueprints in the v13 solution?

**Comment by ssplyuvrajsingh** [comment]
Hi @bergmania 

I got it why I am facing this issue, I explain to you step by step below -

Step 1: First our project in V10 so here firstly I converted nested content to a block list with data by using uSync Migrations package.

Step 2: Secondly, I migrate db from V10 to V11, V11 to V12, and V12 to V13.

Step 3: When I was trying to migrate V13 to V14 at this time I faced that issue.

So the issue with the uSync Migration package, if I did not use this package and try to migrate then successfully migrate db V10 to V14 but now I lost nested content data. So here is a new issue If I am not using the uSync Migration package then how to convert nested content to block list and recover data?

**Comment by bergmania** [comment]
I'm not an expert  in uSync Migration, but based on the stacktrace, some blueprints contain data that is not json, when json is expected. I think, we need to understand what the current data is, and maybe it will be fixed automatically by just saving the existing blueprints, and maybe it will show up when you try to save the blueprint, and then we can dive even deeper.

**Comment by bergmania** [comment]
In understand that part - Nested content is no more, and there are different ways to migration - Like you say uSync Migrator, Umbraco Deploy or manually. But when using uSync, what is the content afterwards? Based on the stack trace it is not JSON.

**Comment by bielu** [comment]
I dont think usync migrations by default affects content templates, but I might be wrong here 🤔 so I would check if usync actually updated properties in content templates, if not there will be need of writing handler for content template, which shouldn't be too complicated ;p

**Comment by AndyButland** [comment]
Error handling added in https://github.com/umbraco/Umbraco-CMS/pull/18576 and due in 16.0.0-rc3.
