### ISSUE TITLE
Unsupported migration paths block Umbraco from loading without logging

### ISSUE THREAD

**Issue by timgaunt** [umbraco/Umbraco-CMS#17672]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.5.1

### Bug summary

When running a site that has an invalid path in the umbracoKeyValue table in product mode, the site loads with the Umbraco failed screen but there's nothing in the logs

### Specifics

When there is an invalid migration path and the developer is running locally there is a nice error message explaining the issue:

```
 
BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details. -> Umbraco.Cms.Core.Exceptions.BootFailedException: The migration plan does not support migrating from state "006909ca-4940-475b-abe5-63a25f2d5aa5". -> System.InvalidOperationException: The migration plan does not support migrating from state "006909ca-4940-475b-abe5-63a25f2d5aa5". at Umbraco.Cms.Infrastructure.Migrations.MigrationPlan.ThrowOnUnknownInitialState(String state) at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.RunMigrationPlan(MigrationPlan plan, String fromState) at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.ExecutePlan(MigrationPlan plan, String fromState) at 
...
 ```

However when this is run on the server, there is no logging at all to explain the issue and the Umbraco "Boot Failed" screen is all you get (the same one when the database can't be contacted).

<img width="619" alt="image" src="https://github.com/user-attachments/assets/15b9c92b-b4eb-454d-bcfd-18fa3b0330a5">

The issue is there is no logging to explain that there is an issue so to track it down you have to run the site in Debug mode.

It would be helpful if there was extra logging before throwing an exceptopn to make it easier to track down. I think something here would make sense: https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.Infrastructure/Migrations/MigrationPlanExecutor.cs#L53

### Steps to reproduce

Create a migration that doesn't have a valid path

### Expected result / actual result

Some form of log message to indicate what went wrong.

**Comment by AndyButland** [comment]
Thanks for raising this @timgaunt - and the related PR where you've looked to add this logging.  On reading I was a little surprised that this should be necessary though.  As you note, in production we don't display the full details of the error on screen, rather just the more generic "Boot failed" message.  But under the hood an exception is still thrown, so I would have expected it would be available in the logs.

So to test I spun up a new Umbraco Cloud website running Umbraco 13, then went into the database and modified the value in `umbracoKeyValue` so it wouldn't be recognised.  Then restarted the environment.  As expected, I see the "Boot failed" message.

But when I look at the logs, I see the detail of the underlying exception:

```
2025-01-31 11:22:22 ERR Database configuration failed
System.InvalidOperationException: The migration plan does not support migrating from state "{CC47C751-A81B-489A-A2BC-0240245DB688}".
at Umbraco.Cms.Infrastructure.Migrations.MigrationPlan.ThrowOnUnknownInitialState(String state)
at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.RunMigrationPlan(MigrationPlan plan, String fromState)
at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.ExecutePlan(MigrationPlan plan, String fromState)
at Umbraco.Cms.Infrastructure.Migrations.Upgrade.Upgrader.Execute(IMigrationPlanExecutor migrationPlanExecutor, ICoreScopeProvider scopeProvider, IKeyValueService keyValueService)
at Umbraco.Cms.Infrastructure.Migrations.Install.DatabaseBuilder.UpgradeSchemaAndData(UmbracoPlan plan)
```

Which is the same as you would have seen on-screen if you were running in debug mode.

So I think we should close this and the related PR, as the additional logging isn't really adding any additional information, and would mostly be repeating what's already in the logs.

Please let me know what you think though.

**Comment by AndyButland** [comment]
I'll close this now since there was no further discussion.
