### ISSUE TITLE
ExamineIndexes FileNotFoundException During Indexing

### ISSUE THREAD

**Issue by AndreasLBorgTwoday** [umbraco/Umbraco-CMS#17686]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.4.1 (Issue also observed in 10.8.2)

### Bug summary

The ExamineIndexes process intermittently fails with a `System.IO.FileNotFoundException`, referencing a missing file in the `ExamineIndexes` directory. This issue persists across multiple Umbraco versions and environments.

Observed in versions: 10.8.2, 13.4.1
Occurrences: 4-6 times over six months.

### Specifics

```
System.IO.FileNotFoundException: Could not find file 'C:\home\site\wwwroot\umbraco\Data\TEMP\ExamineIndexes\InternalIndex\_7j.si'.
File name: 'C:\home\site\wwwroot\umbraco\Data\TEMP\ExamineIndexes\InternalIndex\_7j.si'
...
```

![image](https://github.com/user-attachments/assets/e394d929-4cb7-4226-998d-e0da83fba750)
![image](https://github.com/user-attachments/assets/8cfcffaa-0aaa-4076-b060-d3543c4aae19)

Temporary Fix: Deleting the folder wwwroot\umbraco\Data\TEMP\ExamineIndexes\ and rebooting the site temporarily resolves the issue.
Affected URL: Not URL-specific. The error occurs during Examine indexing.
Browser Check: Not browser-related.

### Steps to reproduce

This issue cannot be consistently reproduced. It occurs intermittently, typically during Examine indexing operations. The problem has been observed under the following conditions:

1. Normal site operation over an extended period.
2. Indexing operations triggered by standard system behavior.

### Expected result / actual result

Expected result
Examine indexing completes without errors, and the system handles all files in the ExamineIndexes directory correctly.

Actual result
The indexing process fails intermittently, throwing a System.IO.FileNotFoundException related to a missing file in the ExamineIndexes directory. The site requires manual intervention (folder deletion and reboot) to temporarily resolve the issue.

**Comment by DarylvdbergDC** [comment]
Hey!

Is there any progress on this issue? We're also experiencing similar issues in multiple or our project running on version 13 and 14.
Would be great if this issue could get some attention.

**Comment by AndreasLBorgTwoday** [comment]
> Hey!
> 
> Is there any progress on this issue? We're also experiencing similar issues in multiple or our project running on version 13 and 14. Would be great if this issue could get some attention.

Hi Daryl,
No not from what I know. We still experience it from time to time. It's rare, but still happens.

**Comment by AndyButland** [comment]
Whilst I don't have anything specific to update on the reported issue I'm afraid, I do just want to leave a response to say it's not going unheard.  There have been several updates of Examine over the past year targeted at fixing reliability issues, so for anyone encountering problems I'd say first please make sure you are on the latest version of Examine - either by updating Umbraco to the latest 13 or 16, or upgrading the Examine dependency on it's own.

After that, as you'll appreciate, sporadic, hard to reproduce bugs in an upstream dependency are tricky to replicate and resolve, particularly without log files or stack traces to try to pinpoint the problem.  So if anything concrete like that can be reported, it would be appreciated.

**Comment by TimBoonstra** [comment]
We're running into this issue pretty much every other day on a load balanced environment, so if we can provide any additional data please let us know using the latest umbraco v13 


`System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\WINDOWS\TEMP\ExamineIndexes\75a28c78d699da38f8b9afea0e56eb68\InternalIndex\_0.cfs'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Lucene.Net.Store.MMapDirectory.OpenInput(String name, IOContext context)
   at Lucene.Net.Store.MMapDirectory.CreateSlicer(String name, IOContext context)
   at Lucene.Net.Store.NRTCachingDirectory.CreateSlicer(String name, IOContext context)
   at Lucene.Net.Store.CompoundFileDirectory..ctor(Directory directory, String fileName, IOContext context, Boolean openForWrite)
   at Lucene.Net.Index.SegmentReader.ReadFieldInfos(SegmentCommitInfo info)
   at Lucene.Net.Index.SegmentReader..ctor(SegmentCommitInfo si, Int32 termInfosIndexDivisor, IOContext context)
   at Lucene.Net.Index.ReadersAndUpdates.GetReader(IOContext context)
   at Lucene.Net.Index.ReadersAndUpdates.GetReadOnlyClone(IOContext context)
   at Lucene.Net.Index.StandardDirectoryReader.Open(IndexWriter writer, SegmentInfos infos, Boolean applyAllDeletes)
   at Lucene.Net.Index.IndexWriter.GetReader(Boolean applyAllDeletes)
   at Lucene.Net.Index.DirectoryReader.Open(IndexWriter writer, Boolean applyAllDeletes)
   at Lucene.Net.Search.SearcherManager..ctor(IndexWriter writer, Boolean applyAllDeletes, SearcherFactory searcherFactory)
   at Examine.Lucene.Providers.LuceneIndex.CreateSearcher()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Examine.Lucene.Providers.LuceneIndex.get_Searcher()
`

**Comment by AndreasLBorgTwoday** [comment]
Hi @TimBoonstra,

I actually haven’t seen this error in quite a while. Which exact version are you running atm?
Is it on a site with a lot of content/nodes?
Also, are you updating the content with an import or something similar?

**Comment by TimBoonstra** [comment]
Pretty much every Umbraco v13 release, currently 13.10.0, pretty much in hope its fixed.
Currently the internal index has 61913 items. 

We do use expand on the external index and the members index with some crappy code.. 

`    public void Configure(string name, LuceneDirectoryIndexOptions options)
    {
        if (name.Equals(Umbraco.Cms.Core.Constants.UmbracoIndexes.ExternalIndexName))
        {
            options.FieldDefinitions.AddOrUpdate(new FieldDefinition("sTCDate", FieldDefinitionTypes.DateTime));
            options.FieldDefinitions.AddOrUpdate(new FieldDefinition("modStatus", FieldDefinitionTypes.Integer));
            options.FieldDefinitions.AddOrUpdate(new FieldDefinition("companyId", FieldDefinitionTypes.Integer));
            options.FieldDefinitions.AddOrUpdate(new FieldDefinition("aircraftProgramId", FieldDefinitionTypes.InvariantCultureIgnoreCase));
            options.FieldDefinitions.AddOrUpdate(new FieldDefinition("aircraftTypeId", FieldDefinitionTypes.InvariantCultureIgnoreCase));
            options.FieldDefinitions.AddOrUpdate(new FieldDefinition("categoryId", FieldDefinitionTypes.InvariantCultureIgnoreCase));
        }

        if (name.Equals(Umbraco.Cms.Core.Constants.UmbracoIndexes.MembersIndexName))
        {
            var additionalFields = new[] { "company", "country", "fullName", "role", "isApproved" };
            options.Validator = new MemberValueSetValidator(null, null, MemberValueSetValidator.DefaultMemberIndexFields.Concat(additionalFields), null);
            options.FieldDefinitions.AddOrUpdate(new FieldDefinition("companyId", FieldDefinitionTypes.Integer));
            options.FieldDefinitions.AddOrUpdate(new FieldDefinition("role", FieldDefinitionTypes.Integer));
            options.FieldDefinitions.AddOrUpdate(new FieldDefinition("isApproved", FieldDefinitionTypes.Integer));

        }

    }
`
and the enricher:

`    public class ExamineIndexModificationComponent(IExamineManager examineManager, IUmbracoContextFactory umbracoContextFactory, ILogger<ExamineIndexModificationComponent> logger, IMemberService memberService) : IComponent
    {
        public void Initialize()
        {
            if (examineManager.TryGetIndex(Umbraco.Cms.Core.Constants.UmbracoIndexes.ExternalIndexName, out var externalIndex))
            {
                ((BaseIndexProvider)externalIndex).TransformingIndexValues += IndexerEnricherModification;
            }

            if (examineManager.TryGetIndex(Umbraco.Cms.Core.Constants.UmbracoIndexes.MembersIndexName, out var membersIndex))
            {
                ((BaseIndexProvider)membersIndex).TransformingIndexValues += IndexerEnricherMembers;
            }
        }

        private void IndexerEnricherModification(object? sender, IndexingItemEventArgs e)
        {
            if (e.ValueSet.Category == IndexTypes.Content
                && string.Equals(Modification.ModelTypeAlias, e.ValueSet.ItemType, StringComparison.InvariantCultureIgnoreCase))
            {
                try
                {
                    var values = e.ValueSet.Values.ToDictionary(x => x.Key, x => x.Value.ToList());

                    var strValue = (e.ValueSet.GetValue("modStatus")?.ToString());
                    if (!string.IsNullOrWhiteSpace(strValue))
                    {
                        var val = System.Text.Json.JsonSerializer.Deserialize<string[]>(strValue);
                        if (val.Length > 0 && Enum.TryParse(val[0], true, out EnumModStatus enumValue))
                        {
                            values["modStatus"] = [(int)enumValue];
                        }
                    }

                    if (int.TryParse((e.ValueSet.GetValue("parentID")?.ToString()), out var companyId) && companyId > 0)
                    {
                        values["companyId"] = [companyId];
                    }

                    using var ctx = umbracoContextFactory.EnsureUmbracoContext();
                    var content = umbracoContextFactory.EnsureUmbracoContext().UmbracoContext.Content;

                    var aircraftTypes = (e.ValueSet.GetValue("umbRelation_AircraftType_Modification")?.ToString() ?? "").Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
                    var aircraftTypeIds = new List<object>();
                    var aicraftProgramIds = new List<object>();
                    var categoryIds = UdiGuidsToIds("umbRelation_ModificationCategory_Modification", e.ValueSet, content);

                    foreach (var aircraftType in aircraftTypes)
                    {
                        var udi = UdiParser.Parse(aircraftType);
                        var aircraftId = content.GetById(udi)?.Id;
                        var aircraftProgramId = content.GetById(udi)?.Parent?.Id;
                        if (aircraftId is > 0) aircraftTypeIds.Add(aircraftId.Value);
                        if (aircraftProgramId is > 0) aicraftProgramIds.Add(aircraftProgramId.Value);
                    }

                    values["aircraftTypeId"] = aircraftTypeIds;
                    values["aircraftProgramId"] = aicraftProgramIds;
                    values["categoryId"] = categoryIds;

                    e.SetValues(values.ToDictionary(x => x.Key, x => (IEnumerable<object>)x.Value));
                }
                catch (Exception ex)
                {
                    logger.LogError(ex, "Error updating node: {nodeId}, type: {nodeType} err: {err}", e.ValueSet.Id, e.ValueSet.ItemType, ex.Message);
                }
            }
        }

        private void IndexerEnricherMembers(object? sender, IndexingItemEventArgs e)
        {
            if (e.ValueSet.Category == IndexTypes.Member
                & string.Equals(ModStoreMember.ModelTypeAlias, e.ValueSet.ItemType, StringComparison.InvariantCultureIgnoreCase))
            {
                try
                {
                    var values = e.ValueSet.Values.ToDictionary(x => x.Key, x => x.Value.ToList());

                    using var ctx = umbracoContextFactory.EnsureUmbracoContext();
                    var content = umbracoContextFactory.EnsureUmbracoContext().UmbracoContext.Content;

                    var companyIds = UdiGuidsToIds("company", e.ValueSet, content);
                    values["companyId"] = companyIds;


                    var _roles = new List<int>();
                    var member = memberService.GetById(int.Parse(e.ValueSet.Id));
                    values["isApproved"] = [member?.IsApproved == true ? 1 : 0];

                    if (member != null)
                    {
                        var currentRoles = memberService.GetAllRoles(int.Parse(e.ValueSet.Id));
                        foreach (var currentRole in currentRoles)
                        {
                            if (Enum<ModStoreRole>.ParseOrNull(currentRole) is { } role)
                            {
                                _roles.Add((int)role);
                            }
                        }
                    }

                    values["role"] = _roles.Select(e => (object)e).ToList();

                    e.SetValues(values.ToDictionary(x => x.Key, x => (IEnumerable<object>)x.Value));

                }
                catch (Exception ex)
                {
                    logger.LogError(ex, "Error updating node: {nodeId}, type: {nodeType} err: {err}", e.ValueSet.Id, e.ValueSet.ItemType, ex.Message);
                }
            }
        }

        private static List<object> UdiGuidsToIds(string property, ValueSet valueSet, IPublishedContentCache content)
        {
            var ids = new List<object>();
            var udiStrings = (valueSet.GetValue(property)?.ToString() ?? "").Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);

            foreach (var udiString in udiStrings)
            {
                Udi udi;
                if (UdiParser.TryParse(udiString, out udi))
                {
                    var id = content.GetById(udi)?.Id;
                    if (id is > 0) ids.Add(id.Value);
                }
            }
            return ids;
        }

        public void Terminate()
        {
        }
    }
`

**Comment by AndreasLBorgTwoday** [comment]
@TimBoonstra have you tried using the scope provider from CMS infrastructure?
Here is a code snippet example for you:

```
using Umbraco.Cms.Infrastructure.Scoping;

using ( IScope scope = _scopeProvider.CreateScope() ) {
	foreach ( Umbraco.Models.HotelPage hotelPage in hotelsToUnpublish ) {
		context.WriteLine( ConsoleTextColor.Red, $"Hotel {hotelPage.Name( "da-DK" )} unpublished" );
		IContent? hotelContent = _contentService.GetById( hotelPage.Id );
		_contentService.Unpublish( hotelContent );
	}

	scope.Complete();
}
```

They also have autocomplete: `_scopeProvider.CreateScope( autoComplete: true )`

**Comment by carlitolr96** [comment]
**Recurring Examine Index corruption on Umbraco 17.3.4 hosted on Azure App Service after saving and publishing content**

<img width="1062" height="326" alt="Image" src="https://github.com/user-attachments/assets/c3a7cf78-3044-4b0d-91a2-c7f6c8132303" />

## Umbraco Version

- Umbraco CMS: 17.3.4
- .NET: 10
- Hosting: Azure App Service (Windows)
- Single App Service instance

## Issue Description

We are experiencing a recurring issue where the Examine indexes (`InternalIndex` and `ExternalIndex`) become corrupted after editors work in the Backoffice for some time.

The website works normally for several days after deployment or after manually rebuilding the indexes. However, after multiple **Save and Publish** operations, the indexes become corrupted again.

The issue occurs most frequently when editing content in two Document Types:

- Aliados
- Nuevas Ofertas

These are high-traffic content sections that are updated frequently by editors.

## Error

After clicking **Save and Publish**, Examine starts indexing the content, but eventually fails with a `System.IO.FileNotFoundException`.

Example:

System.IO.FileNotFoundException:
Could not find file

C:\home\site\wwwroot\umbraco\Data\TEMP\ExamineIndexes\InternalIndex\_25.cfs

Sometimes the missing file changes (`_2.si`, `_3b.si`, `_25.cfs`, etc.), but the behavior is always the same.

The stack trace always points to Lucene committing the index:

- Lucene.Net.Index.IndexWriter.Commit()
- Examine.Lucene.Providers.LuceneIndex.IndexCommiter.CommitNow()

## Health Check

The Examine Management dashboard reports:

- InternalIndex → Possible corrupt index detected
- ExternalIndex → Possible corrupt index detected

Example errors:

- Could not find file '_2.si'
- Could not find file '_25.cfs'
- invalid deletion count: 7 vs docCount=1

## Current Workaround

The only way to recover the site is to:

1. Stop the Azure App Service.
2. Delete the following folders:

/umbraco/Data/TEMP/ExamineIndexes/InternalIndex
/umbraco/Data/TEMP/ExamineIndexes/ExternalIndex

3. Start the App Service again.

The indexes are rebuilt successfully and everything works again, but after a few days of editing content, the same issue returns.

## Additional Information

- Running on Azure App Service (Windows).
- Single App Service instance (no scale-out).
- `/umbraco/Data/TEMP` is excluded from deployment.
- No deployments occur when the issue happens.
- The problem appears only after editors have been working in the Backoffice for some time.
- Rebuilding the indexes fixes the issue only temporarily.
- The issue has been reproduced multiple times.

We also have several custom `ContentSavingNotification` handlers for these Document Types, but no exceptions are logged from those handlers before the index corruption occurs.

Additionally, the uSync Health Check reports:

"There are 793 clashes where files share the same keys."

We are not sure whether this is related to the Examine corruption or is an independent issue.

## Question

Has anyone experienced recurring Examine/Lucene index corruption on Umbraco 17 running on Azure App Service?

Is this a known issue with Examine, Lucene, or Azure file storage?

Are there any recommended configurations or best practices to prevent recurring index corruption in this scenario?

Any guidance or suggestions would be greatly appreciated.

Thank you.
