### ISSUE TITLE
Transaction (Process ID 68) was deadlocked on lock resources with another process and has been chosen as the deadlock victim

### ISSUE THREAD

**Issue by PeterKvayt** [umbraco/Umbraco-CMS#17872]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.1.1

### Bug summary

When I create a document in the content tree and try to save and publish it sometimes I face with deadlock error:
![image](https://github.com/user-attachments/assets/898234b9-a440-45ec-ba8e-0a892f31190e)
The document was saved and published but a deadlock error occurred.

### Specifics

Starck trace:
```
Microsoft.Data.SqlClient.SqlException (0x80131904): Transaction (Process ID 68) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)

   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)

   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)

   at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)

   at NPoco.Database.Read[T](Object instance, DbDataReader r, PocoData pd)+MoveNext()

   at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at NPoco.Database.PageImpAsync[T](Int64 page, Int64 itemsPerPage, String sql, Object[] args, Boolean sync)

   at NPoco.AsyncHelper.RunSync[T](Task`1 task)

   at NPoco.Database.Page[T](Int64 page, Int64 itemsPerPage, Sql sql)

   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.EntityRepository.GetPagedResultsByQuery(IQuery`1 query, Guid[] objectTypes, Int64 pageIndex, Int32 pageSize, Int64& totalRecords, IQuery`1 filter, Ordering ordering, Action`1 sqlCustomization)

   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.EntityRepository.GetPagedResultsByQuery(IQuery`1 query, ISet`1 objectTypes, Int64 pageIndex, Int32 pageSize, Int64& totalRecords, IQuery`1 filter, Ordering ordering)

   at Umbraco.Cms.Core.Persistence.Repositories.IEntityRepository.GetPagedResultsByQuery(IQuery`1 query, Guid objectType, Int64 pageIndex, Int32 pageSize, Int64& totalRecords, IQuery`1 filter, Ordering ordering)

   at Umbraco.Cms.Core.Services.EntityService.GetPagedChildren(Int32 id, UmbracoObjectTypes objectType, Int64 pageIndex, Int32 pageSize, Boolean trashed, IQuery`1 filter, Ordering ordering, Int64& totalRecords)

   at Umbraco.Cms.Core.Services.EntityService.GetPagedChildren(Int32 id, UmbracoObjectTypes objectType, Int64 pageIndex, Int32 pageSize, Int64& totalRecords, IQuery`1 filter, Ordering ordering)

   at Umbraco.Cms.Core.Services.EntityService.GetPagedChildren(Nullable`1 parentKey, IEnumerable`1 parentObjectTypes, UmbracoObjectTypes childObjectType, Int32 skip, Int32 take, Int64& totalRecords, IQuery`1 filter, Ordering ordering)

   at Umbraco.Cms.Core.Services.EntityService.GetPagedChildren(Nullable`1 parentKey, UmbracoObjectTypes childObjectType, Int32 skip, Int32 take, Int64& totalRecords, IQuery`1 filter, Ordering ordering)

   at Umbraco.Cms.Api.Management.Controllers.Tree.EntityTreeControllerBase`1.GetPagedChildEntities(Guid parentKey, Int32 skip, Int32 take, Int64& totalItems)

   at Umbraco.Cms.Api.Management.Controllers.Tree.UserStartNodeTreeControllerBase`1.GetPagedChildEntities(Guid parentKey, Int32 skip, Int32 take, Int64& totalItems)

   at Umbraco.Cms.Api.Management.Controllers.Tree.EntityTreeControllerBase`1.GetChildren(Guid parentId, Int32 skip, Int32 take)

   at Umbraco.Cms.Api.Management.Controllers.Document.Tree.ChildrenDocumentTreeController.Children(CancellationToken cancellationToken, Guid parentId, Int32 skip, Int32 take, Nullable`1 dataTypeId)

   at lambda_method680(Closure, Object)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

   at Umbraco.Cms.Web.Common.Middleware.BasicAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)

   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()

--- End of stack trace from previous location ---

   at Umbraco.Cms.Api.Management.Middleware.BackOfficeExternalLoginProviderErrorMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)

   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()

--- End of stack trace from previous location ---

   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)

   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)

   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 112

   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)

   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)

   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()

--- End of stack trace from previous location ---

   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)

   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()

--- End of stack trace from previous location ---

   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)

   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)

ClientConnectionId:b34f6e32-c277-4866-85c8-8dd9b432c2ce

Error Number:1205,State:51,Class:13
```

### Steps to reproduce

1. Open content tree
2. Select "create" in the context menu
3. Fill necessary content fields
4. Click "Save and publish"
There is a deadlock error sometimes.

### Expected result / actual result

Expected result: there are no deadlocks
Actual result: there is a deadlock

**Comment by NguyenThuyLan** [comment]
Thank you @PeterKvayt for reporting this issue.
I have had this same issue a few times.

**Comment by AhmedElmehalawi** [comment]
i have faced the same issue as well

**Comment by PeterKvayt** [comment]
It is still reproduced on v16.0.0

**Comment by cheeseytoastie** [comment]
Reproduced in a very empty vanilla v16.2.0.

Running on SQL Express locally so no latency with Azure DB to blame. Only thing I was doing was trying to create a few nodes to make a new site structure. This doc type had no fields - was just a "folder" - so document type with no template. 

Cannot recreate again though. Tried multiple times. 

Log suggests the node was published correctly (as does the notification popup) then a read warning appears so perhaps it's something in the reload of the node content following a publish - hitting a race condition or something!? 

<img width="1406" height="262" alt="Image" src="https://github.com/user-attachments/assets/16d2c850-36f2-4093-bf3c-fb2032912e9e" />

**Comment by cheeseytoastie** [comment]
> It is still reproduced on v16.0.0
@PeterKvayt 
Out of interest - did this happen again when publishing a new "Section folder" again - might be a coincidence but I was publishing a "folder" type (doc type with no template) and can see that similarity in your first screenshot?!

**Comment by PeterKvayt** [comment]
@cheeseytoastie Hi!
I haven't checkedout the bug since I created it, but maybe it has already been fixed by [21156](https://github.com/umbraco/Umbraco-CMS/pull/21156)

Currently, I am using v16.0.0, and I haven't faced the bug pretty much time.
Once I have some free time, I will check what you asked me.
