### ISSUE TITLE
U 7.12.3 - Validation of Value type for Label Data Type

### ISSUE THREAD

**Issue by jmvivas** [umbraco/Umbraco-CMS#3565]
When selecting a "Label" Data Type, if the value type is not selected it generates an exception

Reproduction
------------

### Specifics

- OSX - Chrome / Safari
- Umbraco 7.12.3

### Steps to reproduce

- Create a new "Label" data type
- Do not choose a value type
- Save

### Expected result

- A validation message should indicate the value type is required

### Actual result

Exception: Object reference not set to an instance of an object.

at Umbraco.Core.PropertyEditors.PropertyValueEditor.GetDatabaseType(String valueType)
   at Umbraco.Core.Services.DataTypeService.SaveDataTypeAndPreValues(IDataTypeDefinition dataTypeDefinition, IDictionary`2 values, Int32 userId)
   at Umbraco.Web.Editors.DataTypeController.PostSave(DataTypeSave dataType)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---

**Comment by nul800sebastiaan** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/3572
