### ISSUE TITLE
Exception of type 'Lucene.Net.Index.MergePolicy+MergeException'

### ISSUE THREAD

**Issue by Okarlchen** [umbraco/Umbraco-CMS#3823]
in v7.10.4 , Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. 
And it makes IIS 503 error

The error in the logs is:

` 2018-12-04 02:01:32,379 [P9492/D2/TLucene Merge Thread #0] ERROR Umbraco.Core.UmbracoApplicationBase - Unhandled exception in AppDomain (terminating)
Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> 
Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _ra: fieldsReader shows 1 but segmentInfo shows 76
   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge)
   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge)
   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run()
   --- End of inner exception stack trace ---
   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc)
   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()`

Is there any solution? 
Thanks

**Comment by nickornotto** [comment]
@Okarlchen have you everfixed your issue? I am experiencing something similar.

**Comment by nickornotto** [comment]
@Okarlchen have you ever resolved the issue?

We are struggling with it for over a year.
