### ISSUE TITLE
Assigning a new file to an existing IMedia with extension SetValue causes exception 'Illegal characters in path' (U4-9904)

### ISSUE THREAD

**Issue by dampee** [umbraco/Umbraco-CMS#3937]
Reproduction
------------

### Bug summary

This has been reported in the [old issue tracker (U4-9904)](https://issues.umbraco.org/issue/U4-9904).  

An exception is thrown if you override an existing image using the `MediaService`.  This used to work in order versions (tested 7.4.3).

### Steps to reproduce

* Create an empty umbraco website (v7.12.4)
* Add [this gist](https://gist.github.com/dampee/fc037b5e0b44b554676ecb6d667106fa) to your website
* run the Api Controller `/umbraco/api/MediaTest/CreateImage?withworkaround=false`

You will receive an exception.  If you call  `/umbraco/api/MediaTest/CreateImage?withworkaround=true` the code will update the image just fine.

### Expected result

No need to empty the field (use the work around) to update an image.  

### Actual result

The exception stacktrace looks like this:

```stacktrace
at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Umbraco.Core.IO.PhysicalFileSystem.GetFullPath(String path)
   at Umbraco.Core.IO.PhysicalFileSystem.DeleteFile(String path)
   at Umbraco.Core.IO.ShadowWrapper.DeleteFile(String path)
   at Umbraco.Core.IO.MediaFileSystem.StoreFile(IContentBase content, PropertyType propertyType, String filename, Stream filestream, String oldpath)
   at Umbraco.Core.IO.MediaFileSystem.SetUploadFile(IContentBase content, String propertyTypeAlias, String filename, Stream filestream)
   at Umbraco.Core.Models.ContentExtensions.SetValue(IContentBase content, String propertyTypeAlias, String filename, Stream filestream)
   at U4_9904.Controllers.MediaTestController.GetAndSaveImage(Boolean withworkaround)
   at U4_9904.Controllers.MediaTestController.CreateImage(Int32 timesToRun, Nullable`1 withworkaround)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()</StackTrace>
```

**Comment by kjac** [comment]
PR in #3940

**Comment by nul800sebastiaan** [comment]
Just FYI: this method moved to `ContentExtensions` in v8 and I've just applied the same fix there, I forgot during the merge.
