### ISSUE TITLE
The database failed to upgrade. V8

### ISSUE THREAD

**Issue by mehrdadab** [umbraco/Umbraco-CMS#4155]
I tried to install Umbraco 8 for the first time. I downloaded the code and ran it by visual studio.
When I entered my connection string info to install I received this error: Object reference not set to an instance of an object. I tried again, this time I see:

Error during installation
The database failed to upgrade. ERROR: The database configuration failed with the following message: Object reference not set to an instance of an object. 
Please check log file for additional information (can be found in '/App_Data/Logs/UmbracoTraceLog.txt')

Reproduction
I am not sure how I can reproduce it as it is always happening on my computer. But I can provide the information below:

Umbraco Version 8 (Latest version).
SQL Server: 2016

When I check the database I see the tables have been added but it says the database failed to upgrade.
I also see on the log file this error: 
```
2019-01-20 12:24:07,930 [P16256/D4/T12] ERROR  Umbraco.Web.Install.Controllers.InstallApiController - An error occurred during installation step DatabaseUpgrade
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Umbraco.Web.Install.InstallException: The database failed to upgrade. ERROR: The database configuration failed with the following message: Object reference not set to an instance of an object.
 Please check log file for additional information (can be found in '/App_Data/Logs/UmbracoTraceLog.txt')
   at Umbraco.Web.Install.InstallSteps.DatabaseUpgradeStep.ExecuteAsync(Object model) in C:\Umbraco\Umbraco-CMS-temp8\src\Umbraco.Web\Install\InstallSteps\DatabaseUpgradeStep.cs:line 41
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Umbraco.Web.Install.Controllers.InstallApiController.<ExecuteStepAsync>d__17.MoveNext() in C:\Umbraco\Umbraco-CMS-temp8\src\Umbraco.Web\Install\Controllers\InstallApiController.cs:line 242
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Umbraco.Web.Install.Controllers.InstallApiController.<PostPerformInstall>d__14.MoveNext() in C:\Umbraco\Umbraco-CMS-temp8\src\Umbraco.Web\Install\Controllers\InstallApiController.cs:line 110
```
And when I debug the code I see on the code below UmbracoVersion.LocalVersion is null when we are reading UmbracoVersion.LocalVersion.Major so it throws exception:
```
Umbraco.Core.Services.Implement.KeyValueService{
   private void Initialize()
        {
            // the key/value service is entirely self-managed, because it is used by the
            // upgrader and anything we might change need to happen before everything else

            // if already running 8, either following an upgrade or an install,
            // then everything should be ok (the table should exist, etc)

            if (UmbracoVersion.LocalVersion.Major >= 8)
                return;

            // else we are upgrading from 7, we can assume that the locks table
            // exists, but we need to create everything for key/value

            using (var scope = _scopeProvider.CreateScope())
            {
                var context = new MigrationContext(scope.Database, _logger);
                var initMigration = new InitializeMigration(context);
                initMigration.Migrate();
                scope.Complete();
            }
        }
}
```

### Steps to reproduce

I cannot say how reproduce, as it is happening always on my computer, I also removed the database and tried again, but same thing happened, however I can keep it as it is to answer if you have any question.

### Expected result

Install umbraco successfully or showing a clear error message.
### Actual result

Cannot install umbraco and the message is not clear enough.

**Comment by zpqrtbnk** [comment]
Have seen it happen on my machine once and assumed it was a glitch - but if it's been reproduced, then we might have an issue indeed. Some of the installer code changed recently. Looking into it.

**Comment by zpqrtbnk** [comment]
it would definitively, as the commit I mentioned fix this issue, precisely

**Comment by nul800sebastiaan** [comment]
Yep, that was when this issue was fixed, I'll close this issue for now.

Please note: if you're installing Umbraco just to play with it, it's much easier to use the nuget package as listed on [our download page](http://our.umbraco.org/download). The command to run in your package manager console is: `Install-Package UmbracoCms -Pre -Source https://www.myget.org/F/umbracocore/api/v3/index.json`

You should only run Umbraco from source code if you're trying to contribute to the source.
