### ISSUE TITLE
Issuu oembed doesn't work

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4156]
It seems the issuu oembed provider which was added in v7.11 doesn't work:
https://our.umbraco.com/download/releases//7110
https://github.com/umbraco/Umbraco-CMS/pull/2694

Maybe something has changed?
I have trieds in different Umbraco version incl. latest v7.13.1, e.g. the following publication:
https://issuu.com/gylupake/docs/1981521275-i_am_10_and_magical_by_w

![image](https://user-images.githubusercontent.com/2919859/51440726-5c5bc380-1cca-11e9-9e22-6d25100d28a8.png)

**Comment by bjarnef** [comment]
The log file show this stacktrace: `Data from the transport connection could not be read: An existing connection was forcibly interrupted by an external host`.

```
 2019-01-20 15:46:51,965 [P10400/D12/T142] ERROR Umbraco.Web.PropertyEditors.RteEmbedController - Error embedding url https://issuu.com/gylupake/docs/1981521275-i_am_10_and_magical_by_w - width: 360 height: 240
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Der opstod en fejl under afsendelse af anmodningen. ---> System.Net.WebException: Den underliggende forbindelse blev lukket: Der opstod en uventet fejl ved afsendelse.. ---> System.IO.IOException: Der kunne ikke læses data fra transportforbindelsen: En eksisterende forbindelse blev tvangsafbrudt af en ekstern vært. ---> System.Net.Sockets.SocketException: En eksisterende forbindelse blev tvangsafbrudt af en ekstern vært
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Umbraco.Web.Media.EmbedProviders.AbstractOEmbedProvider.DownloadResponse(String url)
   at Umbraco.Web.Media.EmbedProviders.AbstractOEmbedProvider.GetJsonResponse[T](String url)
   at Umbraco.Web.Media.EmbedProviders.OEmbedJson.GetMarkup(String url, Int32 maxWidth, Int32 maxHeight)
   at Umbraco.Web.PropertyEditors.RteEmbedController.GetEmbed(String url, Int32 width, Int32 height)
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Der opstod en fejl under afsendelse af anmodningen. ---> System.Net.WebException: Den underliggende forbindelse blev lukket: Der opstod en uventet fejl ved afsendelse.. ---> System.IO.IOException: Der kunne ikke læses data fra transportforbindelsen: En eksisterende forbindelse blev tvangsafbrudt af en ekstern vært. ---> System.Net.Sockets.SocketException: En eksisterende forbindelse blev tvangsafbrudt af en ekstern vært
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallb
```

**Comment by nul800sebastiaan** [comment]
It's difficult to decipher the Danish error message, but I suspect it might be that Issuu is only allowing TLS 1.2 connections. There's a package that will help re-order the way your site tries to connect to other sites. It tried TLS 1.2 first, then 1.1, then 1.0. Can you try that?  https://our.umbraco.com/packages/developer-tools/codesharetls12umbraco/

**Comment by nul800sebastiaan** [comment]
Ps. I've tested this now, it works :-)

**Comment by bjarnef** [comment]
Sorry @nul800sebastiaan 
Here it is in English 😀 

```
System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: En eksisterende forbindelse blev tvangsafbrudt af en ekstern vært. ---> System.Net.Sockets.SocketException: En eksisterende forbindelse blev tvangsafbrudt af en ekstern vært
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at Umbraco.Web.Media.EmbedProviders.AbstractOEmbedProvider.DownloadResponse(String url)
   at Umbraco.Web.Media.EmbedProviders.AbstractOEmbedProvider.GetJsonResponse[T](String url)
   at Umbraco.Web.Media.EmbedProviders.OEmbedJson.GetMarkup(String url, Int32 maxWidth, Int32 maxHeight)
   at Umbraco.Web.PropertyEditors.RteEmbedController.GetEmbed(String url, Int32 width, Int32 height)
```

**Comment by nul800sebastiaan** [comment]
Thanks.. too late now, the solution is above! :)

**Comment by bjarnef** [comment]
@nul800sebastiaan yes, I have tested this and it works when set `SecurityProtocol` (I always forget about this when requesting various API endpoints via https protocol.

Is it possible the `GetEmbed` can handle this or do we just have to remember to set this? 😬

```
using System.Net;
using Umbraco.Core;
using Umbraco.Web;

namespace App_Code.Events
{
    public class RegisterEvents : ApplicationEventHandler
    {
        protected override void ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
        {
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;
        }
    }
}
```

**Comment by nul800sebastiaan** [comment]
Yep, will be fixed in: https://github.com/umbraco/Umbraco-CMS/issues/4166

**Comment by bjarnef** [comment]
@nul800sebastiaan can you tell if there is any of these approach which are preferred? The one I posted or this one:

```
public class RegisterEvents : ApplicationEventHandler
{
    protected override void ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
    {
        if (ServicePointManager.SecurityProtocol.HasFlag(SecurityProtocolType.Tls12) == false)
        {
            ServicePointManager.SecurityProtocol = ServicePointManager.SecurityProtocol | SecurityProtocolType.Tls12;
        }
    }
}
```
https://github.com/prjseal/CodeShare.TLS1.2.Umbraco/blob/master/CodeShare.TLS1.2.Umbraco/EventHandlers/RegisterEvents.cs

In the latter one if only sets `Tls12` if `SecurityProtocolType` not already is `Tls12`.

In the example I posted is fallback to `Tls11` or `Tls`.

**Comment by nul800sebastiaan** [comment]
Paul's code above is sufficient, there's automatic fallbacks to lower protocols.
