### ISSUE TITLE
Random SQL connection error in umbraco.org service CheckForUpgrade.asmx

### ISSUE THREAD

**Issue by JoseMarcenaro** [umbraco/Umbraco-CMS#4221]
### Bug summary
This service http://update.umbraco.org/checkforupgrade.asmx , which is periodically called from every Umbraco installation, is randomly failing and throwing the following error in the Umbraco backoffice:

	System.Web.Services.Protocols.SoapException: Server was unable to process request. 
	---> System.Data.SqlClient.SqlException: Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding. 
	---> System.ComponentModel.Win32Exception: The wait operation timed out 
	--- End of inner exception stack trace --- 
	at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) 
	at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) 
	at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) 
	at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString) 
	at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds) 
	at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite) 
	at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
	at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
	at umbracoUpgradeChecker.BusinessLogic.Logger.Log(String server, Int32 major, Int32 minor, Int32 patch, String comment) 
	in D:\Dev\UpgradeChecker\umbracoUpgradeChecker\BusinessLogic\Logger.cs:line 31 
	at umbracoUpgradeChecker.CheckForUpgrade.CheckUpgrade(Int32 versionMajor, Int32 versionMinor, Int32 versionPatch, String versionComment) 
	in D:\Dev\UpgradeChecker\umbracoUpgradeChecker\CheckForUpgrade.asmx.cs:line 52 
	--- End of inner exception stack trace ---

### Specifics
I'm running Umbraco v7.12.1  - but I'don't think it is related to my Umbraco version.
The error is thrown, at random times, while using the Umbraco backoffice - not related to a specific activity.

### Workaround

For now, I just disabled the update check by adding this line to the appSettings in web.config:

	<add key="umbracoVersionCheckPeriod" value="0"/>

**Comment by nul800sebastiaan** [comment]
Thanks for the report, we've found the problem on the server and it's been fixed now. Apologies for the inconvenience! We're working on making this site less server-dependent, so if there's errors it will just report that there's no updates. :)
