### ISSUE TITLE
V8: ClientDependency throws "Umbraco cannot run. Sad." exception

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#4320]
Latest temp8 doesn't want to boot:

![image](https://user-images.githubusercontent.com/7405322/51963270-4cc74200-2463-11e9-909c-16c3938c7279.png)

Seems a bit strange since `CdfLogger` indeed does implement `ClientDependency.Core.Logging.ILogger`. Maybe @Shazwazza has an idea here?

#### Full stack trace

[BootFailedException: Boot failed: Umbraco cannot run. Sad. See Umbraco's log file for more details.

-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.ArgumentException: The loggerType 'Umbraco.Web.UI.CdfLogger, Umbraco.Web' does not inherit from ClientDependency.Core.Logging.ILogger
   at ClientDependency.Core.Config.ClientDependencySettings.LoadProviders(HttpContextBase http) in C:\Users\Shannon\Documents\_Projects\ClientDependency\ClientDependency\ClientDependency.Core\Config\ClientDependencySettings.cs:line 313
   at ClientDependency.Core.Config.ClientDependencySettings.<.ctor>b__3_0() in C:\Users\Shannon\Documents\_Projects\ClientDependency\ClientDependency\ClientDependency.Core\Config\ClientDependencySettings.cs:line 40
   at ClientDependency.Core.Config.ClientDependencySettings.get_Instance() in C:\Users\Shannon\Documents\_Projects\ClientDependency\ClientDependency\ClientDependency.Core\Config\ClientDependencySettings.cs:line 92
   at Umbraco.Web.Runtime.WebRuntimeComponent.ConfigureClientDependency(IGlobalSettings globalSettings) in C:\Projects\Umbraco-CMS-V8\src\Umbraco.Web\Runtime\WebRuntimeComponent.cs:line 276
   at Umbraco.Web.Runtime.WebRuntimeComponent.Initialize() in C:\Projects\Umbraco-CMS-V8\src\Umbraco.Web\Runtime\WebRuntimeComponent.cs:line 77
   at Umbraco.Core.Components.ComponentCollection.Initialize() in C:\Projects\Umbraco-CMS-V8\src\Umbraco.Core\Components\ComponentCollection.cs:line 32
   at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in C:\Projects\Umbraco-CMS-V8\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 161]
   Umbraco.Core.Exceptions.BootFailedException.Rethrow(BootFailedException bootFailedException) in C:\Projects\Umbraco-CMS-V8\src\Umbraco.Core\Exceptions\BootFailedException.cs:57
   Umbraco.Web.<>c.<Init>b__22_0(Object sender, EventArgs args) in C:\Projects\Umbraco-CMS-V8\src\Umbraco.Web\UmbracoInjectedModule.cs:461
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +200
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +132
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +73

**Comment by Shazwazza** [comment]
You'll need to manually update your config/clientdependency.config file (it's git ignored)

Update your /config/ClientDependency.config file to point to the correct class, should be the top line, the type is now `Umbraco.Web.CdfLogger` (no UI)

**Comment by kjac** [comment]
Ah 👍 thanks!
