### ISSUE TITLE
v8 Error: "failed to retrieve children" when opening list view

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#4440]
I get this error when trying to open a list view with items in it: 

![image](https://user-images.githubusercontent.com/304656/52332946-405f5e00-29fc-11e9-8d3d-63b30f54c911.png)

Detailed error: 

```
Error mapping types.

Mapping types:
IContent -> ContentItemBasic`1
Umbraco.Core.Models.IContent -> Umbraco.Web.Models.ContentEditing.ContentItemBasic`1[[Umbraco.Web.Models.ContentEditing.ContentPropertyBasic, Umbraco.Web, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null]]

Type Map configuration:
IContent -> ContentItemBasic`1
Umbraco.Core.Models.IContent -> Umbraco.Web.Models.ContentEditing.ContentItemBasic`1[[Umbraco.Web.Models.ContentEditing.ContentPropertyBasic, Umbraco.Web, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null]]

Property:
UpdateDate
```

The Blog Overview (list view) doctype is not configured as variant, the Blog Post doctype is variant and has 2 variant fields. It has other properties too from a composition that are not variant. Can provide database if needed.

**Comment by nul800sebastiaan** [comment]
Okay, I found it: I only had 1 language set up and no additional languages yet. So there was no selection for any language in the backoffice yet. I feel like if there's no explicit language chosen and only 1 language is set up then that one should be "selected" for everything.

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4540

**Comment by thomashdk** [comment]
Getting same error in 8.16.0

with this in the log:

` Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out`
 
 
 ` Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172
   at NPoco.Database.ExecuteScalarHelper(DbCommand cmd)`
