### ISSUE TITLE
v8 Cannot detect sql server version, sql syntax error

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#4479]
I get this error in my logs on startup 

```
2019-02-08 17:19:29,457 [P21756/D35/T245] ERROR  Umbraco.Core.Persistence.UmbracoDatabaseFactory - Failed to detected SqlServer version.
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at System.Data.SqlClient.SqlBuffer.get_String()
   at Umbraco.Core.Persistence.SqlSyntax.SqlServerSyntaxProvider.GetSetVersion(String connectionString, String providerName, ILogger logger) in C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\src\Umbraco.Core\Persistence\SqlSyntax\SqlServerSyntaxProvider.cs:line 138
```

**Comment by zpqrtbnk** [comment]
Which version of v8 is this? Thought I had fixed this. Can you run the following query and report results:
```
select
    SERVERPROPERTY('Edition') Edition,
    SERVERPROPERTY('EditionID') EditionId,
    SERVERPROPERTY('InstanceName') InstanceName,
    SERVERPROPERTY('ProductVersion') ProductVersion,
    SERVERPROPERTY('BuildClrVersion') BuildClrVersion,
    SERVERPROPERTY('EngineEdition') EngineEdition,
    SERVERPROPERTY('IsClustered') IsClustered,
    SERVERPROPERTY('MachineName') MachineName,
    SERVERPROPERTY('ResourceLastUpdateDateTime') ResourceLastUpdateDateTime,
    SERVERPROPERTY('ProductLevel') ProductLevel;
```

**Comment by Shazwazza** [comment]
This is the output 

![image](https://user-images.githubusercontent.com/1742685/52544698-79d20800-2e06-11e9-9de3-eed6782c70be.png)

**Comment by zpqrtbnk** [comment]
Now b5a90bf26a should fix for real

**Comment by bergmania** [comment]
@Shazwazza, can you verify this can be closed?

**Comment by Shazwazza** [comment]
I don't see this error in my logs anymore so i think it's ok, closing
