### ISSUE TITLE
System.NotSupportedException: An IMember model can only be retreived when using the built-in Umbraco membership providers

### ISSUE THREAD

**Issue by SimonHilo** [umbraco/Umbraco-CMS#4606]
After upgrading to 7.13.2 from 7.12.3 I get the following exeption when 
1) using a custom MembershipProvider with Umbraco
2) requesting a node that is restricted
3) the member has access to the node

```
System.NotSupportedException: An IMember model can only be retreived when using the built-in Umbraco membership providers
   at Umbraco.Core.Cache.HttpRequestCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem)
   at Umbraco.Core.Cache.CacheProviderExtensions.GetCacheItem[T](ICacheProvider provider, String cacheKey, Func`1 getCacheItem)
   at Umbraco.Web.Security.MembershipHelper.GetCurrentPersistedMember()
   at Umbraco.Web.Security.MembershipHelper.GetCurrentMember()
   at Umbraco.Web.Routing.PublishedContentRequestEngine.EnsurePublishedContentAccess()
   at Umbraco.Web.Routing.PublishedContentRequestEngine.HandlePublishedContent()
   at Umbraco.Web.Routing.PublishedContentRequestEngine.FindPublishedContentAndTemplate()
   at Umbraco.Web.Routing.PublishedContentRequestEngine.PrepareRequest()
   at Umbraco.Web.UmbracoModule.ProcessRequest(HttpContextBase httpContext)
   at Umbraco.Web.UmbracoModule.<Init>b__12_3(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)

```

Source
------------
I've tracked down the source of the problem to the changes in this pull request:
https://github.com/umbraco/Umbraco-CMS/pull/3588

This change includes a call to Umbraco.Web.Security.MembershipHelper.GetCurrentMember() that fails if not using the built-in MembershipProvider.

As far as I see, the solution should be to only check if the member is approved if we are using the built-in MembershipProvider.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4607
