### ISSUE TITLE
v8: dot in Hostname breaks content section

### ISSUE THREAD

**Issue by AllanKirk** [umbraco/Umbraco-CMS#4628]
A brief description of the issue goes here.

Don't ask me why, but for some reason I decided to simply put a dot in a hostname in "Culture and Hostnames", and I was able to save with no warning. Now I get an error whenever I try to navigate in the content section.

I was able to remove it again, and that solved the problem.

Error message
----------------
Received an error from the server
An error occured
Error mapping types.
 
 Mapping types:
 IContent -> ContentItemDisplay
 Umbraco.Core.Models.IContent -> Umbraco.Web.Models.ContentEditing.ContentItemDisplay
 
 Type Map configuration:
 IContent -> ContentItemDisplay
 Umbraco.Core.Models.IContent -> Umbraco.Web.Models.ContentEditing.ContentItemDisplay
 
 Destination Member:
 Urls

Exception Details
AutoMapper.AutoMapperMappingException: Error mapping types.
 
 Mapping types:
 IContent -> ContentItemDisplay
 Umbraco.Core.Models.IContent -> Umbraco.Web.Models.ContentEditing.ContentItemDisplay
 
 Type Map configuration:
 IContent -> ContentItemDisplay
 Umbraco.Core.Models.IContent -> Umbraco.Web.Models.ContentEditing.ContentItemDisplay
 
 Destination Member:
 Urls
Stacktrace
at lambda_method(Closure , Content , ContentItemDisplay , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at Umbraco.Web.Editors.ContentController.MapToDisplay(IContent content) in C:\Users\Kirk\Documents\Git\Umbraco-CMS\src\Umbraco.Web\Editors\ContentController.cs:line 2057
   at Umbraco.Web.Editors.ContentController.GetById(Int32 id) in C:\Users\Kirk\Documents\Git\Umbraco-CMS\src\Umbraco.Web\Editors\ContentController.cs:line 300
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)

**Comment by kjac** [comment]
I've found the issue on this one. Soon as I'm able to get to I'll post a PR... Unless of course someone else is dying to fix it 😊

**Comment by kjac** [comment]
PR in #4721
