### ISSUE TITLE
Cannot insert duplicate key row in object 'dbo.umbracoPropertyData' when sorting Media

### ISSUE THREAD

**Issue by robertjf** [umbraco/Umbraco-CMS#4719]
I just tried sorting the media items in a folder in the new Site Starter package for Umbraco 8.  First I tried moving the Biker Jacket to the middle of the list and it worked, sorting succesfully.  Then I tried moving it to the top of the list and received the following error:

```
Cannot insert duplicate key row in object 'dbo.umbracoPropertyData' with unique index 'IX_umbracoPropertyData_VersionId'. The duplicate key value is (30, 7, <NULL>, <NULL>).
 The statement has been terminated.

Exception Details
System.Data.SqlClient.SqlException: Cannot insert duplicate key row in object 'dbo.umbracoPropertyData' with unique index 'IX_umbracoPropertyData_VersionId'. The duplicate key value is (30, 7, <NULL>, <NULL>).
 The statement has been terminated.
Stacktrace
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteScalar() in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 334
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<ExecuteScalar>b__32_0()
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f)
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteScalar()
```

The Sorting dialog also updated with "Failed to sort media" underneath the error dialog.

Reproduction
------------

1. Install Umbraco from latest nightly (version **8.0.0-alpha.2503**) with the starter kit
2. Go to Media, browse to the Products folder
3. Select the Sort action, move the Jacket item to halfway up the list and submit
4. Select the Sort action again, move the Jacket item to the top of the list and submit

It should submit successfully and the Jacket item should be displayed at the top of the list instead of the above error.

**Note:** After refreshing the page and re-attempting the above, I was unable to reproduce the issue.  Perhaps something wasn't set in the database initially that caused the versioning to fail?  Submitting the bug anyway in case it can be traced back and resolved as I can't replicate it (or maybe I just need to do a clean install and try again)

**Comment by zpqrtbnk** [comment]
Should not happy = issue ;-) Now if it cannot be repro, it's not a major issue - but an issue, still.

**Comment by clausjensen** [comment]
I'm going to close this issue for now. If anyone is able to reproduce we will be happy to open up again and look into it! :)
