### ISSUE TITLE
Data Integrity Health Check - Possible issue

### ISSUE THREAD

**Issue by NikRimington** [umbraco/Umbraco-CMS#5081]
I'm not sure if this is an Umbraco Core issue or a conflict issue with the following Package: https://github.com/prjseal/Our.Umbraco.HealthChecks

I have a site that has been upgraded to 7.13.2. I've then installed the package mentioned above and now running the Data Integrity Health Checks is failing when trying to validate the XML Data Integrity Health Check.

The error is thrown in the method: "CheckContent"

Error
-------------
```
An error occured
There is already an open DataReader associated with this Command which must be closed first.

Exception Details
System.InvalidOperationException: There is already an open DataReader associated with this Command which must be closed first.
```
Stack trace:
--------------
```
Stacktrace
at System.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)
   at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.<>c__DisplayClass11_0.<ExecuteScalarWithRetry>b__0()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.Database.ExecuteScalar[T](String sql, Object[] args)
   at Umbraco.Web.HealthCheck.Checks.DataIntegrity.XmlDataIntegrityHealthCheck.CheckContent()
   at Umbraco.Web.HealthCheck.Checks.DataIntegrity.XmlDataIntegrityHealthCheck.GetStatus()
   at Umbraco.Web.HealthCheck.HealthCheckController.GetStatus(Guid id)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---

```

This is the core health check that is failing but I don't know if it is being caused by something else so thought worth raising the issue here.

As mentioned above, this is an Umbraco 7.13.2 site, it also has over 8000 content nodes and 80,000 versions.

Reproduction
--------------

I've not been able to reproduce this on a clean install set up.

Thoughts
------------

Is this caused by too much data being present and too many different things accessing the DB resulting in unfinished tasks when others are active?

**Comment by nul800sebastiaan** [comment]
Ah.. not normally a problem, but maybe with loads of data.. sure. I've asked Shannon about this and his reply was:

> might be a problem with how the database is being referenced. Generally this isn't good to do: https://github.com/umbraco/Umbraco-CMS/blob/v7/dev/src/Umbraco.Web/HealthCheck/Checks/DataIntegrity/XmlDataIntegrityHealthCheck.cs#L31

> the database should always be resolved from the db context when it is needed else depending on when/where the method you are using it in, it might be hanging on to a stale db connection or another scope or something. my advice would be to store a reference to the _databaseContext instead of _database and then use _databaseContext.Database throughout the code.

> not sure if in this case that is a problem or not but that's what stands out to me


I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
