### ISSUE TITLE
Deploy 3.0: Accessing backoffice from an alternate URL breaks deployment

### ISSUE THREAD

**Issue by Zweben** [umbraco/Umbraco-CMS#5234]
Accessing the backoffice from an alternate URL, via a rewrite rule in Web.config, causes Deploy to break. 

### Bug summary

When trying to deploy content from Local to a Cloud environment, the source environment will throw a "Umbraco.Deploy.Exceptions.RemoteApiException" error every time. 

This same configuration and process works without issue in Umbraco 7.14.0 / Deploy 2.0.15.

### Steps to reproduce

1. Access a project running Umbraco 8.0.1 and Deploy 3.0.0
2. Add the following rewrite rule to Web.config:
```
        <rule name="ChangeBackofficeUrl" stopProcessing="true">
          <match url="^admin/(.*)" />
          <action type="Rewrite" url="umbraco/{R:1}" />
        </rule>
```
3. Access the backoffice via the URL "/admin/"
4. Try to deploy any content to a Cloud environment

### Specifics

The full Deploy error is:

`The source environment has thrown a Umbraco.Deploy.Exceptions.RemoteApiException with message: The remote API has failed, and its response text could not be parsed into a RemoteHttpError (System.NullReferenceException: Object reference not set to an instance of an object.). It might have been caused by an inner with message: (empty)

The technical details may contain more information.

ad1d4dd7 - Executing, 10%
ad1d4dd7 - Executing, 10% - Get remote session
ad1d4dd7 - Executing, 80% - Exception!
ad1d4dd7 - Executing, 80% - Abort remote session
ad1d4dd7 - Failed, 80% - Total time 00:00:00.653.

-- EXCEPTION ---------------------------------------------------
 (proper exception traces at the end of this log)
Umbraco.Deploy.Exceptions.RemoteApiException: The remote API has failed, and its response text could not be parsed into a RemoteHttpError (System.NullReferenceException: Object reference not set to an instance of an object.).
----------------------------------------------------------------

EXCEPTION:

Umbraco.Deploy.Exceptions.RemoteApiException: The remote API has failed, and its response text could not be parsed into a RemoteHttpError (System.NullReferenceException: Object reference not set to an instance of an object.).
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<SucceedOrThrow>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<BeginSessionAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.DeployRestoreWorkItemBase.<GetSessionOn>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsyncSub>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsyncSub>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsync>d__15.MoveNext()

REMOTE:
TEXT: 
`

**Comment by Shazwazza** [comment]
Hi thanks for reporting, would you be able to submit this issue to the Cloud repo? https://github.com/umbraco/Umbraco.Cloud.Issues

Thanks!
