### ISSUE TITLE
V8 : Auditservices sql error

### ISSUE THREAD

**Issue by filefontaine** [umbraco/Umbraco-CMS#5268]
Hello, 
I have a error when i use AuditService GetUserLogs

Reproduction
------------
### Bug summary

Sql problem conversion fail nvarchar to int

### Specifics

* In a controller with `UmbracoAuthorizedJsonController`
* An `[HttpGet]` public function

### Steps to reproduce

Use the function like this (user exist) : 

```
IEnumerable<IAuditItem> test;
test = Services.AuditService.GetUserLogs(4, AuditType.Unpublish);
```

### Expected result

a `IEnumerable<IAuditItem>`

### Actual result

```
System.Data.SqlClient.SqlException (0x80131904): Conversion failed when converting the nvarchar value 'SaveVariant' to data type int.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at NPoco.Database.<Read>d__156`1.MoveNext()
   at NPoco.Database.<QueryImp>d__164`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NPoco.Database.Fetch[T](Sql sql)
   at Umbraco.Core.Persistence.Repositories.Implement.AuditRepository.PerformGetByQuery(IQuery`1 query)
   at Umbraco.Core.Persistence.Repositories.Implement.RepositoryBase`2.Get(IQuery`1 query)
   at Umbraco.Core.Services.Implement.AuditService.GetUserLogs(Int32 userId, AuditType type, Nullable`1 sinceDate)
   at HEGFR.Web.Controllers.DashboardController.GetRecentActivity() in \HEGFR.Web\Controllers\DashboardController.cs:line 135
ClientConnectionId:36682457-3dcc-478b-b4a2-8d46ae879c89
Error Number:245,State:1,Class:16
```

**Comment by nul800sebastiaan** [comment]
@filefontaine Which Umbraco version are we talking about here please?

**Comment by zpqrtbnk** [comment]
Think I have reproduced it on 8.0.1.

**Comment by zpqrtbnk** [comment]
Confirmed. We have
~~~~
_auditRepository.Get(Query<IAuditItem>().Where(x => x.UserId == userId && x.AuditType == type))
~~~~
And our query mapper ends up mapping this to SQL `AND ([umbracoLog].[logHeader] = @1)` (which is fine) but then assigns the value of `@1` to the object representation of `type`, which is an Enum, so it ends up being an `int` (eg `2`) -- but in our database, we expect a `string` (eg `Unpublished`).

**Comment by zpqrtbnk** [comment]
Following test (if added in `AuditServiceTests`) fails:
~~~~
        [Test]
        public void CanReadEntries()
        {
            var yesterday = DateTime.UtcNow.AddDays(-1);

            for (var i = 0; i < 10; i++)
            {
                yesterday = yesterday.AddMinutes(1);
                ServiceContext.AuditService.Add(AuditType.Unpublish, -1, 33, "", "blah");
            }

            var logs = ServiceContext.AuditService.GetUserLogs(-1, AuditType.Unpublish);
        }
~~~~

**Comment by zpqrtbnk** [comment]
Have fixed in 8.1 with PR #5270 
Still needs to be fixed in 8.0
And @filefontaine  if you can tell use in which version you are seeing this? Probably exists in 7.x too

**Comment by filefontaine** [comment]
Hello @zpqrtbnk sorry for the late response.
My version is 8.0.1.
I check with the GetLogs() methods and i have the same error.

**Comment by Shazwazza** [comment]
has been added to our backlog AB#435

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5270
