### ISSUE TITLE
Internation Domain Names

### ISSUE THREAD

**Issue by croban** [umbraco/Umbraco-CMS#5298]
Umbraco version 7.7.9 assembly: 1.0.6596.21099

If there are internation domain specified than I geting constantliy this error:
For example this Hostname: www.öetwas.at

2019-04-19 16:31:38,202 [74] ERROR Umbraco.Core.UmbracoApplicationBase [(null)] - An unhandled exception occurred

HOSTNAME: RD0003FF74A1C6
HTTP_HOST: www.%C3%B6etwas.at
URL: (null)
QUERY_STRING: (null)

System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Microsoft.Owin.OwinRequest.get_Uri()
   at Umbraco.Web.Security.Identity.BackOfficeCookieManager.Microsoft.Owin.Infrastructure.ICookieManager.GetRequestCookie(IOwinContext context, String key)
   at Microsoft.Owin.Security.Cookies.CookieAuthenticationHandler.<AuthenticateCoreAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Security.Infrastructure.AuthenticationHandler.<BaseInitializeAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Identity.Owin.IdentityFactoryMiddleware`2.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Identity.Owin.IdentityFactoryMiddleware`2.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.<RunApp>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.<DoFinalWork>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by abjerner** [comment]
Hi @croban and thanks for reporting this issue 👍 

As 7.7.9 was released a little over a year ago, would it by any chance be possible for you to test whether this issue still exists in the most recent version of Umbraco 7?

I'm not 100% sure when you're seeing this error. Is it when Umbraco is booting up?

If so, from what I can tell, newer versions (I'm testing with 7.13.2), Umbraco will correctly set the cookie for `www.xn--etwas-iua.at`, which should be the correct domain name according to the [Punycode format](https://en.wikipedia.org/wiki/Punycode).

**Comment by croban** [comment]
Domain name is set in punycode format, really strange, everything works correctly on Frontend also inside backoffice. I think that checktimeout ajax call from umbraco which happens periodically cause this one also. I don't see this error log4net send me emails ;)

**Comment by nul800sebastiaan** [comment]
I'll close this for now since we haven't gotten more feedback since. Feel free to report back if this is still and issue in 7.14!
