### ISSUE TITLE
Using Umbraco v8.0.2 as IIS Virtual application is throwing an exception...

### ISSUE THREAD

**Issue by driekus77** [umbraco/Umbraco-CMS#5564]
Hello all,

I'm new to Umbraco and stumbled upon, what IMHO is a bug in version 8.0.2. 
When using Umbraco as a Virtual folder application under IIS I get into throuble when trying to create a new stylesheet and/or script file.

### Bug summary

When using Umbraco under an IIS Virtual folder/application some actions are throwing errors. E.g. creating new scripts and/or stylesheets are not succeding. 

### Specifics

I tried setting the inheritInChildApplications web.config setting to false but that didn't help. (From: https://stackoverflow.com/questions/36853115/umbraco-child-mvc-application-virtual-directory-could-not-load-file-or-assem)

### Steps to reproduce

Make sure you installed Umbraco under an IIS Virtual path.
Under Umbraco's Admin page goto Settings -> Templates -> Scripts and try adding new script e.g. main.js.
Note: Can also reproduce this when trying to add a Stylesheet e.g. main.css.

### Expected result

main.js added as new and empty file under the scripts folder.

### Actual result

Umbraco.Core.IO.FileSecurityException: File '/scripts/main.js' is outside this filesystem's root.
   at Umbraco.Core.IO.PhysicalFileSystem.GetFullPath(String path)
   at Umbraco.Core.IO.PhysicalFileSystem.FileExists(String path)
   at Umbraco.Core.Persistence.Repositories.Implement.ScriptRepository.Get(String id)
   at Umbraco.Core.Services.Implement.FileService.GetScriptByName(String name)
   at Umbraco.Web.Editors.CodeFileController.CreateOrUpdateFile[T](CodeFileDisplay display, String extension, IFileSystem fileSystem, Func`2 getFileByName, Action`2 saveFile, Func`2 createFile)
   at Umbraco.Web.Editors.CodeFileController.CreateOrUpdateScript(CodeFileDisplay display)
   at Umbraco.Web.Editors.CodeFileController.PostSave(CodeFileDisplay display)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---

When switching Umbraco to my Root/Default website everything works OK.

**Comment by nul800sebastiaan** [comment]
Thanks @driekus77 - unfortunately we don't really support running Umbraco in a vdir under another app. I seem to recall it can be done but it will probably require a bit more configuration somewhere else. 

I would recommend you [ask around on the forum](https://our.umbraco.com) to see if anyone else has managed to do this and how.
