### ISSUE TITLE
Error reading MIME multipart body part when Publishing

### ISSUE THREAD

**Issue by deanmarcussen** [umbraco/Umbraco-CMS#5837]
We are experiencing an aggregate exception randomly, but regularly on one of our Umbraco sites running v7.7.4

It occurs when publishing content when the content item is large , e.g. content-length: 75840, but does not happen if I reduce the content size.

The exception is aggregated but looks to be thrown from inside the `ContentItemBaseBinder` during the `GetModelAsync` call.

I can replicate across two different servers, and have been trying to resolve for a few days now, so could really do with some advice.

`maxAllowedContentLength` is plenty big enough (though I doubled it just to be sure)

Exception that occurs is
```
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Error reading MIME multipart body part. ---> System.Web.HttpException: An error occurred while communicating with the remote host. The error code is 0x800703E5. ---> System.Runtime.InteropServices.COMException: Overlapped I/O operation is in progress. (Exception from HRESULT: 0x800703E5)
   --- End of inner exception stack trace ---
   at System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect)
   at System.Web.Hosting.IIS7WorkerRequest.ReadEntityCoreSync(Byte[] buffer, Int32 offset, Int32 size)
   at System.Web.HttpRequest.GetEntireRawContent()
   at System.Web.HttpRequest.get_InputStream()
   at System.Web.Http.WebHost.HttpControllerHandler.<>c__DisplayClass13.<GetStreamContent>b__f()
   at System.Web.Http.WebHost.HttpControllerHandler.LazyStreamContent.get_StreamContent()
   at System.Web.Http.WebHost.HttpControllerHandler.LazyStreamContent.CreateContentReadStreamAsync()
   at System.Net.Http.HttpContent.ReadAsStreamAsync()
   at System.Net.Http.HttpContentMultipartExtensions.<ReadAsMultipartAsync>d__0`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContentMultipartExtensions.<ReadAsMultipartAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.<GetModelAsync>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.<>c__DisplayClass5_0.<BindModel>b__1(Task`1 x)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.BindModel(HttpActionContext actionContext, ModelBindingContext bindingContext)
   at System.Web.Http.ModelBinding.ModelBinderParameterBinding.ExecuteBindingAsync(ModelMetadataProvider metadataProvider, HttpActionContext actionContext, CancellationToken cancellationToken)
   at System.Web.Http.Controllers.HttpActionBinding.<ExecuteBindingAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Error reading MIME multipart body part. ---> System.Web.HttpException: An error occurred while communicating with the remote host. The error code is 0x800703E5. ---> System.Runtime.InteropServices.COMException: Overlapped I/O operation is in progress. (Exception from HRESULT: 0x800703E5)
   --- End of inner exception stack trace ---
   at System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect)
   at System.Web.Hosting.IIS7WorkerRequest.ReadEntityCoreSync(Byte[] buffer, Int32 offset, Int32 size)
   at System.Web.HttpRequest.GetEntireRawContent()
   at System.Web.HttpRequest.get_InputStream()
   at System.Web.Http.WebHost.HttpControllerHandler.<>c__DisplayClass13.<GetStreamContent>b__f()
   at System.Web.Http.WebHost.HttpControllerHandler.LazyStreamContent.get_StreamContent()
   at System.Web.Http.WebHost.HttpControllerHandler.LazyStreamContent.CreateContentReadStreamAsync()
   at System.Net.Http.HttpContent.ReadAsStreamAsync()
   at System.Net.Http.HttpContentMultipartExtensions.<ReadAsMultipartAsync>d__0`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContentMultipartExtensions.<ReadAsMultipartAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.<GetModelAsync>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.<>c__DisplayClass5_0.<BindModel>b__1(Task`1 x)
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.IO.IOException: Error reading MIME multipart body part. ---> System.Web.HttpException: An error occurred while communicating with the remote host. The error code is 0x800703E5. ---> System.Runtime.InteropServices.COMException: Overlapped I/O operation is in progress. (Exception from HRESULT: 0x800703E5)
   --- End of inner exception stack trace ---
   at System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect)
   at System.Web.Hosting.IIS7WorkerRequest.ReadEntityCoreSync(Byte[] buffer, Int32 offset, Int32 size)
   at System.Web.HttpRequest.GetEntireRawContent()
   at System.Web.HttpRequest.get_InputStream()
   at System.Web.Http.WebHost.HttpControllerHandler.<>c__DisplayClass13.<GetStreamContent>b__f()
   at System.Web.Http.WebHost.HttpControllerHandler.LazyStreamContent.get_StreamContent()
   at System.Web.Http.WebHost.HttpControllerHandler.LazyStreamContent.CreateContentReadStreamAsync()
   at System.Net.Http.HttpContent.ReadAsStreamAsync()
   at System.Net.Http.HttpContentMultipartExtensions.<ReadAsMultipartAsync>d__0`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContentMultipartExtensions.<ReadAsMultipartAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.<GetModelAsync>d__7.MoveNext()<---
<---
```

**Comment by nul800sebastiaan** [comment]
Hey there @deanmarcussen - sorry to hear you've been having problems. Unfortunately you're using a pretty old version of Umbraco. I would recommend you update to the latest version and try again. If you can still reproduce this on v7.15.0 we can re-open this issue.

Thanks!
