### ISSUE TITLE
Search Application Restarting

### ISSUE THREAD

**Issue by TomDaria** [umbraco/Umbraco-CMS#5870]
Hello:

We are on Umbraco 7.11.1.
We have set up a search schedule in umbracoSettings.config to fire off our custom search in the SearchEventHandlers() class every 24 hours.  However, in the logs we see the following two errors all the time and our search index is now corrupt and not building the right number of search entries.

System.TimeoutException: Failed to enter the lock within timeout.
   at Umbraco.Core.AsyncLock.Lock(Int32 millisecondsTimeout)
   at Umbraco.Core.MainDom.Acquire()
   at Umbraco.Core.ApplicationContext.Init()
   at Umbraco.Core.CoreBootManager.CreateApplicationContext(DatabaseContext dbContext, ServiceContext serviceContext)
   at Umbraco.Core.CoreBootManager.Initialize()
   at Umbraco.Web.WebBootManager.Initialize()
   at Umbraco.Core.UmbracoApplicationBase.StartApplication(Object sender, EventArgs e)

Followed by INFO Message
Application shutdown. Details: HostingEnvironment

_shutDownMessage=HostingEnvironment initiated shutdown
HostingEnvironment caused shutdown

_shutDownStack=   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Web.Hosting.HostingEnvironment.InitiateShutdownInternal()
   at System.Web.Hosting.HostingEnvironment.InitiateShutdownWithoutDemand()
   at System.Web.Hosting.PipelineRuntime.StopProcessing()

Does anyone know why this is happening and is there a fix?

**Comment by nul800sebastiaan** [comment]
Hey there @TomDaria - make sure [to post your questions in the forums](https://our.umbraco.com) where our community can try to help you out. If you can reproduce the problem in any way in the latest version of Umbraco (7.15.0) we'd love to hear some more details.

**Comment by nul800sebastiaan** [comment]
Ps. as a general recommendation, try to investigate using a more advanced scheduler than the one built into Umbraco, that way you also have more control over what happens and when, and if there should be retries etc. Hangfire is great!

**Comment by TomDaria** [comment]
OK Thanks.
BTW, I did send this request to Umbraco support and to https://our.umbraco.com/.
https://our.umbraco.com/ never responded.
Umbraco support told me since I custom coded the searchEventHandlers I'd have to upgrade software support to a higher level.  
Anyway I got the issue fixed over the weekend.

Thanks
