### ISSUE TITLE
When upgrading to 7.15, custom web api filters stop working

### ISSUE THREAD

**Issue by simonech** [umbraco/Umbraco-CMS#6087]
With the upgrade to 7.15, many MVC and WebAPI dlls have been upgraded to the latest version.
One of them causes the reference of `System.Net.Http` to go from 4.0.0.0 to 4.2.0.0.

Umbraco keeps on working fine, but custom web api that use filters give this error

```
<Error><Message>An error has occurred.</Message><ExceptionMessage>Method not found: 'System.Net.Http.HttpRequestMessage System.Web.Http.Filters.HttpActionExecutedContext.get_Request()'.</ExceptionMessage><ExceptionType>System.MissingMethodException</ExceptionType><StackTrace>   at Headless.Core.Mvc.Filters.ApiExceptionFilterAttribute.OnException(HttpActionExecutedContext context)
   at System.Web.Http.Filters.ExceptionFilterAttribute.OnExceptionAsync(HttpActionExecutedContext actionExecutedContext, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ExceptionFilterAttribute.<ExecuteExceptionFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()</StackTrace></Error>

```
The error doesn't appear on a local machine, but only on the servers (which do not have 4.7.2 installed)

We solved the problem by changing the redirection of that assembly to 4.2

```
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.0" />
      </dependentAssembly>

```

Not sure if it's a generic problem or just our own environment.

**Comment by nul800sebastiaan** [comment]
Yep, going from .NET 4.5 to 4.5.2 and upgrading all dependencies will be a bit painful for 7.15 upgraders. This is exactly what you need to do, most of the time, NuGet will do the right thing and update this redirect for you.. but magically, it sometimes does not. 🤦‍♂️

Weirdly, it works fine with a redirect to 4.0.0.0 for most people. I don't know why it wouldn't work for you though. DLL hell is still present I guess. 

I'll keep an eye on it, but I think it might be localized to only a handful of setups. Thanks for reporting!
