### ISSUE TITLE
 The configuration for data type xxxx: Umbraco.MarkdownEditor is invalid after v8 migration

### ISSUE THREAD

**Issue by balintbako** [umbraco/Umbraco-CMS#6194]
Editor JSON configuration created incorrectly when upgrading from 7.15.1 to 8.1.3.
I get the following exception when opening a page with a Markdown Editor on one of its properties after the upgrade:
```
{"@t":"2019-08-26T09:30:05.7023397Z","@mt":"Unhandled controller exception occurred for request '{RequestUrl}'","@l":"Error","@x":
"System.InvalidOperationException: The configuration for data type 1118 : Umbraco.MarkdownEditor is invalid (see inner exception). Please fix the configuration and ensure it is valid. The site may fail to start and / or load data types and run. 
---> System.InvalidOperationException: Failed to parse configuration \"{\"preview\":\"\",\"defaultValue\":\"\"}\" as \"MarkdownConfiguration\" (see inner exception). ---> Newtonsoft.Json.JsonSerializationException: Error converting value \"\" to type 'System.Boolean'. Path 'preview', line 1, position 13. 
---> System.FormatException: String was not recognized as a valid Boolean.
   at System.Boolean.Parse(String value)
   at System.String.System.IConvertible.ToBoolean(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)  
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 982
--- End of inner exception stack trace ---
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 989
 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 196


```

Reproduction
------------

The database changes are the following:
Pre-upgrade data:
pk	nodeId	propertyEditorAlias	dbType
91	1118	Umbraco.MarkdownEditor	Ntext

id	datatypeNodeId	value	sortorder	alias
133	1118		1	preview
134	1118		2	defaultValue

Post-upgrade data:
nodeId	propertyEditorAlias	dbType	config
1118	Umbraco.MarkdownEditor	Ntext	{"preview":"","defaultValue":""}

The post-upgrde config is a valid JSON but it doesn't meet the expected schema.

The "preview":"" should be migrated to "preview": false.

Workaround
------------

Runinng the following SQL resolved the issue:
UPDATE [dbo].[umbracoDataType]
  SET config =  CAST(N'{"preview":false,"defaultValue":""}' AS ntext)
  WHERE CAST(config AS nvarchar(max)) = N'{"preview":"","defaultValue":""}'

**Comment by stevemegson** [comment]
The migration of data type configuration knows which prevalues should be parsed as bool or int, but MarkdownEditor was missing. I've added it in #6200.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6200

Cherry picked for 8.1.4 71aad30f8ea63662606b42bd5abb540fd3ffd559
