### ISSUE TITLE
ModelsBuilder RTE is not resolving LocalLink in preview mode and throws a null exception

### ISSUE THREAD

**Issue by CodeCheetah** [umbraco/Umbraco-CMS#6437]
Using umbraco 7.13.2, when previewing content, generated model file returns a null exception with the following stacktrace.

When viewing the content in published mode it correctly resolves the LocalLink reference.

   at umbraco.presentation.preview.PreviewContent.EnsureInitialized(User user, String previewSet, Boolean validate, Action initialize)
   at Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedContentCache.<>c.<get_GetXmlDelegate>b__42_0(UmbracoContext context, Boolean preview)
   at Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedContentCache.GetXml(UmbracoContext umbracoContext, Boolean preview)
   at Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedContentCache.DetermineRouteById(UmbracoContext umbracoContext, Boolean preview, Int32 contentId)
   at Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedContentCache.GetRouteById(UmbracoContext umbracoContext, Boolean preview, Int32 contentId)
   at Umbraco.Web.Routing.DefaultUrlProvider.GetUrl(UmbracoContext umbracoContext, Int32 id, Uri current, UrlProviderMode mode)
   at Umbraco.Web.Routing.UrlProvider.<>c__DisplayClass16_0.<GetUrl>b__0(IUrlProvider provider)
   at Umbraco.Web.Routing.UrlProvider.GetUrl(Int32 id, Uri current, UrlProviderMode mode)
   at Umbraco.Web.Routing.UrlProvider.GetUrl(Guid id)
   at Umbraco.Web.Templates.TemplateUtilities.ParseInternalLinks(String text, UrlProvider urlProvider)
   at Umbraco.Web.Templates.TemplateUtilities.ParseInternalLinks(String text, Boolean preview)
   at Umbraco.Web.PropertyEditors.ValueConverters.RteMacroRenderingValueConverter.ConvertDataToSource(PublishedPropertyType propertyType, Object source, Boolean preview)
   at Umbraco.Web.Models.DetachedPublishedProperty.<.ctor>b__7_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Umbraco.Web.Models.DetachedPublishedProperty.<.ctor>b__7_1()
   at System.Lazy`1.CreateValue()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Umbraco.Web.PublishedPropertyExtension.GetValue[T](IPublishedProperty property, Boolean withDefaultValue, T defaultValue)
   at Umbraco.Web.PublishedContentExtensions.GetPropertyValue[T](IPublishedContent content, String alias)

Generated models builder file contains the following reference where it fails.

```
[ImplementPropertyType("text")]
public IHtmlString Text
{
get { return this.GetPropertyValue<IHtmlString>("text"); }
}
```

Any ideas?

**Comment by nul800sebastiaan** [comment]
Have you tried to update to the latest available version of modelsbuilder for v7? I am not sure what version shipped with 7.13.2, but there may be an update out.

**Comment by CodeCheetah** [comment]
Hi @nul800sebastiaan, I'm running version 3.0.10 which is the latest for v7. The next available version is for v8.

**Comment by CodeCheetah** [comment]
If I remove an internal link in the RTE, and preview the content, it works without problems.

Any ideas?

**Comment by stevemegson** [comment]
@CodeCheetah is there more to the stack trace, showing where the `Text` property is being accessed from?

The only way I can see for `PreviewContent.EnsureInitialized` to throw a `NullReferenceException` is if the `user` argument is null. But if we had no current user, we wouldn't be in preview mode. It looks like there must be some sort of caching issue where the current user is available when the `IPublishedContent` is created, but when the `Text` property is accessed we've lost that context.

**Comment by nul800sebastiaan** [comment]
Thanks @CodeCheetah - I would recommend you create an issue in the Modelsbuilder issue tracker instead, you can find it here: https://github.com/zpqrtbnk/Zbu.ModelsBuilder

**Comment by dawoe** [comment]
@CodeCheetah 

Can you see if the following works for you when previewing.

Instead of `@Model.Text ` in your view, use the following code (non modelsbuilder)

`@Model.GetPropertyValue<IHtmlString>("text")`

I have a site still running 7.13.2 and I am not seeing this by the way. So it could be specific to your implementation.

Have you tried producing it on a clean 7.13.2 install
