### ISSUE TITLE
Panic, exception while loading cache data

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco-CMS#6450]
While creating a workaround for another issue, I had 2 PVCs that wanted to be the converter for a property (one from an internal framework package and the other still from the project itself).

Instead of throwing an exception on startup (indicating something was completely broken and stop working), it only logged a fatal error `Panic, exception while loading cache data` with the following exception:

```
System.InvalidOperationException: Type 'Framework.FlexibleDropdownPropertyValueConverter' cannot be an IPropertyValueConverter for property 'seoChangeFrequency' of content type 'home' because type 'Project.FlexibleDropdownPropertyValueConverter' has already been detected as a converter for that property, and only one converter can exist for a property.
   at Umbraco.Core.Models.PublishedContent.PublishedPropertyType.InitializeLocked() in d:\a\1\s\src\Umbraco.Core\Models\PublishedContent\PublishedPropertyType.cs:line 166
   at Umbraco.Core.Models.PublishedContent.PublishedPropertyType.Initialize() in d:\a\1\s\src\Umbraco.Core\Models\PublishedContent\PublishedPropertyType.cs:line 104
   at Umbraco.Core.Models.PublishedContent.PublishedPropertyType.get_CacheLevel() in d:\a\1\s\src\Umbraco.Core\Models\PublishedContent\PublishedPropertyType.cs:line 197
   at Umbraco.Core.Models.PublishedContent.PublishedPropertyBase..ctor(IPublishedPropertyType propertyType, PropertyCacheLevel referenceCacheLevel) in d:\a\1\s\src\Umbraco.Core\Models\PublishedContent\PublishedPropertyBase.cs:line 18
   at Umbraco.Web.PublishedCache.NuCache.Property..ctor(IPublishedPropertyType propertyType, PublishedContent content, PropertyData[] sourceValues, IPublishedSnapshotAccessor publishedSnapshotAccessor, PropertyCacheLevel referenceCacheLevel) in d:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\Property.cs:line 47
   at Umbraco.Web.PublishedCache.NuCache.PublishedContent..ctor(ContentNode contentNode, ContentData contentData, IPublishedSnapshotAccessor publishedSnapshotAccessor, IVariationContextAccessor variationContextAccessor) in d:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\PublishedContent.cs:line 41
   at Umbraco.Web.PublishedCache.NuCache.ContentNode.SetContentTypeAndData(IPublishedContentType contentType, ContentData draftData, ContentData publishedData, IPublishedSnapshotAccessor publishedSnapshotAccessor, IVariationContextAccessor variationContextAccessor) in d:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\ContentNode.cs:line 82
   at Umbraco.Web.PublishedCache.NuCache.ContentNodeKit.Build(IPublishedContentType contentType, IPublishedSnapshotAccessor publishedSnapshotAccessor, IVariationContextAccessor variationContextAccessor, Boolean canBePublished) in d:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\ContentNodeKit.cs:line 37
   at Umbraco.Web.PublishedCache.NuCache.ContentStore.BuildKit(ContentNodeKit kit) in d:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\ContentStore.cs:line 496
   at Umbraco.Web.PublishedCache.NuCache.ContentStore.SetAll(IEnumerable`1 kits, Boolean fromLocalDb) in d:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\ContentStore.cs:line 602
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.LoadContentFromLocalDbLocked(IScope scope) in d:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\PublishedSnapshotService.cs:line 383
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.LockAndLoadContent(Func`2 action) in d:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\PublishedSnapshotService.cs:line 340
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.LoadCaches() in d:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\PublishedSnapshotService.cs:line 188
```

And besides swallowing the exception, the cache didn't load and all front-end requests showed the `noNodes.aspx` page ('Welcome to your Umbraco installation') with a `200 OK` status code!

This is quite concerning, as apparantly any exception thrown while loading the cache can cause this page to be shown to visitors (instead of a custom error page), allow search engines to index this page (removing the actual content from the index) and not indicate there's a problem (e.g. when using status monitoring software doing HTTP checks). These results are similair to those I've raised in issue https://github.com/umbraco/Umbraco-CMS/issues/6334.

Reproduction
------------

### Bug summary
Tested in Umbraco 8.1.4 and 8.1.5.

### Steps to reproduce
Add a duplicate PVC and request a page.

### Expected result
The exception to be thrown and stop the application (YSOD).

### Actual result
Fatal error logged, cache not loaded and `noNodes.aspx` returned on every front-end request (the Umbraco back-office can be loaded and publishing content showed the same exception in a dialog).

**Comment by stevemegson** [comment]
It looks like this is fixed for 8.2. `PublishedSnapshotService.LoadCaches` now rethrows the exception after logging it, leading to a `BootFailedException` which brings the whole site down as you'd expect. 

Previously it would end up setting the `_isReady` flag even though nothing had been loaded, leaving the site in a state which looked just like the caches had been successfully loaded from a brand new empty database.

**Comment by nul800sebastiaan** [comment]
Yeah it should be "better" in 8.2.0, @ronaldbarendse could you test in a build of one of the latest commits? The artifacts can be found here: https://umbraco.visualstudio.com/Umbraco%20Cms/_build/results?buildId=26410

**Comment by ronaldbarendse** [comment]
I see @Shazwazza has indeed done a major refactor of the NuCache in https://github.com/umbraco/Umbraco-CMS/pull/6347. I'll check whether the latest code does indeed throw a `BootFailedException` in this case, as that's indeed what I would expect 👍

**Comment by ronaldbarendse** [comment]
I can confirm Umbraco 8.5.2 currently throws the `InvalidOperationException` on startup 👍

```
[InvalidOperationException: Type 'Umbraco.Web.UI.Core.Test2ValueConverter' cannot be an IPropertyValueConverter for property 'test' of content type 'home' because type 'Umbraco.Web.UI.Core.TestValueConverter' has already been detected as a converter for that property, and only one converter can exist for a property.]
   Umbraco.Core.Models.PublishedContent.PublishedPropertyType.InitializeLocked() in Umbraco.Core\Models\PublishedContent\PublishedPropertyType.cs:166
   Umbraco.Core.Models.PublishedContent.PublishedPropertyType.Initialize() in Umbraco.Core\Models\PublishedContent\PublishedPropertyType.cs:104
   Umbraco.Core.Models.PublishedContent.PublishedPropertyType.get_CacheLevel() in Umbraco.Core\Models\PublishedContent\PublishedPropertyType.cs:197
   Umbraco.Core.Models.PublishedContent.PublishedPropertyBase..ctor(IPublishedPropertyType propertyType, PropertyCacheLevel referenceCacheLevel) in Umbraco.Core\Models\PublishedContent\PublishedPropertyBase.cs:21
   Umbraco.Web.PublishedCache.NuCache.Property..ctor(IPublishedPropertyType propertyType, PublishedContent content, PropertyData[] sourceValues, IPublishedSnapshotAccessor publishedSnapshotAccessor, PropertyCacheLevel referenceCacheLevel) in Umbraco.Web\PublishedCache\NuCache\Property.cs:47
   Umbraco.Web.PublishedCache.NuCache.PublishedContent..ctor(ContentNode contentNode, ContentData contentData, IPublishedSnapshotAccessor publishedSnapshotAccessor, IVariationContextAccessor variationContextAccessor) in Umbraco.Web\PublishedCache\NuCache\PublishedContent.cs:42
   Umbraco.Web.PublishedCache.NuCache.ContentNode.GetModel(IPublishedContent& model, ContentData contentData) in Umbraco.Web\PublishedCache\NuCache\ContentNode.cs:148
   Umbraco.Web.PublishedCache.NuCache.ContentNode.get_PublishedModel() in Umbraco.Web\PublishedCache\NuCache\ContentNode.cs:160
   Umbraco.Web.PublishedCache.NuCache.<>c.<HasContent>b__25_0(ContentNode x) in Umbraco.Web\PublishedCache\NuCache\ContentCache.cs:312
   System.Linq.Enumerable.Any(IEnumerable`1 source, Func`2 predicate) +140
   Umbraco.Web.PublishedCache.NuCache.ContentCache.HasContent(Boolean preview) in Umbraco.Web\PublishedCache\NuCache\ContentCache.cs:310
   Umbraco.Web.PublishedCache.PublishedCacheBase.HasContent() in Umbraco.Web\PublishedCache\PublishedCacheBase.cs:88
   Umbraco.Web.UmbracoInjectedModule.EnsureHasContent(UmbracoContext context, HttpContextBase httpContext) in Umbraco.Web\UmbracoInjectedModule.cs:234
   Umbraco.Web.UmbracoInjectedModule.EnsureUmbracoRoutablePage(UmbracoContext context, HttpContextBase httpContext) in Umbraco.Web\UmbracoInjectedModule.cs:175
   Umbraco.Web.UmbracoInjectedModule.ProcessRequest(HttpContextBase httpContext) in Umbraco.Web\UmbracoInjectedModule.cs:116
   Umbraco.Web.UmbracoInjectedModule.<Init>b__18_4(Object sender, EventArgs e) in Umbraco.Web\UmbracoInjectedModule.cs:414
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +201
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +132
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +73
```
