### ISSUE TITLE
 Umbraco.Core.Exceptions.BootFailedException: Boot failed.

### ISSUE THREAD

**Issue by parejajd** [umbraco/Umbraco-CMS#7113]
I am using Umbraco 8.1.4 in a hosting provider.

I am getting the error 

Boot failed: Umbraco cannot run. See Umbraco's log file for more details.
-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.
-> System.TimeoutException: Failed to enter the lock within timeout.
  at Umbraco.Core.AsyncLock.Lock(Int32 millisecondsTimeout) in d:\a\1\s\src\Umbraco.Core\AsyncLock.cs:line 114
  at Umbraco.Core.MainDom.Acquire() in d:\a\1\s\src\Umbraco.Core\MainDom.cs:line 170
  at Umbraco.Core.Runtime.CoreRuntime.AcquireMainDom(MainDom mainDom) in d:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 232
  at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in d:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 143

## Umbraco version 8.1.4

Reproduction
------------
the error disappears and reappears a few days later.

This file is a LOG generated after that stop and restart IIS.

[UmbracoTraceLog.WIN5129.20191108.json.txt](https://github.com/umbraco/Umbraco-CMS/files/3826294/UmbracoTraceLog.WIN5129.20191108.json.txt)

**Comment by nul800sebastiaan** [comment]
Hi there @parejajd. Luckily this doesn't seem to happen for most people, so I have to assume there's a problem on your end somewhere.

Make sure to open a topic on the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
