### ISSUE TITLE
NuCache Object  reference ex. inside non HttpContext based threads for culture based content

### ISSUE THREAD

**Issue by ekovand** [umbraco/Umbraco-CMS#7844]
UmbracoContext.Content methods in non HttpContext based scopes return ONLY non culture based content.
Any try to get variant nodes results in object reference in NuCache.

`umbracoContext.Content.GetAtRoot() `
- returns only invariant nodes.

```csharp
var contentType = umbracoContext.Content.GetContentType(Frontpage.ModelTypeAlias); 
var frontpages = umbracoContext.Content.GetByContentType(contentType) 
```

- throws Object reference at Umbraco.Web:

```
at Umbraco.Web.PublishedCache.NuCache.PublishedContent.<>c.<.cctor>b__81_0(IPublishedSnapshot publishedShapshot, Boolean previewing, Int32 id)
   at Umbraco.Web.PublishedCache.NuCache.PublishedContent.<get_ChildrenForAllCultures>d__57.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at Umbraco.Web.PublishedContentExtensions.<EnumerateDescendants>d__83.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()
```

I was using UmbracoContext through IUmbracoContextFactory or IUmbracoContextAccessor - same result. Usage is inside uCommerce pipelines. I am not able to get variant content i any possible way. Using Umbraco.Composing.Current leads to the same results. 

## Umbraco version

8.4.0

### Specifics

Non HttpContext based scopes. Task based methods

### Steps to reproduce

Try to get with  _umbracoContext.Content.GetAtRoot or _umbracoContext.Content.GetByContentType frontpage or any other culture based content. inside non HttpContext thread

**Comment by ekovand** [comment]
@Shazwazza  sorry for tagging, but i know that you was working on NuCache refactor. Maybe you know  how to workaround this. It is not possible to retrieve in any way culture based content from inside pipiline Tasks. In HttpContext flow all works as expected.

**Comment by nul800sebastiaan** [comment]
Thanks @ekovand. Any chance you have some sample code instead of describing the things you are pulling in. It's a bit difficult to understand (for dumb old me 😊).

We'll have to investigate and get back to you.

**Comment by ekovand** [comment]
I have investigated something already. Inside service constructor (lets call it A) where UmbracoContext is injected  culture based content is perfectly returned with .Content helper methods. Inside another thread, calling service method of A - UmbracoContext returns only non culture based content. Direct access of culture based content (as ex. GetByContentType) produces exception in NuCache:

```
var contentType = umbracoContext.Content.GetContentType(Frontpage.ModelTypeAlias); 
var frontpages = umbracoContext.Content.GetByContentType(contentType) 
```

I assume this issue is related to another issue registered by me half a year ago [https://github.com/umbraco/Umbraco-CMS/issues/6044](url). 
I am using Scope based services with your Lifetime.Scope, even in HttpContext based scopes, as Lifetime.Request disposes at the end of thread. 
So i can assume something inside your NuCache which relies on HttpContext for culture based Content gets disposed automatically jumping between threads

**Comment by Shazwazza** [comment]
Can you provide a fully reproducable example with code in its simplest form?

**Comment by Shazwazza** [comment]
Closing this issue due to inactivity, please feel free to re-open with a reproduceable example in it's simplest form. Thanks.

**Comment by jamiehowarth0** [comment]
I've just started getting this error too, I'm trying to retrieve the children of a node and I'm getting a nullref.
Umbraco 8.15.2, even getting the Children of an IPublishedContent inside a background task is erroring.
