### ISSUE TITLE
Services.ContentService.SaveAndPublishWithStatus Results in System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by MichaelRevolvo** [umbraco/Umbraco-CMS#7871]
When saving a document using Services.ContentService.SaveAndPublishWithStatus, I get a System.IndexOutOfRangeException:

> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Umbraco.Core.Persistence.Repositories.SimilarNodeName.get_NumPos()
   at Umbraco.Core.Persistence.Repositories.SimilarNodeName.Comparer.Compare(SimilarNodeName x, SimilarNodeName y)
   at System.Linq.EnumerableSorter`2.CompareKeys(Int32 index1, Int32 index2)
   at System.Linq.EnumerableSorter`1.QuickSort(Int32[] map, Int32 left, Int32 right)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at Umbraco.Core.Persistence.Repositories.SimilarNodeName.GetUniqueName(IEnumerable`1 names, Int32 nodeId, String nodeName)
   at Umbraco.Core.Persistence.Repositories.ContentRepository.EnsureUniqueNodeName(Int32 parentId, String nodeName, Int32 id)
   at Umbraco.Core.Persistence.Repositories.ContentRepository.PersistUpdatedItem(IContent entity)
   at Umbraco.Core.Cache.DefaultRepositoryCachePolicy`2.Update(TEntity entity, Action`1 persistUpdated)
   at Umbraco.Core.Persistence.UnitOfWork.ScopeUnitOfWork.Commit(Action`1 transactionCompleting)
   at Umbraco.Core.Services.ContentService.SaveAndPublishDo(IContent content, Int32 userId, Boolean raiseEvents)
   at Umbraco.Core.Services.ContentService.Umbraco.Core.Services.IContentServiceOperations.SaveAndPublish(IContent content, Int32 userId, Boolean raiseEvents)
   at Umbraco.Core.Services.ContentService.SaveAndPublishWithStatus(IContent content, Int32 userId, Boolean raiseEvents)

It doesn't seem to matter if I change any properties or not. 

I can simply do:

`var doc = Services.ContentService.GetById(id);
Services.ContentService.SaveAndPublishWithStatus(doc, 0, raiseEvents: true);`

And it fails

## Umbraco version

I am seeing this issue on Umbraco version: 7.7.4

Reproduction
------------

`var doc = Services.ContentService.GetById(id);
Services.ContentService.SaveAndPublishWithStatus(doc, 0, raiseEvents: true);`

**Comment by nul800sebastiaan** [comment]
Hey there @MichaelRevolvo - thanks for reporting. Unfortunately I don't know if this issue has been fixed since 7.7.4 but there's a few year's worth of new releases after that, so you might want to try this again after upgrading to 7.15.

Many people are successfully using these eventhandlers so it might be a problem in your specific setup. The comments in this issue might help move you forward: https://issues.umbraco.org/issue/U4-10451

If that doesn't help, make sure to head out to the forum for some help from the community: https://our.umbraco.com/
