### ISSUE TITLE
Error with Grid in Nested Content

### ISSUE THREAD

**Issue by mattchanner** [umbraco/Umbraco-CMS#7874]
I am seeing the same issue as #7058 but the fix there did not resolve it for me.

There's one more place in GridPropertyEditor that's calling `DeserializeGridValue` with a null JSON string.

See the stack trace below, the GetReferences method is the place where it errors for me:

```
Umbraco.Web.PropertyEditors.GridPropertyEditor.GridPropertyValueEditor.DeserializeGridValue(String rawJson, IEnumerable`1& richTextValues, IEnumerable`1& mediaValues) in D:\a\1\s\src\Umbraco.Web\PropertyEditors\GridPropertyEditor.cs:line 150

   at Umbraco.Web.PropertyEditors.GridPropertyEditor.GridPropertyValueEditor.<GetReferences>d__9.MoveNext() in D:\a\1\s\src\Umbraco.Web\PropertyEditors\GridPropertyEditor.cs:line 168

   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)

   at Umbraco.Web.PropertyEditors.NestedContentPropertyEditor.NestedContentPropertyValueEditor.GetReferences(Object value) in D:\a\1\s\src\Umbraco.Web\PropertyEditors\NestedContentPropertyEditor.cs:line 251
```

## Umbraco version

I am seeing this issue on Umbraco version: 8.6

Reproduction
------------
### Bug summary
I have a number of nested content sections that I add to my page.  I incrementally added sections and saved, and at some point (not reliably the same), this error occurs.

**Comment by emmary2020** [comment]
👍

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/7875

**Comment by nul800sebastiaan** [comment]
Cherry picked for 8.6.1 in d0eee32f1d184da7a8eb8207482ba90c3130bd9c
