### ISSUE TITLE
Error on adding Member with a custom User Role

### ISSUE THREAD

**Issue by jpiombo** [umbraco/Umbraco-CMS#8029]
We created a new User Role(Member Administrator) with just permissions to Member section. When hen trying to create new members using a user with Member Administrator Role we are getting an error saying: 

System.InvalidOperationException: No member type found with alias 
   at Umbraco.Web.Editors.Binders.MemberBinder.CreateNew(MemberSave model)
   at Umbraco.Web.Editors.Binders.MemberBinder.BindModel(HttpActionContext actionContext, ModelBindingContext bindingContext)
   at System.Web.Http.ModelBinding.ModelBinderParameterBinding.ExecuteBindingAsync(ModelMetadataProvider metadataProvider, 
----
Unhandled controller exception occurred for request '/umbraco/backoffice/UmbracoApi/Member/PostSave"

## Umbraco version

8.6.0

Reproduction
------------

Create a new user group("Members Admin"), add permissions to just Members Area. 
Create a new user with that new role. 
Login as new user and try to add a new member. 
You get an error and user is not created. 

### Bug summary

Members cannot be created with a new User Group. 

### Specifics
    * /umbraco#/member/member/edit/Member?doctype=Member&create=true
    * 8.6.0
    * Chrome
    * NO
    `Exception
System.InvalidOperationException: No member type found with alias 
   at Umbraco.Web.Editors.Binders.MemberBinder.CreateNew(MemberSave model)
   at Umbraco.Web.Editors.Binders.MemberBinder.BindModel(HttpActionContext actionContext, ModelBindingContext bindingContext)
   at System.Web.Http.ModelBinding.ModelBinderParameterBinding.ExecuteBindingAsync(ModelMetadataProvider metadataProvider, HttpActionContext actionContext, CancellationToken cancellationToken)
   at System.Web.Http.Controllers.HttpActionBinding.<ExecuteBindingAsyncCore>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()`

### Steps to reproduce

*Create a new user group("Members Admin"), add permissions to just Members Area. 
*Create a new user with that new role. 
*Login as new user and try to add a new member. 
*You get an error and user is not created. 

### Expected result

* New Member is created and no error is displayed. 

### Actual result

    * You get an error
    * Member is not saved.
    * Server error: Contact administrator, see log for full details. No member type found with alias

**Comment by jpiombo** [comment]
![image](https://user-images.githubusercontent.com/63891925/80500938-37caae80-8945-11ea-858c-ca4969cc0596.png)

**Comment by jpiombo** [comment]
Seems to be a duplicate issue. more details here: 
https://github.com/umbraco/Umbraco-CMS/issues/8004

Closing this one.
