### ISSUE TITLE
netcore - linux startup exception - unsupported named synchronisation primitive - new System.Threading.Semaphore(int,int,string)

### ISSUE THREAD

**Issue by pijemcolu** [umbraco/Umbraco-CMS#8130]
Using branch `netcore/dev`, Umbraco doesn't start up on Linux. It throws an exception:

```
Unhandled exception. System.PlatformNotSupportedException: The named version of this synchronization primitive is not supported on this platform.
   at System.Threading.Semaphore.CreateSemaphoreCore(Int32 initialCount, Int32 maximumCount, String name, Boolean& createdNew)
   at System.Threading.Semaphore..ctor(Int32 initialCount, Int32 maximumCount, String name, Boolean& createdNew)
   at System.Threading.Semaphore..ctor(Int32 initialCount, Int32 maximumCount, String name)
   at Umbraco.Core.SystemLock..ctor(String name) in /home/mikulas/code/Umbraco-CMS/src/Umbraco.Core/SystemLock.cs:line 58
   at Umbraco.Core.Runtime.MainDomSemaphoreLock..ctor(ILogger logger, IHostingEnvironment hostingEnvironment) in /home/mikulas/code/Umbraco-CMS/src/Umbraco.Infrastructure/Runtime/MainDomSemaphoreLock.cs:line 25
   at Umbraco.Web.Common.Extensions.UmbracoCoreServiceCollectionExtensions.GetCoreRuntime(Configs configs, IUmbracoVersion umbracoVersion, IIOHelper ioHelper, ILogger logger, IProfiler profiler, IHostingEnvironment hostingEnvironment, IBackOfficeInfo backOfficeInfo, ITypeFinder typeFinder, IRequestCache requestCache) in /home/mikulas/code/Umbraco-CMS/src/Umbraco.Web.Common/Extensions/UmbracoCoreServiceCollectionExtensions.cs:line 178
   at Umbraco.Web.Common.Extensions.UmbracoCoreServiceCollectionExtensions.AddUmbracoCore(IServiceCollection services, IWebHostEnvironment webHostEnvironment, IRegister umbContainer, Assembly entryAssembly, IRequestCache requestCache, ILoggingConfiguration loggingConfiguration, IFactory& factory) in /home/mikulas/code/Umbraco-CMS/src/Umbraco.Web.Common/Extensions/UmbracoCoreServiceCollectionExtensions.cs:line 138
   at Umbraco.Web.Common.Extensions.UmbracoCoreServiceCollectionExtensions.AddUmbracoCore(IServiceCollection services, IWebHostEnvironment webHostEnvironment, IFactory& factory) in /home/mikulas/code/Umbraco-CMS/src/Umbraco.Web.Common/Extensions/UmbracoCoreServiceCollectionExtensions.cs:line 89
   at Umbraco.Web.UI.BackOffice.Startup.ConfigureServices(IServiceCollection services) in /home/mikulas/code/Umbraco-CMS/src/Umbraco.Web.UI.NetCore/Startup.cs:line 45
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Umbraco.Web.UI.BackOffice.Program.Main(String[] args) in /home/mikulas/code/Umbraco-CMS/src/Umbraco.Web.UI.NetCore/Program.cs:line 11
```

## Umbraco version

dotnetcore (9? - X? - Umbraco?)

## Reproduction

On Linux:
```zsh
$ dotnet run --project Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj   
```

## Extras

System.Thread.Semaphore(int,int,string) is not supported on Linux. The named lock is being created [here in Umbraco:](https://github.com/umbraco/Umbraco-CMS/blob/netcore%2Fdev/src/Umbraco.Infrastructure/Runtime/MainDomSemaphoreLock.cs#L24)

The [named event handle created just below](https://github.com/umbraco/Umbraco-CMS/blob/netcore%2Fdev/src/Umbraco.Infrastructure/Runtime/MainDomSemaphoreLock.cs#L28) will also be an issue.

Most I could find is the implementation where the exception is thrown in [netcorefx github repo](https://github.com/dotnet/coreclr/pull/1387/files#diff-3160d26a085746f6fc9bf5297f9574bfR103)

Last comment on an [issue in dotnet runtime](https://github.com/dotnet/runtime/issues/4370) states the exception is thrown by design and named SystemLock won't be implemented, hinting at using a Mutex instead.

**Comment by Shazwazza** [comment]
We already have a work around for this which is to use the SqlMainDomLock configuration setting: https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/azure-web-apps#recommended-configuration

IIRC we cannot use a Mutex lock for this requirement. For the netcore project though we can detect what OS we are running in and apply the setting automatically. Else we can consider only using the SqlMainDomLock though it comes with a 'penalty' of a simple SQL query per second which isn't really anything to worry about. Anyways, something to consider.

**Comment by pijemcolu** [comment]
I've made a small PR for detecting the OS runtime and using Sql lock as default in that case. We might want to move that OSPlatform check elsewhere though I am unsure what's your opinion on that.
