### ISSUE TITLE
GetAllContentTypeAliases with objectTypes throws ArgumentException

### ISSUE THREAD

**Issue by stefankip** [umbraco/Umbraco-CMS#8599]
Umbraco v8.6.3

I'm trying to get all document type aliases using:
`_contentTypeService.GetAllContentTypeAliases(Umbraco.Core.Constants.ObjectTypes.DocumentType)`

This throws an exception:
```
System.ArgumentException: Parameter '@objectTypes' specified but none of the passed arguments have a property with this name (in 'WHERE (umbracoNode.nodeObjectType IN (@objectTypes))')
  at NPoco.ParameterHelper.ProcessParam(String& sql, String rawParam, Object[] args_src, List`1 args_dest)
  at NPoco.ParameterHelper.<>c__DisplayClass1_0.<ProcessParams>b__0(Match m)
  at System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
  at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator, Int32 count, Int32 startat)
  at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
  at NPoco.ParameterHelper.ProcessParams(String sql, Object[] args_src, List`1 args_dest)
  at NPoco.Sql.Build(StringBuilder sb, List`1 args, Sql lhs)
  at NPoco.Sql.Build(StringBuilder sb, List`1 args, Sql lhs)
  at NPoco.Sql.Build(StringBuilder sb, List`1 args, Sql lhs)
  at NPoco.Sql.Build(StringBuilder sb, List`1 args, Sql lhs)
  at NPoco.Sql.Build(StringBuilder sb, List`1 args, Sql lhs)
  at NPoco.Sql.Build()
  at NPoco.Database.<QueryImp>d__164`1.MoveNext()
  at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
  at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
  at NPoco.Database.Fetch[T](Sql sql)
  at Umbraco.Core.Persistence.Repositories.Implement.ContentTypeRepository.GetAllContentTypeAliases(Guid[] objectTypes) in d:\a\1\s\src\Umbraco.Core\Persistence\Repositories\Implement\ContentTypeRepository.cs:line 137
  at Umbraco.Core.Services.Implement.ContentTypeService.GetAllContentTypeAliases(Guid[] guids) in d:\a\1\s\src\Umbraco.Core\Services\Implement\ContentTypeService.cs:line 71
```

The line of code where this is happening:
https://github.com/umbraco/Umbraco-CMS/blob/db6714d3b8f8e04dceb607c3a25117331f6b525d/src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeRepository.cs#L137

I think this should be:
`sql = sql.Where("umbracoNode.nodeObjectType IN (@objectTypes)", new { objectTypes });`
instead?

**Comment by kjac** [comment]
@stefankip right you are! Thank you for reporting - PR in #8611

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/8611

Cherry picked for 8.7.0 in a06c8df6eea2419ffe3b78b510257aa3f0ad4f85
