### ISSUE TITLE
Search in back-office throws exception when query contains a dash

### ISSUE THREAD

**Issue by stefankip** [umbraco/Umbraco-CMS#8991]
Reproducible in Umbraco 8.6 and 8.7

When I enter a query in the back-office search containing a dash "-", an exception is thrown.
I use dashes to create structure in the dictionary, that's why I was searching for something containing a dash.

The exception and stacktrace (in this example I searched for **newsletter - fields - forms**):

```
Lucene.Net.QueryParsers.ParseException: Cannot parse '+(nodeName:"newsletter \- fields \- forms"^10.0 nodeName_en-gb:"newsletter \- fields \- forms"^10.0 nodeName_nl-nl:"newsletter \- fields \- forms"^10.0 nodeName:(newsletter* \-* fields* \-* forms* ) nodeName_en-gb:(newsletter* \-* fields* \-* forms* ) nodeName_nl-nl:(newsletter* \-* fields* \-* forms* ) id:(newsletter* \-* fields* \-* forms* ) __NodeId:(newsletter* \-* fields* \-* forms* ) __Key:(newsletter* \-* fields* \-* forms* ) umbracoFileSrc:(newsletter* * fields* * forms* ) ) +__IndexType:media': '*' or '?' not allowed as first character in WildcardQuery ---> Lucene.Net.QueryParsers.ParseException: '*' or '?' not allowed as first character in WildcardQuery
   at Lucene.Net.QueryParsers.QueryParser.GetWildcardQuery(String field, String termStr) in d:\Lucene.Net\FullRepo\trunk\src\core\QueryParser\QueryParser.cs:line 996
   at Lucene.Net.QueryParsers.MultiFieldQueryParser.GetWildcardQuery(String field, String termStr) in d:\Lucene.Net\FullRepo\trunk\src\core\QueryParser\MultiFieldQueryParser.cs:line 202
   at Lucene.Net.QueryParsers.QueryParser.Term(String field) in d:\Lucene.Net\FullRepo\trunk\src\core\QueryParser\QueryParser.cs:line 1494
   at Lucene.Net.QueryParsers.QueryParser.Clause(String field) in d:\Lucene.Net\FullRepo\trunk\src\core\QueryParser\QueryParser.cs:line 1383
   at Lucene.Net.QueryParsers.QueryParser.Query(String field) in d:\Lucene.Net\FullRepo\trunk\src\core\QueryParser\QueryParser.cs:line 1331
   at Lucene.Net.QueryParsers.QueryParser.Clause(String field) in d:\Lucene.Net\FullRepo\trunk\src\core\QueryParser\QueryParser.cs:line 1387
   at Lucene.Net.QueryParsers.QueryParser.Query(String field) in d:\Lucene.Net\FullRepo\trunk\src\core\QueryParser\QueryParser.cs:line 1331
   at Lucene.Net.QueryParsers.QueryParser.Clause(String field) in d:\Lucene.Net\FullRepo\trunk\src\core\QueryParser\QueryParser.cs:line 1387
   at Lucene.Net.QueryParsers.QueryParser.Query(String field) in d:\Lucene.Net\FullRepo\trunk\src\core\QueryParser\QueryParser.cs:line 1301
   at Lucene.Net.QueryParsers.QueryParser.Parse(String query) in d:\Lucene.Net\FullRepo\trunk\src\core\QueryParser\QueryParser.cs:line 223
   --- End of inner exception stack trace ---
   at Lucene.Net.QueryParsers.QueryParser.Parse(String query) in d:\Lucene.Net\FullRepo\trunk\src\core\QueryParser\QueryParser.cs:line 229
   at Examine.LuceneEngine.Search.LuceneSearchQueryBase.NativeQuery(String query) in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Search\LuceneSearchQueryBase.cs:line 86
   at Umbraco.Web.Search.UmbracoTreeSearcher.ExamineSearch(String query, UmbracoEntityTypes entityType, Int32 pageSize, Int64 pageIndex, String culture, Int64& totalFound, String searchFrom, Boolean ignoreUserStartNodes) in D:\a\1\s\src\Umbraco.Web\Search\UmbracoTreeSearcher.cs:line 139
   at Umbraco.Web.Trees.MediaTreeController.Search(String query, Int32 pageSize, Int64 pageIndex, Int64& totalFound, String searchFrom) in D:\a\1\s\src\Umbraco.Web\Trees\MediaTreeController.cs:line 171
   at Umbraco.Web.Editors.EntityController.SearchAll(String query) in D:\a\1\s\src\Umbraco.Web\Editors\EntityController.cs:line 152
```

**Comment by nathanwoulfe** [comment]
`umbracoFileSrc:(newsletter* * fields* * forms* )` will be causing the error - the `-` isn't being escaped here, rather it is removed, which leaves the wildcard char and causes the error. From a very quick look, it's an issue in `createQuery`, which is an Examine method...

**Comment by Shazwazza** [comment]
This is an Umbraco issue. The `UmbracoTreeSearcher.ExamineSearch` creates a raw Lucene string to search on which is passed to `NativeQuery` and when doing that it's up to you to make sure your lucene query is good, not up to Examine. I mentioned that here too https://github.com/Shazwazza/Examine/issues/187#issuecomment-744799353

**Comment by RyuLindow** [comment]
I've smashed through my entire keyboard(both EN and DK layout) after I've encountered this issue and noticed that this happens with * and ' as well.

**Comment by Shazwazza** [comment]
yes any reserved lucene chars will most likely throw, Umbraco needs to escape these strings before passing them as a raw lucene query.

**Comment by nul800sebastiaan** [comment]
Not sure what changed but I can't reproduce this on 8.11.1 

![image](https://user-images.githubusercontent.com/304656/109812247-2076e480-7c2c-11eb-89df-6ae7ea29c70f.png)

![image](https://user-images.githubusercontent.com/304656/109812250-21a81180-7c2c-11eb-9672-c6192de72156.png)

If this is still an issue on 8.11 then we'll need some repro steps, but it seems like it works now. We can re-open if this is still a problem.
