### ISSUE TITLE
Save and Publish of multiple content nodes in background tasks raises errors

### ISSUE THREAD

**Issue by deekoulos** [umbraco/Umbraco-CMS#9355]
using Umbraco 8.7.0.

Hi!

before I get into the details, I found, that similiar issues were already fixed within 8.6.4 see: https://github.com/umbraco/Umbraco-CMS/pull/7994 why I assume, that this error shouldn't occur in 8.7.0.

But there is also this issue: https://github.com/umbraco/Umbraco-CMS/pull/8772 which also seems to be similiar and fixed in 8.7.1

The question is, if the exceptions I am facing are related to one of these issues or if its a new one. 

Here is the code within PerformRun:

```
using (UmbracoContextReference context = _umbracoContextFactory.EnsureUmbracoContext())
                {
                    // doing stuff...

                    using (var scope = _scopeProvider.CreateScope())
                    {
                        foreach (var item in providerOverview)
                        {
                            var categoryContent = _contentService.GetById(item.Item1);

                            categoryContent.SetValue("membersCount", item.Item2);
                            categoryContent.SetValue("reviewsCount", item.Item3);

                            _contentService.SaveAndPublish(categoryContent);
                        }

                        scope.Complete();
                    }                    
                }
```

This is what appears in the logs:

```
System.AggregateException: Exceptions were thrown by listed actions. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Core.Scoping.Scope.<>c__DisplayClass71_0.<RobustExit>b__2()
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)
   at Umbraco.Core.Scoping.Scope.RobustExit(Boolean completed, Boolean onException)
   at Umbraco.Core.Scoping.Scope.DisposeLastScope()
   at Umbraco.Core.Scoping.Scope.Dispose()
   at Umbraco.Core.Services.Implement.PublicAccessService.GetEntryForContent(String contentPath)
   at Umbraco.Core.Services.Implement.PublicAccessService.IsProtected(String contentPath)
   at Umbraco.Examine.ContentValueSetValidator.ValidateProtectedContent(String path, String category)
   at Umbraco.Examine.ContentValueSetValidator.Validate(ValueSet valueSet)
   at Examine.Providers.BaseIndexProvider.<IndexItems>b__12_0(ValueSet x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at Umbraco.Examine.UmbracoContentIndex.PerformIndexItems(IEnumerable`1 values, Action`1 onComplete)
   at Examine.Providers.BaseIndexProvider.IndexItems(IEnumerable`1 values)
   at Umbraco.Web.Search.ExamineComponent.DeferedReIndexForContent.Execute(ExamineComponent examineComponent, IContent content, Boolean isPublished)
   at Umbraco.Web.Search.ExamineComponent.DeferedReIndexForContent.Execute()
   at Umbraco.Web.Search.ExamineComponent.DeferedActions.Execute()
   at Umbraco.Web.Search.ExamineComponent.DeferedActions.<>c.<Get>b__1_1(Boolean completed, DeferedActions actions)
   at Umbraco.Core.Scoping.ScopeContext.EnlistedObject`1.Execute(Boolean completed)
   at Umbraco.Core.Scoping.ScopeContext.ScopeExit(Boolean completed)
   --- End of inner exception stack trace ---
   at Umbraco.Core.Scoping.ScopeContext.ScopeExit(Boolean completed)
   at Umbraco.Core.Scoping.Scope.<>c__DisplayClass71_0.<RobustExit>b__2()
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)
   at Umbraco.Core.Scoping.Scope.RobustExit(Boolean completed, Boolean onException)
   at Umbraco.Core.Scoping.Scope.DisposeLastScope()
   at Umbraco.Core.Scoping.Scope.Dispose()
   at Feedbax.Core.Extensions.UpdateCounts.PerformRun()
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Core.Scoping.Scope.<>c__DisplayClass71_0.<RobustExit>b__2()
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)
   at Umbraco.Core.Scoping.Scope.RobustExit(Boolean completed, Boolean onException)
   at Umbraco.Core.Scoping.Scope.DisposeLastScope()
   at Umbraco.Core.Scoping.Scope.Dispose()
   at Umbraco.Core.Services.Implement.PublicAccessService.GetEntryForContent(String contentPath)
   at Umbraco.Core.Services.Implement.PublicAccessService.IsProtected(String contentPath)
   at Umbraco.Examine.ContentValueSetValidator.ValidateProtectedContent(String path, String category)
   at Umbraco.Examine.ContentValueSetValidator.Validate(ValueSet valueSet)
   at Examine.Providers.BaseIndexProvider.<IndexItems>b__12_0(ValueSet x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at Umbraco.Examine.UmbracoContentIndex.PerformIndexItems(IEnumerable`1 values, Action`1 onComplete)
   at Examine.Providers.BaseIndexProvider.IndexItems(IEnumerable`1 values)
   at Umbraco.Web.Search.ExamineComponent.DeferedReIndexForContent.Execute(ExamineComponent examineComponent, IContent content, Boolean isPublished)
   at Umbraco.Web.Search.ExamineComponent.DeferedReIndexForContent.Execute()
   at Umbraco.Web.Search.ExamineComponent.DeferedActions.Execute()
   at Umbraco.Web.Search.ExamineComponent.DeferedActions.<>c.<Get>b__1_1(Boolean completed, DeferedActions actions)
   at Umbraco.Core.Scoping.ScopeContext.EnlistedObject`1.Execute(Boolean completed)
   at Umbraco.Core.Scoping.ScopeContext.ScopeExit(Boolean completed)<---
```

Best
Dee

**Comment by deekoulos** [comment]
after upgrading to 8.7.1 the issue is resolved for me!
