### ISSUE TITLE
Members section giving Failed to retrieve member paged result

### ISSUE THREAD

**Issue by richarth** [umbraco/Umbraco-CMS#9435]
Our client has a v8.9.1 site with approximately 500 members in the members section.  When they click on all members to see the listing they are presented with an error:

Failed to retrieve member paged result

This used to work so I'm wondering if the number of members has gotten too large.  You can still find members by email using the search.

**Comment by richarth** [comment]
If I debug the site locally I'm getting the following error:

`An error occured
The 'ObjectContent`1' type failed to serialize the response body for content type 'application/json; charset=utf-8'.

Exception Details
System.InvalidOperationException: The 'ObjectContent`1' type failed to serialize the response body for content type 'application/json; charset=utf-8'.
Stacktrace
Inner Exception
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: &. Path '', line 1, position 2.
at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Umbraco.Web.PropertyEditors.MultipleValueEditor.ToEditor(Property property, IDataTypeService dataTypeService, String culture, String segment) in D:\a\1\s\src\Umbraco.Web\PropertyEditors\MultipleValueEditor.cs:line 38
   at Umbraco.Web.Models.Mapping.ContentPropertyBasicMapper`1.Map(Property property, TDestination dest, MapperContext context) in D:\a\1\s\src\Umbraco.Web\Models\Mapping\ContentPropertyBasicMapper.cs:line 82
   at Umbraco.Web.Models.Mapping.ContentPropertyMapDefinition.Map(Property source, ContentPropertyBasic target, MapperContext context) in D:\a\1\s\src\Umbraco.Web\Models\Mapping\ContentPropertyMapDefinition.cs:line 46
   at Umbraco.Core.Mapping.UmbracoMapper.<>c__DisplayClass8_0`2.<Define>b__1(Object source, Object target, MapperContext context) in D:\a\1\s\src\Umbraco.Core\Mapping\UmbracoMapper.cs:line 106
   at Umbraco.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, Type sourceType, MapperContext context) in D:\a\1\s\src\Umbraco.Core\Mapping\UmbracoMapper.cs:line 206
   at Umbraco.Core.Mapping.UmbracoMapper.Map[TSource,TTarget](TSource source, MapperContext context) in D:\a\1\s\src\Umbraco.Core\Mapping\UmbracoMapper.cs:line 190
   at Umbraco.Core.Mapping.MapperContext.Map[TSource,TTarget](TSource source) in D:\a\1\s\src\Umbraco.Core\Mapping\MapperContext.cs:line 68
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Umbraco.Core.Mapping.MapperContext.MapEnumerable[TSourceElement,TTargetElement](IEnumerable`1 source) in D:\a\1\s\src\Umbraco.Core\Mapping\MapperContext.cs:line 125
   at Umbraco.Web.Models.Mapping.MemberMapDefinition.Map(IMember source, MemberBasic target, MapperContext context) in D:\a\1\s\src\Umbraco.Web\Models\Mapping\MemberMapDefinition.cs:line 117
   at Umbraco.Core.Mapping.UmbracoMapper.<>c__DisplayClass8_0`2.<Define>b__1(Object source, Object target, MapperContext context) in D:\a\1\s\src\Umbraco.Core\Mapping\UmbracoMapper.cs:line 106
   at Umbraco.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, Type sourceType, MapperContext context) in D:\a\1\s\src\Umbraco.Core\Mapping\UmbracoMapper.cs:line 206
   at Umbraco.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, MapperContext context) in D:\a\1\s\src\Umbraco.Core\Mapping\UmbracoMapper.cs:line 154
   at Umbraco.Web.Editors.MemberController.<GetPagedResults>b__5_0(IMember x) in D:\a\1\s\src\Umbraco.Web\Editors\MemberController.cs:line 90
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)
   at System.Net.Http.Formatting.JsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)
   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content)
   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.WebApi.AngularJsonMediaTypeFormatter.<WriteToStreamAsync>d__1.MoveNext() in D:\a\1\s\src\Umbraco.Web\WebApi\AngularJsonMediaTypeFormatter.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.WebHost.HttpControllerHandler.<WriteBufferedResponseContentAsync>d__22.MoveNext()`

**Comment by nul800sebastiaan** [comment]
500 members should absolutely work. The error ` Unexpected character encountered while parsing value: &` leads me to think there might be a member with an `&` in it's name, but I can't reproduce the problem if I try to put one in for a member. 

I would have a look at line 2 that comes back from the `GetPagedResults` call and put that through a json linter to see where the error in the json is.

![image](https://user-images.githubusercontent.com/304656/102141358-fef23200-3e60-11eb-88a6-3bd1ba9fe71e.png)

**Comment by richarth** [comment]
Thanks for the help.  The GetPagedResults call is giving the following response on the second line:

`{"Message":"An error has occurred.","ExceptionMessage":"The 'ObjectContent'1' type failed to serialize the response body for content type 'application/json; charset=utf-8'.","ExceptionType":"System.InvalidOperationException","StackTrace":null,"InnerException":{"Message":"An error has occurred.","ExceptionMessage":"Unexpected character encountered while parsing value: &. Path '', line 1, position 2.","ExceptionType":"Newtonsoft.Json.JsonReaderException","StackTrace":"   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)\r\n   at Newtonsoft.Json.JsonTextReader.ReadAsString()\r\n   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)\r\n   at Umbraco.Web.PropertyEditors.MultipleValueEditor.ToEditor(Property property, IDataTypeService dataTypeService, String culture, String segment) in D:\\a\\1\\s\\src\\Umbraco.Web\\PropertyEditors\\MultipleValueEditor.cs:line 38\r\n   at Umbraco.Web.Models.Mapping.ContentPropertyBasicMapper'1.Map(Property property, TDestination dest, MapperContext context) in D:\\a\\1\\s\\src\\Umbraco.Web\\Models\\Mapping\\ContentPropertyBasicMapper.cs:line 82\r\n   at Umbraco.Web.Models.Mapping.ContentPropertyMapDefinition.Map(Property source, ContentPropertyBasic target, MapperContext context) in D:\\a\\1\\s\\src\\Umbraco.Web\\Models\\Mapping\\ContentPropertyMapDefinition.cs:line 46\r\n   at Umbraco.Core.Mapping.UmbracoMapper.<>c__DisplayClass8_0'2.<Define>b__1(Object source, Object target, MapperContext context) in D:\\a\\1\\s\\src\\Umbraco.Core\\Mapping\\UmbracoMapper.cs:line 106\r\n   at Umbraco.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, Type sourceType, MapperContext context) in D:\\a\\1\\s\\src\\Umbraco.Core\\Mapping\\UmbracoMapper.cs:line 206\r\n   at Umbraco.Core.Mapping.UmbracoMapper.Map[TSource,TTarget](TSource source, MapperContext context) in D:\\a\\1\\s\\src\\Umbraco.Core\\Mapping\\UmbracoMapper.cs:line 190\r\n   at Umbraco.Core.Mapping.MapperContext.Map[TSource,TTarget](TSource source) in D:\\a\\1\\s\\src\\Umbraco.Core\\Mapping\\MapperContext.cs:line 68\r\n   at System.Linq.Enumerable.WhereSelectEnumerableIterator'2.MoveNext()\r\n   at System.Collections.Generic.List'1..ctor(IEnumerable'1 collection)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable'1 source)\r\n   at Umbraco.Core.Mapping.MapperContext.MapEnumerable[TSourceElement,TTargetElement](IEnumerable'1 source) in D:\\a\\1\\s\\src\\Umbraco.Core\\Mapping\\MapperContext.cs:line 125\r\n   at Umbraco.Web.Models.Mapping.MemberMapDefinition.Map(IMember source, MemberBasic target, MapperContext context) in D:\\a\\1\\s\\src\\Umbraco.Web\\Models\\Mapping\\MemberMapDefinition.cs:line 117\r\n   at Umbraco.Core.Mapping.UmbracoMapper.<>c__DisplayClass8_0'2.<Define>b__1(Object source, Object target, MapperContext context) in D:\\a\\1\\s\\src\\Umbraco.Core\\Mapping\\UmbracoMapper.cs:line 106\r\n   at Umbraco.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, Type sourceType, MapperContext context) in D:\\a\\1\\s\\src\\Umbraco.Core\\Mapping\\UmbracoMapper.cs:line 206\r\n   at Umbraco.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, MapperContext context) in D:\\a\\1\\s\\src\\Umbraco.Core\\Mapping\\UmbracoMapper.cs:line 154\r\n   at Umbraco.Web.Editors.MemberController.<GetPagedResults>b__5_0(IMember x) in D:\\a\\1\\s\\src\\Umbraco.Web\\Editors\\MemberController.cs:line 90\r\n   at System.Linq.Enumerable.WhereSelectArrayIterator'2.MoveNext()\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)\r\n   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)\r\n   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)\r\n   at System.Net.Http.Formatting.JsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)\r\n   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content)\r\n   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.WebApi.AngularJsonMediaTypeFormatter.<WriteToStreamAsync>d__1.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\WebApi\\AngularJsonMediaTypeFormatter.cs:line 52\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.WebHost.HttpControllerHandler.<WriteBufferedResponseContentAsync>d__22.MoveNext()"}}`

Something appears to go awry preparing the response, I'm guessing there is a value it doesn't like somewhere which I'll try and track down.
