### ISSUE TITLE
v8.8.2 error but work when using PublishedRequest.SetRedirect

### ISSUE THREAD

**Issue by filefontaine** [umbraco/Umbraco-CMS#9560]
An error occur when i set a  contentRequest.SetRedirect(contentRequest.PublishedContent.Url(contentRequest.Culture.Name));
on IContentFinder.

```
System.InvalidOperationException: The route handler 'Umbraco.Web.Mvc.RenderRouteHandler' did not return an IHttpHandler from its GetHttpHandler() method.
   at System.Web.Routing.UrlRoutingModule.PostResolveRequestCache(HttpContextBase context)
   at Umbraco.Web.UmbracoInjectedModule.ProcessRequest(HttpContextBase httpContext) in D:\a\1\s\src\Umbraco.Web\UmbracoInjectedModule.cs:line 144
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

The redirect works, but a error log is set.

**Comment by filefontaine** [comment]
Ok its my fault, i use the contentRequest.SetRedirect on IContentLastChanceFinder, so its a 302 and a 404, its maybe why that bug.
