### ISSUE TITLE
Starting Alpha 3 with empty database crashes on startup

### ISSUE THREAD

**Issue by benjaminc** [umbraco/Umbraco-CMS#9843]
When starting a new site, if you have already configured a database connection pointing to an empty database, the application crashes.

Reproduction
------------

1. Create an empty SQL database
2. Create a new project using the Alpha 3 release
3. Update the appsettings.json to put the connection string to the database in the ConnectionString.umbracoDbDSN field
4. Execute `dotnet run` to start the application
5. See that the application crashes

### Expected result

In previous versions, including alpha 2, the upgrade wizard would display to update the database to the current version.  Whether it does this, or takes you into the installer with the connection information already filled in, either way is fine, but it shouldn't crash the application.

### Actual result

Umbraco does not start, and reports the following error.
```
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'umbracoCacheInstruction'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 216
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass30_0.<ExecuteDbDataReader>b__0()
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f)
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd)
   at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NPoco.Database.Fetch[T](Sql sql)
   at Umbraco.Core.Sync.DatabaseServerMessenger.EnsureInstructions(IUmbracoDatabase database)
   at Umbraco.Core.Sync.DatabaseServerMessenger.EnsureInitialized()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Umbraco.Core.Sync.DatabaseServerMessenger.Sync()
   at Umbraco.Infrastructure.Cache.DatabaseServerMessengerNotificationHandler.Handle(UmbracoApplicationStarting notification)
   at Umbraco.Core.Events.NotificationHandlerWrapperImpl`1.<>c__DisplayClass0_0.<Handle>b__1(INotification theNotification)
   at Umbraco.Core.Events.EventAggregator.PublishCore(IEnumerable`1 allHandlers, INotification notification)
   at Umbraco.Core.Events.NotificationHandlerWrapperImpl`1.Handle(INotification notification, ServiceFactory serviceFactory, Action`2 publish)
   at Umbraco.Core.Events.EventAggregator.PublishNotification(INotification notification)
   at Umbraco.Core.Events.EventAggregator.PublishAsync[TNotification](TNotification notification, CancellationToken cancellationToken)
   at Umbraco.Infrastructure.Runtime.CoreRuntime.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
Unhandled exception.    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at UnicoreDemo.Program.Main(String[] args) in C:\src\UnicoreGridsome\Backend\UnicoreDemo\Program.cs:line 12
```

**Comment by bergmania** [comment]
@rasmusjp, Is this different from V8 or is this the expected behaviour if UnattendedInstalls are `false`?

**Comment by rasmusjp** [comment]
@bergmania yeah, it shouldn't crash. Instead the installer should start normally, but the configure database step should be skipped

**Comment by benjaminc** [comment]
With the #10001 (missed the first five digit PR by just a few hours!) PR, the behavior Rasmus lists is what happens.  It takes me to the installer, prompts for a username and password, and then skips the DB Config step.  Given that we have no starter kits or other steps right now, it immediately starts installing whether I use the Customize button or the Install button.
