### ISSUE TITLE
Alpha 3 publish package doesn't work on Linux

### ISSUE THREAD

**Issue by benjaminc** [umbraco/Umbraco-CMS#9845]
After publishing a newly created project and copying that publish package to Linux, the server starts, but when you try to browse to the website you get a 500 error after being redirected to the /install page.  An error is recorded in the logs relating to an unfound page.

Reproduction
------------

### Specifics

This has been tested on Ubuntu Linux 20.04 LTS with .NET 5 SDK and ASP.NET Core 5 installed as per https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2004-.  It has also been tested on Azure, in a Web App running .NET 5 with a Linux OS.

### Steps to reproduce

1. Create a new project from the Alpha 3 release
2. Open a command prompt in the project directory and run `dotnet publish -o dist`
3. Copy the contents of the `dist` directory to a Linux server that has the .NET 5 SDK and ASP.NET Core 5 installed
4. Open a command prompt on the Linux server and run `dotnet MyProject.dll`
5. With the command prompt left open, open a browser on the Linux machine and navigate to `http://localhost:5000`

### Expected result

The Umbraco site should redirect you to the Install Wizard, and then walk you through setting up the site.

### Actual result

You are redirected to http://localhost:5000/install?redir=true&url=http://localhost:5000/.  Once at that URL, a generic HTTP 500 error page is returned.

Looking at the Umbraco logs, you can find the following error messages.
```
The view '/umbraco/UmbracoInstall/Index.cshtml' was not found. Searched locations: ["/umbraco/UmbracoInstall/Index.cshtml"]
```
```
Connection id "0HM6K9ANC0G47", Request id "0HM6K9ANC0G47:00000003": An unhandled exception was thrown by the application.
System.InvalidOperationException: The view '/umbraco/UmbracoInstall/Index.cshtml' was not found. The following locations were searched:
/umbraco/UmbracoInstall/Index.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 119
   at Umbraco.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Umbraco.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by benjaminc** [comment]
I have tested this with the latest code on the `netcore/dev` branch, and the changes made by @bergmania to the .csproj file in the template for #9811 seems to have resolved the issue.
