### ISSUE TITLE
"[Umbraco.Web.Scheduling.IBackgroundTask] " Task has failed on deleting a member

### ISSUE THREAD

**Issue by deekoulos** [umbraco/Umbraco-CMS#9872]
Hi!

using Umbraco 8.10.2 and Examine 1.1.0

Everytime we delete a member through backoffice, the following exception is raised and logged:

Message: "[Umbraco.Web.Scheduling.IBackgroundTask] " Task has failed
StackTrace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Examine.MemberValueSetBuilder.<GetValueSets>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Umbraco.Web.Search.ExamineComponent.DeferedReIndexForMember.<>c__DisplayClass4_0.<Execute>b__0()
   at Umbraco.Web.Scheduling.SimpleTask.Run()
   at Umbraco.Web.Scheduling.BackgroundTaskRunner`1.<RunAsync>d__40.MoveNext()
```

It seems that we are not alone with this issue: https://our.umbraco.com/forum/using-umbraco-and-getting-started/105051-examine-error-when-deleting-member

Any ideas?

Best
Dee

**Comment by nul800sebastiaan** [comment]
Thanks, this should be fixed for 8.12 and probably should be backported to 8.9+ patch releases as well, make sure to follow https://github.com/umbraco/Umbraco-CMS/issues/9684 for updates!
